{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs-fs",
    "version": "2.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-fs-2.3.9.jar",
          "url": "osrs-fs-2.3.9.jar",
          "size": 26599,
          "sha512": "0fbf90111e51a69acae132902efe6776151ecb8d2e52d41bd2c9415f144371917f4d39ce6b92665480b7df800b5fc0d8f811c5d930c7a012b4bdefd042d66441",
          "sha256": "ef5536b510711ca9c9d08ef7767de54031c22666580f9b54f42d92189a08e78e",
          "sha1": "6c4351da0767e4acd89a11da7085407bc5e8869b",
          "md5": "6e869d60e526f894d988781ac991cfe2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.3.9"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.3.9"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.3.9"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-fs-2.3.9.jar",
          "url": "osrs-fs-2.3.9.jar",
          "size": 26599,
          "sha512": "0fbf90111e51a69acae132902efe6776151ecb8d2e52d41bd2c9415f144371917f4d39ce6b92665480b7df800b5fc0d8f811c5d930c7a012b4bdefd042d66441",
          "sha256": "ef5536b510711ca9c9d08ef7767de54031c22666580f9b54f42d92189a08e78e",
          "sha1": "6c4351da0767e4acd89a11da7085407bc5e8869b",
          "md5": "6e869d60e526f894d988781ac991cfe2"
        }
      ]
    }
  ]
}
