{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "opcode",
    "version": "2.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "opcode-2.4.1.jar",
          "url": "opcode-2.4.1.jar",
          "size": 127100,
          "sha512": "e06e92ca6489123cd785bf8b8e7612e3a657678de8a02f9023b307c6117d97709243b2e86cdd9126c1bf05e3a461cc0975f9d738370665a1390d9bbbed6a7210",
          "sha256": "4f9bd0bbed5fc09529ffe506803a3994e7d5cc06441670a169610dc9028d30a1",
          "sha1": "f82810091192ac179c2b11fe07241457d1cc4e81",
          "md5": "fd6d312bb569719aa85c749a5518cf88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "opcode-2.4.1.jar",
          "url": "opcode-2.4.1.jar",
          "size": 127100,
          "sha512": "e06e92ca6489123cd785bf8b8e7612e3a657678de8a02f9023b307c6117d97709243b2e86cdd9126c1bf05e3a461cc0975f9d738370665a1390d9bbbed6a7210",
          "sha256": "4f9bd0bbed5fc09529ffe506803a3994e7d5cc06441670a169610dc9028d30a1",
          "sha1": "f82810091192ac179c2b11fe07241457d1cc4e81",
          "md5": "fd6d312bb569719aa85c749a5518cf88"
        }
      ]
    }
  ]
}
