{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "tools",
    "version": "2.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "tools-2.3.3.jar",
          "url": "tools-2.3.3.jar",
          "size": 347509,
          "sha512": "8231fcdad0bd6e6e0c0ad475925f10185dd439cbe29daa76706105a5edbde2824b51c40e8d8a4dc86e02603ec426f5bdebc3a50e688e1b9ade895e305bb7ae19",
          "sha256": "fa72452a505a6cf4612c237176b02e89904cb32194384b25a5f3a233c1206c80",
          "sha1": "70e645fca6a6c5b2c4f8f0049417ef5573f6b101",
          "md5": "ec6e0861799f626958a6c051eedbe228"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs-fs",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.11.5"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "dev.or2",
          "module": "displee",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "cc.ekblad",
          "module": "4koma",
          "version": {
            "requires": "1.2.2-openrune"
          }
        },
        {
          "group": "me.filby",
          "module": "clientscript-compiler",
          "version": {
            "requires": "0.0.2-openrune"
          }
        }
      ],
      "files": [
        {
          "name": "tools-2.3.3.jar",
          "url": "tools-2.3.3.jar",
          "size": 347509,
          "sha512": "8231fcdad0bd6e6e0c0ad475925f10185dd439cbe29daa76706105a5edbde2824b51c40e8d8a4dc86e02603ec426f5bdebc3a50e688e1b9ade895e305bb7ae19",
          "sha256": "fa72452a505a6cf4612c237176b02e89904cb32194384b25a5f3a233c1206c80",
          "sha1": "70e645fca6a6c5b2c4f8f0049417ef5573f6b101",
          "md5": "ec6e0861799f626958a6c051eedbe228"
        }
      ]
    }
  ]
}
