{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "openrune-central",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "openrune-central-1.3.1.jar",
          "url": "openrune-central-1.3.1.jar",
          "size": 480512,
          "sha512": "4931d63de2e8a46785c37a3955a16379083831f9cfd1989b60a06ea3781c339fc9db8776a245cf5e37e6302992c3b8fd0c5e08ba966b039f65f6a0185e406493",
          "sha256": "b78b82e64fa324fd73629d931090a17733c201b3cd23fff53dbab4d61343466e",
          "sha1": "5a320ef465d68c1f13b19134077c7ed042926c57",
          "md5": "70e2cd56578722a68567296693f7348e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.or2",
          "module": "central-common",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-bom",
          "version": {
            "requires": "3.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-content-negotiation"
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-status-pages"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-forwarded-header"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-config-yaml"
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.7"
          }
        },
        {
          "group": "io.zonky.test",
          "module": "embedded-postgres",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.16"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "de.mkammerer",
          "module": "argon2-jvm",
          "version": {
            "requires": "2.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "openrune-central-1.3.1.jar",
          "url": "openrune-central-1.3.1.jar",
          "size": 480512,
          "sha512": "4931d63de2e8a46785c37a3955a16379083831f9cfd1989b60a06ea3781c339fc9db8776a245cf5e37e6302992c3b8fd0c5e08ba966b039f65f6a0185e406493",
          "sha256": "b78b82e64fa324fd73629d931090a17733c201b3cd23fff53dbab4d61343466e",
          "sha1": "5a320ef465d68c1f13b19134077c7ed042926c57",
          "md5": "70e2cd56578722a68567296693f7348e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "openrune-central-1.3.1-all.jar",
          "url": "openrune-central-1.3.1-all.jar",
          "size": 101466958,
          "sha512": "88bf363b92e218abce817938f2f41dcb275234ecbf5d1476a0a7b3a80f6df6745b8bd2310a45873769673f00df821a5103afa41c3af4e7946bdf7c9b799d9d2f",
          "sha256": "98c2def259fa2426e2b51f19b5296c1b5bae1ef8586fbe3af34a8fca7c087ea9",
          "sha1": "4f5e1a12b0907f8ab5ae6cbcb64b0a8850073dc4",
          "md5": "098aae919ffe53fd341f556ac8b322b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "openrune-central-1.3.1-sources.jar",
          "url": "openrune-central-1.3.1-sources.jar",
          "size": 71918,
          "sha512": "dcf48968137364ca199b7c069de42685547df36e199488c2f464daf072f25a756a2b97ad15388b1af930a2b9b70fa356295e8102be92d0b08ead5b4e69676cad",
          "sha256": "d09ee7efe9a93f6354c7237be413e73731a9c4f73d25c0795bbc1913d4c0d890",
          "sha1": "3fae34668840f5493f66c17c36831fb77c65aa78",
          "md5": "9b82e403840be1751acd4be2b9991833"
        }
      ]
    }
  ]
}
