{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "runescript-parser",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescript-parser-0.0.1-SNAPSHOT.jar",
          "url": "runescript-parser-0.0.1-SNAPSHOT.jar",
          "size": 205799,
          "sha512": "1ee6b28ad7ea5d38193272972cf957551a0186e3ef2dc7e9dfc40bda285a402fe3003798f9024c043e614f2b68ebf46a156657505ea21410fda16fd15ae75433",
          "sha256": "4919ad7efb054642a981d5b36b7e8f53980a42a4e457a1cc6be8e96645922bff",
          "sha1": "bb476e1cde54f54778c98a41e4483e2e070cacc5",
          "md5": "38517e45052906a24c2ea3fb353e5eb5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.0-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescript-parser-0.0.1-SNAPSHOT.jar",
          "url": "runescript-parser-0.0.1-SNAPSHOT.jar",
          "size": 205799,
          "sha512": "1ee6b28ad7ea5d38193272972cf957551a0186e3ef2dc7e9dfc40bda285a402fe3003798f9024c043e614f2b68ebf46a156657505ea21410fda16fd15ae75433",
          "sha256": "4919ad7efb054642a981d5b36b7e8f53980a42a4e457a1cc6be8e96645922bff",
          "sha1": "bb476e1cde54f54778c98a41e4483e2e070cacc5",
          "md5": "38517e45052906a24c2ea3fb353e5eb5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescript-parser-0.0.1-SNAPSHOT-sources.jar",
          "url": "runescript-parser-0.0.1-SNAPSHOT-sources.jar",
          "size": 65257,
          "sha512": "8e676a7dc4b85da4bb84baad10e2ff48babe347a773514aa92ce7d0ee168145925eb92fa3a41e3bfca985ce11a01da01302186a277b8e7f3e8519dc3e0df2034",
          "sha256": "c0469049d56d49954aabbcabeb6a4c98a9bd495a3c1555badb5aff74ad710f30",
          "sha1": "0922de372fbef425a6424dc51691ab030d69c630",
          "md5": "e68ac8706c635f0be8e3405e386ad89b"
        },
        {
          "name": "runescript-parser-0.0.1-SNAPSHOT-sources.jar",
          "url": "runescript-parser-0.0.1-SNAPSHOT-sources.jar",
          "size": 65257,
          "sha512": "8e676a7dc4b85da4bb84baad10e2ff48babe347a773514aa92ce7d0ee168145925eb92fa3a41e3bfca985ce11a01da01302186a277b8e7f3e8519dc3e0df2034",
          "sha256": "c0469049d56d49954aabbcabeb6a4c98a9bd495a3c1555badb5aff74ad710f30",
          "sha1": "0922de372fbef425a6424dc51691ab030d69c630",
          "md5": "e68ac8706c635f0be8e3405e386ad89b"
        }
      ]
    }
  ]
}
