{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "runescript-parser",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescript-parser-0.0.1-SNAPSHOT.jar",
          "url": "runescript-parser-0.0.1-SNAPSHOT.jar",
          "size": 205799,
          "sha512": "1ee6b28ad7ea5d38193272972cf957551a0186e3ef2dc7e9dfc40bda285a402fe3003798f9024c043e614f2b68ebf46a156657505ea21410fda16fd15ae75433",
          "sha256": "4919ad7efb054642a981d5b36b7e8f53980a42a4e457a1cc6be8e96645922bff",
          "sha1": "bb476e1cde54f54778c98a41e4483e2e070cacc5",
          "md5": "38517e45052906a24c2ea3fb353e5eb5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.0-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescript-parser-0.0.1-SNAPSHOT.jar",
          "url": "runescript-parser-0.0.1-SNAPSHOT.jar",
          "size": 205799,
          "sha512": "1ee6b28ad7ea5d38193272972cf957551a0186e3ef2dc7e9dfc40bda285a402fe3003798f9024c043e614f2b68ebf46a156657505ea21410fda16fd15ae75433",
          "sha256": "4919ad7efb054642a981d5b36b7e8f53980a42a4e457a1cc6be8e96645922bff",
          "sha1": "bb476e1cde54f54778c98a41e4483e2e070cacc5",
          "md5": "38517e45052906a24c2ea3fb353e5eb5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescript-parser-0.0.1-SNAPSHOT-sources.jar",
          "url": "runescript-parser-0.0.1-SNAPSHOT-sources.jar",
          "size": 65257,
          "sha512": "91f41de68cc3cefd8a15f0463287b0ff6a3612b8daf98fb6e1b5899421a10241ec6199b9211c045f1beae5850961e8793dfe5639e8cfb3181552522dcaf50f99",
          "sha256": "aad82a0bc4bceb8a13c7de408488dfd7250726863e1569b29f7620cee2d2af3d",
          "sha1": "2acf03e56c9c6b77f1013e8018e18d9aba239afa",
          "md5": "2bbb0951bc809c0b598cbabaeed6e886"
        },
        {
          "name": "runescript-parser-0.0.1-SNAPSHOT-sources.jar",
          "url": "runescript-parser-0.0.1-SNAPSHOT-sources.jar",
          "size": 65257,
          "sha512": "91f41de68cc3cefd8a15f0463287b0ff6a3612b8daf98fb6e1b5899421a10241ec6199b9211c045f1beae5850961e8793dfe5639e8cfb3181552522dcaf50f99",
          "sha256": "aad82a0bc4bceb8a13c7de408488dfd7250726863e1569b29f7620cee2d2af3d",
          "sha1": "2acf03e56c9c6b77f1013e8018e18d9aba239afa",
          "md5": "2bbb0951bc809c0b598cbabaeed6e886"
        }
      ]
    }
  ]
}
