{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "runescript-parser",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescript-parser-0.0.1-SNAPSHOT.jar",
          "url": "runescript-parser-0.0.1-SNAPSHOT.jar",
          "size": 205799,
          "sha512": "1ee6b28ad7ea5d38193272972cf957551a0186e3ef2dc7e9dfc40bda285a402fe3003798f9024c043e614f2b68ebf46a156657505ea21410fda16fd15ae75433",
          "sha256": "4919ad7efb054642a981d5b36b7e8f53980a42a4e457a1cc6be8e96645922bff",
          "sha1": "bb476e1cde54f54778c98a41e4483e2e070cacc5",
          "md5": "38517e45052906a24c2ea3fb353e5eb5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.0-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescript-parser-0.0.1-SNAPSHOT.jar",
          "url": "runescript-parser-0.0.1-SNAPSHOT.jar",
          "size": 205799,
          "sha512": "1ee6b28ad7ea5d38193272972cf957551a0186e3ef2dc7e9dfc40bda285a402fe3003798f9024c043e614f2b68ebf46a156657505ea21410fda16fd15ae75433",
          "sha256": "4919ad7efb054642a981d5b36b7e8f53980a42a4e457a1cc6be8e96645922bff",
          "sha1": "bb476e1cde54f54778c98a41e4483e2e070cacc5",
          "md5": "38517e45052906a24c2ea3fb353e5eb5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescript-parser-0.0.1-SNAPSHOT-sources.jar",
          "url": "runescript-parser-0.0.1-SNAPSHOT-sources.jar",
          "size": 65257,
          "sha512": "eeb7275545a82838590435f8415faa69c9833756f8a8c38ba8e7c9fb6b4ab1af279e7d008386a7e37311a10ca382cee27b8895140d6daa94e484f337938705db",
          "sha256": "d685a8f841eba7aa5c987ff15d541e4de32b727715d80087cd0b38820efb1dab",
          "sha1": "eb2c5f0cce63e6205da58c03da6d9ceceaaf148e",
          "md5": "4101339193dea72c672361fda11bcdc5"
        },
        {
          "name": "runescript-parser-0.0.1-SNAPSHOT-sources.jar",
          "url": "runescript-parser-0.0.1-SNAPSHOT-sources.jar",
          "size": 65257,
          "sha512": "eeb7275545a82838590435f8415faa69c9833756f8a8c38ba8e7c9fb6b4ab1af279e7d008386a7e37311a10ca382cee27b8895140d6daa94e484f337938705db",
          "sha256": "d685a8f841eba7aa5c987ff15d541e4de32b727715d80087cd0b38820efb1dab",
          "sha1": "eb2c5f0cce63e6205da58c03da6d9ceceaaf148e",
          "md5": "4101339193dea72c672361fda11bcdc5"
        }
      ]
    }
  ]
}
