{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.2.5.jar",
          "url": "displee-2.2.5.jar",
          "size": 111913,
          "sha512": "67f5b276add9f1e153939766d7ec88e6b9fafa32f6a57446141f16e44e71e6554c8ce81726cad82ba7152ab535a0ca58a3ed7c21683f6a4ec59ff9a4f676a92f",
          "sha256": "195208b793a394c81b0f6c529e6951e0c41bf1c59a099cf66fcf1dc2fead109d",
          "sha1": "c12b19f52cf66658b2b286b6cbbf351deb37d3c2",
          "md5": "62543251ce0359e4beefbdb2173ac5d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.2.5.jar",
          "url": "displee-2.2.5.jar",
          "size": 111913,
          "sha512": "67f5b276add9f1e153939766d7ec88e6b9fafa32f6a57446141f16e44e71e6554c8ce81726cad82ba7152ab535a0ca58a3ed7c21683f6a4ec59ff9a4f676a92f",
          "sha256": "195208b793a394c81b0f6c529e6951e0c41bf1c59a099cf66fcf1dc2fead109d",
          "sha1": "c12b19f52cf66658b2b286b6cbbf351deb37d3c2",
          "md5": "62543251ce0359e4beefbdb2173ac5d9"
        }
      ]
    }
  ]
}
