{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.0.10.jar",
          "url": "displee-2.0.10.jar",
          "size": 111768,
          "sha512": "14e3da1a7b82d21b9136c60366e0defd7984188ba1c9bd3c8b29de5d9980310babbc1c035f19943d738f78186915cf980b131bde7736c490800085db604e1393",
          "sha256": "db5d46de61313867a5cf5a7280ff958df6d75b10e68a3f5bc9060ee3a4c5d46c",
          "sha1": "3345eb7daa6aee7f2a19b824d42a28f4119a6706",
          "md5": "a300a8afbb7080ed3d5acb05a1790f8a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.0.10.jar",
          "url": "displee-2.0.10.jar",
          "size": 111768,
          "sha512": "14e3da1a7b82d21b9136c60366e0defd7984188ba1c9bd3c8b29de5d9980310babbc1c035f19943d738f78186915cf980b131bde7736c490800085db604e1393",
          "sha256": "db5d46de61313867a5cf5a7280ff958df6d75b10e68a3f5bc9060ee3a4c5d46c",
          "sha1": "3345eb7daa6aee7f2a19b824d42a28f4119a6706",
          "md5": "a300a8afbb7080ed3d5acb05a1790f8a"
        }
      ]
    }
  ]
}
