{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "filestore",
    "version": "1.3.89",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-1.3.89.jar",
          "url": "filestore-1.3.89.jar",
          "size": 353712,
          "sha512": "0039466343a410022ee8337072eab3b206fbec8c056d4eca91cb0d5cafda11f88458d191e05999393dce0200de07b06b615a51273ceea17383d16ec305c17a6b",
          "sha256": "dac6ec969ee248224a18e24dc82a7e77d208fe342626d2e927e1431df8de5ae1",
          "sha1": "ecc4aa06dc111e0b4ab64fd870ae134e7e3d8e8a",
          "md5": "f45ca5c334100cc55b702eed08c4454f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-file",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0-Beta1"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-1.3.89.jar",
          "url": "filestore-1.3.89.jar",
          "size": 353712,
          "sha512": "0039466343a410022ee8337072eab3b206fbec8c056d4eca91cb0d5cafda11f88458d191e05999393dce0200de07b06b615a51273ceea17383d16ec305c17a6b",
          "sha256": "dac6ec969ee248224a18e24dc82a7e77d208fe342626d2e927e1431df8de5ae1",
          "sha1": "ecc4aa06dc111e0b4ab64fd870ae134e7e3d8e8a",
          "md5": "f45ca5c334100cc55b702eed08c4454f"
        }
      ]
    }
  ]
}
