{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "rs3",
    "version": "2.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "rs3-2.3.2.jar",
          "url": "rs3-2.3.2.jar",
          "size": 8746,
          "sha512": "883d62ecb74cf3336b61da5c39da5439654a2ca1d99d5638287a95cafce00f1eec7714ad72e7148865fd198a8a6bca51238c951d362db35bed62a8f89c525fd4",
          "sha256": "610698aaf419c247cc6bf753949a868dfead875456d6e8eff03d21e856c7ecea",
          "sha1": "70e23d6683874b45dc77bb11d9111073377abd54",
          "md5": "306e8070de33786fa14aaa64598e6e79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "rs3-2.3.2.jar",
          "url": "rs3-2.3.2.jar",
          "size": 8746,
          "sha512": "883d62ecb74cf3336b61da5c39da5439654a2ca1d99d5638287a95cafce00f1eec7714ad72e7148865fd198a8a6bca51238c951d362db35bed62a8f89c525fd4",
          "sha256": "610698aaf419c247cc6bf753949a868dfead875456d6e8eff03d21e856c7ecea",
          "sha1": "70e23d6683874b45dc77bb11d9111073377abd54",
          "md5": "306e8070de33786fa14aaa64598e6e79"
        }
      ]
    }
  ]
}
