{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filestore-server-osrs",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-server-osrs-0.3.jar",
          "url": "filestore-server-osrs-0.3.jar",
          "size": 261,
          "sha512": "8a71ff7029bdaec1b928ca6e294bd5ef6225dff90242f5703153532ae4851a2ac0cbcee96985d6a6892d126c915f3fad1dbb4e222e5be427ae05432c06579cf6",
          "sha256": "9ecc327081daa5263808795dc78f5a43329dcfc11c3fb975cc03a55ddca389e1",
          "sha1": "bab799ea42785a88eb10ef93d1ad57bd2d9ca655",
          "md5": "a36e0bf0ffbca08b3ba1c33fad20cb58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.or2",
          "module": "all",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-server-osrs-0.3.jar",
          "url": "filestore-server-osrs-0.3.jar",
          "size": 261,
          "sha512": "8a71ff7029bdaec1b928ca6e294bd5ef6225dff90242f5703153532ae4851a2ac0cbcee96985d6a6892d126c915f3fad1dbb4e222e5be427ae05432c06579cf6",
          "sha256": "9ecc327081daa5263808795dc78f5a43329dcfc11c3fb975cc03a55ddca389e1",
          "sha1": "bab799ea42785a88eb10ef93d1ad57bd2d9ca655",
          "md5": "a36e0bf0ffbca08b3ba1c33fad20cb58"
        }
      ]
    }
  ]
}
