{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "opcode",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "opcode-2.4.0.jar",
          "url": "opcode-2.4.0.jar",
          "size": 127288,
          "sha512": "83189ca74da1daa04fd4fcbe8e8c766e83c5c94aa7fe2814a219f365a3ee67950ff746a2d90faf4861d5084af82ff92854ba97497ba4d808f193a077766e1b17",
          "sha256": "d22b175b40227416eba78e21471c317fea997cc83f6b0f3f9486684469420411",
          "sha1": "5eb6b2e804ab6cc939c8dde1aad00051cc91c64a",
          "md5": "5db75dd4475fbb6a4225d8634a008ebf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "opcode-2.4.0.jar",
          "url": "opcode-2.4.0.jar",
          "size": 127288,
          "sha512": "83189ca74da1daa04fd4fcbe8e8c766e83c5c94aa7fe2814a219f365a3ee67950ff746a2d90faf4861d5084af82ff92854ba97497ba4d808f193a077766e1b17",
          "sha256": "d22b175b40227416eba78e21471c317fea997cc83f6b0f3f9486684469420411",
          "sha1": "5eb6b2e804ab6cc939c8dde1aad00051cc91c64a",
          "md5": "5db75dd4475fbb6a4225d8634a008ebf"
        }
      ]
    }
  ]
}
