{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.0.17.jar",
          "url": "displee-2.0.17.jar",
          "size": 111913,
          "sha512": "39ad2c1aad67b6135e2b2d0aefc7e9df0f4add00ec6803b3ad9920d8bad3e06bb2a8acac046d05a72afc152978796a72c8f254b7a1064e97fe2718a71d19c27a",
          "sha256": "ef12d2f6bbfa6185e5f515ef60aed919aed44beae40d9f7155091bc53fce711d",
          "sha1": "c3489cd5c7256e348d82dddf81d37cdc7cc70752",
          "md5": "84152691a14cc6e7958a124e356f3b0c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.0.17.jar",
          "url": "displee-2.0.17.jar",
          "size": 111913,
          "sha512": "39ad2c1aad67b6135e2b2d0aefc7e9df0f4add00ec6803b3ad9920d8bad3e06bb2a8acac046d05a72afc152978796a72c8f254b7a1064e97fe2718a71d19c27a",
          "sha256": "ef12d2f6bbfa6185e5f515ef60aed919aed44beae40d9f7155091bc53fce711d",
          "sha1": "c3489cd5c7256e348d82dddf81d37cdc7cc70752",
          "md5": "84152691a14cc6e7958a124e356f3b0c"
        }
      ]
    }
  ]
}
