{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "runescript-runtime",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "runescript-runtime-0.0.1-SNAPSHOT.jar",
          "url": "runescript-runtime-0.0.1-SNAPSHOT.jar",
          "size": 40587,
          "sha512": "db9f4c1deee2a8b521ea6fc0dbc812c4593903a2213261659733cf5fb95b3c6000ce8fa519299848141f557eac21b5892305987243e8d11fd8ebe62dbcc30c56",
          "sha256": "291443fce08ed8e98844c12e7e3602cf65a33ec409052299fbcc2140a5cee465",
          "sha1": "aa0f53f975e5b8b7dd512e6df57e26b844f98efe",
          "md5": "2027b41419e35b4b68edd2f7b26b51a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.0-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "dev.or2",
          "module": "runescript-compiler",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "runescript-runtime-0.0.1-SNAPSHOT.jar",
          "url": "runescript-runtime-0.0.1-SNAPSHOT.jar",
          "size": 40587,
          "sha512": "db9f4c1deee2a8b521ea6fc0dbc812c4593903a2213261659733cf5fb95b3c6000ce8fa519299848141f557eac21b5892305987243e8d11fd8ebe62dbcc30c56",
          "sha256": "291443fce08ed8e98844c12e7e3602cf65a33ec409052299fbcc2140a5cee465",
          "sha1": "aa0f53f975e5b8b7dd512e6df57e26b844f98efe",
          "md5": "2027b41419e35b4b68edd2f7b26b51a6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescript-runtime-0.0.1-SNAPSHOT-sources.jar",
          "url": "runescript-runtime-0.0.1-SNAPSHOT-sources.jar",
          "size": 13755,
          "sha512": "72c29333ab0098e423d6e3b359e21a39e20288637e21526a77220da973feec8f5fd450bbb0ccc7ca8126889942649674b4b52bd14d8996b97d782719e76847c2",
          "sha256": "c0c3d393c4cc1f047de687c55659f4b3af54c0e149537b9cee1c7bcd06454490",
          "sha1": "0393144eb184ff7803cbab9b3da59192a935da5f",
          "md5": "735178ebc3f8828e3988cd56c2ca0978"
        },
        {
          "name": "runescript-runtime-0.0.1-SNAPSHOT-sources.jar",
          "url": "runescript-runtime-0.0.1-SNAPSHOT-sources.jar",
          "size": 13755,
          "sha512": "72c29333ab0098e423d6e3b359e21a39e20288637e21526a77220da973feec8f5fd450bbb0ccc7ca8126889942649674b4b52bd14d8996b97d782719e76847c2",
          "sha256": "c0c3d393c4cc1f047de687c55659f4b3af54c0e149537b9cee1c7bcd06454490",
          "sha1": "0393144eb184ff7803cbab9b3da59192a935da5f",
          "md5": "735178ebc3f8828e3988cd56c2ca0978"
        }
      ]
    }
  ]
}
