{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.0.16.jar",
          "url": "displee-2.0.16.jar",
          "size": 111913,
          "sha512": "12b1fba51d7c9a789dce72fe5abaeefa820a3b2098e1197cdbc33536de7e11c5b9b16dad39062928b390bc9a22447e266bffe08d3442758e9680306b0994f1c0",
          "sha256": "e8ce726f2c2f3de12030771fd99aeb7d0ffc74166fd56d207d86e1cbacb3abd0",
          "sha1": "481a519517d0f6d61b809e806741d92a628819bb",
          "md5": "b0fa92ab85468db1c49f36166cfc3c9a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.0.16.jar",
          "url": "displee-2.0.16.jar",
          "size": 111913,
          "sha512": "12b1fba51d7c9a789dce72fe5abaeefa820a3b2098e1197cdbc33536de7e11c5b9b16dad39062928b390bc9a22447e266bffe08d3442758e9680306b0994f1c0",
          "sha256": "e8ce726f2c2f3de12030771fd99aeb7d0ffc74166fd56d207d86e1cbacb3abd0",
          "sha1": "481a519517d0f6d61b809e806741d92a628819bb",
          "md5": "b0fa92ab85468db1c49f36166cfc3c9a"
        }
      ]
    }
  ]
}
