{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filesystem",
    "version": "2.0.92",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filesystem-2.0.92.jar",
          "url": "filesystem-2.0.92.jar",
          "size": 74762,
          "sha512": "da8d0e0740b8c42b6706c37ee5219deaf3a5efdb069f61415d835d7747905cc4c280986a5f6bc27562cd7a89efde884b61bd13db414fa46a52d822ee3680bece",
          "sha256": "dc0b5621bf339a4b5786bd0ea2adec69910a0a3ac43d1d9a47b3d0c500e51103",
          "sha1": "db17e0bb35b617822421a4e9efb36acc98c119c4",
          "md5": "bdfca4a1283c0fc3de8ae21c2aec5dbf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "filesystem-2.0.92.jar",
          "url": "filesystem-2.0.92.jar",
          "size": 74762,
          "sha512": "da8d0e0740b8c42b6706c37ee5219deaf3a5efdb069f61415d835d7747905cc4c280986a5f6bc27562cd7a89efde884b61bd13db414fa46a52d822ee3680bece",
          "sha256": "dc0b5621bf339a4b5786bd0ea2adec69910a0a3ac43d1d9a47b3d0c500e51103",
          "sha1": "db17e0bb35b617822421a4e9efb36acc98c119c4",
          "md5": "bdfca4a1283c0fc3de8ae21c2aec5dbf"
        }
      ]
    }
  ]
}
