{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "opcode",
    "version": "2.4.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "opcode-2.4.19.jar",
          "url": "opcode-2.4.19.jar",
          "size": 127117,
          "sha512": "d1d96403ef649a045fd74f4f505d967ed942cc119a592a948c46ed865b34ee3312ffddd94124edab2523df9ede53baf89521e9bcd3d82cde33c12c12a2d122fc",
          "sha256": "2c016e7fd8f056d7835dcc01d00c49743eee8f6e082d79171db14d031e633b60",
          "sha1": "1ec53ad744bdeee074627a048ff520234dbd6393",
          "md5": "056e519696ceea3c701d0e481b0b8f51"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.19"
          }
        }
      ],
      "files": [
        {
          "name": "opcode-2.4.19.jar",
          "url": "opcode-2.4.19.jar",
          "size": 127117,
          "sha512": "d1d96403ef649a045fd74f4f505d967ed942cc119a592a948c46ed865b34ee3312ffddd94124edab2523df9ede53baf89521e9bcd3d82cde33c12c12a2d122fc",
          "sha256": "2c016e7fd8f056d7835dcc01d00c49743eee8f6e082d79171db14d031e633b60",
          "sha1": "1ec53ad744bdeee074627a048ff520234dbd6393",
          "md5": "056e519696ceea3c701d0e481b0b8f51"
        }
      ]
    }
  ]
}
