{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.3.7.jar",
          "url": "displee-2.3.7.jar",
          "size": 111913,
          "sha512": "b18d16e3c2f2232d387ed0d9b0cd294f040a61b2f20480e531ddccdefd91d4b7797f10253b5a8e74ccf44af72c7973b445c5ffad03d13e1c4c316a465fb9f900",
          "sha256": "bf5c216116e8d1402eaf3585122c2687e36c212a361d954e8bd156e0add82a2f",
          "sha1": "d2aca481ecefbc0a12ea8ff66a22a42377d137e1",
          "md5": "031c3ca97e9dc6da5d61009d12ede6c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.3.7.jar",
          "url": "displee-2.3.7.jar",
          "size": 111913,
          "sha512": "b18d16e3c2f2232d387ed0d9b0cd294f040a61b2f20480e531ddccdefd91d4b7797f10253b5a8e74ccf44af72c7973b445c5ffad03d13e1c4c316a465fb9f900",
          "sha256": "bf5c216116e8d1402eaf3585122c2687e36c212a361d954e8bd156e0add82a2f",
          "sha1": "d2aca481ecefbc0a12ea8ff66a22a42377d137e1",
          "md5": "031c3ca97e9dc6da5d61009d12ede6c3"
        }
      ]
    }
  ]
}
