{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filestore-server-osrs",
    "version": "0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-server-osrs-0.6.jar",
          "url": "filestore-server-osrs-0.6.jar",
          "size": 198735,
          "sha512": "7a92f712f505d1d724d9007de9667da9b647bcc552ea1a8149d500386f1d2dba2eccb1f582f478cba9abcaaa0269e1bbcc8a728cb9dd77bdb3410f0ec923d74a",
          "sha256": "42342063731a87a481192863b1804f53e30d535f1c58cc5a1be3669c20c9c3ff",
          "sha1": "3879ad72901dafe189567c708b42ee2cf888a023",
          "md5": "ee3cc0c834b1dcacac5209056cdb3327"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore-server",
          "version": {
            "requires": "0.6"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-server-osrs-0.6.jar",
          "url": "filestore-server-osrs-0.6.jar",
          "size": 198735,
          "sha512": "7a92f712f505d1d724d9007de9667da9b647bcc552ea1a8149d500386f1d2dba2eccb1f582f478cba9abcaaa0269e1bbcc8a728cb9dd77bdb3410f0ec923d74a",
          "sha256": "42342063731a87a481192863b1804f53e30d535f1c58cc5a1be3669c20c9c3ff",
          "sha1": "3879ad72901dafe189567c708b42ee2cf888a023",
          "md5": "ee3cc0c834b1dcacac5209056cdb3327"
        }
      ]
    }
  ]
}
