{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718",
    "version": "2.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-2.3.2.jar",
          "url": "r718-2.3.2.jar",
          "size": 14132,
          "sha512": "7c2a001507c55e76362270ffdd5fd8939757e6514ac84a72982ba8d20f8388f6ae2f565ec89c62022a1b0b0d5d948bc62c0f4e25545928ba8b0e5bbd7d4c5ba4",
          "sha256": "ed2f960ad7ddd284cfd50e2fea5ac9a25a5f9974264136a96fcee9536663a453",
          "sha1": "5edd9adcd35fbbc94447e9f9636c8a99b8086f7c",
          "md5": "2f36c8621e0166cca6b5c0a310588bee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "r718-2.3.2.jar",
          "url": "r718-2.3.2.jar",
          "size": 14132,
          "sha512": "7c2a001507c55e76362270ffdd5fd8939757e6514ac84a72982ba8d20f8388f6ae2f565ec89c62022a1b0b0d5d948bc62c0f4e25545928ba8b0e5bbd7d4c5ba4",
          "sha256": "ed2f960ad7ddd284cfd50e2fea5ac9a25a5f9974264136a96fcee9536663a453",
          "sha1": "5edd9adcd35fbbc94447e9f9636c8a99b8086f7c",
          "md5": "2f36c8621e0166cca6b5c0a310588bee"
        }
      ]
    }
  ]
}
