{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.4.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.4.8.jar",
          "url": "displee-2.4.8.jar",
          "size": 111913,
          "sha512": "debf8d40e89f6755132a24f5663875db1a8b3c636d60da143b6307304357a298a041d7ff9ef00ebe485191de55deecbdca97502c9344a6ad390bba5b2280ed3e",
          "sha256": "1820adb9cc75da2c9c4562a2fb161b203b7f358cd1d00a4abe923b7b73108172",
          "sha1": "e3ff3787a8bdf9adccf6c9a211262c4501a0d13a",
          "md5": "4c09078296008dfcce780055b481049a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.4.8.jar",
          "url": "displee-2.4.8.jar",
          "size": 111913,
          "sha512": "debf8d40e89f6755132a24f5663875db1a8b3c636d60da143b6307304357a298a041d7ff9ef00ebe485191de55deecbdca97502c9344a6ad390bba5b2280ed3e",
          "sha256": "1820adb9cc75da2c9c4562a2fb161b203b7f358cd1d00a4abe923b7b73108172",
          "sha1": "e3ff3787a8bdf9adccf6c9a211262c4501a0d13a",
          "md5": "4c09078296008dfcce780055b481049a"
        }
      ]
    }
  ]
}
