{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "bootstrap",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "bootstrap-1.2.jar",
          "url": "bootstrap-1.2.jar",
          "size": 88540,
          "sha512": "30b2968eec6405f8a15fc111f50fb412972e87d74550c2f7a2347b2ba7fbf9a0072b8dc2d35236be8a332e1171ba2b3e36b7f9ca5884d88f419e9676b895ef85",
          "sha256": "4b0214c7aae11e7f0a56dac56088a60b959676254a66af46a65b1b57a827087d",
          "sha1": "32649d5d983372689daf6558c7f561a20453cbec",
          "md5": "16e36e7da57dc86cdece29215d577f6e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.2"
          }
        },
        {
          "group": "com.beust",
          "module": "klaxon",
          "version": {
            "requires": "5.5"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.9.0.202403050737-r"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.11"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "bootstrap-1.2.jar",
          "url": "bootstrap-1.2.jar",
          "size": 88540,
          "sha512": "30b2968eec6405f8a15fc111f50fb412972e87d74550c2f7a2347b2ba7fbf9a0072b8dc2d35236be8a332e1171ba2b3e36b7f9ca5884d88f419e9676b895ef85",
          "sha256": "4b0214c7aae11e7f0a56dac56088a60b959676254a66af46a65b1b57a827087d",
          "sha1": "32649d5d983372689daf6558c7f561a20453cbec",
          "md5": "16e36e7da57dc86cdece29215d577f6e"
        }
      ]
    }
  ]
}
