{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs",
    "version": "2.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-2.0.9.jar",
          "url": "osrs-2.0.9.jar",
          "size": 73475,
          "sha512": "3c530a065cef72e25441978e1a4f58fbc4fd20effa3fdf1123f528cf07ca0679da5c3a150b2097463f760dc4d5a17c30e7a3d4d27dbd8f368073384d77a90260",
          "sha256": "be298569745a457d42c3c2a2552f2270e627100c73dd8723a3bf11eba444cf62",
          "sha1": "a8517876c3a19696f5d7be7674c5ec80e21719ff",
          "md5": "eb8d5a794d180d4447ed93049c8c8b37"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-2.0.9.jar",
          "url": "osrs-2.0.9.jar",
          "size": 73475,
          "sha512": "3c530a065cef72e25441978e1a4f58fbc4fd20effa3fdf1123f528cf07ca0679da5c3a150b2097463f760dc4d5a17c30e7a3d4d27dbd8f368073384d77a90260",
          "sha256": "be298569745a457d42c3c2a2552f2270e627100c73dd8723a3bf11eba444cf62",
          "sha1": "a8517876c3a19696f5d7be7674c5ec80e21719ff",
          "md5": "eb8d5a794d180d4447ed93049c8c8b37"
        }
      ]
    }
  ]
}
