{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.4.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.4.7.jar",
          "url": "displee-2.4.7.jar",
          "size": 111913,
          "sha512": "f329ad22f8e6928a6eee3ac4a5fccabe0efc5a068d920b56c3856b2041ebd7d5d2b8565242bfa0d09257593c8e81741a901cebd68694c2f934520c9e984273fb",
          "sha256": "2a26e0642214b25e154fefd92b7428dda8dfb910582a598095678dc9eadbfc85",
          "sha1": "2e57fe572de7fcae391aa2fdd9ba41ad58cb4f75",
          "md5": "a9b50df94bdf12c79d2919a3e194a580"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.4.7.jar",
          "url": "displee-2.4.7.jar",
          "size": 111913,
          "sha512": "f329ad22f8e6928a6eee3ac4a5fccabe0efc5a068d920b56c3856b2041ebd7d5d2b8565242bfa0d09257593c8e81741a901cebd68694c2f934520c9e984273fb",
          "sha256": "2a26e0642214b25e154fefd92b7428dda8dfb910582a598095678dc9eadbfc85",
          "sha1": "2e57fe572de7fcae391aa2fdd9ba41ad58cb4f75",
          "md5": "a9b50df94bdf12c79d2919a3e194a580"
        }
      ]
    }
  ]
}
