{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filestore",
    "version": "2.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-2.2.7.jar",
          "url": "filestore-2.2.7.jar",
          "size": 74859,
          "sha512": "962bbfa03d723d7d12039f81390fbf51f3a8042456d62739e6cf99b381006ed89b05a1b74de7deb3c225be7c90fca305d7c2ad4c86cbe5aa9efc709a80b0d428",
          "sha256": "6edc0e9c8dcd201908640a8ecff4351046f7435695ee73a10d6e2f643cb8c6e4",
          "sha1": "466409d11978ab28a0c3dce6dffbe564dd16713b",
          "md5": "f01c1a0ad7a91d29f22db1124d03c2bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.2.7"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-2.2.7.jar",
          "url": "filestore-2.2.7.jar",
          "size": 74859,
          "sha512": "962bbfa03d723d7d12039f81390fbf51f3a8042456d62739e6cf99b381006ed89b05a1b74de7deb3c225be7c90fca305d7c2ad4c86cbe5aa9efc709a80b0d428",
          "sha256": "6edc0e9c8dcd201908640a8ecff4351046f7435695ee73a10d6e2f643cb8c6e4",
          "sha1": "466409d11978ab28a0c3dce6dffbe564dd16713b",
          "md5": "f01c1a0ad7a91d29f22db1124d03c2bf"
        }
      ]
    }
  ]
}
