{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "js5server",
    "version": "2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-buffer"
        },
        {
          "group": "net.rsprot",
          "module": "protocol",
          "version": {
            "requires": "1.0.0-ALPHA-20250328"
          }
        },
        {
          "group": "net.rsprot",
          "module": "compression",
          "version": {
            "requires": "1.0.0-ALPHA-20250328"
          }
        },
        {
          "group": "net.rsprot",
          "module": "crypto",
          "version": {
            "requires": "1.0.0-ALPHA-20250328"
          }
        },
        {
          "group": "net.rsprot",
          "module": "osrs-229-common",
          "version": {
            "requires": "1.0.0-ALPHA-20250328"
          }
        },
        {
          "group": "net.rsprot",
          "module": "osrs-229-model",
          "version": {
            "requires": "1.0.0-ALPHA-20250328"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "js5server-2.1.jar",
          "url": "js5server-2.1.jar",
          "size": 224372,
          "sha512": "d9677bbb559fc4e4e31561b62fc915ccc793c24417c86bb40900e75d7758d83cbc6664d2d170d7c3cf3c3b6243bbae6226f230198bac99fa8321cac6a7e9f937",
          "sha256": "e44ddb03f7d40c95921cf62b5eee42d5a6954d99dd1015d6df4c65c725d0ad2e",
          "sha1": "f8700ad5955c9eadabfd80d97f80d6d21874f088",
          "md5": "c9644d669163c0a7d1fa6858fe102a74"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-bom",
          "version": {
            "requires": "4.1.107.Final"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport"
        },
        {
          "group": "io.netty",
          "module": "netty-handler"
        },
        {
          "group": "io.netty",
          "module": "netty-transport-native-epoll"
        },
        {
          "group": "io.netty",
          "module": "netty-transport-native-kqueue"
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-transport-native-io_uring",
          "version": {
            "requires": "0.0.25.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-resolver-dns-native-macos"
        },
        {
          "group": "io.netty",
          "module": "netty-transport-native-epoll",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-transport-native-epoll",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux-aarch_64"
            }
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-native-epoll",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-transport-native-epoll",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux-x86_64"
            }
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-native-epoll",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-transport-native-epoll",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux-riscv64"
            }
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-native-kqueue",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-transport-native-kqueue",
              "type": "jar",
              "extension": "jar",
              "classifier": "osx-x86_64"
            }
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-transport-native-io_uring",
          "version": {
            "requires": "0.0.25.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-incubator-transport-native-io_uring",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux-aarch_64"
            }
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-transport-native-io_uring",
          "version": {
            "requires": "0.0.25.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-incubator-transport-native-io_uring",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux-x86_64"
            }
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "net.rsprot",
          "module": "osrs-229-internal",
          "version": {
            "requires": "1.0.0-ALPHA-20250328"
          }
        },
        {
          "group": "net.rsprot",
          "module": "osrs-229-desktop",
          "version": {
            "requires": "1.0.0-ALPHA-20250328"
          }
        },
        {
          "group": "net.rsprot",
          "module": "osrs-229-shared",
          "version": {
            "requires": "1.0.0-ALPHA-20250328"
          }
        },
        {
          "group": "net.rsprot",
          "module": "buffer",
          "version": {
            "requires": "1.0.0-ALPHA-20250328"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer"
        },
        {
          "group": "net.rsprot",
          "module": "protocol",
          "version": {
            "requires": "1.0.0-ALPHA-20250328"
          }
        },
        {
          "group": "net.rsprot",
          "module": "compression",
          "version": {
            "requires": "1.0.0-ALPHA-20250328"
          }
        },
        {
          "group": "net.rsprot",
          "module": "crypto",
          "version": {
            "requires": "1.0.0-ALPHA-20250328"
          }
        },
        {
          "group": "net.rsprot",
          "module": "osrs-229-common",
          "version": {
            "requires": "1.0.0-ALPHA-20250328"
          }
        },
        {
          "group": "net.rsprot",
          "module": "osrs-229-model",
          "version": {
            "requires": "1.0.0-ALPHA-20250328"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "js5server-2.1.jar",
          "url": "js5server-2.1.jar",
          "size": 224372,
          "sha512": "d9677bbb559fc4e4e31561b62fc915ccc793c24417c86bb40900e75d7758d83cbc6664d2d170d7c3cf3c3b6243bbae6226f230198bac99fa8321cac6a7e9f937",
          "sha256": "e44ddb03f7d40c95921cf62b5eee42d5a6954d99dd1015d6df4c65c725d0ad2e",
          "sha1": "f8700ad5955c9eadabfd80d97f80d6d21874f088",
          "md5": "c9644d669163c0a7d1fa6858fe102a74"
        }
      ]
    }
  ]
}
