{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718-fs",
    "version": "2.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-fs-2.2.8.jar",
          "url": "r718-fs-2.2.8.jar",
          "size": 7588,
          "sha512": "bf3fc26606bd4913ff0539a34827a0345d3523ddf4b68dc5fcd3c1b6ad3cbe80fac3319e3dbe9771f350fa656c122be5ffcd6b29b98bb0a1d849deea82e63980",
          "sha256": "883839a0a7de2156ca53d21f6195f48825611475150ce6180db75406168d6aaa",
          "sha1": "e3d387d0d023f96b5ce2d9a20361e15026c8b258",
          "md5": "dc3c35453666c9b13298ce1a85852f24"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "dev.or2",
          "module": "r718",
          "version": {
            "requires": "2.2.8"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.2.8"
          }
        }
      ],
      "files": [
        {
          "name": "r718-fs-2.2.8.jar",
          "url": "r718-fs-2.2.8.jar",
          "size": 7588,
          "sha512": "bf3fc26606bd4913ff0539a34827a0345d3523ddf4b68dc5fcd3c1b6ad3cbe80fac3319e3dbe9771f350fa656c122be5ffcd6b29b98bb0a1d849deea82e63980",
          "sha256": "883839a0a7de2156ca53d21f6195f48825611475150ce6180db75406168d6aaa",
          "sha1": "e3d387d0d023f96b5ce2d9a20361e15026c8b258",
          "md5": "dc3c35453666c9b13298ce1a85852f24"
        }
      ]
    }
  ]
}
