{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718-fs",
    "version": "2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-fs-2.2.jar",
          "url": "r718-fs-2.2.jar",
          "size": 7588,
          "sha512": "8c1c288e9da4fb86eace94030d1a8695a71095bb089dcabb348b9956dbba23351d1abb4225fd49fcab14e4bedf9eb710c104c0af667edd7f5e06c7e976156dd3",
          "sha256": "83907d6223cb355af6cce3ddfd77a466dbacdef91f398032729e4f85bbfa27a8",
          "sha1": "823fbb5b18387965c4255bf332492a0819ea2849",
          "md5": "a678766bbfb4c2bb76049ff49b0174df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "dev.or2",
          "module": "r718",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "r718-fs-2.2.jar",
          "url": "r718-fs-2.2.jar",
          "size": 7588,
          "sha512": "8c1c288e9da4fb86eace94030d1a8695a71095bb089dcabb348b9956dbba23351d1abb4225fd49fcab14e4bedf9eb710c104c0af667edd7f5e06c7e976156dd3",
          "sha256": "83907d6223cb355af6cce3ddfd77a466dbacdef91f398032729e4f85bbfa27a8",
          "sha1": "823fbb5b18387965c4255bf332492a0819ea2849",
          "md5": "a678766bbfb4c2bb76049ff49b0174df"
        }
      ]
    }
  ]
}
