{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs",
    "version": "2.4.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-2.4.12.jar",
          "url": "osrs-2.4.12.jar",
          "size": 92851,
          "sha512": "219c6241c9e9f44e149836638c53fe414142aaa323b83d62ebe2b172932afc3f3ef9aab1949713de9ebf9833a9c57f6c1fd069e193a52fab838cb8de1dcadd02",
          "sha256": "736da91ee2982decfac70cf0ac604aec241853b5850057daa9d90b7d649e3720",
          "sha1": "29d4f50ca87145e30e5d0d0f1f974b4b1354449f",
          "md5": "b37f0bb657a48d188037dcbb45745c12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.12"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-2.4.12.jar",
          "url": "osrs-2.4.12.jar",
          "size": 92851,
          "sha512": "219c6241c9e9f44e149836638c53fe414142aaa323b83d62ebe2b172932afc3f3ef9aab1949713de9ebf9833a9c57f6c1fd069e193a52fab838cb8de1dcadd02",
          "sha256": "736da91ee2982decfac70cf0ac604aec241853b5850057daa9d90b7d649e3720",
          "sha1": "29d4f50ca87145e30e5d0d0f1f974b4b1354449f",
          "md5": "b37f0bb657a48d188037dcbb45745c12"
        }
      ]
    }
  ]
}
