{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "central-worldlink",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.or2",
          "module": "central-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-worldlink-2.0.0.jar",
          "url": "central-worldlink-2.0.0.jar",
          "size": 187755,
          "sha512": "2eb058c25488bdf8f8b6bdb493b0c1d6107817aaa7740e46347bb5c34bc7992e70110e1f3aec501b9108ae77485644b8953049199e088e0686af297523690cb9",
          "sha256": "a4439498059f72280aecaf459bd142e08113ee864a1f6d4730ff55181390eb96",
          "sha1": "f9418a1049f46d6dd9f3cfc828b1546116510d30",
          "md5": "529e874f7d5b0c404480f90ad03194cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "dev.or2",
          "module": "central-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-worldlink-2.0.0.jar",
          "url": "central-worldlink-2.0.0.jar",
          "size": 187755,
          "sha512": "2eb058c25488bdf8f8b6bdb493b0c1d6107817aaa7740e46347bb5c34bc7992e70110e1f3aec501b9108ae77485644b8953049199e088e0686af297523690cb9",
          "sha256": "a4439498059f72280aecaf459bd142e08113ee864a1f6d4730ff55181390eb96",
          "sha1": "f9418a1049f46d6dd9f3cfc828b1546116510d30",
          "md5": "529e874f7d5b0c404480f90ad03194cc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "central-worldlink-2.0.0-sources.jar",
          "url": "central-worldlink-2.0.0-sources.jar",
          "size": 30166,
          "sha512": "12614527e72238ccf8797c4e18d034327f4fd86d9d1c3fa8f7fa4f71585ca02f881059138a803224c42b41f7c3da1378f7544a5daa59a46991ea8d19e00cc804",
          "sha256": "0581a1eb0cc7e7d49b86ec826d7698d578c637c524d8cbdd7ca1d3f22bdbd108",
          "sha1": "31a27b3da64903e64ede39ad7530c102d4049a1b",
          "md5": "6ba3b51bf2eb81bc97668eda758eafc4"
        }
      ]
    }
  ]
}
