{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "rs3",
    "version": "2.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "rs3-2.4.1.jar",
          "url": "rs3-2.4.1.jar",
          "size": 8872,
          "sha512": "97990d01f0a9c82293aceec0779b6ffd368019d148c863aab088433cef83db7fe95f29e2034e15981ec9b7ed73c8e33a62ee49decbad713df4301e698be5d76c",
          "sha256": "8b3b4ffb80e5acfa9c9c1a63996066b8147f05787430ee4eab61bb2614a78ea1",
          "sha1": "7595f8a397acf859971df1002f677ccfd2c79b9c",
          "md5": "b97d7a2f4ef17ffa828d704984b31211"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "rs3-2.4.1.jar",
          "url": "rs3-2.4.1.jar",
          "size": 8872,
          "sha512": "97990d01f0a9c82293aceec0779b6ffd368019d148c863aab088433cef83db7fe95f29e2034e15981ec9b7ed73c8e33a62ee49decbad713df4301e698be5d76c",
          "sha256": "8b3b4ffb80e5acfa9c9c1a63996066b8147f05787430ee4eab61bb2614a78ea1",
          "sha1": "7595f8a397acf859971df1002f677ccfd2c79b9c",
          "md5": "b97d7a2f4ef17ffa828d704984b31211"
        }
      ]
    }
  ]
}
