{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "definition",
    "version": "2.4.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "definition-2.4.11.jar",
          "url": "definition-2.4.11.jar",
          "size": 531679,
          "sha512": "45eabfed5bd35b2d90f47b04d3adcfd68a1fd7d474e1fb2ae0da089eab9d9532e9aadff4a5e2d766c819e8d26b7a2e97291b904df24a5ea2301fecbbbad56e32",
          "sha256": "fd3f8b828c3be255f2b18b3d777c6df143ad991a3718b0e0fadbacf0d04351fe",
          "sha1": "7126ccaf0308e1bb19e91b78bcf0eee8b14e0bb9",
          "md5": "5651780f508759cc7c806ab3cf3c4077"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "toml-core",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "definition-2.4.11.jar",
          "url": "definition-2.4.11.jar",
          "size": 531679,
          "sha512": "45eabfed5bd35b2d90f47b04d3adcfd68a1fd7d474e1fb2ae0da089eab9d9532e9aadff4a5e2d766c819e8d26b7a2e97291b904df24a5ea2301fecbbbad56e32",
          "sha256": "fd3f8b828c3be255f2b18b3d777c6df143ad991a3718b0e0fadbacf0d04351fe",
          "sha1": "7126ccaf0308e1bb19e91b78bcf0eee8b14e0bb9",
          "md5": "5651780f508759cc7c806ab3cf3c4077"
        }
      ]
    }
  ]
}
