{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "rs3",
    "version": "3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "rs3-3.0.2.jar",
          "url": "rs3-3.0.2.jar",
          "size": 9395,
          "sha512": "d833a739be57d61746413b67835e7daf78c6321b1ffc4a4d875c7c0811e1cee70debcb9e6b534dc6ed3132153c374521b89c115e48a9ee921a98c8dbe0fc438e",
          "sha256": "0cf2f5269fb45a93da79ec60a5e157da2415e653779c003349bcbfa322c1aeb5",
          "sha1": "b815c97cf28bf82423a83ae2220b1b807e0c07b3",
          "md5": "4e1d729e39ed6ef252c677a613568d1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "rs3-3.0.2.jar",
          "url": "rs3-3.0.2.jar",
          "size": 9395,
          "sha512": "d833a739be57d61746413b67835e7daf78c6321b1ffc4a4d875c7c0811e1cee70debcb9e6b534dc6ed3132153c374521b89c115e48a9ee921a98c8dbe0fc438e",
          "sha256": "0cf2f5269fb45a93da79ec60a5e157da2415e653779c003349bcbfa322c1aeb5",
          "sha1": "b815c97cf28bf82423a83ae2220b1b807e0c07b3",
          "md5": "4e1d729e39ed6ef252c677a613568d1f"
        }
      ]
    }
  ]
}
