{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "bootstrap",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "bootstrap-1.0.0.jar",
          "url": "bootstrap-1.0.0.jar",
          "size": 51772,
          "sha512": "caef5a363cb8ce4f00e42ad6cfdc1e8fa4cb19dbdd7e467fa7c6f814425a41c9c465e105f674b5fa1cc069a804c4636ffe519ec55e030234d0667f69ebed71af",
          "sha256": "2b988dccfb5fd4e5711560f78e1f89bbbfa292d5b94639f18b98a1e8639ae29d",
          "sha1": "edeeb9d54ec85adbc35f606a0ebf0ffcd3c8cde6",
          "md5": "29e98fc1936911f3edd4e931be7e5827"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awssdk",
          "module": "s3",
          "version": {
            "requires": "2.17.207"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "com.beust",
          "module": "klaxon",
          "version": {
            "requires": "5.5"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "1.12.5"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.29"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.2"
          }
        },
        {
          "group": "com.jcraft",
          "module": "jsch",
          "version": {
            "requires": "0.1.55"
          }
        }
      ],
      "files": [
        {
          "name": "bootstrap-1.0.0.jar",
          "url": "bootstrap-1.0.0.jar",
          "size": 51772,
          "sha512": "caef5a363cb8ce4f00e42ad6cfdc1e8fa4cb19dbdd7e467fa7c6f814425a41c9c465e105f674b5fa1cc069a804c4636ffe519ec55e030234d0667f69ebed71af",
          "sha256": "2b988dccfb5fd4e5711560f78e1f89bbbfa292d5b94639f18b98a1e8639ae29d",
          "sha1": "edeeb9d54ec85adbc35f606a0ebf0ffcd3c8cde6",
          "md5": "29e98fc1936911f3edd4e931be7e5827"
        }
      ]
    }
  ]
}
