{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "bootstrap",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "bootstrap-1.0.0.jar",
          "url": "bootstrap-1.0.0.jar",
          "size": 51749,
          "sha512": "aea837d4160ca716dcece552e1ae5670134c41ffd3bdb9b73f7ed80e8d78e3c62b2a1bf2dbddc883522a85812caf4322e19761911c61eb84150f57f106d46dc7",
          "sha256": "57f35af1b9460b9e7cd996f86bfaa1d47dedbcf831b380dbee1310495b078975",
          "sha1": "deb92493fdd25ac65f227cfdd96d17a43b3b7dea",
          "md5": "ad3f0402a0eaf51d6a77dbee2a99b327"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awssdk",
          "module": "s3",
          "version": {
            "requires": "2.17.207"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "com.beust",
          "module": "klaxon",
          "version": {
            "requires": "5.5"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "1.12.5"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.29"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.2"
          }
        },
        {
          "group": "com.jcraft",
          "module": "jsch",
          "version": {
            "requires": "0.1.55"
          }
        }
      ],
      "files": [
        {
          "name": "bootstrap-1.0.0.jar",
          "url": "bootstrap-1.0.0.jar",
          "size": 51749,
          "sha512": "aea837d4160ca716dcece552e1ae5670134c41ffd3bdb9b73f7ed80e8d78e3c62b2a1bf2dbddc883522a85812caf4322e19761911c61eb84150f57f106d46dc7",
          "sha256": "57f35af1b9460b9e7cd996f86bfaa1d47dedbcf831b380dbee1310495b078975",
          "sha1": "deb92493fdd25ac65f227cfdd96d17a43b3b7dea",
          "md5": "ad3f0402a0eaf51d6a77dbee2a99b327"
        }
      ]
    }
  ]
}
