{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "bootstrap",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "bootstrap-1.0.0.jar",
          "url": "bootstrap-1.0.0.jar",
          "size": 51772,
          "sha512": "0b1fcb1139e92fe5902161ca16edc262a42b2b28b3b53021f0202a131e5f9b5734461c241f9d1315688ea001093ea627b39f3f683fc065cdc767019945457eec",
          "sha256": "0ab1a76909ed4421eaca279ca19c21f58ea643988a5ac25d8ace730a83b3b819",
          "sha1": "2bf82658e45273452051655cc3609fd839ff2409",
          "md5": "6bfd89c8b50b71c95f72447e379a2d41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awssdk",
          "module": "s3",
          "version": {
            "requires": "2.17.207"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "com.beust",
          "module": "klaxon",
          "version": {
            "requires": "5.5"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "1.12.5"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.29"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.2"
          }
        },
        {
          "group": "com.jcraft",
          "module": "jsch",
          "version": {
            "requires": "0.1.55"
          }
        }
      ],
      "files": [
        {
          "name": "bootstrap-1.0.0.jar",
          "url": "bootstrap-1.0.0.jar",
          "size": 51772,
          "sha512": "0b1fcb1139e92fe5902161ca16edc262a42b2b28b3b53021f0202a131e5f9b5734461c241f9d1315688ea001093ea627b39f3f683fc065cdc767019945457eec",
          "sha256": "0ab1a76909ed4421eaca279ca19c21f58ea643988a5ac25d8ace730a83b3b819",
          "sha1": "2bf82658e45273452051655cc3609fd839ff2409",
          "md5": "6bfd89c8b50b71c95f72447e379a2d41"
        }
      ]
    }
  ]
}
