{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs",
    "version": "2.4.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-2.4.20.jar",
          "url": "osrs-2.4.20.jar",
          "size": 92818,
          "sha512": "897043c77534cf889f2c98d3b2fb42073f28f43c764f1e4581f6c2ef40e24da8905ee9e3148aff2d4b00be866e4602a6405ce2ddaa89386dc1e4a59185e29a62",
          "sha256": "d43abe6207a4616623de9723460360009fc1ba2c55c2e7769c30f118fe765aea",
          "sha1": "f6f7ab656fbb329ac3f1227d23f7ceffa5b708c7",
          "md5": "31584f9211da7a0b80c6034d3790cb90"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-2.4.20.jar",
          "url": "osrs-2.4.20.jar",
          "size": 92818,
          "sha512": "897043c77534cf889f2c98d3b2fb42073f28f43c764f1e4581f6c2ef40e24da8905ee9e3148aff2d4b00be866e4602a6405ce2ddaa89386dc1e4a59185e29a62",
          "sha256": "d43abe6207a4616623de9723460360009fc1ba2c55c2e7769c30f118fe765aea",
          "sha1": "f6f7ab656fbb329ac3f1227d23f7ceffa5b708c7",
          "md5": "31584f9211da7a0b80c6034d3790cb90"
        }
      ]
    }
  ]
}
