{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs-fs",
    "version": "2.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-fs-2.4.5.jar",
          "url": "osrs-fs-2.4.5.jar",
          "size": 27384,
          "sha512": "055a6ad1448203a371c5a4fe7665b21d0cb0152c0a85e2acb127ac6917f6f1c603ecd4727cb25313a87bada609c4d73c34ddc8b799458132a51733729c0d78a9",
          "sha256": "80aa462a2935bf16093080f787b71e1e868ccb9bba10a9742524bb34eb64e524",
          "sha1": "e3e510fd62064e585b48b1bf8ca248faaaccb466",
          "md5": "6e4741b374bb9b709c427f78e51b3b44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.4.5"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.5"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.4.5"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.5"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-fs-2.4.5.jar",
          "url": "osrs-fs-2.4.5.jar",
          "size": 27384,
          "sha512": "055a6ad1448203a371c5a4fe7665b21d0cb0152c0a85e2acb127ac6917f6f1c603ecd4727cb25313a87bada609c4d73c34ddc8b799458132a51733729c0d78a9",
          "sha256": "80aa462a2935bf16093080f787b71e1e868ccb9bba10a9742524bb34eb64e524",
          "sha1": "e3e510fd62064e585b48b1bf8ca248faaaccb466",
          "md5": "6e4741b374bb9b709c427f78e51b3b44"
        }
      ]
    }
  ]
}
