{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.0.11.jar",
          "url": "displee-2.0.11.jar",
          "size": 112130,
          "sha512": "388ce6b5c57392e1de4d5a192e3744a28e0a88b12934383f105918f8c3a7f071589ab4179382a60ac924d8742a17073a7e56b2650d8ae822f25437cec438d138",
          "sha256": "676ba72d0fdb78dce3499bd3f109e1735eca4714f8cdc87d48010efec8f1e746",
          "sha1": "297cd45c77e1d7859cf187e259f408eab0f19216",
          "md5": "5fb6f3c4264fd1f84de2e37d0c1349da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.0.11.jar",
          "url": "displee-2.0.11.jar",
          "size": 112130,
          "sha512": "388ce6b5c57392e1de4d5a192e3744a28e0a88b12934383f105918f8c3a7f071589ab4179382a60ac924d8742a17073a7e56b2650d8ae822f25437cec438d138",
          "sha256": "676ba72d0fdb78dce3499bd3f109e1735eca4714f8cdc87d48010efec8f1e746",
          "sha1": "297cd45c77e1d7859cf187e259f408eab0f19216",
          "md5": "5fb6f3c4264fd1f84de2e37d0c1349da"
        }
      ]
    }
  ]
}
