{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "definition",
    "version": "2.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "definition-2.3.9.jar",
          "url": "definition-2.3.9.jar",
          "size": 466969,
          "sha512": "793a5a3ec87c89cba9d70187f904ee568e379013783c2b6fc747c340aa0d4fe3e080bb475608755420b845560c5cf0718b3b5ee5c3340f5c4b4335fa059748b1",
          "sha256": "1b1f04f8be2c4c4ea94c2388fd34d7ccc5abf15ecde35cf3b4ecee0e9fbb27a0",
          "sha1": "2c83b62039a5709b073a78df6c1b44d7a364ce12",
          "md5": "23cfc92c44cdbd004476ebd7fb1a9c80"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        }
      ],
      "files": [
        {
          "name": "definition-2.3.9.jar",
          "url": "definition-2.3.9.jar",
          "size": 466969,
          "sha512": "793a5a3ec87c89cba9d70187f904ee568e379013783c2b6fc747c340aa0d4fe3e080bb475608755420b845560c5cf0718b3b5ee5c3340f5c4b4335fa059748b1",
          "sha256": "1b1f04f8be2c4c4ea94c2388fd34d7ccc5abf15ecde35cf3b4ecee0e9fbb27a0",
          "sha1": "2c83b62039a5709b073a78df6c1b44d7a364ce12",
          "md5": "23cfc92c44cdbd004476ebd7fb1a9c80"
        }
      ]
    }
  ]
}
