{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.0.15.jar",
          "url": "displee-2.0.15.jar",
          "size": 111913,
          "sha512": "d2925074a94c7e2739e5f69d15cd2d00f93ba1134a5d62d435f167a45c3328a55468b4bd4611bea050278a0bb4ce2a8103f23a0726a18170332bf59a2f7c6576",
          "sha256": "d7c1347630cb19ccd7d85daa4367cc03ed33ce025a624a994ef5bcd8fd3bff42",
          "sha1": "179dfc5999257cf84da8a269d8a0458e75189c7f",
          "md5": "0b780d248743f0211115aca3100ff644"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.0.15.jar",
          "url": "displee-2.0.15.jar",
          "size": 111913,
          "sha512": "d2925074a94c7e2739e5f69d15cd2d00f93ba1134a5d62d435f167a45c3328a55468b4bd4611bea050278a0bb4ce2a8103f23a0726a18170332bf59a2f7c6576",
          "sha256": "d7c1347630cb19ccd7d85daa4367cc03ed33ce025a624a994ef5bcd8fd3bff42",
          "sha1": "179dfc5999257cf84da8a269d8a0458e75189c7f",
          "md5": "0b780d248743f0211115aca3100ff644"
        }
      ]
    }
  ]
}
