{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "tools",
    "version": "2.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "tools-2.0.11.jar",
          "url": "tools-2.0.11.jar",
          "size": 172568,
          "sha512": "51715f4799c72d9f295f0c975b51c006786000b36b5daead3a851f37e9aede70469038afbf01165ff39229b0d0fda3c64cb174244bb8e0a1e0bd305a9c46ec58",
          "sha256": "9a545cf36c5d370ca74baf3f6d399b79fd240ee9e7c673e72f86db9f6b47161b",
          "sha1": "1278998be01da0be2e27f1effcda747680e02d93",
          "md5": "22a62a800f5fb7c1c0a02d22be90e78b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.0.11"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.0.11"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.11"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.0.11"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs-fs",
          "version": {
            "requires": "2.0.11"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.11.5"
          }
        },
        {
          "group": "cc.ekblad",
          "module": "4koma",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "dev.or2",
          "module": "displee",
          "version": {
            "requires": "2.0.11"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-file",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "tools-2.0.11.jar",
          "url": "tools-2.0.11.jar",
          "size": 172568,
          "sha512": "51715f4799c72d9f295f0c975b51c006786000b36b5daead3a851f37e9aede70469038afbf01165ff39229b0d0fda3c64cb174244bb8e0a1e0bd305a9c46ec58",
          "sha256": "9a545cf36c5d370ca74baf3f6d399b79fd240ee9e7c673e72f86db9f6b47161b",
          "sha1": "1278998be01da0be2e27f1effcda747680e02d93",
          "md5": "22a62a800f5fb7c1c0a02d22be90e78b"
        }
      ]
    }
  ]
}
