{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.3.9.jar",
          "url": "displee-2.3.9.jar",
          "size": 111913,
          "sha512": "36e663c6c1d749a73b402e5690b185e04353fff1d991504e52002d41da91db991c839999154449f16dde173af0ddb3243cb61d550c500c483cc832bedc0cbefd",
          "sha256": "8127ffbb33543cbb07a16a4f076ed12036ad00f6f0f983f14493fdcfb4272559",
          "sha1": "4d6353505febe98242a6fbe05980ed8796966633",
          "md5": "45072ea1cdfedea0ad4c27e5a4021b51"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.3.9.jar",
          "url": "displee-2.3.9.jar",
          "size": 111913,
          "sha512": "36e663c6c1d749a73b402e5690b185e04353fff1d991504e52002d41da91db991c839999154449f16dde173af0ddb3243cb61d550c500c483cc832bedc0cbefd",
          "sha256": "8127ffbb33543cbb07a16a4f076ed12036ad00f6f0f983f14493fdcfb4272559",
          "sha1": "4d6353505febe98242a6fbe05980ed8796966633",
          "md5": "45072ea1cdfedea0ad4c27e5a4021b51"
        }
      ]
    }
  ]
}
