{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs-fs",
    "version": "2.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-fs-2.3.4.jar",
          "url": "osrs-fs-2.3.4.jar",
          "size": 22316,
          "sha512": "c49873b680d393250e3f3f370248bf867a12936e526dcbedce9aa4000a081cc03c091d086c9b98c1bf8440a2816ac3315c3555c6a945b062ee70aaf8bb9a78de",
          "sha256": "78d89682dda95205c630b5bd15f0d11c6781ed05146b3ba571146ac10da2359b",
          "sha1": "c9ee7628d5ec2c9cc67233289f333582794539af",
          "md5": "2b6aa7ea19a9e20c2ca23c5cbba0c900"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.3.4"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.3.4"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.3.4"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-fs-2.3.4.jar",
          "url": "osrs-fs-2.3.4.jar",
          "size": 22316,
          "sha512": "c49873b680d393250e3f3f370248bf867a12936e526dcbedce9aa4000a081cc03c091d086c9b98c1bf8440a2816ac3315c3555c6a945b062ee70aaf8bb9a78de",
          "sha256": "78d89682dda95205c630b5bd15f0d11c6781ed05146b3ba571146ac10da2359b",
          "sha1": "c9ee7628d5ec2c9cc67233289f333582794539af",
          "md5": "2b6aa7ea19a9e20c2ca23c5cbba0c900"
        }
      ]
    }
  ]
}
