{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "filestore",
    "version": "1.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-1.2.9.jar",
          "url": "filestore-1.2.9.jar",
          "size": 366095,
          "sha512": "223d6cece8b40a5aefe83760a831ce9e126116af391ad59d0884aa0ea94cfe9949afc58337009681c28ca544aeadcd9fa72963d065cca1b3c541cbd29e13cdb4",
          "sha256": "2d9f1210377f724aea7d62e640b1a46faeb2028ffbc72c6619aebdd1b60739ce",
          "sha1": "96e33ec55ab89b038a51ad23f0fdf6eace0ff2d8",
          "md5": "8bf28a5e114d344cf25a05411266c85e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.beust",
          "module": "klaxon",
          "version": {
            "requires": "5.5"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.displee",
          "module": "rs-cache-library",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-1.2.9.jar",
          "url": "filestore-1.2.9.jar",
          "size": 366095,
          "sha512": "223d6cece8b40a5aefe83760a831ce9e126116af391ad59d0884aa0ea94cfe9949afc58337009681c28ca544aeadcd9fa72963d065cca1b3c541cbd29e13cdb4",
          "sha256": "2d9f1210377f724aea7d62e640b1a46faeb2028ffbc72c6619aebdd1b60739ce",
          "sha1": "96e33ec55ab89b038a51ad23f0fdf6eace0ff2d8",
          "md5": "8bf28a5e114d344cf25a05411266c85e"
        }
      ]
    }
  ]
}
