{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "opcode",
    "version": "2.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "opcode-2.3.5.jar",
          "url": "opcode-2.3.5.jar",
          "size": 197282,
          "sha512": "196c0d48fd703240179e893616deb1a902c311d493667aa2d75cf74db9e41422b55be5507aaac1a01530bcfa9a3a76a10c23f653b4bf07155104bd187fb89bf5",
          "sha256": "84524442d156965e4101a3c9f22d0793e5951042f7a1ba80a9aba0b0b2968d5b",
          "sha1": "eb4387b2b7ad3942c7410ac0846807408c3ed97c",
          "md5": "643c28da070325c17658d9e4769a87f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "opcode-2.3.5.jar",
          "url": "opcode-2.3.5.jar",
          "size": 197282,
          "sha512": "196c0d48fd703240179e893616deb1a902c311d493667aa2d75cf74db9e41422b55be5507aaac1a01530bcfa9a3a76a10c23f653b4bf07155104bd187fb89bf5",
          "sha256": "84524442d156965e4101a3c9f22d0793e5951042f7a1ba80a9aba0b0b2968d5b",
          "sha1": "eb4387b2b7ad3942c7410ac0846807408c3ed97c",
          "md5": "643c28da070325c17658d9e4769a87f6"
        }
      ]
    }
  ]
}
