{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.4.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.4.17.jar",
          "url": "displee-2.4.17.jar",
          "size": 111913,
          "sha512": "bad663e2f4c993216ac2e4d7e05d2dc3e49cb1675277b54dcf1b425d29d8c237dc6c89883424051a7b58658d5c698e54fa622cd3f1a532b4cbe9ea9553d09ff9",
          "sha256": "95f6fab6149979164dfa2e6181a2b8a12d5c922668850bd47a717af6a853a807",
          "sha1": "64f28e02ce0a4fb69343357f7e62b7c15957e387",
          "md5": "df700e9eaab4a57fcaf0a5484854c21d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.4.17.jar",
          "url": "displee-2.4.17.jar",
          "size": 111913,
          "sha512": "bad663e2f4c993216ac2e4d7e05d2dc3e49cb1675277b54dcf1b425d29d8c237dc6c89883424051a7b58658d5c698e54fa622cd3f1a532b4cbe9ea9553d09ff9",
          "sha256": "95f6fab6149979164dfa2e6181a2b8a12d5c922668850bd47a717af6a853a807",
          "sha1": "64f28e02ce0a4fb69343357f7e62b7c15957e387",
          "md5": "df700e9eaab4a57fcaf0a5484854c21d"
        }
      ]
    }
  ]
}
