{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "rs3",
    "version": "2.4.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "rs3-2.4.19.jar",
          "url": "rs3-2.4.19.jar",
          "size": 8903,
          "sha512": "733578c0bb9bf8cac7a01c7b2eb33c4378006ecde238579aeb20a848e664dde2dbd93887a2236adaa22376741186b863a59f9281a1b6a62c306063b49b0512b2",
          "sha256": "bac3a8612f8955e7f670377d8330df91a5bf859d9448ad60ddac1b51860e91e0",
          "sha1": "bfc0cf14e9cb238e8e3f1d03ef125f7955a224d6",
          "md5": "c59f5d26d978bbd54a7781119d2cefdf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.19"
          }
        }
      ],
      "files": [
        {
          "name": "rs3-2.4.19.jar",
          "url": "rs3-2.4.19.jar",
          "size": 8903,
          "sha512": "733578c0bb9bf8cac7a01c7b2eb33c4378006ecde238579aeb20a848e664dde2dbd93887a2236adaa22376741186b863a59f9281a1b6a62c306063b49b0512b2",
          "sha256": "bac3a8612f8955e7f670377d8330df91a5bf859d9448ad60ddac1b51860e91e0",
          "sha1": "bfc0cf14e9cb238e8e3f1d03ef125f7955a224d6",
          "md5": "c59f5d26d978bbd54a7781119d2cefdf"
        }
      ]
    }
  ]
}
