{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs-fs",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-fs-2.0.0.jar",
          "url": "osrs-fs-2.0.0.jar",
          "size": 22442,
          "sha512": "6eca7f5819d6f85fc06d108c34b08c8f43e7c42642f6435ad54da591e3286d0c0123b5979c1767e84584db2bebdeda7712aa6f4d122756448cdafeb86a05db3e",
          "sha256": "ee5777e4fc9bdc371bbb5581c591a2c5fb0713cdeaa0b5ea9840b4cfcc26b4ef",
          "sha1": "3964896e63ad3db816d3d31dc71fa03c7a9338f3",
          "md5": "9164e24719459ac08ba935fd55c8611f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-fs-2.0.0.jar",
          "url": "osrs-fs-2.0.0.jar",
          "size": 22442,
          "sha512": "6eca7f5819d6f85fc06d108c34b08c8f43e7c42642f6435ad54da591e3286d0c0123b5979c1767e84584db2bebdeda7712aa6f4d122756448cdafeb86a05db3e",
          "sha256": "ee5777e4fc9bdc371bbb5581c591a2c5fb0713cdeaa0b5ea9840b4cfcc26b4ef",
          "sha1": "3964896e63ad3db816d3d31dc71fa03c7a9338f3",
          "md5": "9164e24719459ac08ba935fd55c8611f"
        }
      ]
    }
  ]
}
