{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filestore",
    "version": "2.4.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-2.4.11.jar",
          "url": "filestore-2.4.11.jar",
          "size": 97539,
          "sha512": "571a1354f94fd4de324a34894f3231011cba983de171f4d10bdb25d9122346200ea0a93fe81975a875c457705e7961f29d0d69c73c444cdcf1775dc1636e6817",
          "sha256": "b6fa1d8a91f3e1ac0ad23d79f368f465cf1bdfc1fc565ac17f6f8e5b73818342",
          "sha1": "1a0fb7dec075281662772e6c761b77249e43cc0f",
          "md5": "79d1db4b4198301b822620cca1d5baf9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.11"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.11"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-2.4.11.jar",
          "url": "filestore-2.4.11.jar",
          "size": 97539,
          "sha512": "571a1354f94fd4de324a34894f3231011cba983de171f4d10bdb25d9122346200ea0a93fe81975a875c457705e7961f29d0d69c73c444cdcf1775dc1636e6817",
          "sha256": "b6fa1d8a91f3e1ac0ad23d79f368f465cf1bdfc1fc565ac17f6f8e5b73818342",
          "sha1": "1a0fb7dec075281662772e6c761b77249e43cc0f",
          "md5": "79d1db4b4198301b822620cca1d5baf9"
        }
      ]
    }
  ]
}
