{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "rs3",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "rs3-2.4.0.jar",
          "url": "rs3-2.4.0.jar",
          "size": 8872,
          "sha512": "f0bb827d7a3764ca9223865e6cc2cc7aff5a9e423fe343e0fb1a0543627af425f013427858d1f304da17d9d82a5c3ad728f823e8cbd87f007a1964d2b7b7988c",
          "sha256": "f819f4639204ba6c885cebfcb7c2cce0f8c318fc6bd916fad44d67d30b7f746d",
          "sha1": "7b7b25b303e20e79f36583c9abcac4ae75911ef4",
          "md5": "15f97d1d5f9ebdb63a8498582982bb22"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "rs3-2.4.0.jar",
          "url": "rs3-2.4.0.jar",
          "size": 8872,
          "sha512": "f0bb827d7a3764ca9223865e6cc2cc7aff5a9e423fe343e0fb1a0543627af425f013427858d1f304da17d9d82a5c3ad728f823e8cbd87f007a1964d2b7b7988c",
          "sha256": "f819f4639204ba6c885cebfcb7c2cce0f8c318fc6bd916fad44d67d30b7f746d",
          "sha1": "7b7b25b303e20e79f36583c9abcac4ae75911ef4",
          "md5": "15f97d1d5f9ebdb63a8498582982bb22"
        }
      ]
    }
  ]
}
