{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs",
    "version": "2.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-2.2.1.jar",
          "url": "osrs-2.2.1.jar",
          "size": 81484,
          "sha512": "43f4fc1dfe0e4a17e167446c8751ffab7682dabd7b9ef18ee6e4c252cd9acd87ae0ddc70bebd0b968c36cfc52694dd7d8cc528ca6fd8fc90454ec7c83eba5327",
          "sha256": "2649f3295a9cd1c589b1044a1ba418db56c89b97fdb8a552c08aa685dcb197a3",
          "sha1": "cb13d95c0e0699bfac99d9b4ac4b608fe565cd48",
          "md5": "56a5f654c60899efde0262b60c86afda"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-2.2.1.jar",
          "url": "osrs-2.2.1.jar",
          "size": 81484,
          "sha512": "43f4fc1dfe0e4a17e167446c8751ffab7682dabd7b9ef18ee6e4c252cd9acd87ae0ddc70bebd0b968c36cfc52694dd7d8cc528ca6fd8fc90454ec7c83eba5327",
          "sha256": "2649f3295a9cd1c589b1044a1ba418db56c89b97fdb8a552c08aa685dcb197a3",
          "sha1": "cb13d95c0e0699bfac99d9b4ac4b608fe565cd48",
          "md5": "56a5f654c60899efde0262b60c86afda"
        }
      ]
    }
  ]
}
