{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "definition",
    "version": "2.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "definition-2.3.4.jar",
          "url": "definition-2.3.4.jar",
          "size": 374160,
          "sha512": "d32e65a2495133b6d6933359b7b2b9f307d3ef92300f89e9f59ee32d1b7f28aaf836aa0723927489dcce4e0f101c926cd6db21b8619ecbc6bbe11a309276998f",
          "sha256": "503cf4ad3fc46bd19354b1aa76e067b9f1e8a714fc28fc2a86d7f7cdd82eafd7",
          "sha1": "29c29f34a59a4311f92759f899d9c1751c7f6001",
          "md5": "20604e3ece7e9f4f5de63de5a6efcfaa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        }
      ],
      "files": [
        {
          "name": "definition-2.3.4.jar",
          "url": "definition-2.3.4.jar",
          "size": 374160,
          "sha512": "d32e65a2495133b6d6933359b7b2b9f307d3ef92300f89e9f59ee32d1b7f28aaf836aa0723927489dcce4e0f101c926cd6db21b8619ecbc6bbe11a309276998f",
          "sha256": "503cf4ad3fc46bd19354b1aa76e067b9f1e8a714fc28fc2a86d7f7cdd82eafd7",
          "sha1": "29c29f34a59a4311f92759f899d9c1751c7f6001",
          "md5": "20604e3ece7e9f4f5de63de5a6efcfaa"
        }
      ]
    }
  ]
}
