{
  "formatVersion": "1.1",
  "component": {
    "group": "org.openrs2",
    "module": "openrs2-inject",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.google.inject.extensions",
          "module": "guice-assistedinject",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "openrs2-inject-0.1.2-SNAPSHOT.jar",
          "url": "openrs2-inject-0.1.2-SNAPSHOT.jar",
          "size": 3579,
          "sha512": "ad271c2dbaf27104980ddf34e0e6b1d9022bbb10a3c807e7853833fb260751b7a7fc20bdb3c0da535c7980fb1480335ed9890a1510f48197257a2b01d3a12efa",
          "sha256": "13842e6f101ca184a93c5e3b0353649a67daf6b2e472ca794029802973d4173f",
          "sha1": "186c640c0eba5b63d297065248c911dedabfe126",
          "md5": "68cf0587f5280323f60ef245aa370895"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.google.inject.extensions",
          "module": "guice-assistedinject",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "openrs2-inject-0.1.2-SNAPSHOT.jar",
          "url": "openrs2-inject-0.1.2-SNAPSHOT.jar",
          "size": 3579,
          "sha512": "ad271c2dbaf27104980ddf34e0e6b1d9022bbb10a3c807e7853833fb260751b7a7fc20bdb3c0da535c7980fb1480335ed9890a1510f48197257a2b01d3a12efa",
          "sha256": "13842e6f101ca184a93c5e3b0353649a67daf6b2e472ca794029802973d4173f",
          "sha1": "186c640c0eba5b63d297065248c911dedabfe126",
          "md5": "68cf0587f5280323f60ef245aa370895"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "openrs2-inject-0.1.2-SNAPSHOT-sources.jar",
          "url": "openrs2-inject-0.1.2-SNAPSHOT-sources.jar",
          "size": 1000,
          "sha512": "d08350418a3080532f65db25197ec9a7395b062f33eeebf02792f07134f602402bfe0a3aeed76431cf841e1eacfaeaac62e734784a2e39a9bf587459b9057b6b",
          "sha256": "4b96868d99b570272f2b48b3431772c4e4b45d8e24bc8625802d58aba1512c04",
          "sha1": "1d98f8cc8bb5f17ce7ea0b654333450353d21301",
          "md5": "c95d7f6226defcf5f59610825a9865db"
        },
        {
          "name": "openrs2-inject-0.1.2-SNAPSHOT-sources.jar",
          "url": "openrs2-inject-0.1.2-SNAPSHOT-sources.jar",
          "size": 1000,
          "sha512": "d08350418a3080532f65db25197ec9a7395b062f33eeebf02792f07134f602402bfe0a3aeed76431cf841e1eacfaeaac62e734784a2e39a9bf587459b9057b6b",
          "sha256": "4b96868d99b570272f2b48b3431772c4e4b45d8e24bc8625802d58aba1512c04",
          "sha1": "1d98f8cc8bb5f17ce7ea0b654333450353d21301",
          "md5": "c95d7f6226defcf5f59610825a9865db"
        }
      ]
    }
  ]
}
