{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "rs3",
    "version": "3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "rs3-3.0.jar",
          "url": "rs3-3.0.jar",
          "size": 8746,
          "sha512": "a286259a5b2e4fa65cda8e53dafe026016c5ef9170d74aa59ebe1c29ab3be986a00098b05ecce51faa396c257d10ddf2486df989a589c82765423b442c8c2a96",
          "sha256": "5344d0ec19532dccb3a9ea57bcf91ad3368f823d562d1b0bb443c6b0d7b69c42",
          "sha1": "502fe4913085bd4670f34a1afd2e50774693dea1",
          "md5": "b7f06417b18c0b9cf1bb12a50d2e2fb7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "3.0"
          }
        }
      ],
      "files": [
        {
          "name": "rs3-3.0.jar",
          "url": "rs3-3.0.jar",
          "size": 8746,
          "sha512": "a286259a5b2e4fa65cda8e53dafe026016c5ef9170d74aa59ebe1c29ab3be986a00098b05ecce51faa396c257d10ddf2486df989a589c82765423b442c8c2a96",
          "sha256": "5344d0ec19532dccb3a9ea57bcf91ad3368f823d562d1b0bb443c6b0d7b69c42",
          "sha1": "502fe4913085bd4670f34a1afd2e50774693dea1",
          "md5": "b7f06417b18c0b9cf1bb12a50d2e2fb7"
        }
      ]
    }
  ]
}
