{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "rs3",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "rs3-2.3.0.jar",
          "url": "rs3-2.3.0.jar",
          "size": 8746,
          "sha512": "ba712c72e408a31a1b8e3e5ea3ee7e6b6a2ea223bc03d13180befa85c8d1669ec8da0c44d83801453d7b2ff462365d3f78d357851e6c6c2da774fb92b40df5c3",
          "sha256": "7ea4409994748054fa2a74233448fddea747dd78d1ca64762178370c38a4a617",
          "sha1": "eb0edb3a8dc0f3b8bfc6ae49b0a1c03e73a4984b",
          "md5": "29b709fed8cc1f450d53ea1e089b6864"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "rs3-2.3.0.jar",
          "url": "rs3-2.3.0.jar",
          "size": 8746,
          "sha512": "ba712c72e408a31a1b8e3e5ea3ee7e6b6a2ea223bc03d13180befa85c8d1669ec8da0c44d83801453d7b2ff462365d3f78d357851e6c6c2da774fb92b40df5c3",
          "sha256": "7ea4409994748054fa2a74233448fddea747dd78d1ca64762178370c38a4a617",
          "sha1": "eb0edb3a8dc0f3b8bfc6ae49b0a1c03e73a4984b",
          "md5": "29b709fed8cc1f450d53ea1e089b6864"
        }
      ]
    }
  ]
}
