{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "wiki",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.or2",
          "module": "filestore-server",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "wiki-0.1.jar",
          "url": "wiki-0.1.jar",
          "size": 145399,
          "sha512": "0fbbd695c419c0271986fbb2473cbab19ce1109607b83a31bf10312b98edd46690d27eaa17d125f8572cb4d0da64d8772d00b957fd648b919b158a2a1d07d914",
          "sha256": "95c6effaa53cc3ba9f68ba6dda326b7fb1fea506c74d2d570eefd0bdfefa8056",
          "sha1": "d48c13ae45fcf93de8dc90551303eebb2edb769d",
          "md5": "6433743cc2df4e45091684db55c7381b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.or2",
          "module": "all",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.12.1"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.5"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.26.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "org.sweble.wikitext",
          "module": "swc-engine",
          "version": {
            "requires": "3.1.9"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore-server",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "wiki-0.1.jar",
          "url": "wiki-0.1.jar",
          "size": 145399,
          "sha512": "0fbbd695c419c0271986fbb2473cbab19ce1109607b83a31bf10312b98edd46690d27eaa17d125f8572cb4d0da64d8772d00b957fd648b919b158a2a1d07d914",
          "sha256": "95c6effaa53cc3ba9f68ba6dda326b7fb1fea506c74d2d570eefd0bdfefa8056",
          "sha1": "d48c13ae45fcf93de8dc90551303eebb2edb769d",
          "md5": "6433743cc2df4e45091684db55c7381b"
        }
      ]
    }
  ]
}
