{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "rs3",
    "version": "2.4.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "rs3-2.4.8.jar",
          "url": "rs3-2.4.8.jar",
          "size": 8903,
          "sha512": "5a6522326fa25eba16c15e0197bfbd00b1a2e379ea1bdcf17178d24d6ea2910f53d22a0cd5e377bd1e64a943374348c142b93d15ebfa1a3044ab0d8d7dce57c4",
          "sha256": "1a8977200b7bb4a9c56bd4099fa2af9a9d909bbc8baa98c832597f2152d5802d",
          "sha1": "cf06335fde7f42b3d8bc3e04d7e99aa537a4da59",
          "md5": "5f440d1584695b5c48aa27299f54ba02"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "rs3-2.4.8.jar",
          "url": "rs3-2.4.8.jar",
          "size": 8903,
          "sha512": "5a6522326fa25eba16c15e0197bfbd00b1a2e379ea1bdcf17178d24d6ea2910f53d22a0cd5e377bd1e64a943374348c142b93d15ebfa1a3044ab0d8d7dce57c4",
          "sha256": "1a8977200b7bb4a9c56bd4099fa2af9a9d909bbc8baa98c832597f2152d5802d",
          "sha1": "cf06335fde7f42b3d8bc3e04d7e99aa537a4da59",
          "md5": "5f440d1584695b5c48aa27299f54ba02"
        }
      ]
    }
  ]
}
