{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "tools",
    "version": "2.4.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "tools-2.4.12.jar",
          "url": "tools-2.4.12.jar",
          "size": 9592698,
          "sha512": "8b63179adedd800b7a08109103c2476207392811885cbd531ca4b6372389d53f509f5437b4a407241daef4ee029bd7f8b0aff912bbf792a6b907dbe7e1bcd8af",
          "sha256": "ad380d809954bd562bdbdcc20df0155da03e7b1a7bce3d8f9ba1b65059d4d10c",
          "sha1": "a269180add83a3f2fb82bffe9e95ae84e2596a26",
          "md5": "62f96ac070ab74539684566455a8ef27"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.4.12"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.12"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.12"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.4.12"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs-fs",
          "version": {
            "requires": "2.4.12"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.11.5"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "dev.or2",
          "module": "displee",
          "version": {
            "requires": "2.4.12"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.16"
          }
        },
        {
          "group": "dev.or2",
          "module": "toml-rsconfig",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "me.filby",
          "module": "clientscript-compiler",
          "version": {
            "requires": "0.0.5-openrune"
          }
        }
      ],
      "files": [
        {
          "name": "tools-2.4.12.jar",
          "url": "tools-2.4.12.jar",
          "size": 9592698,
          "sha512": "8b63179adedd800b7a08109103c2476207392811885cbd531ca4b6372389d53f509f5437b4a407241daef4ee029bd7f8b0aff912bbf792a6b907dbe7e1bcd8af",
          "sha256": "ad380d809954bd562bdbdcc20df0155da03e7b1a7bce3d8f9ba1b65059d4d10c",
          "sha1": "a269180add83a3f2fb82bffe9e95ae84e2596a26",
          "md5": "62f96ac070ab74539684566455a8ef27"
        }
      ]
    }
  ]
}
