{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filesystem",
    "version": "2.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filesystem-2.4.3.jar",
          "url": "filesystem-2.4.3.jar",
          "size": 51650,
          "sha512": "62a9da16df48f271cffbaf2be736f28209c3355caa6ba56a3a69ce7bbeb845866d5c24e4b8ffd51a69f763d4c26db7ed605417e6b3ab2c9fd4f5174b30d27f18",
          "sha256": "fb191c865560f8a339a99017b3e02d8b872b08d2a3448a9b59b83d133fb2fe60",
          "sha1": "a5d383cec1432bf32c7595c4fbf84cb4733e6bcd",
          "md5": "cfbea310b9d5bbcea05622af83fb20e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "filesystem-2.4.3.jar",
          "url": "filesystem-2.4.3.jar",
          "size": 51650,
          "sha512": "62a9da16df48f271cffbaf2be736f28209c3355caa6ba56a3a69ce7bbeb845866d5c24e4b8ffd51a69f763d4c26db7ed605417e6b3ab2c9fd4f5174b30d27f18",
          "sha256": "fb191c865560f8a339a99017b3e02d8b872b08d2a3448a9b59b83d133fb2fe60",
          "sha1": "a5d383cec1432bf32c7595c4fbf84cb4733e6bcd",
          "md5": "cfbea310b9d5bbcea05622af83fb20e0"
        }
      ]
    }
  ]
}
