{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filestore",
    "version": "2.4.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-2.4.13.jar",
          "url": "filestore-2.4.13.jar",
          "size": 97552,
          "sha512": "26260a2ad52554fed453c4c321dee25f0df5322977af1f3eb461be0ca07e3c10e124ac9ef01ceadd2e2fe1658866e7419b40c230a2b15b569e2ce72d7f8ee0c4",
          "sha256": "9d974af7654684a8f14de8756c6593775479e571d73952498dc5f54ecd0a16ba",
          "sha1": "465d9689982ea6d7cf8c7f152ec8729ae1489a63",
          "md5": "e4c08972ab5494a8b4a1faaf1be3f9cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.13"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.13"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-2.4.13.jar",
          "url": "filestore-2.4.13.jar",
          "size": 97552,
          "sha512": "26260a2ad52554fed453c4c321dee25f0df5322977af1f3eb461be0ca07e3c10e124ac9ef01ceadd2e2fe1658866e7419b40c230a2b15b569e2ce72d7f8ee0c4",
          "sha256": "9d974af7654684a8f14de8756c6593775479e571d73952498dc5f54ecd0a16ba",
          "sha1": "465d9689982ea6d7cf8c7f152ec8729ae1489a63",
          "md5": "e4c08972ab5494a8b4a1faaf1be3f9cf"
        }
      ]
    }
  ]
}
