{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "openrune-central",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "openrune-central-2.0.1.jar",
          "url": "openrune-central-2.0.1.jar",
          "size": 345606,
          "sha512": "dfee55663029428d1fdfbc3becca4d3cc43fe5dc666f0eaafbe6b1fbb81fe47b8ce2dd7418c2a43ba492c0ba8c228245fbdf9b11df36e1a4580698bfe22ae611",
          "sha256": "9fb55d8cdcd1586e4a03d1392d18afa1badd62add1a00fd95d54685db347ecf5",
          "sha1": "e533dc9b746491bcc5354f727e78addff961df42",
          "md5": "ac0b07e746496b93efa230520df3f67f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.or2",
          "module": "central-common",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "dev.or2",
          "module": "central-worldlink",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-bom",
          "version": {
            "requires": "3.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-content-negotiation"
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-status-pages"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-forwarded-header"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-config-yaml"
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.7"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core",
          "version": {
            "requires": "11.3.1"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-database-postgresql",
          "version": {
            "requires": "11.3.1"
          }
        },
        {
          "group": "com.sksamuel.hoplite",
          "module": "hoplite-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.sksamuel.hoplite",
          "module": "hoplite-yaml",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-ktor",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-logger-slf4j",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.zonky.test",
          "module": "embedded-postgres",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.16"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "5.5.1"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "openrune-central-2.0.1.jar",
          "url": "openrune-central-2.0.1.jar",
          "size": 345606,
          "sha512": "dfee55663029428d1fdfbc3becca4d3cc43fe5dc666f0eaafbe6b1fbb81fe47b8ce2dd7418c2a43ba492c0ba8c228245fbdf9b11df36e1a4580698bfe22ae611",
          "sha256": "9fb55d8cdcd1586e4a03d1392d18afa1badd62add1a00fd95d54685db347ecf5",
          "sha1": "e533dc9b746491bcc5354f727e78addff961df42",
          "md5": "ac0b07e746496b93efa230520df3f67f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "openrune-central-2.0.1-sources.jar",
          "url": "openrune-central-2.0.1-sources.jar",
          "size": 67155,
          "sha512": "728241ee55542cc9f05f838abaf4e12225a953066649e69e0b3e02af254c4e80e617983b5ad769b257ba50a2d11e80abb9ed0fd7890bed593b05b9edb2985c30",
          "sha256": "f7a5e6d152ebcfe6e23bfa84fca288f7e793212e78fdfaacc0e723bc4261b533",
          "sha1": "d967b1914ab92a6e5267c930b9359287adb6d2d0",
          "md5": "6c72a7b102403cc63843bfca2e607908"
        }
      ]
    }
  ]
}
