{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.4.2.jar",
          "url": "displee-2.4.2.jar",
          "size": 111913,
          "sha512": "14701d28fd2b2426fd42c9d4c9cd1c05e9cf97f105511aabf97f7bd5da2f174e83724c0f73651806f3a14482b2ea4db0c88df885ed39096f51eb3df8a6f09aad",
          "sha256": "073d347f6f25a58f68eee9ec2f1d06893b87340c1700e03f750f559684d32f33",
          "sha1": "620f01fc110a6d48913b85ba0d837314b22e16d8",
          "md5": "89c68227fe54e9a163cd1677b9a2eb14"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.4.2.jar",
          "url": "displee-2.4.2.jar",
          "size": 111913,
          "sha512": "14701d28fd2b2426fd42c9d4c9cd1c05e9cf97f105511aabf97f7bd5da2f174e83724c0f73651806f3a14482b2ea4db0c88df885ed39096f51eb3df8a6f09aad",
          "sha256": "073d347f6f25a58f68eee9ec2f1d06893b87340c1700e03f750f559684d32f33",
          "sha1": "620f01fc110a6d48913b85ba0d837314b22e16d8",
          "md5": "89c68227fe54e9a163cd1677b9a2eb14"
        }
      ]
    }
  ]
}
