{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.3.5.jar",
          "url": "displee-2.3.5.jar",
          "size": 111913,
          "sha512": "609c103cd42dc75740d36d69d92d9623671a6e6bb60937f39335f59366320bdf9f9e2e19df39ec3255d9a51a5a3175d1648c94bbb52ac900aece63bcb2177e7c",
          "sha256": "d8196a3f4daa5b7f0234aa9dd091fee950cec72f6bf773deb39ebcff4f62b5bc",
          "sha1": "7b90a2d0b9c8ffe92330f438a43707516bfedf71",
          "md5": "45fdd5e48818239b7edb963c9ce5ba9e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.3.5.jar",
          "url": "displee-2.3.5.jar",
          "size": 111913,
          "sha512": "609c103cd42dc75740d36d69d92d9623671a6e6bb60937f39335f59366320bdf9f9e2e19df39ec3255d9a51a5a3175d1648c94bbb52ac900aece63bcb2177e7c",
          "sha256": "d8196a3f4daa5b7f0234aa9dd091fee950cec72f6bf773deb39ebcff4f62b5bc",
          "sha1": "7b90a2d0b9c8ffe92330f438a43707516bfedf71",
          "md5": "45fdd5e48818239b7edb963c9ce5ba9e"
        }
      ]
    }
  ]
}
