{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "3.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-3.0.5.jar",
          "url": "displee-3.0.5.jar",
          "size": 119255,
          "sha512": "3e69deafd422dd78c160425a5a7c5abff8ccbdb6c70b089ac1a347f55c7feb33b9c69223579472a24faa3c1268d1f7d8d532acecd325208380e785b47522b05b",
          "sha256": "32855aa440d70de4b93ef95e50f1141a3804ea04d50f3a7d4d55db3b9afc5a2f",
          "sha1": "5885b867c52b10113973811447ab0c836d3c3dee",
          "md5": "b0eac2f92475b21f97b37d4c50752344"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-3.0.5.jar",
          "url": "displee-3.0.5.jar",
          "size": 119255,
          "sha512": "3e69deafd422dd78c160425a5a7c5abff8ccbdb6c70b089ac1a347f55c7feb33b9c69223579472a24faa3c1268d1f7d8d532acecd325208380e785b47522b05b",
          "sha256": "32855aa440d70de4b93ef95e50f1141a3804ea04d50f3a7d4d55db3b9afc5a2f",
          "sha1": "5885b867c52b10113973811447ab0c836d3c3dee",
          "md5": "b0eac2f92475b21f97b37d4c50752344"
        }
      ]
    }
  ]
}
