{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718",
    "version": "2.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-2.4.2.jar",
          "url": "r718-2.4.2.jar",
          "size": 14410,
          "sha512": "ae15361c067f3e49786eef0d1f2a937d521383e8ad95c91cb8f1adcb07c48efd923a942a53aabaf563a3c285803afe37658f5aad04f87205330c5b607badd1e3",
          "sha256": "ad3f629cc4382b00a72b82a2a308acea135f0bbe3dddf21a9dc71ca2067ffd5f",
          "sha1": "c06737494bfed3dd93804be2f48252c824f1eb8d",
          "md5": "205f74a67afeb7d580ecc50f2226f20b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "r718-2.4.2.jar",
          "url": "r718-2.4.2.jar",
          "size": 14410,
          "sha512": "ae15361c067f3e49786eef0d1f2a937d521383e8ad95c91cb8f1adcb07c48efd923a942a53aabaf563a3c285803afe37658f5aad04f87205330c5b607badd1e3",
          "sha256": "ad3f629cc4382b00a72b82a2a308acea135f0bbe3dddf21a9dc71ca2067ffd5f",
          "sha1": "c06737494bfed3dd93804be2f48252c824f1eb8d",
          "md5": "205f74a67afeb7d580ecc50f2226f20b"
        }
      ]
    }
  ]
}
