{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.0.16.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.0.16.2.jar",
          "url": "displee-2.0.16.2.jar",
          "size": 111913,
          "sha512": "c0d7334a99df57619877fb11a9ffe6924d21d146e0d110cebdc0aae8d4938da89d399272c209f63de9dd118a2e018ea53c8fa99822e523105dfa95a40a3a8a46",
          "sha256": "8d2a0cdbe0bd778367e982397a769fa497afbb6ff8e1e778c54925d068f508e3",
          "sha1": "9d25e69a2ee68b0e945bb2025f5e9c168a120cd8",
          "md5": "8412d8b14e3e4af94b0c61c153a01c29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.0.16.2.jar",
          "url": "displee-2.0.16.2.jar",
          "size": 111913,
          "sha512": "c0d7334a99df57619877fb11a9ffe6924d21d146e0d110cebdc0aae8d4938da89d399272c209f63de9dd118a2e018ea53c8fa99822e523105dfa95a40a3a8a46",
          "sha256": "8d2a0cdbe0bd778367e982397a769fa497afbb6ff8e1e778c54925d068f508e3",
          "sha1": "9d25e69a2ee68b0e945bb2025f5e9c168a120cd8",
          "md5": "8412d8b14e3e4af94b0c61c153a01c29"
        }
      ]
    }
  ]
}
