{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs-fs",
    "version": "2.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-fs-2.0.13.jar",
          "url": "osrs-fs-2.0.13.jar",
          "size": 23585,
          "sha512": "bb4b6ecf1d8ab1319cc20d82f7bc1905d4f11d646bcbd502225c943f19da6a46d09f3a63dec4014e5d9b63b931df62d47aa73f7f4ea5415f31ed230ac536c0e8",
          "sha256": "0da8ddf45ccac99d06772c60b71a1d8d8e70393217412b710983edd0ebf9132a",
          "sha1": "822c39193c294d335c134335eb0b6ecd7318f0b2",
          "md5": "f8cc79ba42aa5d5d0dce997b03561c5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.0.13"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.0.13"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.0.13"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-fs-2.0.13.jar",
          "url": "osrs-fs-2.0.13.jar",
          "size": 23585,
          "sha512": "bb4b6ecf1d8ab1319cc20d82f7bc1905d4f11d646bcbd502225c943f19da6a46d09f3a63dec4014e5d9b63b931df62d47aa73f7f4ea5415f31ed230ac536c0e8",
          "sha256": "0da8ddf45ccac99d06772c60b71a1d8d8e70393217412b710983edd0ebf9132a",
          "sha1": "822c39193c294d335c134335eb0b6ecd7318f0b2",
          "md5": "f8cc79ba42aa5d5d0dce997b03561c5c"
        }
      ]
    }
  ]
}
