{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718-fs",
    "version": "2.4.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-fs-2.4.17.jar",
          "url": "r718-fs-2.4.17.jar",
          "size": 7588,
          "sha512": "fecec9457cad462d21c436b6792d8e4f7f3ba38a519852f071fca642ba012aecbcb90f42256065e5bf9de2c200324e4bf45f918a7974ff1bbdab8f0190e4678f",
          "sha256": "335982a424da4e815ee6604f068763602cf9bb47ec7415dd8fdad812923ff21b",
          "sha1": "1f3c53d3aacd8e79a10b3afaa0c89d3e74d3d658",
          "md5": "5361cfc7d13e4b78948beebe06e691b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.4.17"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.17"
          }
        },
        {
          "group": "dev.or2",
          "module": "r718",
          "version": {
            "requires": "2.4.17"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.17"
          }
        }
      ],
      "files": [
        {
          "name": "r718-fs-2.4.17.jar",
          "url": "r718-fs-2.4.17.jar",
          "size": 7588,
          "sha512": "fecec9457cad462d21c436b6792d8e4f7f3ba38a519852f071fca642ba012aecbcb90f42256065e5bf9de2c200324e4bf45f918a7974ff1bbdab8f0190e4678f",
          "sha256": "335982a424da4e815ee6604f068763602cf9bb47ec7415dd8fdad812923ff21b",
          "sha1": "1f3c53d3aacd8e79a10b3afaa0c89d3e74d3d658",
          "md5": "5361cfc7d13e4b78948beebe06e691b4"
        }
      ]
    }
  ]
}
