{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "filestore-tools",
    "version": "1.3.5-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-tools-1.3.5-beta.jar",
          "url": "filestore-tools-1.3.5-beta.jar",
          "size": 99822,
          "sha512": "21fcff5ea34ca326bf13f07d426cfc77d3b15339e1b46270495140c6bf49c96d0ef3ddb913b514b7b4de61ac8717fff294244aacce94fb7aff57e5872ff8d6d3",
          "sha256": "da701fcc54e4d26176fca9d56d4ba98dce2053acdcd19673b87c7b431aacc53b",
          "sha1": "551b05d033c03e612ebf9bea810cf273318c871a",
          "md5": "6d9da63f3611ff5de8dc20be67074953"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.openrune",
          "module": "filestore",
          "version": {
            "requires": "1.3.5-beta"
          }
        },
        {
          "group": "dev.openrune",
          "module": "filestore-osrs",
          "version": {
            "requires": "1.3.5-beta"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.openrune",
          "module": "js5server",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.11.5"
          }
        },
        {
          "group": "cc.ekblad",
          "module": "4koma",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "com.displee",
          "module": "rs-cache-library",
          "version": {
            "requires": "7.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-tools-1.3.5-beta.jar",
          "url": "filestore-tools-1.3.5-beta.jar",
          "size": 99822,
          "sha512": "21fcff5ea34ca326bf13f07d426cfc77d3b15339e1b46270495140c6bf49c96d0ef3ddb913b514b7b4de61ac8717fff294244aacce94fb7aff57e5872ff8d6d3",
          "sha256": "da701fcc54e4d26176fca9d56d4ba98dce2053acdcd19673b87c7b431aacc53b",
          "sha1": "551b05d033c03e612ebf9bea810cf273318c871a",
          "md5": "6d9da63f3611ff5de8dc20be67074953"
        }
      ]
    }
  ]
}
