{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs",
    "version": "2.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-2.4.1.jar",
          "url": "osrs-2.4.1.jar",
          "size": 87689,
          "sha512": "3f8caf7311dd84813a383072bf0bf684d39e7c40edd98dcf10199f2ee1b25736b64cc09bf1342d618b3f5e088296fb23e009c58d7185e5a913351814459cc810",
          "sha256": "d6c4d1f957cc8a1a5139f175a045060cc1a01a6cbb99d989b8eb3f4df8bf1748",
          "sha1": "d9d383c7f029609b1f63806be75bb40c24ef339b",
          "md5": "152e84560552d15dbda601404a6e41ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-2.4.1.jar",
          "url": "osrs-2.4.1.jar",
          "size": 87689,
          "sha512": "3f8caf7311dd84813a383072bf0bf684d39e7c40edd98dcf10199f2ee1b25736b64cc09bf1342d618b3f5e088296fb23e009c58d7185e5a913351814459cc810",
          "sha256": "d6c4d1f957cc8a1a5139f175a045060cc1a01a6cbb99d989b8eb3f4df8bf1748",
          "sha1": "d9d383c7f029609b1f63806be75bb40c24ef339b",
          "md5": "152e84560552d15dbda601404a6e41ea"
        }
      ]
    }
  ]
}
