{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.3.0.jar",
          "url": "displee-2.3.0.jar",
          "size": 111913,
          "sha512": "35310a1758bb8781b2c56833373440a89cc0439417da6adb8a38d89487dc77ce026590952fedaf9b08d05c2a38b32983968e0ae16dfa8832d33833d601ffb441",
          "sha256": "ea6d5acd1f739fa0099e872c4b4e6bfe31e0641ff64ad4c8600b8bcae179ab69",
          "sha1": "343162cd59c42b5bd7f4b7d69c3f7243a7cde467",
          "md5": "a751c5127fd912c32f649643ae166881"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.3.0.jar",
          "url": "displee-2.3.0.jar",
          "size": 111913,
          "sha512": "35310a1758bb8781b2c56833373440a89cc0439417da6adb8a38d89487dc77ce026590952fedaf9b08d05c2a38b32983968e0ae16dfa8832d33833d601ffb441",
          "sha256": "ea6d5acd1f739fa0099e872c4b4e6bfe31e0641ff64ad4c8600b8bcae179ab69",
          "sha1": "343162cd59c42b5bd7f4b7d69c3f7243a7cde467",
          "md5": "a751c5127fd912c32f649643ae166881"
        }
      ]
    }
  ]
}
