{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "filestore",
    "version": "1.3.86",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-1.3.86.jar",
          "url": "filestore-1.3.86.jar",
          "size": 625923,
          "sha512": "c2a62d8622466bd68af1c6fcf1c51d299928cd3675b957e5d1262cddeddfb40515e6ea03a553fab85ab22d743740c036500b7db42b1ae63d33ebb842b0f706f4",
          "sha256": "aaaed09eee2d6e4128fecdf77039048805ab6d7da0c6fd0b1bcdf84e04cbe1c5",
          "sha1": "e4d7c76dc66adbd5b7e0e8cdda948fbd140bc5ba",
          "md5": "4c2e3ce979ae0f27de2953262ff96326"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.10.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-file",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0-Beta1"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-1.3.86.jar",
          "url": "filestore-1.3.86.jar",
          "size": 625923,
          "sha512": "c2a62d8622466bd68af1c6fcf1c51d299928cd3675b957e5d1262cddeddfb40515e6ea03a553fab85ab22d743740c036500b7db42b1ae63d33ebb842b0f706f4",
          "sha256": "aaaed09eee2d6e4128fecdf77039048805ab6d7da0c6fd0b1bcdf84e04cbe1c5",
          "sha1": "e4d7c76dc66adbd5b7e0e8cdda948fbd140bc5ba",
          "md5": "4c2e3ce979ae0f27de2953262ff96326"
        }
      ]
    }
  ]
}
