{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "filestore",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-1.3.4.jar",
          "url": "filestore-1.3.4.jar",
          "size": 259448,
          "sha512": "8947e02dd56d6306e27539e4f246c3d6fbe390817efc2f0c3a55311d3a42bb05decd034a2c1c8a2fe7275618f777cf7341acd9d023644e7d5d8d0ede2fbbd4d2",
          "sha256": "26fdbc7996ce7b366953a13caa4830ddc8aa034016b4eb5417c6e6fc19eefb35",
          "sha1": "6c9928670786cf2f619e891092f626980d472d26",
          "md5": "10d4fbd73be6aeece850c196d3eb8ac1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-1.3.4.jar",
          "url": "filestore-1.3.4.jar",
          "size": 259448,
          "sha512": "8947e02dd56d6306e27539e4f246c3d6fbe390817efc2f0c3a55311d3a42bb05decd034a2c1c8a2fe7275618f777cf7341acd9d023644e7d5d8d0ede2fbbd4d2",
          "sha256": "26fdbc7996ce7b366953a13caa4830ddc8aa034016b4eb5417c6e6fc19eefb35",
          "sha1": "6c9928670786cf2f619e891092f626980d472d26",
          "md5": "10d4fbd73be6aeece850c196d3eb8ac1"
        }
      ]
    }
  ]
}
