{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs",
    "version": "2.4.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-2.4.11.jar",
          "url": "osrs-2.4.11.jar",
          "size": 92710,
          "sha512": "7b5d99dbd24c3d0a232f8131042915e722d32bd1ebd6c9448fe202ff570186bcf5e4b2602b782c5ca3b02280fa51758cf7b525c5b2ec662f1e61df45bc535de3",
          "sha256": "ef0d5aa9f46d0b23e48131c389ceb6b4526b99de494341adab10b6701dc0b5c6",
          "sha1": "8d0d77c9d86e36897e5060346c5d0a8547f8283a",
          "md5": "c1e07c76e1bcb5aa52e8e8c7e94330fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.11"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-2.4.11.jar",
          "url": "osrs-2.4.11.jar",
          "size": 92710,
          "sha512": "7b5d99dbd24c3d0a232f8131042915e722d32bd1ebd6c9448fe202ff570186bcf5e4b2602b782c5ca3b02280fa51758cf7b525c5b2ec662f1e61df45bc535de3",
          "sha256": "ef0d5aa9f46d0b23e48131c389ceb6b4526b99de494341adab10b6701dc0b5c6",
          "sha1": "8d0d77c9d86e36897e5060346c5d0a8547f8283a",
          "md5": "c1e07c76e1bcb5aa52e8e8c7e94330fd"
        }
      ]
    }
  ]
}
