{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "filestore-osrs",
    "version": "1.3.5-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-osrs-1.3.5-beta.jar",
          "url": "filestore-osrs-1.3.5-beta.jar",
          "size": 64938,
          "sha512": "75f1d37fe0b4e9dfe1ff468efd2ec6391c5f3ae9baf5e402c63aa44d78ee6cc97d137132e04fd5473ef669c22195ad042b8feac344255e01dae5c55608188a54",
          "sha256": "fc258e2b7a1d67a84ebbaa6af23bb90468d779b5c2133910acec854767489114",
          "sha1": "f00ea5af6b2f48159fc482c34054958e94dd6e5c",
          "md5": "49ee7fa8259f7cd1a5ec2d4a16b8276f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.openrune",
          "module": "filestore",
          "version": {
            "requires": "1.3.5-beta"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-osrs-1.3.5-beta.jar",
          "url": "filestore-osrs-1.3.5-beta.jar",
          "size": 64938,
          "sha512": "75f1d37fe0b4e9dfe1ff468efd2ec6391c5f3ae9baf5e402c63aa44d78ee6cc97d137132e04fd5473ef669c22195ad042b8feac344255e01dae5c55608188a54",
          "sha256": "fc258e2b7a1d67a84ebbaa6af23bb90468d779b5c2133910acec854767489114",
          "sha1": "f00ea5af6b2f48159fc482c34054958e94dd6e5c",
          "md5": "49ee7fa8259f7cd1a5ec2d4a16b8276f"
        }
      ]
    }
  ]
}
