{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs",
    "version": "2.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-2.0.8.jar",
          "url": "osrs-2.0.8.jar",
          "size": 73079,
          "sha512": "4762d14d00d54aaf55f47dd168a77d2357b047f718d124297f1fb1a9caaf63cba8a98c5cea0a50914496634f8395cf19ede8c9f5fc96b89bce63afbd20481a93",
          "sha256": "c275e49b274bb5d6fe81b0b028d67af548a570e828ee2dac4dc23d15a3892c4a",
          "sha1": "85616cf1acf660d59b5f85ba639d8530e8a61a9c",
          "md5": "04ac6a4d24ccfa4b977b003bbb4d4275"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-2.0.8.jar",
          "url": "osrs-2.0.8.jar",
          "size": 73079,
          "sha512": "4762d14d00d54aaf55f47dd168a77d2357b047f718d124297f1fb1a9caaf63cba8a98c5cea0a50914496634f8395cf19ede8c9f5fc96b89bce63afbd20481a93",
          "sha256": "c275e49b274bb5d6fe81b0b028d67af548a570e828ee2dac4dc23d15a3892c4a",
          "sha1": "85616cf1acf660d59b5f85ba639d8530e8a61a9c",
          "md5": "04ac6a4d24ccfa4b977b003bbb4d4275"
        }
      ]
    }
  ]
}
