{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "runescript-compiler",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.or2",
          "module": "runescript-parser",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "runescript-compiler-0.0.1-SNAPSHOT.jar",
          "url": "runescript-compiler-0.0.1-SNAPSHOT.jar",
          "size": 260598,
          "sha512": "45c7f62247676a2b8cf70811475e9aaa8cefbb4377f0cacbef18bfb57459ee956e5f59fbbfb8ab4f83e911db369269e12c839d70329c7bd44ee5170180006abd",
          "sha256": "4b2c3cbfa83e843fbd99b709a9bb67f013a6ca10855e4854fcdf094f4dc0e0fe",
          "sha1": "1a708656e753c03adb198f43a38263ab597c972f",
          "md5": "60f5eadf700e24fb39c109fa006b6531"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.0-jre"
          }
        },
        {
          "group": "dev.or2",
          "module": "runescript-parser",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.11"
          }
        }
      ],
      "files": [
        {
          "name": "runescript-compiler-0.0.1-SNAPSHOT.jar",
          "url": "runescript-compiler-0.0.1-SNAPSHOT.jar",
          "size": 260598,
          "sha512": "45c7f62247676a2b8cf70811475e9aaa8cefbb4377f0cacbef18bfb57459ee956e5f59fbbfb8ab4f83e911db369269e12c839d70329c7bd44ee5170180006abd",
          "sha256": "4b2c3cbfa83e843fbd99b709a9bb67f013a6ca10855e4854fcdf094f4dc0e0fe",
          "sha1": "1a708656e753c03adb198f43a38263ab597c972f",
          "md5": "60f5eadf700e24fb39c109fa006b6531"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescript-compiler-0.0.1-SNAPSHOT-sources.jar",
          "url": "runescript-compiler-0.0.1-SNAPSHOT-sources.jar",
          "size": 60788,
          "sha512": "32c859a486a31b13157778f3df39ab52f6107a998c25138cfcbfd438a9c50726c2ded95a60aa77d9c12eafef733ff9fa6464a9dea36a48c2efa4d656d3041192",
          "sha256": "dd6bec3789ca3bc1b1ac651a0753953db011c3a6cd926875a8cecd58fe5f2b1e",
          "sha1": "b784028faf879b07a4babbda0f9bf23826558e09",
          "md5": "9ad07fbc20bb9595af9ab3d4c01c08e4"
        },
        {
          "name": "runescript-compiler-0.0.1-SNAPSHOT-sources.jar",
          "url": "runescript-compiler-0.0.1-SNAPSHOT-sources.jar",
          "size": 60788,
          "sha512": "32c859a486a31b13157778f3df39ab52f6107a998c25138cfcbfd438a9c50726c2ded95a60aa77d9c12eafef733ff9fa6464a9dea36a48c2efa4d656d3041192",
          "sha256": "dd6bec3789ca3bc1b1ac651a0753953db011c3a6cd926875a8cecd58fe5f2b1e",
          "sha1": "b784028faf879b07a4babbda0f9bf23826558e09",
          "md5": "9ad07fbc20bb9595af9ab3d4c01c08e4"
        }
      ]
    }
  ]
}
