{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs-fs",
    "version": "2.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-fs-2.3.8.jar",
          "url": "osrs-fs-2.3.8.jar",
          "size": 26599,
          "sha512": "0b2e85944d9bb628e3631c830a8938c409dfe9a1dbd9c554abc1f5e7164ace35e3f9b943f171b60aba7b03e4b90433561aadb6f9e46a6313ba1a68652b408a3b",
          "sha256": "6bf62c5b468a0451b69c1cc3ac0e954a67a99b85d37d80d7a2ce3ae9135ab93c",
          "sha1": "c5a568e4703ade08e9d9b969e53425ba0bcedabc",
          "md5": "2dbed30792dba6ef28e43479ff3dbb23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-fs-2.3.8.jar",
          "url": "osrs-fs-2.3.8.jar",
          "size": 26599,
          "sha512": "0b2e85944d9bb628e3631c830a8938c409dfe9a1dbd9c554abc1f5e7164ace35e3f9b943f171b60aba7b03e4b90433561aadb6f9e46a6313ba1a68652b408a3b",
          "sha256": "6bf62c5b468a0451b69c1cc3ac0e954a67a99b85d37d80d7a2ce3ae9135ab93c",
          "sha1": "c5a568e4703ade08e9d9b969e53425ba0bcedabc",
          "md5": "2dbed30792dba6ef28e43479ff3dbb23"
        }
      ]
    }
  ]
}
