{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "rs3",
    "version": "2.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "rs3-2.3.8.jar",
          "url": "rs3-2.3.8.jar",
          "size": 8873,
          "sha512": "2821be03b65b31d2531fba1bc961846002b2f9db74f23d14414d409a24d5a51e6e67d5e684e98992d6d225287c98285f543700019b1faa1bb861c5dc9dfc1fbf",
          "sha256": "40921fe29cc483ebf70c14b33f29396c149acf3768ae7073d4856ebfaf429727",
          "sha1": "5fcd23bb3823d504342ea5b85a700240e9b2808c",
          "md5": "924165210e47bcac8fc4e69041f3f6a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "rs3-2.3.8.jar",
          "url": "rs3-2.3.8.jar",
          "size": 8873,
          "sha512": "2821be03b65b31d2531fba1bc961846002b2f9db74f23d14414d409a24d5a51e6e67d5e684e98992d6d225287c98285f543700019b1faa1bb861c5dc9dfc1fbf",
          "sha256": "40921fe29cc483ebf70c14b33f29396c149acf3768ae7073d4856ebfaf429727",
          "sha1": "5fcd23bb3823d504342ea5b85a700240e9b2808c",
          "md5": "924165210e47bcac8fc4e69041f3f6a4"
        }
      ]
    }
  ]
}
