{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs",
    "version": "2.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-2.2.3.jar",
          "url": "osrs-2.2.3.jar",
          "size": 82803,
          "sha512": "e5fbad5060b80ea3ef1e32004c2cf031c7e67a63235f47da9545c88d587b9162d00e3e2eb8375c4e0ae72150e28bfdb9859f3d85541e203af27c2a2a6d6c437c",
          "sha256": "dc37f15caff5bc50bb5622e011e439abfe0000c57043648426f5acf894325202",
          "sha1": "991dbc429f0213e876fef675b23e998f384cf096",
          "md5": "f7d505403461325d1be891f3be687661"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-2.2.3.jar",
          "url": "osrs-2.2.3.jar",
          "size": 82803,
          "sha512": "e5fbad5060b80ea3ef1e32004c2cf031c7e67a63235f47da9545c88d587b9162d00e3e2eb8375c4e0ae72150e28bfdb9859f3d85541e203af27c2a2a6d6c437c",
          "sha256": "dc37f15caff5bc50bb5622e011e439abfe0000c57043648426f5acf894325202",
          "sha1": "991dbc429f0213e876fef675b23e998f384cf096",
          "md5": "f7d505403461325d1be891f3be687661"
        }
      ]
    }
  ]
}
