{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "filestore",
    "version": "1.3.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-1.3.6.2.jar",
          "url": "filestore-1.3.6.2.jar",
          "size": 575155,
          "sha512": "c88fd9d30fa25c0af7e284c4b87cccdb8dfbbef3d76313901d9163d00fdab37ca7cd759d039953d18788b1e360bff39eda62ade6d069258fdad987ff202631b3",
          "sha256": "7866d758542522105375bcdfec46f8ee255ce24949d1ec16bef99056a575ee46",
          "sha1": "72586519cf2d6cacccfc6c97634ad30b6032a181",
          "md5": "8247fd6341970cb85c44aad559aa590c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.10.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-1.3.6.2.jar",
          "url": "filestore-1.3.6.2.jar",
          "size": 575155,
          "sha512": "c88fd9d30fa25c0af7e284c4b87cccdb8dfbbef3d76313901d9163d00fdab37ca7cd759d039953d18788b1e360bff39eda62ade6d069258fdad987ff202631b3",
          "sha256": "7866d758542522105375bcdfec46f8ee255ce24949d1ec16bef99056a575ee46",
          "sha1": "72586519cf2d6cacccfc6c97634ad30b6032a181",
          "md5": "8247fd6341970cb85c44aad559aa590c"
        }
      ]
    }
  ]
}
