{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.0.16.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.0.16.1.jar",
          "url": "displee-2.0.16.1.jar",
          "size": 111913,
          "sha512": "b5c8ee5c0834bb89d7a6fec724173530e2e35b502e04bd2d02beafa4f86d35b52a8864152ded1098ad60e661ecc6ac0252ec9b0e870d1bd913e87ea7cb407e89",
          "sha256": "3a09638bfeda9a14393008f51a8abb1848d0c6134e02c7e8ffbc0aad42a6f7dd",
          "sha1": "7ad2102c4a4168e68042f60d3ea8261cae641d87",
          "md5": "64fb3b6c018d56faf2d80ef3106d8231"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.0.16.1.jar",
          "url": "displee-2.0.16.1.jar",
          "size": 111913,
          "sha512": "b5c8ee5c0834bb89d7a6fec724173530e2e35b502e04bd2d02beafa4f86d35b52a8864152ded1098ad60e661ecc6ac0252ec9b0e870d1bd913e87ea7cb407e89",
          "sha256": "3a09638bfeda9a14393008f51a8abb1848d0c6134e02c7e8ffbc0aad42a6f7dd",
          "sha1": "7ad2102c4a4168e68042f60d3ea8261cae641d87",
          "md5": "64fb3b6c018d56faf2d80ef3106d8231"
        }
      ]
    }
  ]
}
