{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.3.4.jar",
          "url": "displee-2.3.4.jar",
          "size": 111913,
          "sha512": "d7d4cadfeee773ad6a441efd3b200c84981bfe0a8db23151cf41c935f5cfed70632349cb8b32eea03a78e45dc4f1fcd78ab254b720464793275ec22ac29bc820",
          "sha256": "9bb4f7d23b4115d28fdb291da7024c4c1d3c1907f91ce2c4a59031cd7e7518db",
          "sha1": "bfb72d01105aab024a840810e75d2ca25ee7d813",
          "md5": "073db99f0cdeec5e080fbb3ba3a69ac9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.3.4.jar",
          "url": "displee-2.3.4.jar",
          "size": 111913,
          "sha512": "d7d4cadfeee773ad6a441efd3b200c84981bfe0a8db23151cf41c935f5cfed70632349cb8b32eea03a78e45dc4f1fcd78ab254b720464793275ec22ac29bc820",
          "sha256": "9bb4f7d23b4115d28fdb291da7024c4c1d3c1907f91ce2c4a59031cd7e7518db",
          "sha1": "bfb72d01105aab024a840810e75d2ca25ee7d813",
          "md5": "073db99f0cdeec5e080fbb3ba3a69ac9"
        }
      ]
    }
  ]
}
