{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filestore",
    "version": "2.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-2.3.8.jar",
          "url": "filestore-2.3.8.jar",
          "size": 94700,
          "sha512": "f78dda7e2d95a35ec7e51d10d37d9d11f7232397ad8a1caea8ef83cf626f99d625a16eed9e9679b6b21ade8446c1e184212aeb2d68c738602bee59075ee87f72",
          "sha256": "e3f83e5304e6827985b6681aa28cb42432263961faf227a356415cd0d9042399",
          "sha1": "f79cbdba18a32a5a7bedb2e6ca2e5b3adeb2fede",
          "md5": "9f55aa12166e948fac4a65873b3def12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-2.3.8.jar",
          "url": "filestore-2.3.8.jar",
          "size": 94700,
          "sha512": "f78dda7e2d95a35ec7e51d10d37d9d11f7232397ad8a1caea8ef83cf626f99d625a16eed9e9679b6b21ade8446c1e184212aeb2d68c738602bee59075ee87f72",
          "sha256": "e3f83e5304e6827985b6681aa28cb42432263961faf227a356415cd0d9042399",
          "sha1": "f79cbdba18a32a5a7bedb2e6ca2e5b3adeb2fede",
          "md5": "9f55aa12166e948fac4a65873b3def12"
        }
      ]
    }
  ]
}
