{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "bootstrap",
    "version": "1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "bootstrap-1.7.jar",
          "url": "bootstrap-1.7.jar",
          "size": 79132,
          "sha512": "ed5fba5b68c1cde9e062c66ea4fcd13289b0a8da80982e9ba7cab545e679b21447e1ebe1280e2de1ae2705156977268ffe5154093ea31e2034d779547dd1d08e",
          "sha256": "01b2ef646bd9ddad68f0553f24606308c4ea78762c3f16ccb8e283bf427da35f",
          "sha1": "74b3d06adae5fba9ad421bdd99eae8ca9cb4b326",
          "md5": "fc08d4c352dbcc6d2b8f6354decae451"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.2"
          }
        },
        {
          "group": "com.beust",
          "module": "klaxon",
          "version": {
            "requires": "5.5"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.9.0.202403050737-r"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.11"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "bootstrap-1.7.jar",
          "url": "bootstrap-1.7.jar",
          "size": 79132,
          "sha512": "ed5fba5b68c1cde9e062c66ea4fcd13289b0a8da80982e9ba7cab545e679b21447e1ebe1280e2de1ae2705156977268ffe5154093ea31e2034d779547dd1d08e",
          "sha256": "01b2ef646bd9ddad68f0553f24606308c4ea78762c3f16ccb8e283bf427da35f",
          "sha1": "74b3d06adae5fba9ad421bdd99eae8ca9cb4b326",
          "md5": "fc08d4c352dbcc6d2b8f6354decae451"
        }
      ]
    }
  ]
}
