{
  "formatVersion": "1.1",
  "component": {
    "group": "me.filby",
    "module": "runescript-parser",
    "version": "0.0.1-openrune",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescript-parser-0.0.1-openrune.jar",
          "url": "runescript-parser-0.0.1-openrune.jar",
          "size": 205831,
          "sha512": "139f130bc9f5f8234b45c85fb58f783b5d762eb7b6d658123523f5a90e669e7da7f18d7c4a61f5ac67c4fb2305717b778414ee5a918dcf9d66456ea72a33cd26",
          "sha256": "9465b6b4825b335f9bad969a9bb65e273e090d1efe5773b3c4964185643dc02a",
          "sha1": "c7fd9a0689f70dd6f95d784cda49b8903571fe22",
          "md5": "7c93e3b3cdcfcf836f417bf452f80673"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.0-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescript-parser-0.0.1-openrune.jar",
          "url": "runescript-parser-0.0.1-openrune.jar",
          "size": 205831,
          "sha512": "139f130bc9f5f8234b45c85fb58f783b5d762eb7b6d658123523f5a90e669e7da7f18d7c4a61f5ac67c4fb2305717b778414ee5a918dcf9d66456ea72a33cd26",
          "sha256": "9465b6b4825b335f9bad969a9bb65e273e090d1efe5773b3c4964185643dc02a",
          "sha1": "c7fd9a0689f70dd6f95d784cda49b8903571fe22",
          "md5": "7c93e3b3cdcfcf836f417bf452f80673"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescript-parser-0.0.1-openrune-sources.jar",
          "url": "runescript-parser-0.0.1-openrune-sources.jar",
          "size": 65257,
          "sha512": "b665cb0f3c45d1c21d1f66dc86a3d3a11ab892873d643ac3a7e6a6d6a47728aaa26f712a41c10c43c21ba3ff305b9e6a008107a3aa2ffe5c6c2b6f6c9fc7744f",
          "sha256": "d813da1784942029e712fb38d91165210c837bd91883ffc3c7ef07241a23bb93",
          "sha1": "4617ff927a2b16158f0910b7f530a2e673593b77",
          "md5": "dc75e2fa201d3027a4727aa92e8be92b"
        },
        {
          "name": "runescript-parser-0.0.1-openrune-sources.jar",
          "url": "runescript-parser-0.0.1-openrune-sources.jar",
          "size": 65257,
          "sha512": "b665cb0f3c45d1c21d1f66dc86a3d3a11ab892873d643ac3a7e6a6d6a47728aaa26f712a41c10c43c21ba3ff305b9e6a008107a3aa2ffe5c6c2b6f6c9fc7744f",
          "sha256": "d813da1784942029e712fb38d91165210c837bd91883ffc3c7ef07241a23bb93",
          "sha1": "4617ff927a2b16158f0910b7f530a2e673593b77",
          "md5": "dc75e2fa201d3027a4727aa92e8be92b"
        }
      ]
    }
  ]
}
