{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718-fs",
    "version": "2.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-fs-2.4.3.jar",
          "url": "r718-fs-2.4.3.jar",
          "size": 7588,
          "sha512": "c63b50aa615a6ff912ae8013219572738dc64c30969a9a12ae126a3524020159e306f7ed3264ed772ae6ffa541077c49329c3dc7d3b88b99c57fea9e83f788d1",
          "sha256": "e631d9719d3a507f7a89f6d93806214c9bee9777b387ff7aec625438a18e8647",
          "sha1": "88495cfd9a8da802cf8c639f940788326e89f125",
          "md5": "c9c49edfa225a2f9198c822375b34c6b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "r718",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "r718-fs-2.4.3.jar",
          "url": "r718-fs-2.4.3.jar",
          "size": 7588,
          "sha512": "c63b50aa615a6ff912ae8013219572738dc64c30969a9a12ae126a3524020159e306f7ed3264ed772ae6ffa541077c49329c3dc7d3b88b99c57fea9e83f788d1",
          "sha256": "e631d9719d3a507f7a89f6d93806214c9bee9777b387ff7aec625438a18e8647",
          "sha1": "88495cfd9a8da802cf8c639f940788326e89f125",
          "md5": "c9c49edfa225a2f9198c822375b34c6b"
        }
      ]
    }
  ]
}
