{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718-fs",
    "version": "2.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-fs-2.2.4.jar",
          "url": "r718-fs-2.2.4.jar",
          "size": 7588,
          "sha512": "c72f60a3ec9ea1e0c7922ab136c0779ea9ddd0f626a1ae56fb475c5b868291f317ae333dbaf41b0da63bc554ae7fa3e6765d4b770f135a8c26febbbcc4cae2af",
          "sha256": "4fa2a6ecdd7009d43792cee1d3ae76677969d525c1eb8b7cd8e966f1d6d630ab",
          "sha1": "f0d3d11021375741fca60ade08a52b998d3b1e6d",
          "md5": "323ff9095f2a1134c12e21c2eb23a979"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "dev.or2",
          "module": "r718",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "r718-fs-2.2.4.jar",
          "url": "r718-fs-2.2.4.jar",
          "size": 7588,
          "sha512": "c72f60a3ec9ea1e0c7922ab136c0779ea9ddd0f626a1ae56fb475c5b868291f317ae333dbaf41b0da63bc554ae7fa3e6765d4b770f135a8c26febbbcc4cae2af",
          "sha256": "4fa2a6ecdd7009d43792cee1d3ae76677969d525c1eb8b7cd8e966f1d6d630ab",
          "sha1": "f0d3d11021375741fca60ade08a52b998d3b1e6d",
          "md5": "323ff9095f2a1134c12e21c2eb23a979"
        }
      ]
    }
  ]
}
