{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs-fs",
    "version": "2.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-fs-2.3.3.jar",
          "url": "osrs-fs-2.3.3.jar",
          "size": 22316,
          "sha512": "b89f56d4b67036569130cc19b1c65d71f5b37d71daca57efd0b4fead8e623ee0bd2b487a159996bbf9578fbfd90ee7b7121411de824e4f019022f332a80d7bea",
          "sha256": "a43584b16cb1b70cbf70804f64ce235ddd55424c41a077672f2bf3afd900e5c0",
          "sha1": "d8bee44bca9f8d1b30e5766f97df58c4a3c50b40",
          "md5": "0731c0638c829930a98387f63d934f91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-fs-2.3.3.jar",
          "url": "osrs-fs-2.3.3.jar",
          "size": 22316,
          "sha512": "b89f56d4b67036569130cc19b1c65d71f5b37d71daca57efd0b4fead8e623ee0bd2b487a159996bbf9578fbfd90ee7b7121411de824e4f019022f332a80d7bea",
          "sha256": "a43584b16cb1b70cbf70804f64ce235ddd55424c41a077672f2bf3afd900e5c0",
          "sha1": "d8bee44bca9f8d1b30e5766f97df58c4a3c50b40",
          "md5": "0731c0638c829930a98387f63d934f91"
        }
      ]
    }
  ]
}
