{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "definition",
    "version": "2.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "definition-2.2.6.jar",
          "url": "definition-2.2.6.jar",
          "size": 373729,
          "sha512": "55aa784f06a0c3ea0ddbb85f7b3998277abb8bda878c272c35ff4652bc5e6cc43fc36b5cf0a61c52dca2f6f65ac380e0351e0b58c56ed5a26091a2f71a884537",
          "sha256": "64ba2ef7c22636a1512a8f857f7d7ede032e21e3689b38ce80712a072f185039",
          "sha1": "a6f3a82ae5d56bff1722b6c57fb1d610778aeca5",
          "md5": "9a64379942b38d799fbe2353f9071b79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        }
      ],
      "files": [
        {
          "name": "definition-2.2.6.jar",
          "url": "definition-2.2.6.jar",
          "size": 373729,
          "sha512": "55aa784f06a0c3ea0ddbb85f7b3998277abb8bda878c272c35ff4652bc5e6cc43fc36b5cf0a61c52dca2f6f65ac380e0351e0b58c56ed5a26091a2f71a884537",
          "sha256": "64ba2ef7c22636a1512a8f857f7d7ede032e21e3689b38ce80712a072f185039",
          "sha1": "a6f3a82ae5d56bff1722b6c57fb1d610778aeca5",
          "md5": "9a64379942b38d799fbe2353f9071b79"
        }
      ]
    }
  ]
}
