{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "filestore",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-1.3.0.jar",
          "url": "filestore-1.3.0.jar",
          "size": 239747,
          "sha512": "8bfec1c273f6eeb028b1dcbafc5e4d89ba780bb956e842721c8fe10c8f98982960a2103ca64c34676a0fb51b721f0a9e10ee81437405771d68400265c7fa5a8e",
          "sha256": "5994f9ce8e9c13a18f7e896ce15b2ce3b02266bba863b6392b32b6f81c1e6bf2",
          "sha1": "2fc9d1a737c8230cc83acd6d3576a60584cbc60a",
          "md5": "30fadde15e71c379d018cbdec1aa5700"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.displee",
          "module": "rs-cache-library",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-1.3.0.jar",
          "url": "filestore-1.3.0.jar",
          "size": 239747,
          "sha512": "8bfec1c273f6eeb028b1dcbafc5e4d89ba780bb956e842721c8fe10c8f98982960a2103ca64c34676a0fb51b721f0a9e10ee81437405771d68400265c7fa5a8e",
          "sha256": "5994f9ce8e9c13a18f7e896ce15b2ce3b02266bba863b6392b32b6f81c1e6bf2",
          "sha1": "2fc9d1a737c8230cc83acd6d3576a60584cbc60a",
          "md5": "30fadde15e71c379d018cbdec1aa5700"
        }
      ]
    }
  ]
}
