{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs",
    "version": "3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-3.0.2.jar",
          "url": "osrs-3.0.2.jar",
          "size": 101837,
          "sha512": "10b0e5d6afa2b170e78e0d47c6177f1777aa4b8981959b3d6bab9aa09bcc0d6263e328dc7bcd06e233322d942c81da94443bef16514847bfc3686b71a9544c86",
          "sha256": "fc0e4b546fb364cf1c5e3be731ead03b01407db501610a4895d9ec6f81214f04",
          "sha1": "fcf30496bc5dc4f8cfb9b9f12a108a4fccb5451f",
          "md5": "50edc449a240788967737702883c6da2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-3.0.2.jar",
          "url": "osrs-3.0.2.jar",
          "size": 101837,
          "sha512": "10b0e5d6afa2b170e78e0d47c6177f1777aa4b8981959b3d6bab9aa09bcc0d6263e328dc7bcd06e233322d942c81da94443bef16514847bfc3686b71a9544c86",
          "sha256": "fc0e4b546fb364cf1c5e3be731ead03b01407db501610a4895d9ec6f81214f04",
          "sha1": "fcf30496bc5dc4f8cfb9b9f12a108a4fccb5451f",
          "md5": "50edc449a240788967737702883c6da2"
        }
      ]
    }
  ]
}
