{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filesystem",
    "version": "2.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filesystem-2.3.9.jar",
          "url": "filesystem-2.3.9.jar",
          "size": 51650,
          "sha512": "2e61b8bfa4411db367edd45082a44f7ae19831bb09e76fafb7b12065fc848bd209bd57af39b30791242f274db3ef116630d72116acdc8fe955dcb33c095da8ab",
          "sha256": "9187aba43038a936694c695bec22e9a5ed6997d26fa151769ecec00869e359f1",
          "sha1": "1699936036b0b0a4c6c87956b4408998daecfd4e",
          "md5": "3327033a2f55bff003cc7519bb18a9d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "filesystem-2.3.9.jar",
          "url": "filesystem-2.3.9.jar",
          "size": 51650,
          "sha512": "2e61b8bfa4411db367edd45082a44f7ae19831bb09e76fafb7b12065fc848bd209bd57af39b30791242f274db3ef116630d72116acdc8fe955dcb33c095da8ab",
          "sha256": "9187aba43038a936694c695bec22e9a5ed6997d26fa151769ecec00869e359f1",
          "sha1": "1699936036b0b0a4c6c87956b4408998daecfd4e",
          "md5": "3327033a2f55bff003cc7519bb18a9d0"
        }
      ]
    }
  ]
}
