{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "definition",
    "version": "2.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "definition-2.0.3.jar",
          "url": "definition-2.0.3.jar",
          "size": 317414,
          "sha512": "69f705d49b4f96a48ef27a6c38bb3ad07a38dd084d62e48dcd2ac764d1fd12760e85ae4064cbdc5f62840ae1c439dfeb0a3d5fe677bd862ece70552fca9b2250",
          "sha256": "9c00e2f0d4430302b083ec1f03e077b5ac5d5ec07332c13cb87ff4e888aa293f",
          "sha1": "1978ec8ba6e97c67b99b5c2b4944ba994e588f36",
          "md5": "0e33861697c5101e0e11728e7f4e9609"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0-Beta1"
          }
        }
      ],
      "files": [
        {
          "name": "definition-2.0.3.jar",
          "url": "definition-2.0.3.jar",
          "size": 317414,
          "sha512": "69f705d49b4f96a48ef27a6c38bb3ad07a38dd084d62e48dcd2ac764d1fd12760e85ae4064cbdc5f62840ae1c439dfeb0a3d5fe677bd862ece70552fca9b2250",
          "sha256": "9c00e2f0d4430302b083ec1f03e077b5ac5d5ec07332c13cb87ff4e888aa293f",
          "sha1": "1978ec8ba6e97c67b99b5c2b4944ba994e588f36",
          "md5": "0e33861697c5101e0e11728e7f4e9609"
        }
      ]
    }
  ]
}
