{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "tools",
    "version": "2.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "tools-2.3.5.jar",
          "url": "tools-2.3.5.jar",
          "size": 358088,
          "sha512": "6cb57ac361c451325b25dd5bbe6980a0143000fb332a0f4251ddfde0286bdcaf027fbcb03d4163c5ef5cb4790e7ac698455e195678be30558c817a03b3ac56bf",
          "sha256": "6a9f68646d3f6456eae945cc5b3afe5aed205abf5f3863069596573a7da33459",
          "sha1": "a655ff29bfb05637159267268f6e873f0ca28149",
          "md5": "a0b5c4c3b23ee31ce0ac24507712d73e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs-fs",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.11.5"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "dev.or2",
          "module": "displee",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "cc.ekblad",
          "module": "4koma",
          "version": {
            "requires": "1.2.2-openrune"
          }
        },
        {
          "group": "me.filby",
          "module": "clientscript-compiler",
          "version": {
            "requires": "0.0.2-openrune"
          }
        }
      ],
      "files": [
        {
          "name": "tools-2.3.5.jar",
          "url": "tools-2.3.5.jar",
          "size": 358088,
          "sha512": "6cb57ac361c451325b25dd5bbe6980a0143000fb332a0f4251ddfde0286bdcaf027fbcb03d4163c5ef5cb4790e7ac698455e195678be30558c817a03b3ac56bf",
          "sha256": "6a9f68646d3f6456eae945cc5b3afe5aed205abf5f3863069596573a7da33459",
          "sha1": "a655ff29bfb05637159267268f6e873f0ca28149",
          "md5": "a0b5c4c3b23ee31ce0ac24507712d73e"
        }
      ]
    }
  ]
}
