{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "wiki",
    "version": "0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.or2",
          "module": "filestore-server",
          "version": {
            "requires": "0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "wiki-0.6.jar",
          "url": "wiki-0.6.jar",
          "size": 138930,
          "sha512": "2352978385f75f591c99ec3d25474d1fa5e5df45c87efdf3020ffb4f6ae436ed28d8113769f7a52f560324a34b2d44cc8ce063004b48e466242db747e3989a5a",
          "sha256": "51d2f9280d76f0745ed9e5d9138e120975b54a96e1c32c26bcbdc45e47163432",
          "sha1": "1767d786ac0a0d04feeef665c4a3e475ccfb2642",
          "md5": "a6ae8282f3b5c3b203cd0399896c56a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.26.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "org.sweble.wikitext",
          "module": "swc-engine",
          "version": {
            "requires": "3.1.9"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore-server",
          "version": {
            "requires": "0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "wiki-0.6.jar",
          "url": "wiki-0.6.jar",
          "size": 138930,
          "sha512": "2352978385f75f591c99ec3d25474d1fa5e5df45c87efdf3020ffb4f6ae436ed28d8113769f7a52f560324a34b2d44cc8ce063004b48e466242db747e3989a5a",
          "sha256": "51d2f9280d76f0745ed9e5d9138e120975b54a96e1c32c26bcbdc45e47163432",
          "sha1": "1767d786ac0a0d04feeef665c4a3e475ccfb2642",
          "md5": "a6ae8282f3b5c3b203cd0399896c56a0"
        }
      ]
    }
  ]
}
