{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.2.jar",
          "url": "displee-2.2.jar",
          "size": 111913,
          "sha512": "25b5fd3f9f99a5b97f0f1671620723d96c8c8b6c45a96225b82ed0b62974abbae70d488fc14cc744ae016e94136a3a8b3e3ae2785a6bba435c73e1eeea9f25c5",
          "sha256": "c17c24e64249361c2c8df064e1fbc48e65c1163b6f166a9a3f41ab4b93469fde",
          "sha1": "2dfd90ddfd11a5d88fb6286e50b5937e033576e1",
          "md5": "f771e8085216daacfe5fc20397596183"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.2.jar",
          "url": "displee-2.2.jar",
          "size": 111913,
          "sha512": "25b5fd3f9f99a5b97f0f1671620723d96c8c8b6c45a96225b82ed0b62974abbae70d488fc14cc744ae016e94136a3a8b3e3ae2785a6bba435c73e1eeea9f25c5",
          "sha256": "c17c24e64249361c2c8df064e1fbc48e65c1163b6f166a9a3f41ab4b93469fde",
          "sha1": "2dfd90ddfd11a5d88fb6286e50b5937e033576e1",
          "md5": "f771e8085216daacfe5fc20397596183"
        }
      ]
    }
  ]
}
