{
  "formatVersion": "1.1",
  "component": {
    "group": "me.filby",
    "module": "clientscript-compiler",
    "version": "0.0.6-openrune",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.filby",
          "module": "runescript-compiler",
          "version": {
            "requires": "0.0.6-openrune"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "clientscript-compiler-0.0.6-openrune.jar",
          "url": "clientscript-compiler-0.0.6-openrune.jar",
          "size": 1566265,
          "sha512": "51dfcdf4cb224e93e90d8e696710e33d81919e468d424427738fdcc30e341117a29d3446877328c2f4a2ffe21014eb17d05e4f3f5df4ddd833ab327efdec03fb",
          "sha256": "5a41397b76877ad7b1d3ef70824e77dd99164febe49657c161fd26d17d41ff5b",
          "sha1": "1186d9009878fea05ed768285872a72b363ece06",
          "md5": "d8fe30d34bf56a724908ca05da45a5d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.0-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.116.Final"
          }
        },
        {
          "group": "cc.ekblad",
          "module": "4koma",
          "version": {
            "requires": "1.2.0-openrune"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          },
          "excludes": [
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.11"
          }
        },
        {
          "group": "me.filby",
          "module": "runescript-compiler",
          "version": {
            "requires": "0.0.6-openrune"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "clientscript-compiler-0.0.6-openrune.jar",
          "url": "clientscript-compiler-0.0.6-openrune.jar",
          "size": 1566265,
          "sha512": "51dfcdf4cb224e93e90d8e696710e33d81919e468d424427738fdcc30e341117a29d3446877328c2f4a2ffe21014eb17d05e4f3f5df4ddd833ab327efdec03fb",
          "sha256": "5a41397b76877ad7b1d3ef70824e77dd99164febe49657c161fd26d17d41ff5b",
          "sha1": "1186d9009878fea05ed768285872a72b363ece06",
          "md5": "d8fe30d34bf56a724908ca05da45a5d6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "clientscript-compiler-0.0.6-openrune-sources.jar",
          "url": "clientscript-compiler-0.0.6-openrune-sources.jar",
          "size": 1411291,
          "sha512": "d4e36f72b7e5f202d5f0ee8c5e4c4f4d2a6b89fc2f0f94cf3e2d9512439cb5b4e28bcef92b63d5d90df591c63a5900b5783014bc6cb7727906024f4837e939d9",
          "sha256": "3096c75613676c75a139b9a8c87c5aca681902c067403399f8b17079a8b09bbc",
          "sha1": "a17fbcc3352fee6350b3a57ca0f1cc4027c6cc22",
          "md5": "ebbd2eb9a51f7e123e6863f06f6c1382"
        },
        {
          "name": "clientscript-compiler-0.0.6-openrune-sources.jar",
          "url": "clientscript-compiler-0.0.6-openrune-sources.jar",
          "size": 1411291,
          "sha512": "d4e36f72b7e5f202d5f0ee8c5e4c4f4d2a6b89fc2f0f94cf3e2d9512439cb5b4e28bcef92b63d5d90df591c63a5900b5783014bc6cb7727906024f4837e939d9",
          "sha256": "3096c75613676c75a139b9a8c87c5aca681902c067403399f8b17079a8b09bbc",
          "sha1": "a17fbcc3352fee6350b3a57ca0f1cc4027c6cc22",
          "md5": "ebbd2eb9a51f7e123e6863f06f6c1382"
        }
      ]
    }
  ]
}
