{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "filestore",
    "version": "1.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-1.3.5.jar",
          "url": "filestore-1.3.5.jar",
          "size": 277553,
          "sha512": "be2a65728ee9340459fc1a7a7e498aec1881cc0fde285623aae7f5944d8b0f8d6748fbcf04f0eb370c7ced6e9d29d14c23f7bf221b67c33ab7e84edbaaf599ae",
          "sha256": "8ed4e7f724126643fe6702e6a39dacb9ea9eef05e9b1909645163e0f0f341eb9",
          "sha1": "565ac671566860593b32529eedccffe82b6db4e4",
          "md5": "39ef805dca4ee7e0b058d47b0738fd52"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-1.3.5.jar",
          "url": "filestore-1.3.5.jar",
          "size": 277553,
          "sha512": "be2a65728ee9340459fc1a7a7e498aec1881cc0fde285623aae7f5944d8b0f8d6748fbcf04f0eb370c7ced6e9d29d14c23f7bf221b67c33ab7e84edbaaf599ae",
          "sha256": "8ed4e7f724126643fe6702e6a39dacb9ea9eef05e9b1909645163e0f0f341eb9",
          "sha1": "565ac671566860593b32529eedccffe82b6db4e4",
          "md5": "39ef805dca4ee7e0b058d47b0738fd52"
        }
      ]
    }
  ]
}
