{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "central-common",
    "version": "1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-common-1.3.jar",
          "url": "central-common-1.3.jar",
          "size": 206132,
          "sha512": "7774f33fbc6e5c14b60037033e9cbc53105f026274f08cae28607504905f52d218537b89810382f47ffa357efc579721363b7060737d2ee636c7d9733d860fb7",
          "sha256": "e40fc2427177a046ac05020594db3687efe32203196345dc18d5475a29789edf",
          "sha1": "000022c60f9d3d640b6bb52b053bab88569f86d0",
          "md5": "8e2ff84a552d625f45c1aa735bfef975"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-common-1.3.jar",
          "url": "central-common-1.3.jar",
          "size": 206132,
          "sha512": "7774f33fbc6e5c14b60037033e9cbc53105f026274f08cae28607504905f52d218537b89810382f47ffa357efc579721363b7060737d2ee636c7d9733d860fb7",
          "sha256": "e40fc2427177a046ac05020594db3687efe32203196345dc18d5475a29789edf",
          "sha1": "000022c60f9d3d640b6bb52b053bab88569f86d0",
          "md5": "8e2ff84a552d625f45c1aa735bfef975"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "central-common-1.3-sources.jar",
          "url": "central-common-1.3-sources.jar",
          "size": 50747,
          "sha512": "ea0b1a2a893dbea40883394ef5227186c6aa26e322cfb92da666b36e3bac6f40a3bcce1b5562009dffa173e329a00913df9a5d78e803e46bdae132ddf3da7c3e",
          "sha256": "34042f34bc2770390e53a2663c375716e1ddac95f9533e1387c9a72dcbb0033b",
          "sha1": "cdfd021f166c3e22702ff546d40ecabaaba0375f",
          "md5": "6065bddc1ad0b77472eaf0662ccb0470"
        }
      ]
    }
  ]
}
