{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "filestore-tools",
    "version": "1.3.86",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-tools-1.3.86.jar",
          "url": "filestore-tools-1.3.86.jar",
          "size": 128234,
          "sha512": "17672b7f29d942c90781631909b7a9dab15490bc22dc00c184efa4130e132579d081d35d0e663d0c554704cf391581db9616be14f4f4bf69d0a696725fcf2978",
          "sha256": "6f1317c8bc6751b14c11101e91965096354031439007f9aedc1ec3a03dd02bc6",
          "sha1": "bb35b476455b504a09590627baa26b145f68f230",
          "md5": "161cb68cb89036f94eeaae98c6625392"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.openrune",
          "module": "filestore",
          "version": {
            "requires": "1.3.86"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.openrune",
          "module": "js5server",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.11.5"
          }
        },
        {
          "group": "cc.ekblad",
          "module": "4koma",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "com.displee",
          "module": "rs-cache-library",
          "version": {
            "requires": "7.1.5"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-file",
          "version": {
            "requires": "0.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-tools-1.3.86.jar",
          "url": "filestore-tools-1.3.86.jar",
          "size": 128234,
          "sha512": "17672b7f29d942c90781631909b7a9dab15490bc22dc00c184efa4130e132579d081d35d0e663d0c554704cf391581db9616be14f4f4bf69d0a696725fcf2978",
          "sha256": "6f1317c8bc6751b14c11101e91965096354031439007f9aedc1ec3a03dd02bc6",
          "sha1": "bb35b476455b504a09590627baa26b145f68f230",
          "md5": "161cb68cb89036f94eeaae98c6625392"
        }
      ]
    }
  ]
}
