{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "filestore-tools",
    "version": "1.3.6-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-tools-1.3.6-beta.jar",
          "url": "filestore-tools-1.3.6-beta.jar",
          "size": 99841,
          "sha512": "975faf1c9a91592e16c84b7592455b67bce258df62e7c3af81180cd6d53b26ca3c15e24c74657dd7129fc21313724572fc30746bfa00b9a3ef309613033679cf",
          "sha256": "384a38c53ab63be3336db08ae91a930422cb5a88d1fd1282ec555e34b221c6a9",
          "sha1": "a1a92e239fea33a1efb853b76589cfb2ce9a5dda",
          "md5": "1eca1ac5610b3f40f5f2464f86b6ba14"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.openrune",
          "module": "filestore",
          "version": {
            "requires": "1.3.6-beta"
          }
        },
        {
          "group": "dev.openrune",
          "module": "filestore-osrs",
          "version": {
            "requires": "1.3.6-beta"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.openrune",
          "module": "js5server",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.11.5"
          }
        },
        {
          "group": "cc.ekblad",
          "module": "4koma",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "com.displee",
          "module": "rs-cache-library",
          "version": {
            "requires": "7.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-tools-1.3.6-beta.jar",
          "url": "filestore-tools-1.3.6-beta.jar",
          "size": 99841,
          "sha512": "975faf1c9a91592e16c84b7592455b67bce258df62e7c3af81180cd6d53b26ca3c15e24c74657dd7129fc21313724572fc30746bfa00b9a3ef309613033679cf",
          "sha256": "384a38c53ab63be3336db08ae91a930422cb5a88d1fd1282ec555e34b221c6a9",
          "sha1": "a1a92e239fea33a1efb853b76589cfb2ce9a5dda",
          "md5": "1eca1ac5610b3f40f5f2464f86b6ba14"
        }
      ]
    }
  ]
}
