{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filestore",
    "version": "2.4.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-2.4.8.jar",
          "url": "filestore-2.4.8.jar",
          "size": 97539,
          "sha512": "55e9faa810f6d25691afb605cba1455735cbf2529cafc07f2b41da19a04a8e7a58dcb0ddedbbdcd567e3c4cc7f6bdb6bbb8a6f8331b2fb2ea329237d386a78dc",
          "sha256": "1feea2d6547be196cc546f898ada9e4861a805c4db0a2619ff1a1be1820262bb",
          "sha1": "3c08bed2b928bda0903ab7d9e3e40ba445f5b6bc",
          "md5": "25ae0098fc792bbdc440643c44884b33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.8"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-2.4.8.jar",
          "url": "filestore-2.4.8.jar",
          "size": 97539,
          "sha512": "55e9faa810f6d25691afb605cba1455735cbf2529cafc07f2b41da19a04a8e7a58dcb0ddedbbdcd567e3c4cc7f6bdb6bbb8a6f8331b2fb2ea329237d386a78dc",
          "sha256": "1feea2d6547be196cc546f898ada9e4861a805c4db0a2619ff1a1be1820262bb",
          "sha1": "3c08bed2b928bda0903ab7d9e3e40ba445f5b6bc",
          "md5": "25ae0098fc792bbdc440643c44884b33"
        }
      ]
    }
  ]
}
