{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "definition",
    "version": "2.4.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "definition-2.4.10.jar",
          "url": "definition-2.4.10.jar",
          "size": 531679,
          "sha512": "6a38372a97ce9be87ab603f3f874ab50da2c6b098b1ecfe83b210c9b0cd79354f9ddc39f59a3826b0db894c3c53bbab10acb1a0af50e9564e9f3b38f0f3df69b",
          "sha256": "533925af6486d67dccc9c56bf0fd17c4effc1e891cd910f281d4cd16540ab4a0",
          "sha1": "25630c842515c8ba965aa6d3e6ae76af52bb9e7e",
          "md5": "af60d4e4f05a86ebe34aae61b2b92f04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "toml-core",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "definition-2.4.10.jar",
          "url": "definition-2.4.10.jar",
          "size": 531679,
          "sha512": "6a38372a97ce9be87ab603f3f874ab50da2c6b098b1ecfe83b210c9b0cd79354f9ddc39f59a3826b0db894c3c53bbab10acb1a0af50e9564e9f3b38f0f3df69b",
          "sha256": "533925af6486d67dccc9c56bf0fd17c4effc1e891cd910f281d4cd16540ab4a0",
          "sha1": "25630c842515c8ba965aa6d3e6ae76af52bb9e7e",
          "md5": "af60d4e4f05a86ebe34aae61b2b92f04"
        }
      ]
    }
  ]
}
