{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.0.9.jar",
          "url": "displee-2.0.9.jar",
          "size": 130815,
          "sha512": "0bc0f76cab6fe8cbcf36741348d16c401c0c2c99a977d0e046f097bc05208bd60d387c4f22dd2b4b7f991c3603bbd3ecaa8bd64c9b2652877669a82dfe6c7ddd",
          "sha256": "f6e889e1a2f563b1f6672fcf48483d9182386e4be4b9d1277fdc49411cb43ce2",
          "sha1": "02f91235a813f88653617fc0fc39ad7b5bff1e5e",
          "md5": "9d516f50dde2ad22103c0d6a89a2c23a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.0.9.jar",
          "url": "displee-2.0.9.jar",
          "size": 130815,
          "sha512": "0bc0f76cab6fe8cbcf36741348d16c401c0c2c99a977d0e046f097bc05208bd60d387c4f22dd2b4b7f991c3603bbd3ecaa8bd64c9b2652877669a82dfe6c7ddd",
          "sha256": "f6e889e1a2f563b1f6672fcf48483d9182386e4be4b9d1277fdc49411cb43ce2",
          "sha1": "02f91235a813f88653617fc0fc39ad7b5bff1e5e",
          "md5": "9d516f50dde2ad22103c0d6a89a2c23a"
        }
      ]
    }
  ]
}
