{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "definition",
    "version": "2.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "definition-2.4.1.jar",
          "url": "definition-2.4.1.jar",
          "size": 502886,
          "sha512": "66a9080b36c164cc2f42fbcc0daed097f79e9a4154aec34d90132b768780a86a2c892a38665bafac0b760167ba76d5b919865cded28f48a8fae438347beb74ea",
          "sha256": "a830605982bb1ca605f645c839afc94a0cf400e1557b615afcee037724b6520e",
          "sha1": "68de4792a82bd7927a2881b7d5f6556a355baca9",
          "md5": "08be43c944b07fd6a4a799899d17fe3d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "toml-core",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "definition-2.4.1.jar",
          "url": "definition-2.4.1.jar",
          "size": 502886,
          "sha512": "66a9080b36c164cc2f42fbcc0daed097f79e9a4154aec34d90132b768780a86a2c892a38665bafac0b760167ba76d5b919865cded28f48a8fae438347beb74ea",
          "sha256": "a830605982bb1ca605f645c839afc94a0cf400e1557b615afcee037724b6520e",
          "sha1": "68de4792a82bd7927a2881b7d5f6556a355baca9",
          "md5": "08be43c944b07fd6a4a799899d17fe3d"
        }
      ]
    }
  ]
}
