{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718-fs",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-fs-3.0.0.jar",
          "url": "r718-fs-3.0.0.jar",
          "size": 7584,
          "sha512": "5f98d4de2c7b7d0abb3d960118be0bec43b0c5f0f32e662daab3667481d2c4bae2547199917f8a737a0798acfdbeee9ce74e2d28ec9d23481a577b35872e4f01",
          "sha256": "30c129b42905b586519c910ec3f12f103a898720b52d5586f0375563e378f0f9",
          "sha1": "742e899a8d3a464c15a2e8b2919bc4122af88c13",
          "md5": "2e10a362a87c6c718bcf908515d0d79b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "dev.or2",
          "module": "r718",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "r718-fs-3.0.0.jar",
          "url": "r718-fs-3.0.0.jar",
          "size": 7584,
          "sha512": "5f98d4de2c7b7d0abb3d960118be0bec43b0c5f0f32e662daab3667481d2c4bae2547199917f8a737a0798acfdbeee9ce74e2d28ec9d23481a577b35872e4f01",
          "sha256": "30c129b42905b586519c910ec3f12f103a898720b52d5586f0375563e378f0f9",
          "sha1": "742e899a8d3a464c15a2e8b2919bc4122af88c13",
          "md5": "2e10a362a87c6c718bcf908515d0d79b"
        }
      ]
    }
  ]
}
