{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs",
    "version": "2.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-2.3.9.jar",
          "url": "osrs-2.3.9.jar",
          "size": 87689,
          "sha512": "c20f004165d45c57a96e0c19215bf9558eaca480a9c2dad594ec0debd805459e252defced6a4f81d945096d247aab41dc4793a3cb4a95557ceb5f2b8ed0eb667",
          "sha256": "8f72ec71fc948beab9afb5831480ffb43d3cf88fe9e2d5429ae7e6c7a385335c",
          "sha1": "65c7736d59d56bb2eec168246bfebc48e93db20b",
          "md5": "b424a61d7d5644eb656a12a9e478e9c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-2.3.9.jar",
          "url": "osrs-2.3.9.jar",
          "size": 87689,
          "sha512": "c20f004165d45c57a96e0c19215bf9558eaca480a9c2dad594ec0debd805459e252defced6a4f81d945096d247aab41dc4793a3cb4a95557ceb5f2b8ed0eb667",
          "sha256": "8f72ec71fc948beab9afb5831480ffb43d3cf88fe9e2d5429ae7e6c7a385335c",
          "sha1": "65c7736d59d56bb2eec168246bfebc48e93db20b",
          "md5": "b424a61d7d5644eb656a12a9e478e9c5"
        }
      ]
    }
  ]
}
