{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs-fs",
    "version": "2.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-fs-2.0.3.jar",
          "url": "osrs-fs-2.0.3.jar",
          "size": 22442,
          "sha512": "baf5c89b5ad2143ffb62247d20c04a28353008821d627d29211bb27226f53ae114040056fab8680e0453d529ad055cba543485fc2619bbe9f3cba9d8020f6190",
          "sha256": "e59749f5735902e25bdca282540ea07bdcb349e22947759f65731440242a779f",
          "sha1": "e0d408c69ab0216697bc5cf28962d4199726cd55",
          "md5": "fae9b9f52d138f5c340d9f8f6970d32c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-fs-2.0.3.jar",
          "url": "osrs-fs-2.0.3.jar",
          "size": 22442,
          "sha512": "baf5c89b5ad2143ffb62247d20c04a28353008821d627d29211bb27226f53ae114040056fab8680e0453d529ad055cba543485fc2619bbe9f3cba9d8020f6190",
          "sha256": "e59749f5735902e25bdca282540ea07bdcb349e22947759f65731440242a779f",
          "sha1": "e0d408c69ab0216697bc5cf28962d4199726cd55",
          "md5": "fae9b9f52d138f5c340d9f8f6970d32c"
        }
      ]
    }
  ]
}
