{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filesystem",
    "version": "2.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filesystem-2.4.2.jar",
          "url": "filesystem-2.4.2.jar",
          "size": 51650,
          "sha512": "250f6208b255a58f12b54eee9e0fab15fb8e79673c3b77dcb2bfa3029449d71aadd36330c76f7796e22ba2d6cf2a6184b4e0de59b0e7562942456e8b199c4aae",
          "sha256": "a567230b4a9e0e0c5b7a7fcc483cc778a4095bdfa04b9ff5d3e86952b07db0ce",
          "sha1": "70042396ed66ca12261232a2d99a3fcc59d43e4a",
          "md5": "62f8f4bdf4eee9634f3e9c8d06fd1b9a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "filesystem-2.4.2.jar",
          "url": "filesystem-2.4.2.jar",
          "size": 51650,
          "sha512": "250f6208b255a58f12b54eee9e0fab15fb8e79673c3b77dcb2bfa3029449d71aadd36330c76f7796e22ba2d6cf2a6184b4e0de59b0e7562942456e8b199c4aae",
          "sha256": "a567230b4a9e0e0c5b7a7fcc483cc778a4095bdfa04b9ff5d3e86952b07db0ce",
          "sha1": "70042396ed66ca12261232a2d99a3fcc59d43e4a",
          "md5": "62f8f4bdf4eee9634f3e9c8d06fd1b9a"
        }
      ]
    }
  ]
}
