{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718",
    "version": "2.4.11-nc",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-2.4.11-nc.jar",
          "url": "r718-2.4.11-nc.jar",
          "size": 14562,
          "sha512": "5e2502abab527bc298b0aea503773ecd0d49926550556eaf67ddc3f0bb8328b8e790d16f51c8b1b0ff2d4ebc5b38088d8741cc9654cbfefbf386469ef00ce452",
          "sha256": "dfe7dce8a84418c6802544551d41380676fbde226afda8eae483e3fe45cda362",
          "sha1": "768828ab34d17fce918832fa6d30182fa7b8fa60",
          "md5": "c05a1ab6f3aa7a0bf79d66997414786c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.11-nc"
          }
        }
      ],
      "files": [
        {
          "name": "r718-2.4.11-nc.jar",
          "url": "r718-2.4.11-nc.jar",
          "size": 14562,
          "sha512": "5e2502abab527bc298b0aea503773ecd0d49926550556eaf67ddc3f0bb8328b8e790d16f51c8b1b0ff2d4ebc5b38088d8741cc9654cbfefbf386469ef00ce452",
          "sha256": "dfe7dce8a84418c6802544551d41380676fbde226afda8eae483e3fe45cda362",
          "sha1": "768828ab34d17fce918832fa6d30182fa7b8fa60",
          "md5": "c05a1ab6f3aa7a0bf79d66997414786c"
        }
      ]
    }
  ]
}
