{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs",
    "version": "2.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-2.0.2.jar",
          "url": "osrs-2.0.2.jar",
          "size": 73575,
          "sha512": "8950928648da9b18e99e0241e0b882f156fd6f8d6e0f566b408c631cc68e021bc62a96b933c4b8d6f0d5b6055831a5bf27b2ac456c2e9baf53bff888eb0a6d19",
          "sha256": "c402598bc4af2f9a99abc1c5e05bc37feff6d8ebe8b1b824fd3f4bcea306c97f",
          "sha1": "70fcc4e60c7dd652ab2af1c0a934ac853616d233",
          "md5": "522e74e2202ba3fbf48831916dcb3bcb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-2.0.2.jar",
          "url": "osrs-2.0.2.jar",
          "size": 73575,
          "sha512": "8950928648da9b18e99e0241e0b882f156fd6f8d6e0f566b408c631cc68e021bc62a96b933c4b8d6f0d5b6055831a5bf27b2ac456c2e9baf53bff888eb0a6d19",
          "sha256": "c402598bc4af2f9a99abc1c5e05bc37feff6d8ebe8b1b824fd3f4bcea306c97f",
          "sha1": "70fcc4e60c7dd652ab2af1c0a934ac853616d233",
          "md5": "522e74e2202ba3fbf48831916dcb3bcb"
        }
      ]
    }
  ]
}
