{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "tools",
    "version": "2.4.2-cache",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "tools-2.4.2-cache.jar",
          "url": "tools-2.4.2-cache.jar",
          "size": 324128,
          "sha512": "6f7804a1b98cf0d23cc2e630c3b1efe4943d06f6815632701814fd04a1238c9aff8572d4c97d0641a621c1e82f8ab1fb4071b6b16c0fc4f23cd8e795b3743181",
          "sha256": "c56f2a838619a634301a6ca79ec9587233c2f4b609ee80cd91843a109936f5e4",
          "sha1": "76c2b559616968c893c29d62244e9dd3d0897f4e",
          "md5": "1aadc29c2a4216a627356a6ad11232e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.4.2-cache"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.2-cache"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.4.2-cache"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs-fs",
          "version": {
            "requires": "2.4.2-cache"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.11.5"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "dev.or2",
          "module": "cache",
          "version": {
            "requires": "2.4.2-cache"
          }
        },
        {
          "group": "dev.or2.openrs2",
          "module": "cache",
          "version": {
            "requires": "1.0.0-openrune"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "toml-rsconfig",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "me.filby",
          "module": "clientscript-compiler",
          "version": {
            "requires": "0.0.2-openrune"
          }
        }
      ],
      "files": [
        {
          "name": "tools-2.4.2-cache.jar",
          "url": "tools-2.4.2-cache.jar",
          "size": 324128,
          "sha512": "6f7804a1b98cf0d23cc2e630c3b1efe4943d06f6815632701814fd04a1238c9aff8572d4c97d0641a621c1e82f8ab1fb4071b6b16c0fc4f23cd8e795b3743181",
          "sha256": "c56f2a838619a634301a6ca79ec9587233c2f4b609ee80cd91843a109936f5e4",
          "sha1": "76c2b559616968c893c29d62244e9dd3d0897f4e",
          "md5": "1aadc29c2a4216a627356a6ad11232e9"
        }
      ]
    }
  ]
}
