{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718",
    "version": "3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-3.0.1.jar",
          "url": "r718-3.0.1.jar",
          "size": 15435,
          "sha512": "c912f689df8fb3c8ec756519fe2444df941ac86a735ef9e95f3fa44d885076aa4fcb0017c85d8a3258163a3e6ad0ee6ad1360304c7d572e0404404bd7845bab9",
          "sha256": "f6b2c3f7e1cf644dda266aa85f28f81d14c7cf7d10e7a54106327a5cf8c77361",
          "sha1": "efbd94efd65fd1fc25f12f8bb02e0f4617fbc9c9",
          "md5": "31145322380a5b28b8364565880ca9c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "3.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "r718-3.0.1.jar",
          "url": "r718-3.0.1.jar",
          "size": 15435,
          "sha512": "c912f689df8fb3c8ec756519fe2444df941ac86a735ef9e95f3fa44d885076aa4fcb0017c85d8a3258163a3e6ad0ee6ad1360304c7d572e0404404bd7845bab9",
          "sha256": "f6b2c3f7e1cf644dda266aa85f28f81d14c7cf7d10e7a54106327a5cf8c77361",
          "sha1": "efbd94efd65fd1fc25f12f8bb02e0f4617fbc9c9",
          "md5": "31145322380a5b28b8364565880ca9c1"
        }
      ]
    }
  ]
}
