{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "opcode",
    "version": "2.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "opcode-2.3.9.jar",
          "url": "opcode-2.3.9.jar",
          "size": 127288,
          "sha512": "326871c7716090bcbf744d079a5628dc7e54ad731c88555400674b127a2ca8f7fbe762b2a4240f6e0653b63f1286bd537cc1c13e5568c08866c8c7c01402adba",
          "sha256": "2e56493321742fc30bac68e8d7bb18e43e86d8322a912b01acb18006cd777402",
          "sha1": "aa6a08767e70db504c77c1bc46813cbf8351a02d",
          "md5": "42b663bc556d7cb8851145cb34ffd5c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "opcode-2.3.9.jar",
          "url": "opcode-2.3.9.jar",
          "size": 127288,
          "sha512": "326871c7716090bcbf744d079a5628dc7e54ad731c88555400674b127a2ca8f7fbe762b2a4240f6e0653b63f1286bd537cc1c13e5568c08866c8c7c01402adba",
          "sha256": "2e56493321742fc30bac68e8d7bb18e43e86d8322a912b01acb18006cd777402",
          "sha1": "aa6a08767e70db504c77c1bc46813cbf8351a02d",
          "md5": "42b663bc556d7cb8851145cb34ffd5c6"
        }
      ]
    }
  ]
}
