{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filestore",
    "version": "2.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-2.4.6.jar",
          "url": "filestore-2.4.6.jar",
          "size": 94748,
          "sha512": "8ce9d9485104bd86d865cf96217835d82cc0264f7f969ce6f1894b53cd72264a66302ec3da7f6da96535f153aaa2f7f1feab18c70ad9bbaab983ba1b502e81a8",
          "sha256": "d56dd8fafda060997433ef00548ccea551341deaa32f6996d526545767098e95",
          "sha1": "df29440558af5a61d36dba4a7d93ee514798d2be",
          "md5": "c382ef97855a03e00d51d67e9fdf821f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.6"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.6"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-2.4.6.jar",
          "url": "filestore-2.4.6.jar",
          "size": 94748,
          "sha512": "8ce9d9485104bd86d865cf96217835d82cc0264f7f969ce6f1894b53cd72264a66302ec3da7f6da96535f153aaa2f7f1feab18c70ad9bbaab983ba1b502e81a8",
          "sha256": "d56dd8fafda060997433ef00548ccea551341deaa32f6996d526545767098e95",
          "sha1": "df29440558af5a61d36dba4a7d93ee514798d2be",
          "md5": "c382ef97855a03e00d51d67e9fdf821f"
        }
      ]
    }
  ]
}
