{
  "formatVersion": "1.1",
  "component": {
    "group": "org.openrs2",
    "module": "openrs2-cache-cli",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.ajalt.clikt",
          "module": "clikt",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "openrs2-cache-cli-0.1.2-SNAPSHOT.jar",
          "url": "openrs2-cache-cli-0.1.2-SNAPSHOT.jar",
          "size": 7245,
          "sha512": "bd70de22724aa1496afaddc278680a4c66b51c98df98651fab93587b70a2beb56632967fa11f4123c3b25c1710c784272e2d047d797bca52911d748cf782e99d",
          "sha256": "e5e9fdd0e2ee27006007ae39da3b02f6e77beadd332a24f5075d1f08bb24d75a",
          "sha1": "b94d156817b8b2c711a76cdc0c54309be85648d9",
          "md5": "49f69e96a9f1d4487eec131585d3e731"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "org.openrs2",
          "module": "openrs2-cache",
          "version": {
            "requires": "0.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.openrs2",
          "module": "openrs2-inject",
          "version": {
            "requires": "0.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.github.ajalt.clikt",
          "module": "clikt",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.12"
          }
        }
      ],
      "files": [
        {
          "name": "openrs2-cache-cli-0.1.2-SNAPSHOT.jar",
          "url": "openrs2-cache-cli-0.1.2-SNAPSHOT.jar",
          "size": 7245,
          "sha512": "bd70de22724aa1496afaddc278680a4c66b51c98df98651fab93587b70a2beb56632967fa11f4123c3b25c1710c784272e2d047d797bca52911d748cf782e99d",
          "sha256": "e5e9fdd0e2ee27006007ae39da3b02f6e77beadd332a24f5075d1f08bb24d75a",
          "sha1": "b94d156817b8b2c711a76cdc0c54309be85648d9",
          "md5": "49f69e96a9f1d4487eec131585d3e731"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "openrs2-cache-cli-0.1.2-SNAPSHOT-sources.jar",
          "url": "openrs2-cache-cli-0.1.2-SNAPSHOT-sources.jar",
          "size": 2244,
          "sha512": "0e37536da458033d2eebcf87200d148f5bcd97fe02cb973434e2497ca7e25cb2ead4e566a64afce6808425bb3cb657951a2743c75b51e315380d699c86950cc1",
          "sha256": "51848921322e4d29869940166804a3ed5ea9c101cc39c95b07dcb0cd8cda8299",
          "sha1": "a8244a5a0ba92dd1dd9c7229dcb66b699766ad15",
          "md5": "941a88696c3cfbb7eb40317d5f051d84"
        },
        {
          "name": "openrs2-cache-cli-0.1.2-SNAPSHOT-sources.jar",
          "url": "openrs2-cache-cli-0.1.2-SNAPSHOT-sources.jar",
          "size": 2244,
          "sha512": "0e37536da458033d2eebcf87200d148f5bcd97fe02cb973434e2497ca7e25cb2ead4e566a64afce6808425bb3cb657951a2743c75b51e315380d699c86950cc1",
          "sha256": "51848921322e4d29869940166804a3ed5ea9c101cc39c95b07dcb0cd8cda8299",
          "sha1": "a8244a5a0ba92dd1dd9c7229dcb66b699766ad15",
          "md5": "941a88696c3cfbb7eb40317d5f051d84"
        }
      ]
    }
  ]
}
