{
  "formatVersion": "1.1",
  "component": {
    "group": "me.filby",
    "module": "runescript-runtime",
    "version": "0.0.1-openrune",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescript-runtime-0.0.1-openrune.jar",
          "url": "runescript-runtime-0.0.1-openrune.jar",
          "size": 41007,
          "sha512": "44b1541d4f8d85ad55824966fe4e3852aba018d4a66854f43ccfca6437a02c474f70e48c370ac7423f9c34b9984fe0d7363601e9d70a54c429485e8cd300c42c",
          "sha256": "f4c0eb7f1ce094d063cabd1956040403516606f2ce1c07850e232f0007124f3d",
          "sha1": "7de4a40c7dfe3c1d86336d1c21cc6deb81fcd338",
          "md5": "1ee3f2722e568e631a20a7d3a2d7f342"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.0-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "me.filby",
          "module": "runescript-compiler",
          "version": {
            "requires": "0.0.1-openrune"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescript-runtime-0.0.1-openrune.jar",
          "url": "runescript-runtime-0.0.1-openrune.jar",
          "size": 41007,
          "sha512": "44b1541d4f8d85ad55824966fe4e3852aba018d4a66854f43ccfca6437a02c474f70e48c370ac7423f9c34b9984fe0d7363601e9d70a54c429485e8cd300c42c",
          "sha256": "f4c0eb7f1ce094d063cabd1956040403516606f2ce1c07850e232f0007124f3d",
          "sha1": "7de4a40c7dfe3c1d86336d1c21cc6deb81fcd338",
          "md5": "1ee3f2722e568e631a20a7d3a2d7f342"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescript-runtime-0.0.1-openrune-sources.jar",
          "url": "runescript-runtime-0.0.1-openrune-sources.jar",
          "size": 13755,
          "sha512": "b5401de1b6ccc672f7dcd9f0b7b893e793e8d89e54e6bda5fd1c998cf27fe91cc1b4fb0a503b6735ad0edb24a483c2f4482876dec869c2b8e30280f46993cd56",
          "sha256": "b7bf84d53a04c54733d416a4217f13f16e90ff38693d6b3f5b3c239fb8eef588",
          "sha1": "e838291faa22f973a172b7e9f9a401bb3afefe1b",
          "md5": "2c382915e2d54cd0d7b009bb4636b5de"
        },
        {
          "name": "runescript-runtime-0.0.1-openrune-sources.jar",
          "url": "runescript-runtime-0.0.1-openrune-sources.jar",
          "size": 13755,
          "sha512": "b5401de1b6ccc672f7dcd9f0b7b893e793e8d89e54e6bda5fd1c998cf27fe91cc1b4fb0a503b6735ad0edb24a483c2f4482876dec869c2b8e30280f46993cd56",
          "sha256": "b7bf84d53a04c54733d416a4217f13f16e90ff38693d6b3f5b3c239fb8eef588",
          "sha1": "e838291faa22f973a172b7e9f9a401bb3afefe1b",
          "md5": "2c382915e2d54cd0d7b009bb4636b5de"
        }
      ]
    }
  ]
}
