{
  "formatVersion": "1.1",
  "component": {
    "group": "me.filby",
    "module": "runescript-compiler",
    "version": "0.0.1-openrune",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.filby",
          "module": "runescript-parser",
          "version": {
            "requires": "0.0.1-openrune"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescript-compiler-0.0.1-openrune.jar",
          "url": "runescript-compiler-0.0.1-openrune.jar",
          "size": 275478,
          "sha512": "d6ba96f7f40c585fb39d11581630c317687ac070de0141abaf7a4a72273ffd1995a95ce27881d2cca2a18c90533f7f0545db4d3bb41283a284453523938c1f2c",
          "sha256": "d9b07a01f27b587a9595ab9267b23edb901febb40774078667991705ed4065ea",
          "sha1": "9a9abba0abdab0465efac1a4111c88bd28fc4712",
          "md5": "9201238d94df5f8fcb64f215916a93f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.0-jre"
          }
        },
        {
          "group": "me.filby",
          "module": "runescript-parser",
          "version": {
            "requires": "0.0.1-openrune"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.11"
          }
        }
      ],
      "files": [
        {
          "name": "runescript-compiler-0.0.1-openrune.jar",
          "url": "runescript-compiler-0.0.1-openrune.jar",
          "size": 275478,
          "sha512": "d6ba96f7f40c585fb39d11581630c317687ac070de0141abaf7a4a72273ffd1995a95ce27881d2cca2a18c90533f7f0545db4d3bb41283a284453523938c1f2c",
          "sha256": "d9b07a01f27b587a9595ab9267b23edb901febb40774078667991705ed4065ea",
          "sha1": "9a9abba0abdab0465efac1a4111c88bd28fc4712",
          "md5": "9201238d94df5f8fcb64f215916a93f2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescript-compiler-0.0.1-openrune-sources.jar",
          "url": "runescript-compiler-0.0.1-openrune-sources.jar",
          "size": 60788,
          "sha512": "69926f9ae9840c3f509bf60a176a1e8aa69674a79647b85aca549c4a997ae6e696184cf1540318be319c6ce98b8f590d3c0ed726f2128ef21b93c8ddc1eeaa79",
          "sha256": "d54c4b412714e55a67f7c65f8335b82cb69e55581522f7c9ad9a8bcbe21a6c73",
          "sha1": "f0ac6c2b50e06ceceeedfa46214df3bffd454db6",
          "md5": "f8738d419adc4e20d9978ea9963891bf"
        },
        {
          "name": "runescript-compiler-0.0.1-openrune-sources.jar",
          "url": "runescript-compiler-0.0.1-openrune-sources.jar",
          "size": 60788,
          "sha512": "69926f9ae9840c3f509bf60a176a1e8aa69674a79647b85aca549c4a997ae6e696184cf1540318be319c6ce98b8f590d3c0ed726f2128ef21b93c8ddc1eeaa79",
          "sha256": "d54c4b412714e55a67f7c65f8335b82cb69e55581522f7c9ad9a8bcbe21a6c73",
          "sha1": "f0ac6c2b50e06ceceeedfa46214df3bffd454db6",
          "md5": "f8738d419adc4e20d9978ea9963891bf"
        }
      ]
    }
  ]
}
