{
  "formatVersion": "1.1",
  "component": {
    "group": "org.openrs2",
    "module": "openrs2-cache-550",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.openrs2",
          "module": "openrs2-cache",
          "version": {
            "requires": "0.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.google.inject.extensions",
          "module": "guice-assistedinject",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "openrs2-cache-550-0.1.2-SNAPSHOT.jar",
          "url": "openrs2-cache-550-0.1.2-SNAPSHOT.jar",
          "size": 45112,
          "sha512": "0ccada47b1b2f5808ae703462b6b4451bd0d94140188d99fe34a57c83c28d8355f389a944978acf20821d8bfce29c593b6a2a324ee96d7f1b7c6cf8d781f0709",
          "sha256": "4232b3040f997c60810330372ff7e3bd5e8c2bfa70a151fb4e1377c5b6220201",
          "sha1": "f940255b97bac512a1fc5fb9945cde9436df2ea8",
          "md5": "e616e4dface0f9ad1b3ac1880869aad2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "org.openrs2",
          "module": "openrs2-buffer",
          "version": {
            "requires": "0.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.openrs2",
          "module": "openrs2-util",
          "version": {
            "requires": "0.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.openrs2",
          "module": "openrs2-cache",
          "version": {
            "requires": "0.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.google.inject.extensions",
          "module": "guice-assistedinject",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "openrs2-cache-550-0.1.2-SNAPSHOT.jar",
          "url": "openrs2-cache-550-0.1.2-SNAPSHOT.jar",
          "size": 45112,
          "sha512": "0ccada47b1b2f5808ae703462b6b4451bd0d94140188d99fe34a57c83c28d8355f389a944978acf20821d8bfce29c593b6a2a324ee96d7f1b7c6cf8d781f0709",
          "sha256": "4232b3040f997c60810330372ff7e3bd5e8c2bfa70a151fb4e1377c5b6220201",
          "sha1": "f940255b97bac512a1fc5fb9945cde9436df2ea8",
          "md5": "e616e4dface0f9ad1b3ac1880869aad2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "openrs2-cache-550-0.1.2-SNAPSHOT-sources.jar",
          "url": "openrs2-cache-550-0.1.2-SNAPSHOT-sources.jar",
          "size": 15598,
          "sha512": "d1575bfde1f84b80252e8aa98a889d9410c0d87c4234e294bd31fdeba389f5e0767ae1594fb235c9d4909490869c60e1bbca49d03d24df18d907279018fbf0b4",
          "sha256": "eac48f69ffd1f869ed409d1aa63dc0c68810ad03f26592b3ad77c0267c80b109",
          "sha1": "fa0cde3016a66b3bbc4f9ddec8034c219baa899a",
          "md5": "5ca9c0e1e3a21efc297bb7bc0e9a2075"
        },
        {
          "name": "openrs2-cache-550-0.1.2-SNAPSHOT-sources.jar",
          "url": "openrs2-cache-550-0.1.2-SNAPSHOT-sources.jar",
          "size": 15598,
          "sha512": "d1575bfde1f84b80252e8aa98a889d9410c0d87c4234e294bd31fdeba389f5e0767ae1594fb235c9d4909490869c60e1bbca49d03d24df18d907279018fbf0b4",
          "sha256": "eac48f69ffd1f869ed409d1aa63dc0c68810ad03f26592b3ad77c0267c80b109",
          "sha1": "fa0cde3016a66b3bbc4f9ddec8034c219baa899a",
          "md5": "5ca9c0e1e3a21efc297bb7bc0e9a2075"
        }
      ]
    }
  ]
}
