{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filesystem",
    "version": "2.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filesystem-2.0.2.jar",
          "url": "filesystem-2.0.2.jar",
          "size": 74762,
          "sha512": "248055b69b0a1d11140e34ff0f053bf99968ea2244eb8fcaa4636a450e2676cf9ea487d12c3929b7ec8e83322a4954343ac00994766bc626292495a81d5454b1",
          "sha256": "b1844a0e6c02ca5f5f92a8574dd533875a872dcb121ce850434186f8082ba4e8",
          "sha1": "a3580de0720fb9f028a3af75e4d6789d36b5f442",
          "md5": "47a9e04763b401de8e4bdd5d2f037db4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "filesystem-2.0.2.jar",
          "url": "filesystem-2.0.2.jar",
          "size": 74762,
          "sha512": "248055b69b0a1d11140e34ff0f053bf99968ea2244eb8fcaa4636a450e2676cf9ea487d12c3929b7ec8e83322a4954343ac00994766bc626292495a81d5454b1",
          "sha256": "b1844a0e6c02ca5f5f92a8574dd533875a872dcb121ce850434186f8082ba4e8",
          "sha1": "a3580de0720fb9f028a3af75e4d6789d36b5f442",
          "md5": "47a9e04763b401de8e4bdd5d2f037db4"
        }
      ]
    }
  ]
}
