{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filestore",
    "version": "2.0.90",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-2.0.90.jar",
          "url": "filestore-2.0.90.jar",
          "size": 24242,
          "sha512": "1a6af37b9900b0fcdd2b5e6e3596320be29a7246267e542fec89b7ebc0530fce0e6312d78479d9ab400de655010a891656d843ebffa6410cc064683f23ae0b16",
          "sha256": "0d132738b92bc382a0abe2b19627957fa81eb9ad959235b152b326cade0e0bd8",
          "sha1": "5024de2281117ba835d4613b75ecd47ae9d19b65",
          "md5": "88af1c1d3a5ea2681e4e875bd6add5e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.90"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.0.90"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-2.0.90.jar",
          "url": "filestore-2.0.90.jar",
          "size": 24242,
          "sha512": "1a6af37b9900b0fcdd2b5e6e3596320be29a7246267e542fec89b7ebc0530fce0e6312d78479d9ab400de655010a891656d843ebffa6410cc064683f23ae0b16",
          "sha256": "0d132738b92bc382a0abe2b19627957fa81eb9ad959235b152b326cade0e0bd8",
          "sha1": "5024de2281117ba835d4613b75ecd47ae9d19b65",
          "md5": "88af1c1d3a5ea2681e4e875bd6add5e9"
        }
      ]
    }
  ]
}
