{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718",
    "version": "2.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-2.0.7.jar",
          "url": "r718-2.0.7.jar",
          "size": 13988,
          "sha512": "a7178b6cf137a632daab88edf7a73dd7ed3aa7372736bde934e8a7c68dc525d782ea7c8e015b3f088907149869d8dfb9b5bde4789b52c7f3f79a18b633bd82de",
          "sha256": "3bb8f565fc3337d6b052a7cfe5a1f1bfb4f705f82915355976bfbfe6fa1adb3c",
          "sha1": "c351888c1b37467fa7949a9a13bb1cef180a1ecb",
          "md5": "329e452e9f16035500806e0538fcfd0a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "r718-2.0.7.jar",
          "url": "r718-2.0.7.jar",
          "size": 13988,
          "sha512": "a7178b6cf137a632daab88edf7a73dd7ed3aa7372736bde934e8a7c68dc525d782ea7c8e015b3f088907149869d8dfb9b5bde4789b52c7f3f79a18b633bd82de",
          "sha256": "3bb8f565fc3337d6b052a7cfe5a1f1bfb4f705f82915355976bfbfe6fa1adb3c",
          "sha1": "c351888c1b37467fa7949a9a13bb1cef180a1ecb",
          "md5": "329e452e9f16035500806e0538fcfd0a"
        }
      ]
    }
  ]
}
