{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718-fs",
    "version": "2.4.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-fs-2.4.12.jar",
          "url": "r718-fs-2.4.12.jar",
          "size": 7588,
          "sha512": "4940612e250d74d9ca51e11766c8e812c59bb3bdb6cf2ff796997a7b104d21a5add28fae933a763a66a2bec3fbf2f47db494d14180ed2d012200f0f332b5cf2a",
          "sha256": "e4474ffbcf5944287abcb29782c097627239e0719a9819f3f6ea55b8276e05b5",
          "sha1": "528ac69fc1b0371b90423b05f8b74e855bcee19d",
          "md5": "305fc418acd23d92add9dbecc8504b04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.4.12"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.12"
          }
        },
        {
          "group": "dev.or2",
          "module": "r718",
          "version": {
            "requires": "2.4.12"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.12"
          }
        }
      ],
      "files": [
        {
          "name": "r718-fs-2.4.12.jar",
          "url": "r718-fs-2.4.12.jar",
          "size": 7588,
          "sha512": "4940612e250d74d9ca51e11766c8e812c59bb3bdb6cf2ff796997a7b104d21a5add28fae933a763a66a2bec3fbf2f47db494d14180ed2d012200f0f332b5cf2a",
          "sha256": "e4474ffbcf5944287abcb29782c097627239e0719a9819f3f6ea55b8276e05b5",
          "sha1": "528ac69fc1b0371b90423b05f8b74e855bcee19d",
          "md5": "305fc418acd23d92add9dbecc8504b04"
        }
      ]
    }
  ]
}
