{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718-fs",
    "version": "2.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-fs-2.0.3.jar",
          "url": "r718-fs-2.0.3.jar",
          "size": 7586,
          "sha512": "2b0f9bc8aea58d1156b403ad2363c9146c09347e94e47744f3511c69a86cb96ea4560aece5f2fe8f40717923cdf48ab8f4727e4c2cc0efa9c6df0524636a641a",
          "sha256": "230dc65f1d120fd8ba706876d49217ff766108058dc85f1cd8a8279d369bdfe7",
          "sha1": "2522a9dac1af2095119833431d15f34634d5c0df",
          "md5": "d1389b1be5fee2b24f657118db89455b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "r718",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "r718-fs-2.0.3.jar",
          "url": "r718-fs-2.0.3.jar",
          "size": 7586,
          "sha512": "2b0f9bc8aea58d1156b403ad2363c9146c09347e94e47744f3511c69a86cb96ea4560aece5f2fe8f40717923cdf48ab8f4727e4c2cc0efa9c6df0524636a641a",
          "sha256": "230dc65f1d120fd8ba706876d49217ff766108058dc85f1cd8a8279d369bdfe7",
          "sha1": "2522a9dac1af2095119833431d15f34634d5c0df",
          "md5": "d1389b1be5fee2b24f657118db89455b"
        }
      ]
    }
  ]
}
