{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "opcode",
    "version": "2.4.2-cache",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "opcode-2.4.2-cache.jar",
          "url": "opcode-2.4.2-cache.jar",
          "size": 127172,
          "sha512": "ac19a66e05fde22a8514b486dcc9deaac5225e00b43a5417ec905cf09d3da67eb76db0253773a3061ac1d7b28c85439c63c520f514148de372f1b76644973bad",
          "sha256": "8955e1f39a025cdd930dcaf4de1e6f53de1c01e9651af9f2908fd6006aa62574",
          "sha1": "640ed03b94470427dd277bad342eccff48f13594",
          "md5": "2674e735c49c1a185ce618f051b2b872"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.2-cache"
          }
        }
      ],
      "files": [
        {
          "name": "opcode-2.4.2-cache.jar",
          "url": "opcode-2.4.2-cache.jar",
          "size": 127172,
          "sha512": "ac19a66e05fde22a8514b486dcc9deaac5225e00b43a5417ec905cf09d3da67eb76db0253773a3061ac1d7b28c85439c63c520f514148de372f1b76644973bad",
          "sha256": "8955e1f39a025cdd930dcaf4de1e6f53de1c01e9651af9f2908fd6006aa62574",
          "sha1": "640ed03b94470427dd277bad342eccff48f13594",
          "md5": "2674e735c49c1a185ce618f051b2b872"
        }
      ]
    }
  ]
}
