{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718-fs",
    "version": "2.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-fs-2.4.1.jar",
          "url": "r718-fs-2.4.1.jar",
          "size": 7588,
          "sha512": "5b1bd001ca8e2ffd0f7a7a13f0a2a1d5c635e573848d7b9ee76020a8f8c3f2b8725582154fc5cf450e86131f611aa28a7194ed603c0cb59a794e7ad1dfc5c45c",
          "sha256": "37e14bf6f1d2fe885e8548abdf79be5ee7366930f4b0cc3ba5469c18dbc339da",
          "sha1": "bee76b34110cdeaea496bfed3c132d634aa81b1b",
          "md5": "52766c9a07a93f2df6f879e485292820"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "dev.or2",
          "module": "r718",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "r718-fs-2.4.1.jar",
          "url": "r718-fs-2.4.1.jar",
          "size": 7588,
          "sha512": "5b1bd001ca8e2ffd0f7a7a13f0a2a1d5c635e573848d7b9ee76020a8f8c3f2b8725582154fc5cf450e86131f611aa28a7194ed603c0cb59a794e7ad1dfc5c45c",
          "sha256": "37e14bf6f1d2fe885e8548abdf79be5ee7366930f4b0cc3ba5469c18dbc339da",
          "sha1": "bee76b34110cdeaea496bfed3c132d634aa81b1b",
          "md5": "52766c9a07a93f2df6f879e485292820"
        }
      ]
    }
  ]
}
