{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filesystem",
    "version": "2.0.90",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filesystem-2.0.90.jar",
          "url": "filesystem-2.0.90.jar",
          "size": 74762,
          "sha512": "27d2052922b6fc7cb16423db0b31302e560a468cd12c26f9ca0ee79873fac3f920614a10a33844311ba67b2c59a8a2811dd74f8296c2a7edaf8c40092c426d05",
          "sha256": "ab43fe14288f90e7a1618ba076bb2541f806021be1715dc681c594cc5539f046",
          "sha1": "a6e8c1db2f3c7ed380502a754501710701480b50",
          "md5": "8ace797f192a16d0fe943acbf622fedd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "filesystem-2.0.90.jar",
          "url": "filesystem-2.0.90.jar",
          "size": 74762,
          "sha512": "27d2052922b6fc7cb16423db0b31302e560a468cd12c26f9ca0ee79873fac3f920614a10a33844311ba67b2c59a8a2811dd74f8296c2a7edaf8c40092c426d05",
          "sha256": "ab43fe14288f90e7a1618ba076bb2541f806021be1715dc681c594cc5539f046",
          "sha1": "a6e8c1db2f3c7ed380502a754501710701480b50",
          "md5": "8ace797f192a16d0fe943acbf622fedd"
        }
      ]
    }
  ]
}
