{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.4.0.jar",
          "url": "displee-2.4.0.jar",
          "size": 111913,
          "sha512": "2a740462d995ea181bd346a9136297e3097ba068709475b47dcdc2a24691bdf3a8577ced1ebdaef39b5389396b2b7c11975ea114b1a372c9851d63663be38bd9",
          "sha256": "5db5475d14ee778d5d0fc13876f79e831a5cd8bf3277ff5c9c770e0974161bfa",
          "sha1": "4ef3b6fed526d0e04c0ea82209316a54aba4bca2",
          "md5": "0fd1cbcfcf6d5c4386ebf85934e6c1db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.4.0.jar",
          "url": "displee-2.4.0.jar",
          "size": 111913,
          "sha512": "2a740462d995ea181bd346a9136297e3097ba068709475b47dcdc2a24691bdf3a8577ced1ebdaef39b5389396b2b7c11975ea114b1a372c9851d63663be38bd9",
          "sha256": "5db5475d14ee778d5d0fc13876f79e831a5cd8bf3277ff5c9c770e0974161bfa",
          "sha1": "4ef3b6fed526d0e04c0ea82209316a54aba4bca2",
          "md5": "0fd1cbcfcf6d5c4386ebf85934e6c1db"
        }
      ]
    }
  ]
}
