{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs-fs",
    "version": "2.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-fs-2.0.10.jar",
          "url": "osrs-fs-2.0.10.jar",
          "size": 23585,
          "sha512": "f71ef3b4d0e6258ef51dacf25b889410a1cba673750cad4ded88044e0edc6c2c18bc84b8f98a1d655629ee17a61fe35ff249f593876f8d1c53ac43b9eccdfd35",
          "sha256": "8f08a0f3aecf7840a42d1060fa188578b4ec84003dc79167dc11969a61e833a6",
          "sha1": "b446854cb331d06bfc3b84afbbb8feb82fd92768",
          "md5": "70a7245a13dbdbdbae20929a4f5bbaed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-fs-2.0.10.jar",
          "url": "osrs-fs-2.0.10.jar",
          "size": 23585,
          "sha512": "f71ef3b4d0e6258ef51dacf25b889410a1cba673750cad4ded88044e0edc6c2c18bc84b8f98a1d655629ee17a61fe35ff249f593876f8d1c53ac43b9eccdfd35",
          "sha256": "8f08a0f3aecf7840a42d1060fa188578b4ec84003dc79167dc11969a61e833a6",
          "sha1": "b446854cb331d06bfc3b84afbbb8feb82fd92768",
          "md5": "70a7245a13dbdbdbae20929a4f5bbaed"
        }
      ]
    }
  ]
}
