{
  "formatVersion": "1.1",
  "component": {
    "group": "me.filby",
    "module": "runescript-runtime",
    "version": "0.0.6-openrune",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescript-runtime-0.0.6-openrune.jar",
          "url": "runescript-runtime-0.0.6-openrune.jar",
          "size": 47519,
          "sha512": "80c5713dc17ef1460bc5a99c6ae4083cfa130b801ba60e16c79fe5806151582099c529867b62eafa0fbe7edf716139fbe742c0a03e95d6549e44818de00dffbe",
          "sha256": "380bac52be5f4ea40f33d74f38d200a7ab04aca8373eb9376a3c98c3cdf41f3b",
          "sha1": "a302a50f89a8e17e27bf391ed9c8ddd21d38a6b7",
          "md5": "d471f38a7ba50eba3efc34fe16c7181a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.0-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "me.filby",
          "module": "runescript-compiler",
          "version": {
            "requires": "0.0.6-openrune"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescript-runtime-0.0.6-openrune.jar",
          "url": "runescript-runtime-0.0.6-openrune.jar",
          "size": 47519,
          "sha512": "80c5713dc17ef1460bc5a99c6ae4083cfa130b801ba60e16c79fe5806151582099c529867b62eafa0fbe7edf716139fbe742c0a03e95d6549e44818de00dffbe",
          "sha256": "380bac52be5f4ea40f33d74f38d200a7ab04aca8373eb9376a3c98c3cdf41f3b",
          "sha1": "a302a50f89a8e17e27bf391ed9c8ddd21d38a6b7",
          "md5": "d471f38a7ba50eba3efc34fe16c7181a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescript-runtime-0.0.6-openrune-sources.jar",
          "url": "runescript-runtime-0.0.6-openrune-sources.jar",
          "size": 15531,
          "sha512": "0dca9686713df2d4b21748a61626b58e52d1c57b077810d2a99cb96dc84183cc2e251ca9c95b5eb4ab1ffa9edb434716727d15532d1fe87bf6bb4c32931534d1",
          "sha256": "8e74726f2b60f4b05be48a54e78c4befe774f3dc10f39d2ace5b1d9464081146",
          "sha1": "df114746ad80341714e41257432e07da15c57313",
          "md5": "d3f816850dce3cace15db826fc3fe560"
        },
        {
          "name": "runescript-runtime-0.0.6-openrune-sources.jar",
          "url": "runescript-runtime-0.0.6-openrune-sources.jar",
          "size": 15531,
          "sha512": "0dca9686713df2d4b21748a61626b58e52d1c57b077810d2a99cb96dc84183cc2e251ca9c95b5eb4ab1ffa9edb434716727d15532d1fe87bf6bb4c32931534d1",
          "sha256": "8e74726f2b60f4b05be48a54e78c4befe774f3dc10f39d2ace5b1d9464081146",
          "sha1": "df114746ad80341714e41257432e07da15c57313",
          "md5": "d3f816850dce3cace15db826fc3fe560"
        }
      ]
    }
  ]
}
