{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718",
    "version": "2.4.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-2.4.13.jar",
          "url": "r718-2.4.13.jar",
          "size": 14515,
          "sha512": "a3f7074b1c4b3d9b0d0c0db356707263aa543828cabf81741687fd378d99a4a1a3ba1ce049e5ebf42f80add275f7de542654ee10e8027436107a29acb303447e",
          "sha256": "bd8dd07b87cf7a3005651e74bf08df1252d123db630b0e6a54b99e2c1bda4d9b",
          "sha1": "21469a643c9d96b3894c61132c74541153bd690f",
          "md5": "c8ebc60c92b699c0b204450c8fd0271f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.13"
          }
        }
      ],
      "files": [
        {
          "name": "r718-2.4.13.jar",
          "url": "r718-2.4.13.jar",
          "size": 14515,
          "sha512": "a3f7074b1c4b3d9b0d0c0db356707263aa543828cabf81741687fd378d99a4a1a3ba1ce049e5ebf42f80add275f7de542654ee10e8027436107a29acb303447e",
          "sha256": "bd8dd07b87cf7a3005651e74bf08df1252d123db630b0e6a54b99e2c1bda4d9b",
          "sha1": "21469a643c9d96b3894c61132c74541153bd690f",
          "md5": "c8ebc60c92b699c0b204450c8fd0271f"
        }
      ]
    }
  ]
}
