{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.4.6.jar",
          "url": "displee-2.4.6.jar",
          "size": 111913,
          "sha512": "627e296cc402df207f6b74d30057255fc9ea32edeaeea5e7dbe0dfb8ad70e249e62bfef0ca267a18c1d80f7adc1015520e6fd8c1a127a098b85e55223562db0e",
          "sha256": "1a0fed55439779f0f99b4d2dc130b4750fdda915f8d3bcfe863cf9e24f146da8",
          "sha1": "76d67e7b71ac4ee7a22c36c5d192c68bfe07afb6",
          "md5": "606ef80b4e5ce346d58e43df690dc206"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.4.6.jar",
          "url": "displee-2.4.6.jar",
          "size": 111913,
          "sha512": "627e296cc402df207f6b74d30057255fc9ea32edeaeea5e7dbe0dfb8ad70e249e62bfef0ca267a18c1d80f7adc1015520e6fd8c1a127a098b85e55223562db0e",
          "sha256": "1a0fed55439779f0f99b4d2dc130b4750fdda915f8d3bcfe863cf9e24f146da8",
          "sha1": "76d67e7b71ac4ee7a22c36c5d192c68bfe07afb6",
          "md5": "606ef80b4e5ce346d58e43df690dc206"
        }
      ]
    }
  ]
}
