{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "filestore-tools",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-tools-1.3.4.jar",
          "url": "filestore-tools-1.3.4.jar",
          "size": 126330,
          "sha512": "053a6235d6ef3a1ec64a51f5416abb36a2cc1f5a6b096a831227b5792f92f9a65b2a98c232da9dbb75a7c37d9cef59395f83357dd2ad9aa94a243b7531328928",
          "sha256": "5f04c32760506aad6fa8b527674cd4f2d0657dccdf1935a567e5ac32511c4d80",
          "sha1": "38984a83ed63b72d7091b3a52450a707d7b676c3",
          "md5": "88e56727a48db902dc9a48c2509f8b5b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.openrune",
          "module": "filestore",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.openrune",
          "module": "js5server",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.11.5"
          }
        },
        {
          "group": "cc.ekblad",
          "module": "4koma",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "com.displee",
          "module": "rs-cache-library",
          "version": {
            "requires": "7.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-tools-1.3.4.jar",
          "url": "filestore-tools-1.3.4.jar",
          "size": 126330,
          "sha512": "053a6235d6ef3a1ec64a51f5416abb36a2cc1f5a6b096a831227b5792f92f9a65b2a98c232da9dbb75a7c37d9cef59395f83357dd2ad9aa94a243b7531328928",
          "sha256": "5f04c32760506aad6fa8b527674cd4f2d0657dccdf1935a567e5ac32511c4d80",
          "sha1": "38984a83ed63b72d7091b3a52450a707d7b676c3",
          "md5": "88e56727a48db902dc9a48c2509f8b5b"
        }
      ]
    }
  ]
}
