{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filesystem",
    "version": "2.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filesystem-2.2.6.jar",
          "url": "filesystem-2.2.6.jar",
          "size": 75565,
          "sha512": "d7efdfee7aa58c2910b05e6ddbbb1a53779784c305f2c7a9e71c8b11a7d89ef31c1fbb63b0d4aab798246dd5e45a3535a5f5da289a46aeb8ea376ee17610ac7e",
          "sha256": "0b84d2403feaa66ad1f6ad560b60306897e5e0f48abba82625c61fd6b7951747",
          "sha1": "d2fe7f27fb7c41b2d60c3c7ef52a887bbb8cc3b6",
          "md5": "f109c4bc56f0f49cc1dfed36da10d660"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "filesystem-2.2.6.jar",
          "url": "filesystem-2.2.6.jar",
          "size": 75565,
          "sha512": "d7efdfee7aa58c2910b05e6ddbbb1a53779784c305f2c7a9e71c8b11a7d89ef31c1fbb63b0d4aab798246dd5e45a3535a5f5da289a46aeb8ea376ee17610ac7e",
          "sha256": "0b84d2403feaa66ad1f6ad560b60306897e5e0f48abba82625c61fd6b7951747",
          "sha1": "d2fe7f27fb7c41b2d60c3c7ef52a887bbb8cc3b6",
          "md5": "f109c4bc56f0f49cc1dfed36da10d660"
        }
      ]
    }
  ]
}
