{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "definition",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "definition-2.4.0.jar",
          "url": "definition-2.4.0.jar",
          "size": 466970,
          "sha512": "d5f8f088ced6588c624525910baf34a4648184a281af5fbc38e989adaf61c83880b90c848dc6fc937cd90719c0abdd79eeacaaf36ddbe30a11ea1bb6fe9ff4a4",
          "sha256": "eb00fb99acbfb80debce38e00fc829954440f22d7ea3f5c42480fe77522ff37e",
          "sha1": "cc57135054301b172a42320c92e7283568fb70b6",
          "md5": "29a8c00e8b4d55e0ace5e15dc0c86777"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        }
      ],
      "files": [
        {
          "name": "definition-2.4.0.jar",
          "url": "definition-2.4.0.jar",
          "size": 466970,
          "sha512": "d5f8f088ced6588c624525910baf34a4648184a281af5fbc38e989adaf61c83880b90c848dc6fc937cd90719c0abdd79eeacaaf36ddbe30a11ea1bb6fe9ff4a4",
          "sha256": "eb00fb99acbfb80debce38e00fc829954440f22d7ea3f5c42480fe77522ff37e",
          "sha1": "cc57135054301b172a42320c92e7283568fb70b6",
          "md5": "29a8c00e8b4d55e0ace5e15dc0c86777"
        }
      ]
    }
  ]
}
