{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filestore-server",
    "version": "0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-server-0.6.jar",
          "url": "filestore-server-0.6.jar",
          "size": 953217,
          "sha512": "5f5145cfe7757c29b52d39564a7704a0fbd69b3810220684b34a07c5eb2942a541db497ed58dcb610cafa11fc74d132b238fcccd137474f68177afb44b2245bb",
          "sha256": "27ef99f5fcd2fdcd66329c2b6ee285b1c4bfd301e9953f62a3942a8684a10d25",
          "sha1": "76b432c7d594bb0c294a8ce06f475e669a4fc583",
          "md5": "36ca0452e1108efd754ebc08e0884569"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-server-0.6.jar",
          "url": "filestore-server-0.6.jar",
          "size": 953217,
          "sha512": "5f5145cfe7757c29b52d39564a7704a0fbd69b3810220684b34a07c5eb2942a541db497ed58dcb610cafa11fc74d132b238fcccd137474f68177afb44b2245bb",
          "sha256": "27ef99f5fcd2fdcd66329c2b6ee285b1c4bfd301e9953f62a3942a8684a10d25",
          "sha1": "76b432c7d594bb0c294a8ce06f475e669a4fc583",
          "md5": "36ca0452e1108efd754ebc08e0884569"
        }
      ]
    }
  ]
}
