{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs-fs",
    "version": "2.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-fs-2.0.7.jar",
          "url": "osrs-fs-2.0.7.jar",
          "size": 22442,
          "sha512": "970307f9aa4fe104d8fcef5d9f11c80869a8f0c1af3c6de2260a5afe33319300830037975bb3d4a8269bdc1c58a1eca3819f2be38051dfb183060b87e6931622",
          "sha256": "a2dcd54e98e016fb5bd2133bc28b60aa236f73b43726fc0f1aa1d0fbb99c4bfc",
          "sha1": "7d5e7bbb7805b47a0b39fe673b3111adad4ae5f0",
          "md5": "7c761927145bca8019fa0a59f8737e4f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-fs-2.0.7.jar",
          "url": "osrs-fs-2.0.7.jar",
          "size": 22442,
          "sha512": "970307f9aa4fe104d8fcef5d9f11c80869a8f0c1af3c6de2260a5afe33319300830037975bb3d4a8269bdc1c58a1eca3819f2be38051dfb183060b87e6931622",
          "sha256": "a2dcd54e98e016fb5bd2133bc28b60aa236f73b43726fc0f1aa1d0fbb99c4bfc",
          "sha1": "7d5e7bbb7805b47a0b39fe673b3111adad4ae5f0",
          "md5": "7c761927145bca8019fa0a59f8737e4f"
        }
      ]
    }
  ]
}
