{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718-fs",
    "version": "2.4.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-fs-2.4.7.jar",
          "url": "r718-fs-2.4.7.jar",
          "size": 7588,
          "sha512": "10f87dc3033a5b74678e7d24883ae9e26fc8214b1bc3c7c0dd262711793f8b0e3c4ec0a4469cc1d1a7319f3e3455c5dc0fefcac65caaf850f51ab027074c0e04",
          "sha256": "211bcbcaa8325874a3611ddff40f3e28e5fe9c74a3bc212bc359294bdcd17c19",
          "sha1": "30edcc5a0ef185699d6cfd425fc38898d24afc07",
          "md5": "5810e2e1846bb19c40c286f00dbb5514"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.4.7"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.7"
          }
        },
        {
          "group": "dev.or2",
          "module": "r718",
          "version": {
            "requires": "2.4.7"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.7"
          }
        }
      ],
      "files": [
        {
          "name": "r718-fs-2.4.7.jar",
          "url": "r718-fs-2.4.7.jar",
          "size": 7588,
          "sha512": "10f87dc3033a5b74678e7d24883ae9e26fc8214b1bc3c7c0dd262711793f8b0e3c4ec0a4469cc1d1a7319f3e3455c5dc0fefcac65caaf850f51ab027074c0e04",
          "sha256": "211bcbcaa8325874a3611ddff40f3e28e5fe9c74a3bc212bc359294bdcd17c19",
          "sha1": "30edcc5a0ef185699d6cfd425fc38898d24afc07",
          "md5": "5810e2e1846bb19c40c286f00dbb5514"
        }
      ]
    }
  ]
}
