{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs-fs",
    "version": "2.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-fs-2.0.14.jar",
          "url": "osrs-fs-2.0.14.jar",
          "size": 23585,
          "sha512": "38fa6c2f85bde306dbacb680ae6508d177eaaab68da41beae80e96af4701068e3c9f01d8a8e9a470a445aa52ad18a549536375866ca65119193d7cef3991c2b5",
          "sha256": "e6375e1c46c92e7fe69b26b39033e3b40c39ac0ca518315e640568c238a6c62c",
          "sha1": "1cce1183fbf026e007d639585cd1fbaccfd91053",
          "md5": "7723f65a8e37cf808008727bcbf110e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.0.14"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.0.14"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.0.14"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.14"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-fs-2.0.14.jar",
          "url": "osrs-fs-2.0.14.jar",
          "size": 23585,
          "sha512": "38fa6c2f85bde306dbacb680ae6508d177eaaab68da41beae80e96af4701068e3c9f01d8a8e9a470a445aa52ad18a549536375866ca65119193d7cef3991c2b5",
          "sha256": "e6375e1c46c92e7fe69b26b39033e3b40c39ac0ca518315e640568c238a6c62c",
          "sha1": "1cce1183fbf026e007d639585cd1fbaccfd91053",
          "md5": "7723f65a8e37cf808008727bcbf110e0"
        }
      ]
    }
  ]
}
