{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "openrune-central",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "openrune-central-2.0.0.jar",
          "url": "openrune-central-2.0.0.jar",
          "size": 345564,
          "sha512": "03c21d530e6f49222b26e0dbc5293605e2df3895cbba70a8146613518ff912430f349da4e847354c9f82d9ff7c4c6de96ae497d3c02612c7a0b3133aaa6a4e70",
          "sha256": "1f5c362378fd9d03c5dd0109c7f33fb3a0265b25a59dc70b710515cf33acecdd",
          "sha1": "2a6f313d516f3af1f9e3d7606ef3c5631303cf79",
          "md5": "d5dd5f2e889c25ef5db66b83d5abdcfa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.or2",
          "module": "central-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "dev.or2",
          "module": "central-worldlink",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-bom",
          "version": {
            "requires": "3.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-content-negotiation"
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-status-pages"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-forwarded-header"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-config-yaml"
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.7"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core",
          "version": {
            "requires": "11.3.1"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-database-postgresql",
          "version": {
            "requires": "11.3.1"
          }
        },
        {
          "group": "com.sksamuel.hoplite",
          "module": "hoplite-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.sksamuel.hoplite",
          "module": "hoplite-yaml",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-ktor",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-logger-slf4j",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.zonky.test",
          "module": "embedded-postgres",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.16"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "5.5.1"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "openrune-central-2.0.0.jar",
          "url": "openrune-central-2.0.0.jar",
          "size": 345564,
          "sha512": "03c21d530e6f49222b26e0dbc5293605e2df3895cbba70a8146613518ff912430f349da4e847354c9f82d9ff7c4c6de96ae497d3c02612c7a0b3133aaa6a4e70",
          "sha256": "1f5c362378fd9d03c5dd0109c7f33fb3a0265b25a59dc70b710515cf33acecdd",
          "sha1": "2a6f313d516f3af1f9e3d7606ef3c5631303cf79",
          "md5": "d5dd5f2e889c25ef5db66b83d5abdcfa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "openrune-central-2.0.0-sources.jar",
          "url": "openrune-central-2.0.0-sources.jar",
          "size": 67155,
          "sha512": "6805b4c45a631ad38b5660c463af68dc79bc16dfb0ae0b60c68325ee354ba7a5ee76b8dba6f719e2b6e3e3cfda3d350e11af35c274e7ae7c4f3624ae34c2573d",
          "sha256": "4349accee7912c9b9964c416e425c36492c9fa6d57fa8ab04fad3019edbdccc8",
          "sha1": "f2e2c796dc252f127ad46f6cffd5eaf4ba8e6f5b",
          "md5": "9622295240d4ebd0c41c51f549ec55c3"
        }
      ]
    }
  ]
}
