{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.0.4.jar",
          "url": "displee-2.0.4.jar",
          "size": 111589,
          "sha512": "42c0b3136f3942d7448222717c74c9914c7c46d99edc9d3554257f515af1c5398a2aaf091201296bc5a576eeecdc3e598c8579b2910f70a96e2c5282ea396965",
          "sha256": "7a302c752e002d76c613204495e9b4bc84bb31653675e5fb7b9ed34be77d80fe",
          "sha1": "a03d06fe95b359dc891ebc8a17c35493681c01e2",
          "md5": "5ddc085cbf5ab29b303ae820236a23c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.0.4.jar",
          "url": "displee-2.0.4.jar",
          "size": 111589,
          "sha512": "42c0b3136f3942d7448222717c74c9914c7c46d99edc9d3554257f515af1c5398a2aaf091201296bc5a576eeecdc3e598c8579b2910f70a96e2c5282ea396965",
          "sha256": "7a302c752e002d76c613204495e9b4bc84bb31653675e5fb7b9ed34be77d80fe",
          "sha1": "a03d06fe95b359dc891ebc8a17c35493681c01e2",
          "md5": "5ddc085cbf5ab29b303ae820236a23c8"
        }
      ]
    }
  ]
}
