{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs-fs",
    "version": "2.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-fs-2.4.4.jar",
          "url": "osrs-fs-2.4.4.jar",
          "size": 26586,
          "sha512": "a2ce922419b408d2a226835c15969ae8df258b4639f757c5807095838b98f72bda5fb50ec5fcb85fb790cdf43cfb89e624f3d9c46c7317ab3a0e84f3d59a324f",
          "sha256": "796d979f79d009afbf9f1f1f755900805c20fe50615f1530c528b80794e76d3b",
          "sha1": "9ff2f1ea767bd02f7fe73b549c1517646944fe79",
          "md5": "babbac392542e916d2f3be4956b73e8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.4.4"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.4"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.4.4"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-fs-2.4.4.jar",
          "url": "osrs-fs-2.4.4.jar",
          "size": 26586,
          "sha512": "a2ce922419b408d2a226835c15969ae8df258b4639f757c5807095838b98f72bda5fb50ec5fcb85fb790cdf43cfb89e624f3d9c46c7317ab3a0e84f3d59a324f",
          "sha256": "796d979f79d009afbf9f1f1f755900805c20fe50615f1530c528b80794e76d3b",
          "sha1": "9ff2f1ea767bd02f7fe73b549c1517646944fe79",
          "md5": "babbac392542e916d2f3be4956b73e8f"
        }
      ]
    }
  ]
}
