{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.4.5.jar",
          "url": "displee-2.4.5.jar",
          "size": 111913,
          "sha512": "a5969ed2eeef44ac9dcb9545c332bdff9abccf1c95dfb538b6eb04da13180733ae028a4cb7e2b2dcbc3ecadbf89a745307b4a7c55aabddc79754228602622cd3",
          "sha256": "dee0c1b270d2bc4601e8624d293275c857da593757ba7815074b01b7663dd482",
          "sha1": "93b2b1a9d12c5412c628eed522ea65f246c5d11e",
          "md5": "ee24763d967271124f3834a557d33e96"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.4.5.jar",
          "url": "displee-2.4.5.jar",
          "size": 111913,
          "sha512": "a5969ed2eeef44ac9dcb9545c332bdff9abccf1c95dfb538b6eb04da13180733ae028a4cb7e2b2dcbc3ecadbf89a745307b4a7c55aabddc79754228602622cd3",
          "sha256": "dee0c1b270d2bc4601e8624d293275c857da593757ba7815074b01b7663dd482",
          "sha1": "93b2b1a9d12c5412c628eed522ea65f246c5d11e",
          "md5": "ee24763d967271124f3834a557d33e96"
        }
      ]
    }
  ]
}
