{
  "formatVersion": "1.1",
  "component": {
    "group": "org.openrs2",
    "module": "openrs2-deob",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.ajalt.clikt",
          "module": "clikt",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "openrs2-deob-0.1.2-SNAPSHOT.jar",
          "url": "openrs2-deob-0.1.2-SNAPSHOT.jar",
          "size": 6393,
          "sha512": "4e43ab39b7966fd780c8eceee0dd01ca5c7ada377e1baf913d239aa19711ccc52e7de625ac0a097dd09d74fa55a0962d43d7cedc56126ebb5353034528c5a105",
          "sha256": "5fd174ef137513aed51e209828f1a12eb82b0124dbf67b78d56853e27b559bf5",
          "sha1": "9323ad8a34b08a9d15548dee54336e6f4ea6a244",
          "md5": "ed375283f915fcf57c4c51c37ec67d7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "org.openrs2",
          "module": "openrs2-decompiler",
          "version": {
            "requires": "0.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.openrs2",
          "module": "openrs2-deob-ast",
          "version": {
            "requires": "0.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.openrs2",
          "module": "openrs2-deob-bytecode",
          "version": {
            "requires": "0.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.openrs2",
          "module": "openrs2-inject",
          "version": {
            "requires": "0.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.openrs2",
          "module": "openrs2-log",
          "version": {
            "requires": "0.1.2-SNAPSHOT"
          }
        },
        {
          "group": "com.github.ajalt.clikt",
          "module": "clikt",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.12"
          }
        }
      ],
      "files": [
        {
          "name": "openrs2-deob-0.1.2-SNAPSHOT.jar",
          "url": "openrs2-deob-0.1.2-SNAPSHOT.jar",
          "size": 6393,
          "sha512": "4e43ab39b7966fd780c8eceee0dd01ca5c7ada377e1baf913d239aa19711ccc52e7de625ac0a097dd09d74fa55a0962d43d7cedc56126ebb5353034528c5a105",
          "sha256": "5fd174ef137513aed51e209828f1a12eb82b0124dbf67b78d56853e27b559bf5",
          "sha1": "9323ad8a34b08a9d15548dee54336e6f4ea6a244",
          "md5": "ed375283f915fcf57c4c51c37ec67d7b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "openrs2-deob-0.1.2-SNAPSHOT-sources.jar",
          "url": "openrs2-deob-0.1.2-SNAPSHOT-sources.jar",
          "size": 1841,
          "sha512": "d1815dd63f4b05212f36bda12af19830fdf95cf41bf2bb59ae137f8f393411ef62360d7667ad7b65460a6532514127f925565d62f7a38cd1abaee56daaab38dc",
          "sha256": "a9ed50dbc746e0324093f54c89d56f588978344a99e0a05b31c22b6054885a2e",
          "sha1": "0c555d4766d3c347fe4dcb8c6b4077de757c4d38",
          "md5": "dbb3defee63cbfd99ca14d706fa798b4"
        },
        {
          "name": "openrs2-deob-0.1.2-SNAPSHOT-sources.jar",
          "url": "openrs2-deob-0.1.2-SNAPSHOT-sources.jar",
          "size": 1841,
          "sha512": "d1815dd63f4b05212f36bda12af19830fdf95cf41bf2bb59ae137f8f393411ef62360d7667ad7b65460a6532514127f925565d62f7a38cd1abaee56daaab38dc",
          "sha256": "a9ed50dbc746e0324093f54c89d56f588978344a99e0a05b31c22b6054885a2e",
          "sha1": "0c555d4766d3c347fe4dcb8c6b4077de757c4d38",
          "md5": "dbb3defee63cbfd99ca14d706fa798b4"
        }
      ]
    }
  ]
}
