{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "filestore-tools",
    "version": "1.3.88",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-tools-1.3.88.jar",
          "url": "filestore-tools-1.3.88.jar",
          "size": 127402,
          "sha512": "015205b9295434b31cd57d092b12ec54ca2b235ca34a9967422a1ab3bbc953e9775a4774061cd4484916f1466584376c20cb8acd00c1bdec249a2c8e90f4509c",
          "sha256": "1499509168973df8ffbb30dab75a4228c253041ee0c6d759453d8f761f4fa506",
          "sha1": "720c817d0187276ad5d6f4d16685df60842cf78f",
          "md5": "c47e57f86e8aaf7bd855baf7378f07fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.openrune",
          "module": "filestore",
          "version": {
            "requires": "1.3.88"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.openrune",
          "module": "js5server",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.11.5"
          }
        },
        {
          "group": "cc.ekblad",
          "module": "4koma",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "com.displee",
          "module": "rs-cache-library",
          "version": {
            "requires": "7.1.5"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-file",
          "version": {
            "requires": "0.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-tools-1.3.88.jar",
          "url": "filestore-tools-1.3.88.jar",
          "size": 127402,
          "sha512": "015205b9295434b31cd57d092b12ec54ca2b235ca34a9967422a1ab3bbc953e9775a4774061cd4484916f1466584376c20cb8acd00c1bdec249a2c8e90f4509c",
          "sha256": "1499509168973df8ffbb30dab75a4228c253041ee0c6d759453d8f761f4fa506",
          "sha1": "720c817d0187276ad5d6f4d16685df60842cf78f",
          "md5": "c47e57f86e8aaf7bd855baf7378f07fb"
        }
      ]
    }
  ]
}
