{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718-fs",
    "version": "2.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-fs-2.0.7.jar",
          "url": "r718-fs-2.0.7.jar",
          "size": 7586,
          "sha512": "277cc976767e3b913d6e0cafe4f7a985ca58c68440c17f4e0e38f7fdcd85c9a6490fd683100ba5a81195a51dfab963dfb4c20219377296dfa928485f10c92c52",
          "sha256": "f3f75bdd7a4477a26dd3406e708ce19d82dece05a4d96998417d35bf9553db05",
          "sha1": "27fa02910a2a4a76b7d794e8de05ebc5ce551ae4",
          "md5": "b496ab57b317129d4a2904baccb2fa81"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "dev.or2",
          "module": "r718",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "r718-fs-2.0.7.jar",
          "url": "r718-fs-2.0.7.jar",
          "size": 7586,
          "sha512": "277cc976767e3b913d6e0cafe4f7a985ca58c68440c17f4e0e38f7fdcd85c9a6490fd683100ba5a81195a51dfab963dfb4c20219377296dfa928485f10c92c52",
          "sha256": "f3f75bdd7a4477a26dd3406e708ce19d82dece05a4d96998417d35bf9553db05",
          "sha1": "27fa02910a2a4a76b7d794e8de05ebc5ce551ae4",
          "md5": "b496ab57b317129d4a2904baccb2fa81"
        }
      ]
    }
  ]
}
