{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filestore",
    "version": "2.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-2.0.16.jar",
          "url": "filestore-2.0.16.jar",
          "size": 22111,
          "sha512": "870650efd593f0686b33725dae27d5c551efd078e8be26acdfa1bdc2b0dc8ac0ac7f39f172cede512a701d5ca079cb6a72954a73d6cab5be5593c3ce9174efec",
          "sha256": "9d92b39cfccff3ca7b194781c1be9e439c3b12abe5b5a19b16472dfbe77666a5",
          "sha1": "fcd33bcc5852bed56a9e9acef2a22491bb890b11",
          "md5": "1dc7aea06af3b753305c6d0c413532e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-2.0.16.jar",
          "url": "filestore-2.0.16.jar",
          "size": 22111,
          "sha512": "870650efd593f0686b33725dae27d5c551efd078e8be26acdfa1bdc2b0dc8ac0ac7f39f172cede512a701d5ca079cb6a72954a73d6cab5be5593c3ce9174efec",
          "sha256": "9d92b39cfccff3ca7b194781c1be9e439c3b12abe5b5a19b16472dfbe77666a5",
          "sha1": "fcd33bcc5852bed56a9e9acef2a22491bb890b11",
          "md5": "1dc7aea06af3b753305c6d0c413532e9"
        }
      ]
    }
  ]
}
