{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-3.0.1.jar",
          "url": "displee-3.0.1.jar",
          "size": 111957,
          "sha512": "8371a36319471a9646e89aa57677f2ef4a976614e8e59002c063d9ce208979148a8fb20b448b18f8a23351adcbe090fcc2b0e99f2fb1d5fcfe4d8c7809265bbd",
          "sha256": "44332be00e461664f9327d0b3e420bff081372725ae28fc167588469baf65fa5",
          "sha1": "bbb1ef71629178508702f3928b4a69d1525e4ba4",
          "md5": "21ec24890bc2eecede1d951ff6b1d3fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-3.0.1.jar",
          "url": "displee-3.0.1.jar",
          "size": 111957,
          "sha512": "8371a36319471a9646e89aa57677f2ef4a976614e8e59002c063d9ce208979148a8fb20b448b18f8a23351adcbe090fcc2b0e99f2fb1d5fcfe4d8c7809265bbd",
          "sha256": "44332be00e461664f9327d0b3e420bff081372725ae28fc167588469baf65fa5",
          "sha1": "bbb1ef71629178508702f3928b4a69d1525e4ba4",
          "md5": "21ec24890bc2eecede1d951ff6b1d3fa"
        }
      ]
    }
  ]
}
