{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs-fs",
    "version": "2.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-fs-2.4.1.jar",
          "url": "osrs-fs-2.4.1.jar",
          "size": 26599,
          "sha512": "ee92e49b417ea21dcf56e06e4daa8534306bc450cdfe984ccd0bcc467659dec94aef13791ac802ee6957fd9c7d3a94b4e8371b7be6c0f908fd512100bf6052b1",
          "sha256": "29be26addb2db28f8da11a4486340ed8ae674f9fbf8acae24b79cd074dfc1f1b",
          "sha1": "0965539b248723f9d67a5ff3978e4f29c8009560",
          "md5": "eb71300efd010da705f7512482325885"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-fs-2.4.1.jar",
          "url": "osrs-fs-2.4.1.jar",
          "size": 26599,
          "sha512": "ee92e49b417ea21dcf56e06e4daa8534306bc450cdfe984ccd0bcc467659dec94aef13791ac802ee6957fd9c7d3a94b4e8371b7be6c0f908fd512100bf6052b1",
          "sha256": "29be26addb2db28f8da11a4486340ed8ae674f9fbf8acae24b79cd074dfc1f1b",
          "sha1": "0965539b248723f9d67a5ff3978e4f29c8009560",
          "md5": "eb71300efd010da705f7512482325885"
        }
      ]
    }
  ]
}
