{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs",
    "version": "2.4.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 20,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-2.4.9.jar",
          "url": "osrs-2.4.9.jar",
          "size": 92738,
          "sha512": "a4ab613871821da9eca033423cb6ff3014e463c65e0a8521af55a6de3b49643ff58e64799815059cfd0badb058a6bb60fa41e165eb58099a44658587b8c4e09c",
          "sha256": "b0b3f4979684f72bfaebc527e07ab3ac37a027cfcdea08adeafa943857479933",
          "sha1": "7ac0b35dc528ab99e89d8748a45e16ce78e7ce4d",
          "md5": "6d3065527aa0180221da74b92bb9d58b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 20,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.9"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-2.4.9.jar",
          "url": "osrs-2.4.9.jar",
          "size": 92738,
          "sha512": "a4ab613871821da9eca033423cb6ff3014e463c65e0a8521af55a6de3b49643ff58e64799815059cfd0badb058a6bb60fa41e165eb58099a44658587b8c4e09c",
          "sha256": "b0b3f4979684f72bfaebc527e07ab3ac37a027cfcdea08adeafa943857479933",
          "sha1": "7ac0b35dc528ab99e89d8748a45e16ce78e7ce4d",
          "md5": "6d3065527aa0180221da74b92bb9d58b"
        }
      ]
    }
  ]
}
