{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.0.12.jar",
          "url": "displee-2.0.12.jar",
          "size": 111759,
          "sha512": "010f909b69ecea8cb767eedd7589fdf651817e9f5420098cc6b13983ddeb6c204be93d5075d3059ddecdfe56947c43618dab5ee5e581673d9459a4a39dcc6de2",
          "sha256": "70b5f8ad4f3c70bec7cab86405ddb32d1a0d9a82475142162afc4d8ae9a0f5d5",
          "sha1": "b50b92b0b1c8603c17686914db143bf8af1cf858",
          "md5": "48645f0564b643ce73378eff647c0fb6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.0.12.jar",
          "url": "displee-2.0.12.jar",
          "size": 111759,
          "sha512": "010f909b69ecea8cb767eedd7589fdf651817e9f5420098cc6b13983ddeb6c204be93d5075d3059ddecdfe56947c43618dab5ee5e581673d9459a4a39dcc6de2",
          "sha256": "70b5f8ad4f3c70bec7cab86405ddb32d1a0d9a82475142162afc4d8ae9a0f5d5",
          "sha1": "b50b92b0b1c8603c17686914db143bf8af1cf858",
          "md5": "48645f0564b643ce73378eff647c0fb6"
        }
      ]
    }
  ]
}
