{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filesystem",
    "version": "2.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filesystem-2.0.11.jar",
          "url": "filesystem-2.0.11.jar",
          "size": 82742,
          "sha512": "5cc0bb75fb67407a51097522943e2ffca9ef044ca0c25d9ec68d45c463f5917f3219f8fd8936f45375e1e86ddceea82d903dc30e2991e9ae0a25e63910a5f74f",
          "sha256": "67df3817fda16090db71c3fda689dfab8c9b79d8b8bc34d2ef48e26bb2ee6ea9",
          "sha1": "05bc848dfecf002a05172a6b166d803bdfafef82",
          "md5": "7036fe53dcbd4ee7220566007b2a1290"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "filesystem-2.0.11.jar",
          "url": "filesystem-2.0.11.jar",
          "size": 82742,
          "sha512": "5cc0bb75fb67407a51097522943e2ffca9ef044ca0c25d9ec68d45c463f5917f3219f8fd8936f45375e1e86ddceea82d903dc30e2991e9ae0a25e63910a5f74f",
          "sha256": "67df3817fda16090db71c3fda689dfab8c9b79d8b8bc34d2ef48e26bb2ee6ea9",
          "sha1": "05bc848dfecf002a05172a6b166d803bdfafef82",
          "md5": "7036fe53dcbd4ee7220566007b2a1290"
        }
      ]
    }
  ]
}
