{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filesystem",
    "version": "2.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filesystem-2.4.5.jar",
          "url": "filesystem-2.4.5.jar",
          "size": 51650,
          "sha512": "924a7facb7e95adf9aadae8d2854cbb2cedd7dbb0d13234bcd48d8f02c14514d131dc9951d61861d1758b25e08a570f7eb5f4460cf33b4327dd9b7f5927f5537",
          "sha256": "bbfbe16b8163e514c1f1033f4ff9e90f198ea7ba590cab787127b2ce3434827f",
          "sha1": "7d74949a545df95b6a07df56bedacef553011f51",
          "md5": "cfc8b6e3909ea5a8b22b581fe7f29ebf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "filesystem-2.4.5.jar",
          "url": "filesystem-2.4.5.jar",
          "size": 51650,
          "sha512": "924a7facb7e95adf9aadae8d2854cbb2cedd7dbb0d13234bcd48d8f02c14514d131dc9951d61861d1758b25e08a570f7eb5f4460cf33b4327dd9b7f5927f5537",
          "sha256": "bbfbe16b8163e514c1f1033f4ff9e90f198ea7ba590cab787127b2ce3434827f",
          "sha1": "7d74949a545df95b6a07df56bedacef553011f51",
          "md5": "cfc8b6e3909ea5a8b22b581fe7f29ebf"
        }
      ]
    }
  ]
}
