{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718-fs",
    "version": "2.4.2-cache",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-fs-2.4.2-cache.jar",
          "url": "r718-fs-2.4.2-cache.jar",
          "size": 7617,
          "sha512": "2153a46bb637e477eb486c6a5b51e094b554412a169f9dc2b665aa682cad326230c06e012c6007cdd67edd642857250d4f402ac6bc309c9323680aed686b0ffb",
          "sha256": "361fd22b9ecb95f27014958920246c7791b06d0e1b0623fda47f5509812f466d",
          "sha1": "f07c43ad01f01f67278cbdd664c3ff5e0bf0c62f",
          "md5": "4656671ff22bbac9dc434c2d3981378d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.4.2-cache"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.2-cache"
          }
        },
        {
          "group": "dev.or2",
          "module": "r718",
          "version": {
            "requires": "2.4.2-cache"
          }
        },
        {
          "group": "dev.or2",
          "module": "cache",
          "version": {
            "requires": "2.4.2-cache"
          }
        }
      ],
      "files": [
        {
          "name": "r718-fs-2.4.2-cache.jar",
          "url": "r718-fs-2.4.2-cache.jar",
          "size": 7617,
          "sha512": "2153a46bb637e477eb486c6a5b51e094b554412a169f9dc2b665aa682cad326230c06e012c6007cdd67edd642857250d4f402ac6bc309c9323680aed686b0ffb",
          "sha256": "361fd22b9ecb95f27014958920246c7791b06d0e1b0623fda47f5509812f466d",
          "sha1": "f07c43ad01f01f67278cbdd664c3ff5e0bf0c62f",
          "md5": "4656671ff22bbac9dc434c2d3981378d"
        }
      ]
    }
  ]
}
