{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "tools",
    "version": "3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.45.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "tools-3.0.4.jar",
          "url": "tools-3.0.4.jar",
          "size": 1622677,
          "sha512": "1d7c383868039dc436629fed3fe4bd0fc0c8262423ec4e6705ab9e2feeb80976746ef6cbeaa4952cc3f486426161ac95d0a1921c7bd72fd5a366b2479021ece8",
          "sha256": "4db4a2c7b02624552ee6ab773ea1ced646dff0954360efaa0cca6b5d2cba12e4",
          "sha1": "d3fb59fd3b2a6f0fb54f73769321387beeb3bb3a",
          "md5": "b2a6137fa0dd63ccf27f11873e3555cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs-fs",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.11.5"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "dev.or2",
          "module": "displee",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.16"
          }
        },
        {
          "group": "dev.or2",
          "module": "toml-rsconfig",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "me.filby",
          "module": "clientscript-compiler",
          "version": {
            "requires": "0.0.7-openrune"
          }
        },
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.45.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "tools-3.0.4.jar",
          "url": "tools-3.0.4.jar",
          "size": 1622677,
          "sha512": "1d7c383868039dc436629fed3fe4bd0fc0c8262423ec4e6705ab9e2feeb80976746ef6cbeaa4952cc3f486426161ac95d0a1921c7bd72fd5a366b2479021ece8",
          "sha256": "4db4a2c7b02624552ee6ab773ea1ced646dff0954360efaa0cca6b5d2cba12e4",
          "sha1": "d3fb59fd3b2a6f0fb54f73769321387beeb3bb3a",
          "md5": "b2a6137fa0dd63ccf27f11873e3555cb"
        }
      ]
    }
  ]
}
