{
  "formatVersion": "1.1",
  "component": {
    "group": "me.filby",
    "module": "runescript-compiler",
    "version": "0.0.7-openrune",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.filby",
          "module": "runescript-parser",
          "version": {
            "requires": "0.0.7-openrune"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescript-compiler-0.0.7-openrune.jar",
          "url": "runescript-compiler-0.0.7-openrune.jar",
          "size": 291957,
          "sha512": "2ecd41ce3ed7f4ca422957a8cded4fd1a547f185f4bd3072bff7eb6f212a42de719a789b464f029b1381c8dd1363b25600eb0c40c81a879dcf10cfed9338afa6",
          "sha256": "ed8f42cf168f489894dcfe9174f26a3da3e7d3a51c41f4928fbfb09ee10e5a5c",
          "sha1": "6c3f32ee3cd8e0924fa26b654e33f8d9966766f3",
          "md5": "009a03b219f8571ae861eef228447ade"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.0-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "me.filby",
          "module": "runescript-parser",
          "version": {
            "requires": "0.0.7-openrune"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.11"
          }
        }
      ],
      "files": [
        {
          "name": "runescript-compiler-0.0.7-openrune.jar",
          "url": "runescript-compiler-0.0.7-openrune.jar",
          "size": 291957,
          "sha512": "2ecd41ce3ed7f4ca422957a8cded4fd1a547f185f4bd3072bff7eb6f212a42de719a789b464f029b1381c8dd1363b25600eb0c40c81a879dcf10cfed9338afa6",
          "sha256": "ed8f42cf168f489894dcfe9174f26a3da3e7d3a51c41f4928fbfb09ee10e5a5c",
          "sha1": "6c3f32ee3cd8e0924fa26b654e33f8d9966766f3",
          "md5": "009a03b219f8571ae861eef228447ade"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescript-compiler-0.0.7-openrune-sources.jar",
          "url": "runescript-compiler-0.0.7-openrune-sources.jar",
          "size": 65865,
          "sha512": "562bf1c7ae83b797a6a1caceb269987532f54431e60710cee543cb7e55d62952442e08a1c51764969e88e63d5910de77bde2f77f945b7306bbe6c9087ab85aa6",
          "sha256": "fc5dd7b1d59c1c76680d6d176349767990d327abae2e471a17c506ebfeb1ef2b",
          "sha1": "0125b9af45c9223e6c84557f4b2f5f25cc5a65ef",
          "md5": "3f9f3160f3c17765ea5b96d3220740e5"
        },
        {
          "name": "runescript-compiler-0.0.7-openrune-sources.jar",
          "url": "runescript-compiler-0.0.7-openrune-sources.jar",
          "size": 65865,
          "sha512": "562bf1c7ae83b797a6a1caceb269987532f54431e60710cee543cb7e55d62952442e08a1c51764969e88e63d5910de77bde2f77f945b7306bbe6c9087ab85aa6",
          "sha256": "fc5dd7b1d59c1c76680d6d176349767990d327abae2e471a17c506ebfeb1ef2b",
          "sha1": "0125b9af45c9223e6c84557f4b2f5f25cc5a65ef",
          "md5": "3f9f3160f3c17765ea5b96d3220740e5"
        }
      ]
    }
  ]
}
