{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "js5server",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "js5server-1.0.9.jar",
          "url": "js5server-1.0.9.jar",
          "size": 63618,
          "sha512": "914a9ffa867376dc62a3835ec1e00834f9da8689a39d900fba0cc6e726ce5a46dfeec84701eb781c5083e5f4b988ea43c6a4a0f4a6a9921173b449162b197d09",
          "sha256": "9ee187501e8369b13cabe7c1031a4bd26ddf792462e3306816e1de96c3521207",
          "sha1": "56e6d629b1bc76e78b734c1b8d86ac6c28eac292",
          "md5": "213a34f9801eae44765367a6b6371845"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.12"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-native-epoll",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-native-kqueue",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-transport-native-io_uring",
          "version": {
            "requires": "0.0.25.Final"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "org.jctools",
          "module": "jctools-core",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "displee",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.12"
          }
        }
      ],
      "files": [
        {
          "name": "js5server-1.0.9.jar",
          "url": "js5server-1.0.9.jar",
          "size": 63618,
          "sha512": "914a9ffa867376dc62a3835ec1e00834f9da8689a39d900fba0cc6e726ce5a46dfeec84701eb781c5083e5f4b988ea43c6a4a0f4a6a9921173b449162b197d09",
          "sha256": "9ee187501e8369b13cabe7c1031a4bd26ddf792462e3306816e1de96c3521207",
          "sha1": "56e6d629b1bc76e78b734c1b8d86ac6c28eac292",
          "md5": "213a34f9801eae44765367a6b6371845"
        }
      ]
    }
  ]
}
