{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "definition",
    "version": "2.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "definition-2.4.2.jar",
          "url": "definition-2.4.2.jar",
          "size": 502886,
          "sha512": "570dc29a1dfc0671feb8b4dc1cb00832b2b75d9dcff144873e172ca7365f8b2e75fcf1e67a860c54c74a6c1e164ab17dd0e7dbb878388d1765b65fc718a3e3e1",
          "sha256": "e985524657a0b09dfa26a627df1d260741eb931412a29038bd2787bb301e798d",
          "sha1": "5a7945a75c5c3c6ed1e7471cbd4d53458f035937",
          "md5": "4593c782363d15df3f2f55528e05ca0c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "toml-core",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "definition-2.4.2.jar",
          "url": "definition-2.4.2.jar",
          "size": 502886,
          "sha512": "570dc29a1dfc0671feb8b4dc1cb00832b2b75d9dcff144873e172ca7365f8b2e75fcf1e67a860c54c74a6c1e164ab17dd0e7dbb878388d1765b65fc718a3e3e1",
          "sha256": "e985524657a0b09dfa26a627df1d260741eb931412a29038bd2787bb301e798d",
          "sha1": "5a7945a75c5c3c6ed1e7471cbd4d53458f035937",
          "md5": "4593c782363d15df3f2f55528e05ca0c"
        }
      ]
    }
  ]
}
