{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.4.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 20,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.4.9.jar",
          "url": "displee-2.4.9.jar",
          "size": 100563,
          "sha512": "f4b1c20176263a287a0b762b9ec1ef8516c1285111080334bc695586ec26c17ea033ec816390c0be542080aee75342dd474056a3bd9ffea5bb00b2d73f7606b5",
          "sha256": "96e5f39d959ca87493b23185b38770729c45874b7a4effdfd65a6736e4c52ce5",
          "sha1": "403f213bca03020b84aa0efa4cc1eadd8817a4ee",
          "md5": "b3b69e16ea0daf7e33aaec8500ed634b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 20,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.4.9.jar",
          "url": "displee-2.4.9.jar",
          "size": 100563,
          "sha512": "f4b1c20176263a287a0b762b9ec1ef8516c1285111080334bc695586ec26c17ea033ec816390c0be542080aee75342dd474056a3bd9ffea5bb00b2d73f7606b5",
          "sha256": "96e5f39d959ca87493b23185b38770729c45874b7a4effdfd65a6736e4c52ce5",
          "sha1": "403f213bca03020b84aa0efa4cc1eadd8817a4ee",
          "md5": "b3b69e16ea0daf7e33aaec8500ed634b"
        }
      ]
    }
  ]
}
