{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filesystem",
    "version": "2.4.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filesystem-2.4.13.jar",
          "url": "filesystem-2.4.13.jar",
          "size": 51650,
          "sha512": "5da16befd361035a40dc8e5a598c799ad192ce5ee795c1dbe965f95dff1bb6af407b21599bab0fe1d8c539eeff72373e397d1f20eade278381acdc5aefe56f4e",
          "sha256": "7e5228948020da3730bbac5354e6f4bcf522fed20ba7de614852a001d6654945",
          "sha1": "e355b7a3934fefd53cd7e502251b186d33a037e5",
          "md5": "bdefb21fcd14da870a7eaaffd0e8fc88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "filesystem-2.4.13.jar",
          "url": "filesystem-2.4.13.jar",
          "size": 51650,
          "sha512": "5da16befd361035a40dc8e5a598c799ad192ce5ee795c1dbe965f95dff1bb6af407b21599bab0fe1d8c539eeff72373e397d1f20eade278381acdc5aefe56f4e",
          "sha256": "7e5228948020da3730bbac5354e6f4bcf522fed20ba7de614852a001d6654945",
          "sha1": "e355b7a3934fefd53cd7e502251b186d33a037e5",
          "md5": "bdefb21fcd14da870a7eaaffd0e8fc88"
        }
      ]
    }
  ]
}
