{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs-fs",
    "version": "2.4.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-fs-2.4.11.jar",
          "url": "osrs-fs-2.4.11.jar",
          "size": 27384,
          "sha512": "ba7194310a38d36be1744afd31b5aae225a90cc03dc11fadf5595e1676f30de86470fb84f567097e9e61fbb3e7434debff96e9fb7993372d4f8f423926e1775b",
          "sha256": "1e4d80536679cee6132f03870b8a85c1a044bb59cc4d314b48f46e1d5c5266a5",
          "sha1": "7b1e74ec97d831cfd0ca440c9a16c50db2e62d74",
          "md5": "6cf201ece7fb221641546c5e79959cd3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.4.11"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.11"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.4.11"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.11"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-fs-2.4.11.jar",
          "url": "osrs-fs-2.4.11.jar",
          "size": 27384,
          "sha512": "ba7194310a38d36be1744afd31b5aae225a90cc03dc11fadf5595e1676f30de86470fb84f567097e9e61fbb3e7434debff96e9fb7993372d4f8f423926e1775b",
          "sha256": "1e4d80536679cee6132f03870b8a85c1a044bb59cc4d314b48f46e1d5c5266a5",
          "sha1": "7b1e74ec97d831cfd0ca440c9a16c50db2e62d74",
          "md5": "6cf201ece7fb221641546c5e79959cd3"
        }
      ]
    }
  ]
}
