{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filestore-server-osrs",
    "version": "0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-server-osrs-0.4.jar",
          "url": "filestore-server-osrs-0.4.jar",
          "size": 150120,
          "sha512": "8bac39fd94304bd10df146c6fe6af97b7218198a015f9e424477b0f579a82705603b9c2075d8855a5e3c2a642ca8254cbfff3190623b6568568dd8f1eae32e68",
          "sha256": "ec82cd6f240d8806557a5f07640a8240adb1792c299efc16c1feddbc8ed3ac7c",
          "sha1": "51d444c0206d8a51bff681acc2ffbbb3cd0473c1",
          "md5": "afa777c8e5c4782ba39d58e23e70060d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.or2",
          "module": "all",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore-server",
          "version": {
            "requires": "0.4"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-server-osrs-0.4.jar",
          "url": "filestore-server-osrs-0.4.jar",
          "size": 150120,
          "sha512": "8bac39fd94304bd10df146c6fe6af97b7218198a015f9e424477b0f579a82705603b9c2075d8855a5e3c2a642ca8254cbfff3190623b6568568dd8f1eae32e68",
          "sha256": "ec82cd6f240d8806557a5f07640a8240adb1792c299efc16c1feddbc8ed3ac7c",
          "sha1": "51d444c0206d8a51bff681acc2ffbbb3cd0473c1",
          "md5": "afa777c8e5c4782ba39d58e23e70060d"
        }
      ]
    }
  ]
}
