{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "definition",
    "version": "2.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "definition-2.0.5.jar",
          "url": "definition-2.0.5.jar",
          "size": 412605,
          "sha512": "347f69c95b91d8042e9be12205212e0976501746db99ca5e0af3f618d5be918421bac1b8ecb9d11b72491ef20e419d74a323a1511d0c3d35c7961e346a971806",
          "sha256": "f06cff6dc1dd94ee39c3136b881c47832d6d5d71df1ee5b9a0f5883f034f6263",
          "sha1": "70fa18603e96c14ba9e9d429e3b010656be74db4",
          "md5": "791c2819c455b495da7dda38d4a8a25b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0-Beta1"
          }
        }
      ],
      "files": [
        {
          "name": "definition-2.0.5.jar",
          "url": "definition-2.0.5.jar",
          "size": 412605,
          "sha512": "347f69c95b91d8042e9be12205212e0976501746db99ca5e0af3f618d5be918421bac1b8ecb9d11b72491ef20e419d74a323a1511d0c3d35c7961e346a971806",
          "sha256": "f06cff6dc1dd94ee39c3136b881c47832d6d5d71df1ee5b9a0f5883f034f6263",
          "sha1": "70fa18603e96c14ba9e9d429e3b010656be74db4",
          "md5": "791c2819c455b495da7dda38d4a8a25b"
        }
      ]
    }
  ]
}
