{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718-fs",
    "version": "2.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-fs-2.2.6.jar",
          "url": "r718-fs-2.2.6.jar",
          "size": 7588,
          "sha512": "a3d33d202b36bdbc20463bbfe6e46bd725e9716f64d4b50c91ab5057136b3d953542ba31650ee1c0884f8566b1788c8fb08f20965081c1c0c89eba3f72a86cd2",
          "sha256": "7267c5f1bf57d879fba166db693a35f4df0c608e0d3d558ca524fd515109f29f",
          "sha1": "b8843f866cf67a03bae6e17fe98323a5b07c2b71",
          "md5": "12298662ae006cdc3f44d074d07fd43b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.2.6"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.2.6"
          }
        },
        {
          "group": "dev.or2",
          "module": "r718",
          "version": {
            "requires": "2.2.6"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "r718-fs-2.2.6.jar",
          "url": "r718-fs-2.2.6.jar",
          "size": 7588,
          "sha512": "a3d33d202b36bdbc20463bbfe6e46bd725e9716f64d4b50c91ab5057136b3d953542ba31650ee1c0884f8566b1788c8fb08f20965081c1c0c89eba3f72a86cd2",
          "sha256": "7267c5f1bf57d879fba166db693a35f4df0c608e0d3d558ca524fd515109f29f",
          "sha1": "b8843f866cf67a03bae6e17fe98323a5b07c2b71",
          "md5": "12298662ae006cdc3f44d074d07fd43b"
        }
      ]
    }
  ]
}
