{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filesystem",
    "version": "2.4.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filesystem-2.4.17.jar",
          "url": "filesystem-2.4.17.jar",
          "size": 51650,
          "sha512": "fc69bffbed53c0998ad709bf446da2bbf09cd3885a7a6bc9f4cefcc4d9a3ed92cac2c5c9eada740325c209f7c62e4a8415c9fa5c974add27eb2a3fcc362c0c92",
          "sha256": "22c09cda3136f34275bb5620c68c44961dd54a863acfeab2dc03ea12a8a44bfa",
          "sha1": "32e44fc23955a7540bdb1e0f70a9d4104660ac3d",
          "md5": "7a5d03ab2efca382c76b3a010a3bab1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "filesystem-2.4.17.jar",
          "url": "filesystem-2.4.17.jar",
          "size": 51650,
          "sha512": "fc69bffbed53c0998ad709bf446da2bbf09cd3885a7a6bc9f4cefcc4d9a3ed92cac2c5c9eada740325c209f7c62e4a8415c9fa5c974add27eb2a3fcc362c0c92",
          "sha256": "22c09cda3136f34275bb5620c68c44961dd54a863acfeab2dc03ea12a8a44bfa",
          "sha1": "32e44fc23955a7540bdb1e0f70a9d4104660ac3d",
          "md5": "7a5d03ab2efca382c76b3a010a3bab1f"
        }
      ]
    }
  ]
}
