{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718-fs",
    "version": "2.0.16.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-fs-2.0.16.2.jar",
          "url": "r718-fs-2.0.16.2.jar",
          "size": 7588,
          "sha512": "8a62817c9e1edbd2a57ef50e035d97eeaf4e980a873a9cb1b6a5ef9eec517b6d27f5d4797e27753b3c1d4e5d7b471a2c4ca78bdea9a99cd0afe84e55933367f5",
          "sha256": "86ff755df3e664f16f1ef769c4d2a41a42d72c5a81f5a617fd0f5d38539c1c6c",
          "sha1": "02fdd1b81580ead652045d8da1875041e0ffc7be",
          "md5": "26c2d60ee233510727b1322fb780458b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.0.16.2"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.16.2"
          }
        },
        {
          "group": "dev.or2",
          "module": "r718",
          "version": {
            "requires": "2.0.16.2"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.0.16.2"
          }
        }
      ],
      "files": [
        {
          "name": "r718-fs-2.0.16.2.jar",
          "url": "r718-fs-2.0.16.2.jar",
          "size": 7588,
          "sha512": "8a62817c9e1edbd2a57ef50e035d97eeaf4e980a873a9cb1b6a5ef9eec517b6d27f5d4797e27753b3c1d4e5d7b471a2c4ca78bdea9a99cd0afe84e55933367f5",
          "sha256": "86ff755df3e664f16f1ef769c4d2a41a42d72c5a81f5a617fd0f5d38539c1c6c",
          "sha1": "02fdd1b81580ead652045d8da1875041e0ffc7be",
          "md5": "26c2d60ee233510727b1322fb780458b"
        }
      ]
    }
  ]
}
