{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718-fs",
    "version": "2.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-fs-2.4.2.jar",
          "url": "r718-fs-2.4.2.jar",
          "size": 7588,
          "sha512": "55173cfa69ccc614f101bca0b9720bb7c728f80822280ed127a9532c75c6654cec09caa2fe4fe0f019e1302b5a4dbf7dc42a64dc58a795297118ee63a8d6363e",
          "sha256": "123550a643550482a231aab69de4aade91a0926ba7fba297da9672bc8a29144b",
          "sha1": "80b98f5cd28365ca16005177d89a160b6f768f60",
          "md5": "5f175dcc18dd5998e0242c70489f03a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "dev.or2",
          "module": "r718",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "r718-fs-2.4.2.jar",
          "url": "r718-fs-2.4.2.jar",
          "size": 7588,
          "sha512": "55173cfa69ccc614f101bca0b9720bb7c728f80822280ed127a9532c75c6654cec09caa2fe4fe0f019e1302b5a4dbf7dc42a64dc58a795297118ee63a8d6363e",
          "sha256": "123550a643550482a231aab69de4aade91a0926ba7fba297da9672bc8a29144b",
          "sha1": "80b98f5cd28365ca16005177d89a160b6f768f60",
          "md5": "5f175dcc18dd5998e0242c70489f03a8"
        }
      ]
    }
  ]
}
