{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filesystem",
    "version": "2.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filesystem-2.3.7.jar",
          "url": "filesystem-2.3.7.jar",
          "size": 51650,
          "sha512": "99254e580220ac170b065ad83fa6fe8ec6cd2f31c22c93c48f6ade0d8df6cabe287a96ca4459081c6261ce5c3d39986a5954afbd985b66e46391eac60df0ae1d",
          "sha256": "c1e2165e7f1c369b66c96f50dd681cfe8b538cd0386ea2db41dda72632e01d7f",
          "sha1": "2b9dfb22b0ca49e71d19608b6deddc4d567d39ed",
          "md5": "81d39fa76ab1d073f0b65570e4fa874e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "filesystem-2.3.7.jar",
          "url": "filesystem-2.3.7.jar",
          "size": 51650,
          "sha512": "99254e580220ac170b065ad83fa6fe8ec6cd2f31c22c93c48f6ade0d8df6cabe287a96ca4459081c6261ce5c3d39986a5954afbd985b66e46391eac60df0ae1d",
          "sha256": "c1e2165e7f1c369b66c96f50dd681cfe8b538cd0386ea2db41dda72632e01d7f",
          "sha1": "2b9dfb22b0ca49e71d19608b6deddc4d567d39ed",
          "md5": "81d39fa76ab1d073f0b65570e4fa874e"
        }
      ]
    }
  ]
}
