{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filesystem",
    "version": "2.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filesystem-2.3.8.jar",
          "url": "filesystem-2.3.8.jar",
          "size": 51650,
          "sha512": "29178208df253cffad0ba057c39e2b5608eafd5d3641f203371a309ed6bfef1d3ecaa2b0a9209da95c440bad3cfbce58eab58d1fe2039f355ed091e7a00d1f62",
          "sha256": "dbb698e987f53b6dedee9dc4b34f943cca04fb291ccf1f114aa9d00e9ea88454",
          "sha1": "0b841ba6045247634457080d8f467daff7b9aeac",
          "md5": "2cfa354782b982655c3fd34e6af94306"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "filesystem-2.3.8.jar",
          "url": "filesystem-2.3.8.jar",
          "size": 51650,
          "sha512": "29178208df253cffad0ba057c39e2b5608eafd5d3641f203371a309ed6bfef1d3ecaa2b0a9209da95c440bad3cfbce58eab58d1fe2039f355ed091e7a00d1f62",
          "sha256": "dbb698e987f53b6dedee9dc4b34f943cca04fb291ccf1f114aa9d00e9ea88454",
          "sha1": "0b841ba6045247634457080d8f467daff7b9aeac",
          "md5": "2cfa354782b982655c3fd34e6af94306"
        }
      ]
    }
  ]
}
