{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "tools",
    "version": "2.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "tools-2.4.3.jar",
          "url": "tools-2.4.3.jar",
          "size": 332986,
          "sha512": "682d774ba0629c26d6a534829bfbd60111b2560b4d7dcc95fdd61bd3ea04f26cb81503eee8841b0fb51e468b0b4e13612965b9539086907256f4f3f5b0f32635",
          "sha256": "3ae7e5e5628f9e37d540fccb396f577bd260cf736d29bc72f6f7d2760c44baf4",
          "sha1": "80a72a0ac199426bbb02a458bba99969d18b3bb4",
          "md5": "abcc3dd8b5658f4ecfe3d7f18dbb2ac3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs-fs",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.11.5"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "dev.or2",
          "module": "displee",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "toml-rsconfig",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "me.filby",
          "module": "clientscript-compiler",
          "version": {
            "requires": "0.0.2-openrune"
          }
        }
      ],
      "files": [
        {
          "name": "tools-2.4.3.jar",
          "url": "tools-2.4.3.jar",
          "size": 332986,
          "sha512": "682d774ba0629c26d6a534829bfbd60111b2560b4d7dcc95fdd61bd3ea04f26cb81503eee8841b0fb51e468b0b4e13612965b9539086907256f4f3f5b0f32635",
          "sha256": "3ae7e5e5628f9e37d540fccb396f577bd260cf736d29bc72f6f7d2760c44baf4",
          "sha1": "80a72a0ac199426bbb02a458bba99969d18b3bb4",
          "md5": "abcc3dd8b5658f4ecfe3d7f18dbb2ac3"
        }
      ]
    }
  ]
}
