{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "filestore",
    "version": "1.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-1.3.6.jar",
          "url": "filestore-1.3.6.jar",
          "size": 277749,
          "sha512": "939401dbbd97c55088f4edb6c413dd592e93f9c4fbee8918e31f4cf7bec9314af4c122f9387ffcc495d5f44214c5e1849c377a8dbbb2d5b856d5623bf2f2c229",
          "sha256": "dc3409e6e2697afe0d1db6a445f6f646ef267be088be6af51ebc370d5ff952ef",
          "sha1": "568bda86649a72ced35567c44d32f77e798b52a9",
          "md5": "963310ee3407aad89c1c4d357df6ca0d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-1.3.6.jar",
          "url": "filestore-1.3.6.jar",
          "size": 277749,
          "sha512": "939401dbbd97c55088f4edb6c413dd592e93f9c4fbee8918e31f4cf7bec9314af4c122f9387ffcc495d5f44214c5e1849c377a8dbbb2d5b856d5623bf2f2c229",
          "sha256": "dc3409e6e2697afe0d1db6a445f6f646ef267be088be6af51ebc370d5ff952ef",
          "sha1": "568bda86649a72ced35567c44d32f77e798b52a9",
          "md5": "963310ee3407aad89c1c4d357df6ca0d"
        }
      ]
    }
  ]
}
