{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718-fs",
    "version": "2.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-fs-2.3.7.jar",
          "url": "r718-fs-2.3.7.jar",
          "size": 7588,
          "sha512": "a388e88c69362dd5756f584ae138b4529415007908e21d2e8caeef9da042151b2bdde96a9513df892e32083328f1dd79f8c1946392d1c2f33c5921e5bd22d8fa",
          "sha256": "fa8ba2095bdbdb39ea5e142df6d2a1890840a8d65890491f3399467c5ef9f303",
          "sha1": "7e9ca10793f512c9098bca4126041329eabc1641",
          "md5": "d33c10f0997b34ebd7724b2f5c938905"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.3.7"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.3.7"
          }
        },
        {
          "group": "dev.or2",
          "module": "r718",
          "version": {
            "requires": "2.3.7"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "r718-fs-2.3.7.jar",
          "url": "r718-fs-2.3.7.jar",
          "size": 7588,
          "sha512": "a388e88c69362dd5756f584ae138b4529415007908e21d2e8caeef9da042151b2bdde96a9513df892e32083328f1dd79f8c1946392d1c2f33c5921e5bd22d8fa",
          "sha256": "fa8ba2095bdbdb39ea5e142df6d2a1890840a8d65890491f3399467c5ef9f303",
          "sha1": "7e9ca10793f512c9098bca4126041329eabc1641",
          "md5": "d33c10f0997b34ebd7724b2f5c938905"
        }
      ]
    }
  ]
}
