{
  "formatVersion": "1.1",
  "component": {
    "group": "me.filby",
    "module": "clientscript-compiler",
    "version": "0.0.4-openrune",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.filby",
          "module": "runescript-compiler",
          "version": {
            "requires": "0.0.4-openrune"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "clientscript-compiler-0.0.4-openrune.jar",
          "url": "clientscript-compiler-0.0.4-openrune.jar",
          "size": 1533990,
          "sha512": "0d4a140b7c27b2e9d614136b380727afd4d99a9a9f7287c531c39cb41f3a587a775dd9e639e0dd560b78c0c43ef6bb61d6a5691829331e681127f9c196d89a42",
          "sha256": "2a28b6950a1d0b9f1e35724dfe6059c124eb66ffbb04d3264a31a5451e5c55cf",
          "sha1": "730fd5013915007ce805a356b5441d6d2817c826",
          "md5": "5dd920d588604a65786e9f608a472b5e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.0-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.116.Final"
          }
        },
        {
          "group": "cc.ekblad",
          "module": "4koma",
          "version": {
            "requires": "1.2.0-openrune"
          }
        },
        {
          "group": "com.github.ajalt.clikt",
          "module": "clikt",
          "version": {
            "requires": "5.0.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          },
          "excludes": [
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.11"
          }
        },
        {
          "group": "me.filby",
          "module": "runescript-compiler",
          "version": {
            "requires": "0.0.4-openrune"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "clientscript-compiler-0.0.4-openrune.jar",
          "url": "clientscript-compiler-0.0.4-openrune.jar",
          "size": 1533990,
          "sha512": "0d4a140b7c27b2e9d614136b380727afd4d99a9a9f7287c531c39cb41f3a587a775dd9e639e0dd560b78c0c43ef6bb61d6a5691829331e681127f9c196d89a42",
          "sha256": "2a28b6950a1d0b9f1e35724dfe6059c124eb66ffbb04d3264a31a5451e5c55cf",
          "sha1": "730fd5013915007ce805a356b5441d6d2817c826",
          "md5": "5dd920d588604a65786e9f608a472b5e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "clientscript-compiler-0.0.4-openrune-sources.jar",
          "url": "clientscript-compiler-0.0.4-openrune-sources.jar",
          "size": 1410213,
          "sha512": "48a8eab074844defe354ec3cf8a99207e2fce24dd76201e327c793a7a2e8a9b587515029948c5d0469d952dcb468144aaa5cd559588dc0e50d01ddf0b20fa204",
          "sha256": "29dfc01b98f7430ab1c5c0426cd0a6f65c073b42c266a8cf9845c2674ecd9079",
          "sha1": "611e376e07f1434f321f62868d0838b169c36b45",
          "md5": "7c7731a580b0f582ccc01d7256d5d92c"
        },
        {
          "name": "clientscript-compiler-0.0.4-openrune-sources.jar",
          "url": "clientscript-compiler-0.0.4-openrune-sources.jar",
          "size": 1410213,
          "sha512": "48a8eab074844defe354ec3cf8a99207e2fce24dd76201e327c793a7a2e8a9b587515029948c5d0469d952dcb468144aaa5cd559588dc0e50d01ddf0b20fa204",
          "sha256": "29dfc01b98f7430ab1c5c0426cd0a6f65c073b42c266a8cf9845c2674ecd9079",
          "sha1": "611e376e07f1434f321f62868d0838b169c36b45",
          "md5": "7c7731a580b0f582ccc01d7256d5d92c"
        }
      ]
    }
  ]
}
