{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filestore",
    "version": "2.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-2.4.5.jar",
          "url": "filestore-2.4.5.jar",
          "size": 94748,
          "sha512": "b82bd45f4cb4e7b506758d675cfa712dae06a68173aa819fa66fe410a75015804640db3ad88a2bd16cf267fafd5717cc703ef5bbd2ae02a8fa2eb80d8364db7d",
          "sha256": "2ac7ec9ad0b218cc62b431a0a67e19204254468c0adfbaa9e587c8063bb84aa1",
          "sha1": "6d2b1c09860eb97582a077ef0850ef5469ac7e82",
          "md5": "48f61662fded7c8bceecebac0e0e418e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.5"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.5"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-2.4.5.jar",
          "url": "filestore-2.4.5.jar",
          "size": 94748,
          "sha512": "b82bd45f4cb4e7b506758d675cfa712dae06a68173aa819fa66fe410a75015804640db3ad88a2bd16cf267fafd5717cc703ef5bbd2ae02a8fa2eb80d8364db7d",
          "sha256": "2ac7ec9ad0b218cc62b431a0a67e19204254468c0adfbaa9e587c8063bb84aa1",
          "sha1": "6d2b1c09860eb97582a077ef0850ef5469ac7e82",
          "md5": "48f61662fded7c8bceecebac0e0e418e"
        }
      ]
    }
  ]
}
