{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs",
    "version": "2.0.92",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-2.0.92.jar",
          "url": "osrs-2.0.92.jar",
          "size": 73215,
          "sha512": "1f7008cffd6d7a33e36d2f5c33bc1878407e95b4ba0728b2cd23f694989f2b1e2361c195a5511e0de4be8b649f3253d7bf13675fb640f240460d48edec3ff6a1",
          "sha256": "393a8bd366fecda6a47e613209fd4ae9cda7be9b89523a0f302619f8c113d1f3",
          "sha1": "f0490e844eaff53e899bf9f1a86e4734cbd9a208",
          "md5": "5df4606f2ada5d7564bd4bcdb9f62f9a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.92"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-2.0.92.jar",
          "url": "osrs-2.0.92.jar",
          "size": 73215,
          "sha512": "1f7008cffd6d7a33e36d2f5c33bc1878407e95b4ba0728b2cd23f694989f2b1e2361c195a5511e0de4be8b649f3253d7bf13675fb640f240460d48edec3ff6a1",
          "sha256": "393a8bd366fecda6a47e613209fd4ae9cda7be9b89523a0f302619f8c113d1f3",
          "sha1": "f0490e844eaff53e899bf9f1a86e4734cbd9a208",
          "md5": "5df4606f2ada5d7564bd4bcdb9f62f9a"
        }
      ]
    }
  ]
}
