{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filesystem",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filesystem-2.4.0.jar",
          "url": "filesystem-2.4.0.jar",
          "size": 51650,
          "sha512": "db350f1d1caab9ca6452af7854b2af63f421a5cbfeeeb85b81d9764c19e95b1f37cbadda96faa3d7fe41e41d3196ae22d4bff85044b3cee6f89da270ad4e6cc4",
          "sha256": "ff2cddfbd5799498bd056cd677f25f511ef9fb76b96fc9566ffc13c16de39941",
          "sha1": "63f0bd68b55171bb973d5e99953dc6784876dd53",
          "md5": "f301ccc88f64af4f24f272fe03d6a939"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "filesystem-2.4.0.jar",
          "url": "filesystem-2.4.0.jar",
          "size": 51650,
          "sha512": "db350f1d1caab9ca6452af7854b2af63f421a5cbfeeeb85b81d9764c19e95b1f37cbadda96faa3d7fe41e41d3196ae22d4bff85044b3cee6f89da270ad4e6cc4",
          "sha256": "ff2cddfbd5799498bd056cd677f25f511ef9fb76b96fc9566ffc13c16de39941",
          "sha1": "63f0bd68b55171bb973d5e99953dc6784876dd53",
          "md5": "f301ccc88f64af4f24f272fe03d6a939"
        }
      ]
    }
  ]
}
