{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "filestore",
    "version": "1.3.88",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-1.3.88.jar",
          "url": "filestore-1.3.88.jar",
          "size": 353793,
          "sha512": "ac0a54beece992685c5e682a3bc6ef81f16f0b9c49e4124e2a8247eb669a54d9e0a6cd6560edeb1000f79d7d9692ec658c75080b19d2cb7515cf8d4d42849d90",
          "sha256": "bd427415202209a6ec331319f0404e27b6f94ecdb78a872ec3fa691d018447a9",
          "sha1": "ac9426b18c6536821f6aa4e6ca098f3f9c6cc7fe",
          "md5": "2eabe7c51576fddc02311b89bf754ac0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-file",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0-Beta1"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-1.3.88.jar",
          "url": "filestore-1.3.88.jar",
          "size": 353793,
          "sha512": "ac0a54beece992685c5e682a3bc6ef81f16f0b9c49e4124e2a8247eb669a54d9e0a6cd6560edeb1000f79d7d9692ec658c75080b19d2cb7515cf8d4d42849d90",
          "sha256": "bd427415202209a6ec331319f0404e27b6f94ecdb78a872ec3fa691d018447a9",
          "sha1": "ac9426b18c6536821f6aa4e6ca098f3f9c6cc7fe",
          "md5": "2eabe7c51576fddc02311b89bf754ac0"
        }
      ]
    }
  ]
}
