{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "filestore",
    "version": "1.3.88",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-1.3.88.jar",
          "url": "filestore-1.3.88.jar",
          "size": 353712,
          "sha512": "2a6ad8d397f4aaa2e546656e494ceffcf4c0d6ff4401ade5b2f2d53f27ed7de12fd56329c9751f6b8b8d298594eab06d250d187028577215d11b3371fb187494",
          "sha256": "4c6f9d12d653643836f6bc2bff62b3cf0693ab608a641806bdbce94a8eb5bf91",
          "sha1": "d001e450384fbc5c80b65a1831e0d5e100981bf5",
          "md5": "d14039945d2ada57f899494e7c6480e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-file",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0-Beta1"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-1.3.88.jar",
          "url": "filestore-1.3.88.jar",
          "size": 353712,
          "sha512": "2a6ad8d397f4aaa2e546656e494ceffcf4c0d6ff4401ade5b2f2d53f27ed7de12fd56329c9751f6b8b8d298594eab06d250d187028577215d11b3371fb187494",
          "sha256": "4c6f9d12d653643836f6bc2bff62b3cf0693ab608a641806bdbce94a8eb5bf91",
          "sha1": "d001e450384fbc5c80b65a1831e0d5e100981bf5",
          "md5": "d14039945d2ada57f899494e7c6480e1"
        }
      ]
    }
  ]
}
