{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filestore",
    "version": "2.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-2.0.5.jar",
          "url": "filestore-2.0.5.jar",
          "size": 24163,
          "sha512": "1e55a333ed2718a9849e34ca61c4321445df707b92ec653d6e177009dd93dcc14cb11f10e20388971317b93470348ac4453266b926447c612ad4f7ef2a214fda",
          "sha256": "7111fac1a40af08bb52914b5316fe3df20a32f98318f5bfc8d7126e546e9cdf6",
          "sha1": "af4817e6b7c54f932a9816a7de8ed2a2f0ae688d",
          "md5": "f1f57a00766fd14e58780c65778957a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-2.0.5.jar",
          "url": "filestore-2.0.5.jar",
          "size": 24163,
          "sha512": "1e55a333ed2718a9849e34ca61c4321445df707b92ec653d6e177009dd93dcc14cb11f10e20388971317b93470348ac4453266b926447c612ad4f7ef2a214fda",
          "sha256": "7111fac1a40af08bb52914b5316fe3df20a32f98318f5bfc8d7126e546e9cdf6",
          "sha1": "af4817e6b7c54f932a9816a7de8ed2a2f0ae688d",
          "md5": "f1f57a00766fd14e58780c65778957a9"
        }
      ]
    }
  ]
}
