{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.4.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.4.11.jar",
          "url": "displee-2.4.11.jar",
          "size": 111913,
          "sha512": "88bac04c3b2620daf679d03cd085d456a4e69b9d636d9e1d6f0197ae77845302dc95dd6391541fe7512b4e41a8e6ce5bea4fd22ec2c15e778fe32d69f717413b",
          "sha256": "2ad6800c3565d295dee936e38fdb3fdbca373fea950109e98c3f924b04bc869d",
          "sha1": "b83251ebd07fbfe1c8a7a36310b880a66a0a78d0",
          "md5": "e4780ae76d1185a02d90d4c506467db9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.4.11.jar",
          "url": "displee-2.4.11.jar",
          "size": 111913,
          "sha512": "88bac04c3b2620daf679d03cd085d456a4e69b9d636d9e1d6f0197ae77845302dc95dd6391541fe7512b4e41a8e6ce5bea4fd22ec2c15e778fe32d69f717413b",
          "sha256": "2ad6800c3565d295dee936e38fdb3fdbca373fea950109e98c3f924b04bc869d",
          "sha1": "b83251ebd07fbfe1c8a7a36310b880a66a0a78d0",
          "md5": "e4780ae76d1185a02d90d4c506467db9"
        }
      ]
    }
  ]
}
