{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.4.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.4.11.jar",
          "url": "displee-2.4.11.jar",
          "size": 111913,
          "sha512": "7e1ebbd650e4bd3dc2c9fe6e668fe0dff9e6275b267fa1c920394d740056c3e0529944382430a377ed7820a1fccd9d1f1d087512c2269e2a768c08452a884ee8",
          "sha256": "4886404645cd45fc5eb3a76456eb9c2505dd3205b2c9e2e0bcaba75cfea32efd",
          "sha1": "72b9be8565cd1d06e6ee93f980d372d75cd3aaf1",
          "md5": "82d96e0af87b3e9429405cbb2e06f3e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.4.11.jar",
          "url": "displee-2.4.11.jar",
          "size": 111913,
          "sha512": "7e1ebbd650e4bd3dc2c9fe6e668fe0dff9e6275b267fa1c920394d740056c3e0529944382430a377ed7820a1fccd9d1f1d087512c2269e2a768c08452a884ee8",
          "sha256": "4886404645cd45fc5eb3a76456eb9c2505dd3205b2c9e2e0bcaba75cfea32efd",
          "sha1": "72b9be8565cd1d06e6ee93f980d372d75cd3aaf1",
          "md5": "82d96e0af87b3e9429405cbb2e06f3e9"
        }
      ]
    }
  ]
}
