{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718-fs",
    "version": "2.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-fs-2.0.12.jar",
          "url": "r718-fs-2.0.12.jar",
          "size": 7586,
          "sha512": "dd01f0df94be83db0e1ea2faf59978a0865aa27b408cd1527008c4a5d8756a0e9fb57aa6c96b871ffd6837a8179f10557af385ab71e681dae0ef9faf718eae7f",
          "sha256": "b52947b30e0d309bbe69d12ccf5f9ba0b23dc03d84dcef5a5dfa9811155dd9f1",
          "sha1": "9fee2906b5dfcbe04eaacf273104954694561f86",
          "md5": "b8c305c941148bef66a9c77e97c5fba1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.0.12"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.12"
          }
        },
        {
          "group": "dev.or2",
          "module": "r718",
          "version": {
            "requires": "2.0.12"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.0.12"
          }
        }
      ],
      "files": [
        {
          "name": "r718-fs-2.0.12.jar",
          "url": "r718-fs-2.0.12.jar",
          "size": 7586,
          "sha512": "dd01f0df94be83db0e1ea2faf59978a0865aa27b408cd1527008c4a5d8756a0e9fb57aa6c96b871ffd6837a8179f10557af385ab71e681dae0ef9faf718eae7f",
          "sha256": "b52947b30e0d309bbe69d12ccf5f9ba0b23dc03d84dcef5a5dfa9811155dd9f1",
          "sha1": "9fee2906b5dfcbe04eaacf273104954694561f86",
          "md5": "b8c305c941148bef66a9c77e97c5fba1"
        }
      ]
    }
  ]
}
