{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718",
    "version": "2.4.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-2.4.11.jar",
          "url": "r718-2.4.11.jar",
          "size": 14446,
          "sha512": "1cc838721f35829d731803d7442aed759c4e9f40166949e09e3fdab96f842893fb98be3574416879c0753586bc1adb7a0b6d9b4a3f2a5a8d8ad438f9dd28bdd3",
          "sha256": "5de7632abcf26746fc65f892431011f36e4ccf5814a98c17945a9d9d516f6933",
          "sha1": "442c773ed848ad4fb9cdc588459f268f148fb778",
          "md5": "0b823c14a7c7af17c364a1619fc981c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.11"
          }
        }
      ],
      "files": [
        {
          "name": "r718-2.4.11.jar",
          "url": "r718-2.4.11.jar",
          "size": 14446,
          "sha512": "1cc838721f35829d731803d7442aed759c4e9f40166949e09e3fdab96f842893fb98be3574416879c0753586bc1adb7a0b6d9b4a3f2a5a8d8ad438f9dd28bdd3",
          "sha256": "5de7632abcf26746fc65f892431011f36e4ccf5814a98c17945a9d9d516f6933",
          "sha1": "442c773ed848ad4fb9cdc588459f268f148fb778",
          "md5": "0b823c14a7c7af17c364a1619fc981c1"
        }
      ]
    }
  ]
}
