{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filestore",
    "version": "2.0.3-snapshot",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-2.0.3-snapshot.jar",
          "url": "filestore-2.0.3-snapshot.jar",
          "size": 24242,
          "sha512": "c3c5da9904c3633231d2e0fdc63fc743d670dac060019e962942a6f258769258f1675f6c5a7ecac6b963cfe5adf94bab2db35b15e861b282037919debfb5f79d",
          "sha256": "71c0ecfcd7c90bbba45a0622e4ff58a551f6950e67cc5355f7ac840487aff587",
          "sha1": "74687d61cd534d5c52869fb1c0984c6761661979",
          "md5": "d196586ddf59dd5622256fd554213a9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.3-snapshot"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.0.3-snapshot"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-2.0.3-snapshot.jar",
          "url": "filestore-2.0.3-snapshot.jar",
          "size": 24242,
          "sha512": "c3c5da9904c3633231d2e0fdc63fc743d670dac060019e962942a6f258769258f1675f6c5a7ecac6b963cfe5adf94bab2db35b15e861b282037919debfb5f79d",
          "sha256": "71c0ecfcd7c90bbba45a0622e4ff58a551f6950e67cc5355f7ac840487aff587",
          "sha1": "74687d61cd534d5c52869fb1c0984c6761661979",
          "md5": "d196586ddf59dd5622256fd554213a9c"
        }
      ]
    }
  ]
}
