{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.0.7.jar",
          "url": "displee-2.0.7.jar",
          "size": 111432,
          "sha512": "a2aff99dd9c255166fa9b1ef4d6506b809d65b6bbc9a303dd60855eea954dcfea97c21bc9a06fc4066f40ed42f37d9979bf0da0bf4cf751ce9aeec2d5916fc7d",
          "sha256": "90ede6c6b26da3702205e2962e5e1c256024a3a11968be63c79c889c931e9695",
          "sha1": "79805762562d3100da6a192e2baedacb2470f684",
          "md5": "74b17e35e8efa84b565b6eade10248ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.0.7.jar",
          "url": "displee-2.0.7.jar",
          "size": 111432,
          "sha512": "a2aff99dd9c255166fa9b1ef4d6506b809d65b6bbc9a303dd60855eea954dcfea97c21bc9a06fc4066f40ed42f37d9979bf0da0bf4cf751ce9aeec2d5916fc7d",
          "sha256": "90ede6c6b26da3702205e2962e5e1c256024a3a11968be63c79c889c931e9695",
          "sha1": "79805762562d3100da6a192e2baedacb2470f684",
          "md5": "74b17e35e8efa84b565b6eade10248ee"
        }
      ]
    }
  ]
}
