{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filesystem",
    "version": "3.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filesystem-3.0.5.jar",
          "url": "filesystem-3.0.5.jar",
          "size": 53959,
          "sha512": "35fb5fcdaafb047044b46d17e1b104b45a6a89efc0d2a53a2503408c241c552867c0e96043a1c86aa310bd1d38b09431438d4ff96242d12c0f0922b57631ca88",
          "sha256": "7f6281286c3e4118d9c2bf1cf16229ca03cd4b142ba6de06da3e73ac8a8aa66d",
          "sha1": "ccb1bd29144df6b638a1c013065953217ff931ac",
          "md5": "d0153bda23d9a70aa548f7e1d63ab32f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "filesystem-3.0.5.jar",
          "url": "filesystem-3.0.5.jar",
          "size": 53959,
          "sha512": "35fb5fcdaafb047044b46d17e1b104b45a6a89efc0d2a53a2503408c241c552867c0e96043a1c86aa310bd1d38b09431438d4ff96242d12c0f0922b57631ca88",
          "sha256": "7f6281286c3e4118d9c2bf1cf16229ca03cd4b142ba6de06da3e73ac8a8aa66d",
          "sha1": "ccb1bd29144df6b638a1c013065953217ff931ac",
          "md5": "d0153bda23d9a70aa548f7e1d63ab32f"
        }
      ]
    }
  ]
}
