{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs-fs",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-fs-2.0.1.jar",
          "url": "osrs-fs-2.0.1.jar",
          "size": 22442,
          "sha512": "b756f009f30a69c48e0340057a44892f75348e60212dd43c7c152f5253da8b455ba853bab5fa491bfcccf8032d86409e6020a9e0e03827fbf78ee8513a7987c9",
          "sha256": "3b5c3566ba16fc811326ce0a48c38eb0427326fee9a12ae076103ce1f5a71a56",
          "sha1": "461fbb6b11524bc15ff0749c9e917ad412b58ecf",
          "md5": "9522142c363319901b064a8882cdbefe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-fs-2.0.1.jar",
          "url": "osrs-fs-2.0.1.jar",
          "size": 22442,
          "sha512": "b756f009f30a69c48e0340057a44892f75348e60212dd43c7c152f5253da8b455ba853bab5fa491bfcccf8032d86409e6020a9e0e03827fbf78ee8513a7987c9",
          "sha256": "3b5c3566ba16fc811326ce0a48c38eb0427326fee9a12ae076103ce1f5a71a56",
          "sha1": "461fbb6b11524bc15ff0749c9e917ad412b58ecf",
          "md5": "9522142c363319901b064a8882cdbefe"
        }
      ]
    }
  ]
}
