{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.4.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.4.10.jar",
          "url": "displee-2.4.10.jar",
          "size": 111913,
          "sha512": "4e48e53a6acd39d8020a305e18b8a5f282172a954c0909d00299070945a7c849f39b7f7919f66bd45a5ff039195b94e615c9fdaf1d4809b7c0f81eb4236fab73",
          "sha256": "d29c764b26b34c0a29100006e698f88a5d872a54373ce74aabac886f672cc279",
          "sha1": "f153306bcc1cb9ae6cc9fd190f626fa4462cde4b",
          "md5": "25799ccd08285fe1a6a397b1c47d1b69"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.4.10.jar",
          "url": "displee-2.4.10.jar",
          "size": 111913,
          "sha512": "4e48e53a6acd39d8020a305e18b8a5f282172a954c0909d00299070945a7c849f39b7f7919f66bd45a5ff039195b94e615c9fdaf1d4809b7c0f81eb4236fab73",
          "sha256": "d29c764b26b34c0a29100006e698f88a5d872a54373ce74aabac886f672cc279",
          "sha1": "f153306bcc1cb9ae6cc9fd190f626fa4462cde4b",
          "md5": "25799ccd08285fe1a6a397b1c47d1b69"
        }
      ]
    }
  ]
}
