{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.4.3.jar",
          "url": "displee-2.4.3.jar",
          "size": 111913,
          "sha512": "798056e1f2695a5ef26dbfc3c502eef44dad206748c22009002a9fee11d7d851b069e606ce51e3ce6da541ed88a2a5b1ab7c4be7c8764f5fb4d107a4389fbf0d",
          "sha256": "e884b42bd9382db6cc8c3a651bc9ff568634cfe65cc2c9917d2667cc12fe4bdc",
          "sha1": "25d8da0d40d69b2ab2128993d154853507a5a257",
          "md5": "b47526ed7cebb69aced51e2354b398f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.4.3.jar",
          "url": "displee-2.4.3.jar",
          "size": 111913,
          "sha512": "798056e1f2695a5ef26dbfc3c502eef44dad206748c22009002a9fee11d7d851b069e606ce51e3ce6da541ed88a2a5b1ab7c4be7c8764f5fb4d107a4389fbf0d",
          "sha256": "e884b42bd9382db6cc8c3a651bc9ff568634cfe65cc2c9917d2667cc12fe4bdc",
          "sha1": "25d8da0d40d69b2ab2128993d154853507a5a257",
          "md5": "b47526ed7cebb69aced51e2354b398f5"
        }
      ]
    }
  ]
}
