{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs",
    "version": "2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-2.1.jar",
          "url": "osrs-2.1.jar",
          "size": 81672,
          "sha512": "54fbc9708ef49dc585b13fc3aae3bbc23ba00e0ab4e73785415bfcd92c520364cdfeb2d6f918099671d8b6a6298763442b9976c3626de6d3916c31a179a25d1b",
          "sha256": "ec096f7e9099c3d11d2823c45ea107e2d42f949d9707cd722ef866e44eb3bbfd",
          "sha1": "f90f68b000fc59bb2c86d0d690b1bfeaf52a2d02",
          "md5": "00db7ce79f784cfd19d0b37680394b49"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.1"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-2.1.jar",
          "url": "osrs-2.1.jar",
          "size": 81672,
          "sha512": "54fbc9708ef49dc585b13fc3aae3bbc23ba00e0ab4e73785415bfcd92c520364cdfeb2d6f918099671d8b6a6298763442b9976c3626de6d3916c31a179a25d1b",
          "sha256": "ec096f7e9099c3d11d2823c45ea107e2d42f949d9707cd722ef866e44eb3bbfd",
          "sha1": "f90f68b000fc59bb2c86d0d690b1bfeaf52a2d02",
          "md5": "00db7ce79f784cfd19d0b37680394b49"
        }
      ]
    }
  ]
}
