{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "filestore-osrs",
    "version": "1.3.6-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-osrs-1.3.6-beta.jar",
          "url": "filestore-osrs-1.3.6-beta.jar",
          "size": 64774,
          "sha512": "2fa9786d2c368ff752e35027eaaf396b167b0cd165f1b6c2415bcec22846e7052b924fc6f3a1bf97d8354c33c603fba09b7d21ee42f45a1940fade693c3a0fe5",
          "sha256": "20dbdc9fd9bf2efe3c51d8895709eead5e14d9a88b13b884a124f56dcd423a03",
          "sha1": "3be71562c28737a8f7147e0a51d0976eeffc27b4",
          "md5": "f2f1d0a99be6aa76281e31fa32935ceb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.openrune",
          "module": "filestore",
          "version": {
            "requires": "1.3.6-beta"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.openrune",
          "module": "js5server",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.11.5"
          }
        },
        {
          "group": "cc.ekblad",
          "module": "4koma",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "com.displee",
          "module": "rs-cache-library",
          "version": {
            "requires": "7.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-osrs-1.3.6-beta.jar",
          "url": "filestore-osrs-1.3.6-beta.jar",
          "size": 64774,
          "sha512": "2fa9786d2c368ff752e35027eaaf396b167b0cd165f1b6c2415bcec22846e7052b924fc6f3a1bf97d8354c33c603fba09b7d21ee42f45a1940fade693c3a0fe5",
          "sha256": "20dbdc9fd9bf2efe3c51d8895709eead5e14d9a88b13b884a124f56dcd423a03",
          "sha1": "3be71562c28737a8f7147e0a51d0976eeffc27b4",
          "md5": "f2f1d0a99be6aa76281e31fa32935ceb"
        }
      ]
    }
  ]
}
