{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "openrune-central",
    "version": "1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "openrune-central-1.3.jar",
          "url": "openrune-central-1.3.jar",
          "size": 433246,
          "sha512": "bb099c585b1e0d4a1d9e3232e1b96a8a8ef058da4517099f794faca704e9af90991175106f7bd2475e213bb39e868045bc2c12b7954df9bfeaa95c4614ea5abb",
          "sha256": "a6deb8eeb9f1e101ba4e12ee63972e0f7fb7cb331890a86e2721368530ae5428",
          "sha1": "05b86874dcc30eda19f5cacf085b206017fecabc",
          "md5": "d62f3c02c62f08700410884afe5bd29e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.or2",
          "module": "central-common",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-bom",
          "version": {
            "requires": "3.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-content-negotiation"
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-status-pages"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-config-yaml"
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.7"
          }
        },
        {
          "group": "io.zonky.test",
          "module": "embedded-postgres",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.16"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "de.mkammerer",
          "module": "argon2-jvm",
          "version": {
            "requires": "2.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "openrune-central-1.3.jar",
          "url": "openrune-central-1.3.jar",
          "size": 433246,
          "sha512": "bb099c585b1e0d4a1d9e3232e1b96a8a8ef058da4517099f794faca704e9af90991175106f7bd2475e213bb39e868045bc2c12b7954df9bfeaa95c4614ea5abb",
          "sha256": "a6deb8eeb9f1e101ba4e12ee63972e0f7fb7cb331890a86e2721368530ae5428",
          "sha1": "05b86874dcc30eda19f5cacf085b206017fecabc",
          "md5": "d62f3c02c62f08700410884afe5bd29e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "openrune-central-1.3-all.jar",
          "url": "openrune-central-1.3-all.jar",
          "size": 101056233,
          "sha512": "6d7bf9d96bc7e8b0dfa70e1d111bea56601b45cb26805b2ca157ed86375b7309834040109fb34587df286f243d7d31dcd8b379296b5ad767f76d40f8a31fd95f",
          "sha256": "2d07022dc732c2a6a0225052fa5b39df56deebedcfdcb4ec84a6eb0199e241c9",
          "sha1": "19f4f91b6644d65b5e380a42a364816ceea9830e",
          "md5": "cd0db5f9c244eafa418cb553f23d0d51"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "openrune-central-1.3-sources.jar",
          "url": "openrune-central-1.3-sources.jar",
          "size": 62818,
          "sha512": "baa9097161b5fe59a15daf0d340639d3f48f5dc86a1e69c6b47742c79fbdae4c1bf918891ff3f6e84b1e3093df67dfac1bf7c42638516437c479acfaad147afa",
          "sha256": "670388f2753a7e297b0f9a97b75eba43f35d1ebf07b5cd9cf15dc6b0256ec7ce",
          "sha1": "df700f1567a4808dee7c090acbc76688d2a1ae0f",
          "md5": "94e2f40c6ad05bb46932314949e31d92"
        }
      ]
    }
  ]
}
