{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "openrune-central",
    "version": "1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "openrune-central-1.3.jar",
          "url": "openrune-central-1.3.jar",
          "size": 480550,
          "sha512": "72e14ac40c9a927ad8e3afab71867bc270ea607aea0a4ad7a82769c5c4317c84daa56b4a694797f45f9f364a95e6801ff0bae945acc6f6dcad7c524a1da05518",
          "sha256": "b8323642a695434fe4530b21a8c093a66b44b2bf4d97f599128a6ee2238ad75f",
          "sha1": "ee08c62ef946e1b2ca3dfea8804089a199743563",
          "md5": "a0f4c5628f25c2f18375f2d54c7069de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.or2",
          "module": "central-common",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-bom",
          "version": {
            "requires": "3.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-content-negotiation"
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-status-pages"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-forwarded-header"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-config-yaml"
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.7"
          }
        },
        {
          "group": "io.zonky.test",
          "module": "embedded-postgres",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.16"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "de.mkammerer",
          "module": "argon2-jvm",
          "version": {
            "requires": "2.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "openrune-central-1.3.jar",
          "url": "openrune-central-1.3.jar",
          "size": 480550,
          "sha512": "72e14ac40c9a927ad8e3afab71867bc270ea607aea0a4ad7a82769c5c4317c84daa56b4a694797f45f9f364a95e6801ff0bae945acc6f6dcad7c524a1da05518",
          "sha256": "b8323642a695434fe4530b21a8c093a66b44b2bf4d97f599128a6ee2238ad75f",
          "sha1": "ee08c62ef946e1b2ca3dfea8804089a199743563",
          "md5": "a0f4c5628f25c2f18375f2d54c7069de"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "openrune-central-1.3-all.jar",
          "url": "openrune-central-1.3-all.jar",
          "size": 101466992,
          "sha512": "1587ab9c44fe11084fa063a02369a6656dee3a1f094144485d98eee5867e38a2d3383aab9c891404ee96bb926c993f3f814a6ce048a866788d25487eaa9a4024",
          "sha256": "ccd5a1624ee8927bc59ea1ec5078b7d67bc020dcf350123f6579952fddbd442f",
          "sha1": "ec3bedff1420812cc6e0d14615212384466c3e2d",
          "md5": "6c206ea7ef772a63a8ded61667267936"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "openrune-central-1.3-sources.jar",
          "url": "openrune-central-1.3-sources.jar",
          "size": 71905,
          "sha512": "69dc85c5d79a385096c0f70c6ac940b83c93a44651c33d02007212cc6fe7dd236e225d51d823cd52273f715f012651d10d2f8c08e08175edbe3a72bf2982a9a5",
          "sha256": "434a7d6236fe68ff139fa88835e126cb9c185c3b50a0a747a81b396c287a287b",
          "sha1": "1a77d6e16ceb6be67aa9a89526e93b6756595965",
          "md5": "accfe89ed0a0cd8a729a88f459116bbe"
        }
      ]
    }
  ]
}
