{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "filestore-tools",
    "version": "1.3.85",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-tools-1.3.85.jar",
          "url": "filestore-tools-1.3.85.jar",
          "size": 129251,
          "sha512": "e1509876bbccffbe6f649527c289ba3ab3b661ef4a1af7ba7297e78953c3c88ec79e5b51befd0b370aaa5abec81a754d463cfb8e9c78388e04082aa24b4835f9",
          "sha256": "0e065970fcab05d2a060dacda6a7ede9c895159eb4a5e26036bd476e9d2594ed",
          "sha1": "28dd6dd3108b80d066f1d8486fcda515d1fcdbfd",
          "md5": "26d7745019d2c0d3e943960258a495d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.openrune",
          "module": "filestore",
          "version": {
            "requires": "1.3.85"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.openrune",
          "module": "js5server",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.11.5"
          }
        },
        {
          "group": "cc.ekblad",
          "module": "4koma",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "com.displee",
          "module": "rs-cache-library",
          "version": {
            "requires": "7.1.5"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-file",
          "version": {
            "requires": "0.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-tools-1.3.85.jar",
          "url": "filestore-tools-1.3.85.jar",
          "size": 129251,
          "sha512": "e1509876bbccffbe6f649527c289ba3ab3b661ef4a1af7ba7297e78953c3c88ec79e5b51befd0b370aaa5abec81a754d463cfb8e9c78388e04082aa24b4835f9",
          "sha256": "0e065970fcab05d2a060dacda6a7ede9c895159eb4a5e26036bd476e9d2594ed",
          "sha1": "28dd6dd3108b80d066f1d8486fcda515d1fcdbfd",
          "md5": "26d7745019d2c0d3e943960258a495d2"
        }
      ]
    }
  ]
}
