{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "tools",
    "version": "2.0.92",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "tools-2.0.92.jar",
          "url": "tools-2.0.92.jar",
          "size": 147594,
          "sha512": "b4c1f6ea9eb1790e5f44666eedf4d569090f6520623da5a9a4d03e602396f316b8616d4a7c855a74044b1fbadc78241444622a5fa31c31c1898eec3d268ed852",
          "sha256": "970bda2f98dc20b61d8d7fb2ee927fd1a0319f9450417a22010041b6ae4d8c13",
          "sha1": "2a53f09c834578bee1b4a6ec91a43db1610530e1",
          "md5": "47fb225baa8977322bdb31b5183333f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.0.92"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.92"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.0.92"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs-fs",
          "version": {
            "requires": "2.0.92"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.openrune",
          "module": "js5server",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.11.5"
          }
        },
        {
          "group": "cc.ekblad",
          "module": "4koma",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "com.displee",
          "module": "rs-cache-library",
          "version": {
            "requires": "7.1.5"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-file",
          "version": {
            "requires": "0.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "tools-2.0.92.jar",
          "url": "tools-2.0.92.jar",
          "size": 147594,
          "sha512": "b4c1f6ea9eb1790e5f44666eedf4d569090f6520623da5a9a4d03e602396f316b8616d4a7c855a74044b1fbadc78241444622a5fa31c31c1898eec3d268ed852",
          "sha256": "970bda2f98dc20b61d8d7fb2ee927fd1a0319f9450417a22010041b6ae4d8c13",
          "sha1": "2a53f09c834578bee1b4a6ec91a43db1610530e1",
          "md5": "47fb225baa8977322bdb31b5183333f9"
        }
      ]
    }
  ]
}
