{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718",
    "version": "2.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-2.0.16.jar",
          "url": "r718-2.0.16.jar",
          "size": 13990,
          "sha512": "bdf79e29313020cbc06c9c167f80c9530471f436a5ae06cb4804b824d3527267046d1054a8c7af8fc3b613fe18407e23bf0b0ef003cc431a50f985f0dd686bf0",
          "sha256": "b7003ab7a48908dc7a81b5423d4756b7ff8b691c01a2963541e04832de7a5d2c",
          "sha1": "742f7319ef936216278bb39f435f8adb51a82f5d",
          "md5": "f78a36a3f3f66c8818a03b0a54376e46"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "r718-2.0.16.jar",
          "url": "r718-2.0.16.jar",
          "size": 13990,
          "sha512": "bdf79e29313020cbc06c9c167f80c9530471f436a5ae06cb4804b824d3527267046d1054a8c7af8fc3b613fe18407e23bf0b0ef003cc431a50f985f0dd686bf0",
          "sha256": "b7003ab7a48908dc7a81b5423d4756b7ff8b691c01a2963541e04832de7a5d2c",
          "sha1": "742f7319ef936216278bb39f435f8adb51a82f5d",
          "md5": "f78a36a3f3f66c8818a03b0a54376e46"
        }
      ]
    }
  ]
}
