{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "rs3",
    "version": "2.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "rs3-2.2.6.jar",
          "url": "rs3-2.2.6.jar",
          "size": 8746,
          "sha512": "eea47b17a258c9f6243554a268c67b10f9bf785bb11e60ee3de1844f5da693e60388f1d244d69b5752d2928caecaad695c9b22dae5c7be1117e5f82a06b0802b",
          "sha256": "a7c44aea9b8c4da16a97f677ba06dd3d4909c0e6d4c0bd0dea0c89fe040dcf1c",
          "sha1": "e84847b364f805c193ab5b5e981fe75115d29fe6",
          "md5": "0048c6ab72ae6a2ed976a65a65d484b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "rs3-2.2.6.jar",
          "url": "rs3-2.2.6.jar",
          "size": 8746,
          "sha512": "eea47b17a258c9f6243554a268c67b10f9bf785bb11e60ee3de1844f5da693e60388f1d244d69b5752d2928caecaad695c9b22dae5c7be1117e5f82a06b0802b",
          "sha256": "a7c44aea9b8c4da16a97f677ba06dd3d4909c0e6d4c0bd0dea0c89fe040dcf1c",
          "sha1": "e84847b364f805c193ab5b5e981fe75115d29fe6",
          "md5": "0048c6ab72ae6a2ed976a65a65d484b3"
        }
      ]
    }
  ]
}
