{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "definition",
    "version": "2.0.91",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "definition-2.0.91.jar",
          "url": "definition-2.0.91.jar",
          "size": 317414,
          "sha512": "746e27a1f9ce122ab61bb4fc5c5053b01bcd5589adc2eb3f19cea55e5045ffbb11fddba43e011900ac4c72c395f1b7f5616f12a2e22453d001318d3507aad460",
          "sha256": "fd860bb21d12ef73a11196dd0fb1e451fb14e2864039de69a5db285c4c56c80a",
          "sha1": "e8004813091d6442c03ba646b34768b57a2a0268",
          "md5": "cb531cbd4a790ef722974b3de96cfb35"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0-Beta1"
          }
        }
      ],
      "files": [
        {
          "name": "definition-2.0.91.jar",
          "url": "definition-2.0.91.jar",
          "size": 317414,
          "sha512": "746e27a1f9ce122ab61bb4fc5c5053b01bcd5589adc2eb3f19cea55e5045ffbb11fddba43e011900ac4c72c395f1b7f5616f12a2e22453d001318d3507aad460",
          "sha256": "fd860bb21d12ef73a11196dd0fb1e451fb14e2864039de69a5db285c4c56c80a",
          "sha1": "e8004813091d6442c03ba646b34768b57a2a0268",
          "md5": "cb531cbd4a790ef722974b3de96cfb35"
        }
      ]
    }
  ]
}
