{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filesystem",
    "version": "2.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filesystem-2.3.6.jar",
          "url": "filesystem-2.3.6.jar",
          "size": 51650,
          "sha512": "8a8bff1ad3ab0731d0b7455d21c8032920c190e869ae9e1fef5bd0855fc1481ae3a730fbc0d94460079235dae456db1a08d18d711aa13c70330587ef69104484",
          "sha256": "9d839e6bc1bf0b8d88a407e20055462335bcbb838d09e5128875a1e8f194fdbb",
          "sha1": "0d5775d040e44641a07bb5879befbd230300c16e",
          "md5": "79a74a5603f98f31c537a6e1cd38765a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "filesystem-2.3.6.jar",
          "url": "filesystem-2.3.6.jar",
          "size": 51650,
          "sha512": "8a8bff1ad3ab0731d0b7455d21c8032920c190e869ae9e1fef5bd0855fc1481ae3a730fbc0d94460079235dae456db1a08d18d711aa13c70330587ef69104484",
          "sha256": "9d839e6bc1bf0b8d88a407e20055462335bcbb838d09e5128875a1e8f194fdbb",
          "sha1": "0d5775d040e44641a07bb5879befbd230300c16e",
          "md5": "79a74a5603f98f31c537a6e1cd38765a"
        }
      ]
    }
  ]
}
