{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filestore",
    "version": "3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-3.0.3.jar",
          "url": "filestore-3.0.3.jar",
          "size": 114525,
          "sha512": "a8c308c059f2e29005c0768818eabb902e0491dba8b502492df6861da78901ee9adf33109b7326a74cbe5ecee62b97b7622ccd0206fbbc4602049f688ec8f9d7",
          "sha256": "75676548e6dd6e0d1b9b902aec2c68dd27872d4cdacc77c5a44e2eab04c11626",
          "sha1": "07bca395ac2e2696922f60bd8faa76fad90badf4",
          "md5": "b9babd19fe3b6d017ca3d110aefbd57b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-3.0.3.jar",
          "url": "filestore-3.0.3.jar",
          "size": 114525,
          "sha512": "a8c308c059f2e29005c0768818eabb902e0491dba8b502492df6861da78901ee9adf33109b7326a74cbe5ecee62b97b7622ccd0206fbbc4602049f688ec8f9d7",
          "sha256": "75676548e6dd6e0d1b9b902aec2c68dd27872d4cdacc77c5a44e2eab04c11626",
          "sha1": "07bca395ac2e2696922f60bd8faa76fad90badf4",
          "md5": "b9babd19fe3b6d017ca3d110aefbd57b"
        }
      ]
    }
  ]
}
