{
  "formatVersion": "1.1",
  "component": {
    "group": "me.filby",
    "module": "runescript-parser",
    "version": "0.0.7-openrune",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescript-parser-0.0.7-openrune.jar",
          "url": "runescript-parser-0.0.7-openrune.jar",
          "size": 221818,
          "sha512": "b25ab2b865a36893f8081e4c53ced3868e2713f247344861835719cedaa4a7aee4cf6ea4ba4ff6e8674487143d31717cb2f268eadbc6068b9fad6e042ea8971b",
          "sha256": "d7f7f076c1e90aae1c15845670fe430ea60e8178f79ff6317ec501e61a921434",
          "sha1": "de54db465fdd62b9e1b871d254b63901b55a98c1",
          "md5": "6a36e1274900199f61c1982fb110828d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.0-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescript-parser-0.0.7-openrune.jar",
          "url": "runescript-parser-0.0.7-openrune.jar",
          "size": 221818,
          "sha512": "b25ab2b865a36893f8081e4c53ced3868e2713f247344861835719cedaa4a7aee4cf6ea4ba4ff6e8674487143d31717cb2f268eadbc6068b9fad6e042ea8971b",
          "sha256": "d7f7f076c1e90aae1c15845670fe430ea60e8178f79ff6317ec501e61a921434",
          "sha1": "de54db465fdd62b9e1b871d254b63901b55a98c1",
          "md5": "6a36e1274900199f61c1982fb110828d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescript-parser-0.0.7-openrune-sources.jar",
          "url": "runescript-parser-0.0.7-openrune-sources.jar",
          "size": 69893,
          "sha512": "811ff37ccf33b489d3083c09644f5c4f74059dc3ce84ea1c15d2e87e272a76705419d891a0aadaca6bc1c79bf06593d8135f1be66c0d909b9648a58aa4a8578f",
          "sha256": "52aa1db8e1fce6ec2a769ea595569e84997735a8d171243a9a0a5264576deebc",
          "sha1": "309427b5cbe7d75a729822b9076fb8cf9010dae9",
          "md5": "36070503adc23b97f3a31ee2f7cb20a2"
        },
        {
          "name": "runescript-parser-0.0.7-openrune-sources.jar",
          "url": "runescript-parser-0.0.7-openrune-sources.jar",
          "size": 69893,
          "sha512": "811ff37ccf33b489d3083c09644f5c4f74059dc3ce84ea1c15d2e87e272a76705419d891a0aadaca6bc1c79bf06593d8135f1be66c0d909b9648a58aa4a8578f",
          "sha256": "52aa1db8e1fce6ec2a769ea595569e84997735a8d171243a9a0a5264576deebc",
          "sha1": "309427b5cbe7d75a729822b9076fb8cf9010dae9",
          "md5": "36070503adc23b97f3a31ee2f7cb20a2"
        }
      ]
    }
  ]
}
