{
  "formatVersion": "1.1",
  "component": {
    "group": "me.filby",
    "module": "runescript-parser",
    "version": "0.0.7-openrune",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescript-parser-0.0.7-openrune.jar",
          "url": "runescript-parser-0.0.7-openrune.jar",
          "size": 221818,
          "sha512": "b25ab2b865a36893f8081e4c53ced3868e2713f247344861835719cedaa4a7aee4cf6ea4ba4ff6e8674487143d31717cb2f268eadbc6068b9fad6e042ea8971b",
          "sha256": "d7f7f076c1e90aae1c15845670fe430ea60e8178f79ff6317ec501e61a921434",
          "sha1": "de54db465fdd62b9e1b871d254b63901b55a98c1",
          "md5": "6a36e1274900199f61c1982fb110828d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.0-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescript-parser-0.0.7-openrune.jar",
          "url": "runescript-parser-0.0.7-openrune.jar",
          "size": 221818,
          "sha512": "b25ab2b865a36893f8081e4c53ced3868e2713f247344861835719cedaa4a7aee4cf6ea4ba4ff6e8674487143d31717cb2f268eadbc6068b9fad6e042ea8971b",
          "sha256": "d7f7f076c1e90aae1c15845670fe430ea60e8178f79ff6317ec501e61a921434",
          "sha1": "de54db465fdd62b9e1b871d254b63901b55a98c1",
          "md5": "6a36e1274900199f61c1982fb110828d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runescript-parser-0.0.7-openrune-sources.jar",
          "url": "runescript-parser-0.0.7-openrune-sources.jar",
          "size": 69893,
          "sha512": "5e47daa1ae254ff2033f0df5bcd0ee65feed08055621000431d74a03c9e243d47b2493be1b04e869957ca7ca2b1721dff44a972fbcfc99f3f9f8aed019e7c608",
          "sha256": "137efe946cbed1bb67d25a5fce8df6843d93cd62ab2d09adb9a55c9272d5c460",
          "sha1": "ea404965c4fc05b125df36d76b1ecb55a3fe4766",
          "md5": "27b97f479e91dd6b240f83032bc93330"
        },
        {
          "name": "runescript-parser-0.0.7-openrune-sources.jar",
          "url": "runescript-parser-0.0.7-openrune-sources.jar",
          "size": 69893,
          "sha512": "5e47daa1ae254ff2033f0df5bcd0ee65feed08055621000431d74a03c9e243d47b2493be1b04e869957ca7ca2b1721dff44a972fbcfc99f3f9f8aed019e7c608",
          "sha256": "137efe946cbed1bb67d25a5fce8df6843d93cd62ab2d09adb9a55c9272d5c460",
          "sha1": "ea404965c4fc05b125df36d76b1ecb55a3fe4766",
          "md5": "27b97f479e91dd6b240f83032bc93330"
        }
      ]
    }
  ]
}
