{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.4.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.4.14.jar",
          "url": "displee-2.4.14.jar",
          "size": 111913,
          "sha512": "583487e87cabadd8f0c8fe6cf3efd2a81711201f25b48c8a1fdfedeee614b0f3026aac8621d1c48f9ea3a750a500ef5e4f96584d829532c5259fe10b0a6fb59c",
          "sha256": "4d5beb07ddbaeaca0aec30e3b1f32af3185e78ab34b2cb7a8ef1ed9586e4d4c0",
          "sha1": "9f6c9bd7d88607ad7ceb34d5db8a669a761f405b",
          "md5": "81650b5f584192c1b428f52b60c03566"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.4.14.jar",
          "url": "displee-2.4.14.jar",
          "size": 111913,
          "sha512": "583487e87cabadd8f0c8fe6cf3efd2a81711201f25b48c8a1fdfedeee614b0f3026aac8621d1c48f9ea3a750a500ef5e4f96584d829532c5259fe10b0a6fb59c",
          "sha256": "4d5beb07ddbaeaca0aec30e3b1f32af3185e78ab34b2cb7a8ef1ed9586e4d4c0",
          "sha1": "9f6c9bd7d88607ad7ceb34d5db8a669a761f405b",
          "md5": "81650b5f584192c1b428f52b60c03566"
        }
      ]
    }
  ]
}
