{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718",
    "version": "2.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-2.0.15.jar",
          "url": "r718-2.0.15.jar",
          "size": 13990,
          "sha512": "1907aa35807a678e50aac1bed66aa18117f9d62eb5e214910f0bfbe44e5cb32b487cd239d70b890a034b662176dc870e54c4271fbdbc468ec47d8662e6e98e2b",
          "sha256": "6edfb9f26b1a28afc2e249142ca47e2beb7db1179bb1b6576f6aa809197e4c41",
          "sha1": "72f2583b7b98865adb27f6f0ef5645847a72b76b",
          "md5": "fd7f86f9c5b396343f564fef2629f63d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.15"
          }
        }
      ],
      "files": [
        {
          "name": "r718-2.0.15.jar",
          "url": "r718-2.0.15.jar",
          "size": 13990,
          "sha512": "1907aa35807a678e50aac1bed66aa18117f9d62eb5e214910f0bfbe44e5cb32b487cd239d70b890a034b662176dc870e54c4271fbdbc468ec47d8662e6e98e2b",
          "sha256": "6edfb9f26b1a28afc2e249142ca47e2beb7db1179bb1b6576f6aa809197e4c41",
          "sha1": "72f2583b7b98865adb27f6f0ef5645847a72b76b",
          "md5": "fd7f86f9c5b396343f564fef2629f63d"
        }
      ]
    }
  ]
}
