{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.4.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.4.19.jar",
          "url": "displee-2.4.19.jar",
          "size": 111913,
          "sha512": "9a603f83e230ad316af2760b0170fab230bd0041d5902e38f08ebfedeff9247758aba43468d0512dac24b963f9174fb5ab63939440f42a9b1fc2477004ff3633",
          "sha256": "3f43485729aa0a38c60f45e1ea135b5d93b22479a8a6811416aae85d4ee6910c",
          "sha1": "0c2a896e7a3f20b77832c618a100fa7c99ba8543",
          "md5": "ad3eab108a79fbf78184269d506edd31"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.4.19.jar",
          "url": "displee-2.4.19.jar",
          "size": 111913,
          "sha512": "9a603f83e230ad316af2760b0170fab230bd0041d5902e38f08ebfedeff9247758aba43468d0512dac24b963f9174fb5ab63939440f42a9b1fc2477004ff3633",
          "sha256": "3f43485729aa0a38c60f45e1ea135b5d93b22479a8a6811416aae85d4ee6910c",
          "sha1": "0c2a896e7a3f20b77832c618a100fa7c99ba8543",
          "md5": "ad3eab108a79fbf78184269d506edd31"
        }
      ]
    }
  ]
}
