{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.2.3.jar",
          "url": "displee-2.2.3.jar",
          "size": 111913,
          "sha512": "876d43a9574db44fab224802f3639c1714140ffb4318fcddfe7fef0c3c7626792c035456e3cd6f0dd68dbb50b0a3458cffab5ca3785836dd409222e0099e9e81",
          "sha256": "01d9085355c452ec8ee3f82b6ed9dedb46816c0feac2e1d075f6e8f36c487a1f",
          "sha1": "f09e8965b061b42c9fb2acdaea60c85915bffaf5",
          "md5": "926ba46b83ca4b5e7645418ca236ff62"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.2.3.jar",
          "url": "displee-2.2.3.jar",
          "size": 111913,
          "sha512": "876d43a9574db44fab224802f3639c1714140ffb4318fcddfe7fef0c3c7626792c035456e3cd6f0dd68dbb50b0a3458cffab5ca3785836dd409222e0099e9e81",
          "sha256": "01d9085355c452ec8ee3f82b6ed9dedb46816c0feac2e1d075f6e8f36c487a1f",
          "sha1": "f09e8965b061b42c9fb2acdaea60c85915bffaf5",
          "md5": "926ba46b83ca4b5e7645418ca236ff62"
        }
      ]
    }
  ]
}
