{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs",
    "version": "2.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-2.3.7.jar",
          "url": "osrs-2.3.7.jar",
          "size": 84163,
          "sha512": "539a3a4eec0e3ee2d7ca1ae8a7b21a242340a3f09bd110077021c2080636a43b4726293b839a1c8f684edcffc9c806c7d12616d17a629c2e51e77129a3ea2008",
          "sha256": "956e8ab5c2da73be7de4c92aeb47080cbe4cc8348ce9c970c924e7be05f306cf",
          "sha1": "9c52f0b3986c700645770c2566e7265202766e44",
          "md5": "67a7ce5809424a5b08571dc141bef42a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-2.3.7.jar",
          "url": "osrs-2.3.7.jar",
          "size": 84163,
          "sha512": "539a3a4eec0e3ee2d7ca1ae8a7b21a242340a3f09bd110077021c2080636a43b4726293b839a1c8f684edcffc9c806c7d12616d17a629c2e51e77129a3ea2008",
          "sha256": "956e8ab5c2da73be7de4c92aeb47080cbe4cc8348ce9c970c924e7be05f306cf",
          "sha1": "9c52f0b3986c700645770c2566e7265202766e44",
          "md5": "67a7ce5809424a5b08571dc141bef42a"
        }
      ]
    }
  ]
}
