{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs",
    "version": "2.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-2.3.7.jar",
          "url": "osrs-2.3.7.jar",
          "size": 84172,
          "sha512": "16dffb3eb710b9689bb927dbb4a5e872aa19c73771e9c4b56b68b298a3bc94e334fcdafad4dd80a7e7f3b8fa53a1f5feb41fe1119923cde3d97d60b5a6cfbcf0",
          "sha256": "9aa377eaf992b7dbd2ea4e8f72ffdb50940e4ad88cda1e5b57ebdebeb1b6d4f7",
          "sha1": "8af8139ab3d368d53257652f944dc614fa3b35b8",
          "md5": "026c30b44dcb2e43b3078ab1e62257e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-2.3.7.jar",
          "url": "osrs-2.3.7.jar",
          "size": 84172,
          "sha512": "16dffb3eb710b9689bb927dbb4a5e872aa19c73771e9c4b56b68b298a3bc94e334fcdafad4dd80a7e7f3b8fa53a1f5feb41fe1119923cde3d97d60b5a6cfbcf0",
          "sha256": "9aa377eaf992b7dbd2ea4e8f72ffdb50940e4ad88cda1e5b57ebdebeb1b6d4f7",
          "sha1": "8af8139ab3d368d53257652f944dc614fa3b35b8",
          "md5": "026c30b44dcb2e43b3078ab1e62257e8"
        }
      ]
    }
  ]
}
