{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs-fs",
    "version": "2.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-fs-2.0.6.jar",
          "url": "osrs-fs-2.0.6.jar",
          "size": 22442,
          "sha512": "c472d47f8b4f79df768bdc6c55122fffb5bff392d773d534b408a0249eb61b96ce850283a1453d51c226efd361b9fd76a12192ceb5e9d0d294bfe2356d4c4c0b",
          "sha256": "42ed572a7441377448e48b3f4015102affcb1ccbabfe3ab970c1f4333d6dea7a",
          "sha1": "265f8f5f515fde5e807b136e94ca7ef67173177a",
          "md5": "232c1e23d6c022fca9918af15504d12d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-fs-2.0.6.jar",
          "url": "osrs-fs-2.0.6.jar",
          "size": 22442,
          "sha512": "c472d47f8b4f79df768bdc6c55122fffb5bff392d773d534b408a0249eb61b96ce850283a1453d51c226efd361b9fd76a12192ceb5e9d0d294bfe2356d4c4c0b",
          "sha256": "42ed572a7441377448e48b3f4015102affcb1ccbabfe3ab970c1f4333d6dea7a",
          "sha1": "265f8f5f515fde5e807b136e94ca7ef67173177a",
          "md5": "232c1e23d6c022fca9918af15504d12d"
        }
      ]
    }
  ]
}
