{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718",
    "version": "2.0.90",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-2.0.90.jar",
          "url": "r718-2.0.90.jar",
          "size": 14003,
          "sha512": "144faf04574dc4f50c06478c31008c4257fe303d1aed46666bb0cd2a1ebf9210de35a1b29c63252464602130d25e614053b8b3e702f5d68e55204c7f0c0bd86a",
          "sha256": "a6b66530bdcd073aa7bbb0839931358ea9fbd3aed325b82aca07425d4615d095",
          "sha1": "81128e47d2c60c65ecd8628adf72c4fecc8bcd3c",
          "md5": "535f58cca933520080fe6f378006e643"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.90"
          }
        }
      ],
      "files": [
        {
          "name": "r718-2.0.90.jar",
          "url": "r718-2.0.90.jar",
          "size": 14003,
          "sha512": "144faf04574dc4f50c06478c31008c4257fe303d1aed46666bb0cd2a1ebf9210de35a1b29c63252464602130d25e614053b8b3e702f5d68e55204c7f0c0bd86a",
          "sha256": "a6b66530bdcd073aa7bbb0839931358ea9fbd3aed325b82aca07425d4615d095",
          "sha1": "81128e47d2c60c65ecd8628adf72c4fecc8bcd3c",
          "md5": "535f58cca933520080fe6f378006e643"
        }
      ]
    }
  ]
}
