{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs-fs",
    "version": "2.0.16.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-fs-2.0.16.1.jar",
          "url": "osrs-fs-2.0.16.1.jar",
          "size": 22443,
          "sha512": "ef1ed70d920712bd6dfc2cd4d98e69e75633a9090cdca54bb1c168dfa0d423b747967c265e01d7d5fd1e3975af42c8395674697218f516a1f955fa3b76ac83f9",
          "sha256": "2b79a6e47b2251527604e32d88c5dd6ee2d24eb5a937c34b5fd3827d8abff13f",
          "sha1": "dd0f6f759594385ee980704dbaac3e870e9f07cc",
          "md5": "b36798fe3ad5acf31e22f66f53cafd2d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.0.16.1"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.0.16.1"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.0.16.1"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-fs-2.0.16.1.jar",
          "url": "osrs-fs-2.0.16.1.jar",
          "size": 22443,
          "sha512": "ef1ed70d920712bd6dfc2cd4d98e69e75633a9090cdca54bb1c168dfa0d423b747967c265e01d7d5fd1e3975af42c8395674697218f516a1f955fa3b76ac83f9",
          "sha256": "2b79a6e47b2251527604e32d88c5dd6ee2d24eb5a937c34b5fd3827d8abff13f",
          "sha1": "dd0f6f759594385ee980704dbaac3e870e9f07cc",
          "md5": "b36798fe3ad5acf31e22f66f53cafd2d"
        }
      ]
    }
  ]
}
