{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filesystem",
    "version": "2.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filesystem-2.4.1.jar",
          "url": "filesystem-2.4.1.jar",
          "size": 51650,
          "sha512": "4cb2c92aa83bda45667baa6dfb590e23ca423716dbd195b68336093b52a6be77f04ead5655bc19d5f1edf1edeafa45e4cda91093b6e441db7e4efe0dd50bfca1",
          "sha256": "991c0a35119817993e0ed3eb926585324bcdf41b48207024267bfd7e64e6878f",
          "sha1": "b1e65626c94634fed7063e3fef86ee06073d6f5f",
          "md5": "028e7c5ac4132dd6940c000b75f8bc8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "filesystem-2.4.1.jar",
          "url": "filesystem-2.4.1.jar",
          "size": 51650,
          "sha512": "4cb2c92aa83bda45667baa6dfb590e23ca423716dbd195b68336093b52a6be77f04ead5655bc19d5f1edf1edeafa45e4cda91093b6e441db7e4efe0dd50bfca1",
          "sha256": "991c0a35119817993e0ed3eb926585324bcdf41b48207024267bfd7e64e6878f",
          "sha1": "b1e65626c94634fed7063e3fef86ee06073d6f5f",
          "md5": "028e7c5ac4132dd6940c000b75f8bc8e"
        }
      ]
    }
  ]
}
