{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "central-common",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-common-1.3.1.jar",
          "url": "central-common-1.3.1.jar",
          "size": 206634,
          "sha512": "e8cfd3e54ce55341d7b72cf950a4a2c35778e22f0d62ccd3759d6a68d8f90bb0020df0c0d37de7a37fd4064386a640d64cbf11395efced532da17b06d6f6f376",
          "sha256": "490b27ac439438007302725fdf4bf7b3dd1168a6a5f99850dc8eb5b8134f18a6",
          "sha1": "e02fc10bfc6e95c989d5dc905353233756adb36b",
          "md5": "b939daa4c88ca8a6ad353caa5978c94d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "central-common-1.3.1.jar",
          "url": "central-common-1.3.1.jar",
          "size": 206634,
          "sha512": "e8cfd3e54ce55341d7b72cf950a4a2c35778e22f0d62ccd3759d6a68d8f90bb0020df0c0d37de7a37fd4064386a640d64cbf11395efced532da17b06d6f6f376",
          "sha256": "490b27ac439438007302725fdf4bf7b3dd1168a6a5f99850dc8eb5b8134f18a6",
          "sha1": "e02fc10bfc6e95c989d5dc905353233756adb36b",
          "md5": "b939daa4c88ca8a6ad353caa5978c94d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "central-common-1.3.1-sources.jar",
          "url": "central-common-1.3.1-sources.jar",
          "size": 51249,
          "sha512": "3d7a3a51a12ea74cca2019b60e79457a0e4a89f7362fc6a1a2228d8a1911e6ae6d8551b70706d1b70aed4015da6e1c8b82062da90158db0a013abadd5d7092b7",
          "sha256": "8a63e07986d6d2800beef500c0f64ccc48f2df09d1c7af2078155c0e0efa9198",
          "sha1": "0c6b1e9b87742e10c6520edb45615b6412ff6803",
          "md5": "1e77802d9f3758b49da83359c452391a"
        }
      ]
    }
  ]
}
