{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "definition",
    "version": "2.4.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "definition-2.4.16.jar",
          "url": "definition-2.4.16.jar",
          "size": 537810,
          "sha512": "d51427bb4f9f230f7b9a2e190cbc7aa31881edb1afa4a81f26be6a99895774b7a4db7d037423d5982c9d036360d48b61c9ca73fbae8de58da307c2d2b0a3b7f1",
          "sha256": "7d6514618bbf2f464699e809737973df6fa3af54f22eb3590a37d2209014d37a",
          "sha1": "0d4709073bccead0b22b333d57982aada4823023",
          "md5": "6b29d1d4de4d4e21a7c8bd05be6effa6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "toml-core",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "definition-2.4.16.jar",
          "url": "definition-2.4.16.jar",
          "size": 537810,
          "sha512": "d51427bb4f9f230f7b9a2e190cbc7aa31881edb1afa4a81f26be6a99895774b7a4db7d037423d5982c9d036360d48b61c9ca73fbae8de58da307c2d2b0a3b7f1",
          "sha256": "7d6514618bbf2f464699e809737973df6fa3af54f22eb3590a37d2209014d37a",
          "sha1": "0d4709073bccead0b22b333d57982aada4823023",
          "md5": "6b29d1d4de4d4e21a7c8bd05be6effa6"
        }
      ]
    }
  ]
}
