{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718",
    "version": "2.0.92",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-2.0.92.jar",
          "url": "r718-2.0.92.jar",
          "size": 14003,
          "sha512": "bc2507c5845caca0962082d535a51f07c2e6fc1ac4941e878018d98fb6a32b04bb6c41cc9af351f8e5711226131b0619d607c474fdb676271fe779d9f334a97f",
          "sha256": "4f33b00df87c4fb573900505fe994c1f45aaa26d82f5b701987519a94abbf47c",
          "sha1": "ba4b72aa195fd79b69d469cfe769d70362fc298b",
          "md5": "789da52c445d287377eb0ced78b9529b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.92"
          }
        }
      ],
      "files": [
        {
          "name": "r718-2.0.92.jar",
          "url": "r718-2.0.92.jar",
          "size": 14003,
          "sha512": "bc2507c5845caca0962082d535a51f07c2e6fc1ac4941e878018d98fb6a32b04bb6c41cc9af351f8e5711226131b0619d607c474fdb676271fe779d9f334a97f",
          "sha256": "4f33b00df87c4fb573900505fe994c1f45aaa26d82f5b701987519a94abbf47c",
          "sha1": "ba4b72aa195fd79b69d469cfe769d70362fc298b",
          "md5": "789da52c445d287377eb0ced78b9529b"
        }
      ]
    }
  ]
}
