{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718-fs",
    "version": "2.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-fs-2.0.4.jar",
          "url": "r718-fs-2.0.4.jar",
          "size": 7586,
          "sha512": "6a15b8a9508c4ac8b60fb4a65e8f263933afe712435d9d9691d853e649dde6b1375b3cb81a021bdce9eff08b03557ddfb8c73ae4f7d298ea8d6cd6d1c3a560ab",
          "sha256": "477cc8e017daef1dfd1c7f33beca4f86a11ccf09222604bbef33dd4fde07dae7",
          "sha1": "611e01ed844103b843cfad7840daa544ad8d5022",
          "md5": "0ee8f6f02946ee85937f5473ae0902de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "dev.or2",
          "module": "r718",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "r718-fs-2.0.4.jar",
          "url": "r718-fs-2.0.4.jar",
          "size": 7586,
          "sha512": "6a15b8a9508c4ac8b60fb4a65e8f263933afe712435d9d9691d853e649dde6b1375b3cb81a021bdce9eff08b03557ddfb8c73ae4f7d298ea8d6cd6d1c3a560ab",
          "sha256": "477cc8e017daef1dfd1c7f33beca4f86a11ccf09222604bbef33dd4fde07dae7",
          "sha1": "611e01ed844103b843cfad7840daa544ad8d5022",
          "md5": "0ee8f6f02946ee85937f5473ae0902de"
        }
      ]
    }
  ]
}
