{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "definition",
    "version": "2.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "definition-2.3.5.jar",
          "url": "definition-2.3.5.jar",
          "size": 404242,
          "sha512": "a238b547fb222e5167cbe2fc8aeb7fff9433e45506e64b7073f9dc73cfd554c41310e881e2d9f03f3bba67b582bac582d4070fa71f2481ed4492dd7b664b2c72",
          "sha256": "124144220211478b433db5a63b11fe9c10c4ab412d630be85fbb6123f13b255c",
          "sha1": "6179572bd97742d806e87125a7728d2077572962",
          "md5": "e071e3b394a57e9541ff2555fc3b52b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        }
      ],
      "files": [
        {
          "name": "definition-2.3.5.jar",
          "url": "definition-2.3.5.jar",
          "size": 404242,
          "sha512": "a238b547fb222e5167cbe2fc8aeb7fff9433e45506e64b7073f9dc73cfd554c41310e881e2d9f03f3bba67b582bac582d4070fa71f2481ed4492dd7b664b2c72",
          "sha256": "124144220211478b433db5a63b11fe9c10c4ab412d630be85fbb6123f13b255c",
          "sha1": "6179572bd97742d806e87125a7728d2077572962",
          "md5": "e071e3b394a57e9541ff2555fc3b52b4"
        }
      ]
    }
  ]
}
