{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "js5server",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "js5server-1.0.6.jar",
          "url": "js5server-1.0.6.jar",
          "size": 62266,
          "sha512": "52e29e91b8911ba97103d04cb2fe6d4389646592566fbfced75456c3875daf684674573369ce3117726b54ac6fa69016bfb14469dd2c65f588511dbbf940fd59",
          "sha256": "dfbd9d1846bb075e718d07c611102d1a1597e7eb9aa56832c596aafd22c2414f",
          "sha1": "8368dc4a0aad01c556f04cf7d8e7af97f5c433c3",
          "md5": "f0413926764e4d9b397ea345a791cd23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.12"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-native-epoll",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-native-kqueue",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-transport-native-io_uring",
          "version": {
            "requires": "0.0.25.Final"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "org.jctools",
          "module": "jctools-core",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "com.displee",
          "module": "rs-cache-library",
          "version": {
            "requires": "7.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.12"
          }
        }
      ],
      "files": [
        {
          "name": "js5server-1.0.6.jar",
          "url": "js5server-1.0.6.jar",
          "size": 62266,
          "sha512": "52e29e91b8911ba97103d04cb2fe6d4389646592566fbfced75456c3875daf684674573369ce3117726b54ac6fa69016bfb14469dd2c65f588511dbbf940fd59",
          "sha256": "dfbd9d1846bb075e718d07c611102d1a1597e7eb9aa56832c596aafd22c2414f",
          "sha1": "8368dc4a0aad01c556f04cf7d8e7af97f5c433c3",
          "md5": "f0413926764e4d9b397ea345a791cd23"
        }
      ]
    }
  ]
}
