{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718-fs",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-fs-2.4.0.jar",
          "url": "r718-fs-2.4.0.jar",
          "size": 7588,
          "sha512": "ff4ffc7af8375e92b99d0ca0d64ed48541bdec72ef07f0967380bee1a1bb1f8468190ae53a495359ffb6b5c95c1db5ba335662363a12273cc775c0bb45105bf9",
          "sha256": "fa1da07becffff71e5e68746fd79beaacf9a3cb9302535cda2683488ec4c6d75",
          "sha1": "325151a3244682431b48ea8b949ca9a5f304f98a",
          "md5": "b95b03ebed79eaa97446f8f8485c90bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "dev.or2",
          "module": "r718",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "r718-fs-2.4.0.jar",
          "url": "r718-fs-2.4.0.jar",
          "size": 7588,
          "sha512": "ff4ffc7af8375e92b99d0ca0d64ed48541bdec72ef07f0967380bee1a1bb1f8468190ae53a495359ffb6b5c95c1db5ba335662363a12273cc775c0bb45105bf9",
          "sha256": "fa1da07becffff71e5e68746fd79beaacf9a3cb9302535cda2683488ec4c6d75",
          "sha1": "325151a3244682431b48ea8b949ca9a5f304f98a",
          "md5": "b95b03ebed79eaa97446f8f8485c90bd"
        }
      ]
    }
  ]
}
