{
  "formatVersion": "1.1",
  "component": {
    "group": "cc.ekblad",
    "module": "4koma",
    "version": "1.2.2-openrune",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "4koma-1.2.2-openrune.jar",
          "url": "4koma-1.2.2-openrune.jar",
          "size": 442840,
          "sha512": "14b8c5ac408c298e197c588db2e895486499d2180bea2e61b9bfb1e46138bb63a364e210fdad90b61c04fffe0e1efe7c3a9621076ebfbfbdff1ec86fccc40ee1",
          "sha256": "52d6b37728472de67dc6e42c72b4f54fd6d06f1a36c24908f36a0c4af5e641ec",
          "sha1": "1499c04ee52a1b79816e7396f999a8bd0257eab0",
          "md5": "5e6f7c217e1e565fbf3cdf88c3afe949"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "cc.ekblad.konbini",
          "module": "konbini",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "4koma-1.2.2-openrune.jar",
          "url": "4koma-1.2.2-openrune.jar",
          "size": 442840,
          "sha512": "14b8c5ac408c298e197c588db2e895486499d2180bea2e61b9bfb1e46138bb63a364e210fdad90b61c04fffe0e1efe7c3a9621076ebfbfbdff1ec86fccc40ee1",
          "sha256": "52d6b37728472de67dc6e42c72b4f54fd6d06f1a36c24908f36a0c4af5e641ec",
          "sha1": "1499c04ee52a1b79816e7396f999a8bd0257eab0",
          "md5": "5e6f7c217e1e565fbf3cdf88c3afe949"
        }
      ]
    }
  ]
}
