{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "opcode",
    "version": "2.4.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "opcode-2.4.12.jar",
          "url": "opcode-2.4.12.jar",
          "size": 127117,
          "sha512": "4e328a2b469ae7cb2688a57ad829fe25e1a72ad115d00da686a5f2192bec1616964ac677f7bce94c13546a5ded4c9ba00903deeb38b1d45b9a24a78066ea4efa",
          "sha256": "5dd2278063a9a26b92610cef3ffdc4ef5f5cc31a9ddf09439fa54bd8aa8ca017",
          "sha1": "70a3fc0443a69534c0061e10621c8e66599d2787",
          "md5": "8a5d096bdfe452e0793bd7d6765659dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.12"
          }
        }
      ],
      "files": [
        {
          "name": "opcode-2.4.12.jar",
          "url": "opcode-2.4.12.jar",
          "size": 127117,
          "sha512": "4e328a2b469ae7cb2688a57ad829fe25e1a72ad115d00da686a5f2192bec1616964ac677f7bce94c13546a5ded4c9ba00903deeb38b1d45b9a24a78066ea4efa",
          "sha256": "5dd2278063a9a26b92610cef3ffdc4ef5f5cc31a9ddf09439fa54bd8aa8ca017",
          "sha1": "70a3fc0443a69534c0061e10621c8e66599d2787",
          "md5": "8a5d096bdfe452e0793bd7d6765659dc"
        }
      ]
    }
  ]
}
