{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filestore",
    "version": "2.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-2.0.8.jar",
          "url": "filestore-2.0.8.jar",
          "size": 23553,
          "sha512": "caecd27632a9f812ecc696393fe07cc87786c57d249a1152f2e3fd3e9c4cf3990ddddf2b3b367a648e3348fd994f0ff0d2df5070a37d7860dd0ed03fde726d09",
          "sha256": "019db7e9e3433fa90934a9c45855c55d1b20bdbb023768648c704e597de97083",
          "sha1": "629f02c96f3b4c9ee7a9e88c54f789ee12be3d3b",
          "md5": "75dc152cc979357e073120f6c4b6042e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.8"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-2.0.8.jar",
          "url": "filestore-2.0.8.jar",
          "size": 23553,
          "sha512": "caecd27632a9f812ecc696393fe07cc87786c57d249a1152f2e3fd3e9c4cf3990ddddf2b3b367a648e3348fd994f0ff0d2df5070a37d7860dd0ed03fde726d09",
          "sha256": "019db7e9e3433fa90934a9c45855c55d1b20bdbb023768648c704e597de97083",
          "sha1": "629f02c96f3b4c9ee7a9e88c54f789ee12be3d3b",
          "md5": "75dc152cc979357e073120f6c4b6042e"
        }
      ]
    }
  ]
}
