{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "bootstrap",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "bootstrap-1.0.jar",
          "url": "bootstrap-1.0.jar",
          "size": 87811,
          "sha512": "50108314dd9144c95264313f65c4d65fe46c3d7f961c5664384da2c63a804e252289de7faf908191e72c7cd552f00e90cd361a916ac9f17c2e05b6ba54f3493a",
          "sha256": "179b333fc97634443bfd9f54cad6d672b4f3674c7a8b46708cc791b28402758a",
          "sha1": "68c89d6110029e4efe06aaa0240f5bbd56abc45b",
          "md5": "570f4a337f8735dbbd7ea33fc71eb08f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.2"
          }
        },
        {
          "group": "com.beust",
          "module": "klaxon",
          "version": {
            "requires": "5.5"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.9.0.202403050737-r"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.11"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "commons-net",
          "module": "commons-net",
          "version": {
            "requires": "3.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "bootstrap-1.0.jar",
          "url": "bootstrap-1.0.jar",
          "size": 87811,
          "sha512": "50108314dd9144c95264313f65c4d65fe46c3d7f961c5664384da2c63a804e252289de7faf908191e72c7cd552f00e90cd361a916ac9f17c2e05b6ba54f3493a",
          "sha256": "179b333fc97634443bfd9f54cad6d672b4f3674c7a8b46708cc791b28402758a",
          "sha1": "68c89d6110029e4efe06aaa0240f5bbd56abc45b",
          "md5": "570f4a337f8735dbbd7ea33fc71eb08f"
        }
      ]
    }
  ]
}
