{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs-fs",
    "version": "2.0.91",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-fs-2.0.91.jar",
          "url": "osrs-fs-2.0.91.jar",
          "size": 22442,
          "sha512": "636f93cf1ee352aee94f6c1b972ab6753403a8875cb14bb55a3efa928022326910b58d77367bd527a2f36ebba75f361d9b4b4443c5bd93e3e83e510d979ae983",
          "sha256": "963250963f328c7a77af3599599b32b4bda8bc1fd134b5ed5d42e0f62e1bafea",
          "sha1": "2d65bb90528deb154853053aa8cb2210246b8a09",
          "md5": "c7dd5b5d8a97b12f27e618d68e13e54d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.0.91"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.0.91"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.0.91"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.91"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-fs-2.0.91.jar",
          "url": "osrs-fs-2.0.91.jar",
          "size": 22442,
          "sha512": "636f93cf1ee352aee94f6c1b972ab6753403a8875cb14bb55a3efa928022326910b58d77367bd527a2f36ebba75f361d9b4b4443c5bd93e3e83e510d979ae983",
          "sha256": "963250963f328c7a77af3599599b32b4bda8bc1fd134b5ed5d42e0f62e1bafea",
          "sha1": "2d65bb90528deb154853053aa8cb2210246b8a09",
          "md5": "c7dd5b5d8a97b12f27e618d68e13e54d"
        }
      ]
    }
  ]
}
