{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs-fs",
    "version": "2.0.90",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-fs-2.0.90.jar",
          "url": "osrs-fs-2.0.90.jar",
          "size": 22442,
          "sha512": "3cca435507a8a86e75b0b3a87de8e886502052b57d9e8ac03e05fe01c4bf02546cf49e46a4f360bba92dd24e7fd2f512212208a5de51810f6d620d6f269d3ce8",
          "sha256": "332d9bbac9f942de3f815ae0218feb2b8ae219aa0a15b23166438005b62a0299",
          "sha1": "7366b444833b641ec6d6ee4e8d2eb72ff629087e",
          "md5": "c86f1b6e3c377591566b8ef6f5f14dc3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.0.90"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.0.90"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.0.90"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.90"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-fs-2.0.90.jar",
          "url": "osrs-fs-2.0.90.jar",
          "size": 22442,
          "sha512": "3cca435507a8a86e75b0b3a87de8e886502052b57d9e8ac03e05fe01c4bf02546cf49e46a4f360bba92dd24e7fd2f512212208a5de51810f6d620d6f269d3ce8",
          "sha256": "332d9bbac9f942de3f815ae0218feb2b8ae219aa0a15b23166438005b62a0299",
          "sha1": "7366b444833b641ec6d6ee4e8d2eb72ff629087e",
          "md5": "c86f1b6e3c377591566b8ef6f5f14dc3"
        }
      ]
    }
  ]
}
