{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.1.jar",
          "url": "displee-2.1.jar",
          "size": 111913,
          "sha512": "a29031dbf373fcf0a989ecb01c90b0e95506d8af96f49191ce3dcb400cd794397ff1f7bd17a4fae9af5b5be96701555b54705a0a4b469c50dceebe7c680e8f1f",
          "sha256": "8db94848557dec5d5cc50049c9456b3df84c5650376cb40f9489da3e251c3cc2",
          "sha1": "2028490d0c032ee2ecffa930014c8cced78e86df",
          "md5": "d911894914a72685318301746f1e54c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.1.jar",
          "url": "displee-2.1.jar",
          "size": 111913,
          "sha512": "a29031dbf373fcf0a989ecb01c90b0e95506d8af96f49191ce3dcb400cd794397ff1f7bd17a4fae9af5b5be96701555b54705a0a4b469c50dceebe7c680e8f1f",
          "sha256": "8db94848557dec5d5cc50049c9456b3df84c5650376cb40f9489da3e251c3cc2",
          "sha1": "2028490d0c032ee2ecffa930014c8cced78e86df",
          "md5": "d911894914a72685318301746f1e54c5"
        }
      ]
    }
  ]
}
