{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "rs3",
    "version": "2.4.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "rs3-2.4.16.jar",
          "url": "rs3-2.4.16.jar",
          "size": 8903,
          "sha512": "25e06d3ebeefa0242fb723a7dd00142e6667e4fd5ff966b0fc25b5d15fedc87e93de81f4ae0cdfe1766a17468cd8f727ce3d4fd012c80e3251e0afc697689502",
          "sha256": "4d09e808c26a703f08790235b4025445b4f74f08fac14119912d3dbcdebb8879",
          "sha1": "25e4baf2053fdcebac2942b2e2e1820d70431fa8",
          "md5": "048665477f8c498e34becba7096cd114"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.16"
          }
        }
      ],
      "files": [
        {
          "name": "rs3-2.4.16.jar",
          "url": "rs3-2.4.16.jar",
          "size": 8903,
          "sha512": "25e06d3ebeefa0242fb723a7dd00142e6667e4fd5ff966b0fc25b5d15fedc87e93de81f4ae0cdfe1766a17468cd8f727ce3d4fd012c80e3251e0afc697689502",
          "sha256": "4d09e808c26a703f08790235b4025445b4f74f08fac14119912d3dbcdebb8879",
          "sha1": "25e4baf2053fdcebac2942b2e2e1820d70431fa8",
          "md5": "048665477f8c498e34becba7096cd114"
        }
      ]
    }
  ]
}
