{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.0.16.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.0.16.3.jar",
          "url": "displee-2.0.16.3.jar",
          "size": 111913,
          "sha512": "85a201f00964384ce9246000ebb34bd290d4f5bc592f359686808b663926488806d885a12482e5544a45e21df30a7458bfe857fd1d85e6037c456aa0906a71b5",
          "sha256": "b814c17b861fcc6c28a71e59a59f5aee69465fe479b2223e32b9cfefb68f4b92",
          "sha1": "338eeccd7ceeadb69a5f3ef2ed8d019e5d31affd",
          "md5": "5fb8bed75753123c406e298b1ec495a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.0.16.3.jar",
          "url": "displee-2.0.16.3.jar",
          "size": 111913,
          "sha512": "85a201f00964384ce9246000ebb34bd290d4f5bc592f359686808b663926488806d885a12482e5544a45e21df30a7458bfe857fd1d85e6037c456aa0906a71b5",
          "sha256": "b814c17b861fcc6c28a71e59a59f5aee69465fe479b2223e32b9cfefb68f4b92",
          "sha1": "338eeccd7ceeadb69a5f3ef2ed8d019e5d31affd",
          "md5": "5fb8bed75753123c406e298b1ec495a3"
        }
      ]
    }
  ]
}
