{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs-fs",
    "version": "2.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-fs-2.2.9.jar",
          "url": "osrs-fs-2.2.9.jar",
          "size": 21519,
          "sha512": "b8b4cf2ebfe39ff0920cf79f73fa94a97bfddb92b50d6e3a5b1bdd7cac24c790ac82f026172f31aa2f7c7cbe68ace4facd924ecb0229f93a1f8eb77b546cf78c",
          "sha256": "9269e98a708501fc2a3551a2cacdf6734e9b0cd2c717924591d2790b82a184a6",
          "sha1": "bfc21c18b7105f6e849103871083e1e84db3795c",
          "md5": "0cbfac6cf278f8b90645cc49bbe0acf4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.2.9"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.2.9"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.2.9"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.2.9"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-fs-2.2.9.jar",
          "url": "osrs-fs-2.2.9.jar",
          "size": 21519,
          "sha512": "b8b4cf2ebfe39ff0920cf79f73fa94a97bfddb92b50d6e3a5b1bdd7cac24c790ac82f026172f31aa2f7c7cbe68ace4facd924ecb0229f93a1f8eb77b546cf78c",
          "sha256": "9269e98a708501fc2a3551a2cacdf6734e9b0cd2c717924591d2790b82a184a6",
          "sha1": "bfc21c18b7105f6e849103871083e1e84db3795c",
          "md5": "0cbfac6cf278f8b90645cc49bbe0acf4"
        }
      ]
    }
  ]
}
