{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filesystem",
    "version": "2.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filesystem-2.4.6.jar",
          "url": "filesystem-2.4.6.jar",
          "size": 51650,
          "sha512": "74d9a98206fa9393818e94d2cb2615eba030870711c85a2ba715e664c66fdad29a7e8746fa5e0cd900593ea033480fedcc52cb35fcc5b1dfe6e2d915a6db8b89",
          "sha256": "73587ddf3fb225493e908332ad8fe4585ecef28fbe700fc206fd5ff7db4c2ad1",
          "sha1": "90c67cdb308064dc6533d7c0fbfea95fb2ea7b4f",
          "md5": "44fef27b6b755d2481559729c81a276e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "filesystem-2.4.6.jar",
          "url": "filesystem-2.4.6.jar",
          "size": 51650,
          "sha512": "74d9a98206fa9393818e94d2cb2615eba030870711c85a2ba715e664c66fdad29a7e8746fa5e0cd900593ea033480fedcc52cb35fcc5b1dfe6e2d915a6db8b89",
          "sha256": "73587ddf3fb225493e908332ad8fe4585ecef28fbe700fc206fd5ff7db4c2ad1",
          "sha1": "90c67cdb308064dc6533d7c0fbfea95fb2ea7b4f",
          "md5": "44fef27b6b755d2481559729c81a276e"
        }
      ]
    }
  ]
}
