{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs-fs",
    "version": "2.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-fs-2.0.11.jar",
          "url": "osrs-fs-2.0.11.jar",
          "size": 23585,
          "sha512": "290502055d1b31521706a0b443a606ffdc2a6f16353df1b72a18a8ad3623670cb75438e249412b6f6f3c60176c0f75d4fd0b4b6401079caf7e5889a1d043f55b",
          "sha256": "2d2980641ca2f8a211e308ba87b5f6ff909f40e11c2ed2e28f8075115aab18bb",
          "sha1": "40eb45e638e9fd83597219c6f2095bb6f3c878f6",
          "md5": "c09286de70d91edabfd46e27dbfaf094"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.0.11"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.0.11"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.0.11"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.11"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-fs-2.0.11.jar",
          "url": "osrs-fs-2.0.11.jar",
          "size": 23585,
          "sha512": "290502055d1b31521706a0b443a606ffdc2a6f16353df1b72a18a8ad3623670cb75438e249412b6f6f3c60176c0f75d4fd0b4b6401079caf7e5889a1d043f55b",
          "sha256": "2d2980641ca2f8a211e308ba87b5f6ff909f40e11c2ed2e28f8075115aab18bb",
          "sha1": "40eb45e638e9fd83597219c6f2095bb6f3c878f6",
          "md5": "c09286de70d91edabfd46e27dbfaf094"
        }
      ]
    }
  ]
}
