{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "filestore",
    "version": "1.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-1.3.2.jar",
          "url": "filestore-1.3.2.jar",
          "size": 258075,
          "sha512": "b21ece6feb82a41e1a9447f2cc8d7e5d5d3216d1a3d8d70a027a78d34e9b2ac04f90b4f7f4317900399d482ffffab9aa4c45d1e3d5bc05832d08bebe3bca6d4e",
          "sha256": "d83041e1d0e79c7b8d768826f761b4142c3a88fae8b1042b54a96c27e3c7165a",
          "sha1": "484dc73be2be56b9d5c1ce4bb988e03ed49c48b8",
          "md5": "f6d46587e1d09bb00dfa3f3ebbd5e3e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-1.3.2.jar",
          "url": "filestore-1.3.2.jar",
          "size": 258075,
          "sha512": "b21ece6feb82a41e1a9447f2cc8d7e5d5d3216d1a3d8d70a027a78d34e9b2ac04f90b4f7f4317900399d482ffffab9aa4c45d1e3d5bc05832d08bebe3bca6d4e",
          "sha256": "d83041e1d0e79c7b8d768826f761b4142c3a88fae8b1042b54a96c27e3c7165a",
          "sha1": "484dc73be2be56b9d5c1ce4bb988e03ed49c48b8",
          "md5": "f6d46587e1d09bb00dfa3f3ebbd5e3e3"
        }
      ]
    }
  ]
}
