{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.2.2.jar",
          "url": "displee-2.2.2.jar",
          "size": 111913,
          "sha512": "d808ed61339a618a113e3371b3d710603ba78c50cf0cedcf730c52f0eabf105a8ed90c3f3445c027e6481d6f48d3c25f0ae686443fa6f9fde77301d0361007e5",
          "sha256": "8572452fed60507677ffbc6a63ed3d7eccccf484738e3c55559697b3fcc48be9",
          "sha1": "0a9668bb68f3cce386ae0f89e73da1fa62fed75f",
          "md5": "ea854f4e91c4c7ead2c506e05c788830"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.2.2.jar",
          "url": "displee-2.2.2.jar",
          "size": 111913,
          "sha512": "d808ed61339a618a113e3371b3d710603ba78c50cf0cedcf730c52f0eabf105a8ed90c3f3445c027e6481d6f48d3c25f0ae686443fa6f9fde77301d0361007e5",
          "sha256": "8572452fed60507677ffbc6a63ed3d7eccccf484738e3c55559697b3fcc48be9",
          "sha1": "0a9668bb68f3cce386ae0f89e73da1fa62fed75f",
          "md5": "ea854f4e91c4c7ead2c506e05c788830"
        }
      ]
    }
  ]
}
