{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filestore",
    "version": "2.4.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-2.4.10.jar",
          "url": "filestore-2.4.10.jar",
          "size": 97539,
          "sha512": "00e157239a567b0e2c1a5d585b5a04368ed7cd2533932b983691ea3eb2a1a549e7dd655929a857cc7a381cb253c41eb33d10cb49ae9576c2cd2ea10951dc0920",
          "sha256": "69afac25ef18c0df88521da66e64998d44cbf37bff21a0e8463b90dfde77ba6c",
          "sha1": "e33ae416a54a09274975143fe37166f691c25d39",
          "md5": "1ebeea587d32ab93143bc7b85bba2172"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-2.4.10.jar",
          "url": "filestore-2.4.10.jar",
          "size": 97539,
          "sha512": "00e157239a567b0e2c1a5d585b5a04368ed7cd2533932b983691ea3eb2a1a549e7dd655929a857cc7a381cb253c41eb33d10cb49ae9576c2cd2ea10951dc0920",
          "sha256": "69afac25ef18c0df88521da66e64998d44cbf37bff21a0e8463b90dfde77ba6c",
          "sha1": "e33ae416a54a09274975143fe37166f691c25d39",
          "md5": "1ebeea587d32ab93143bc7b85bba2172"
        }
      ]
    }
  ]
}
