{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.2.8.jar",
          "url": "displee-2.2.8.jar",
          "size": 111913,
          "sha512": "1ffee6cbf77112921c9bb2867c451776d8d56f08cdaffb26c49abb8d1c8fef91ed42a811d0b01a305d9c25ed59faca6f59d10b55a1c1b30f18a798a82da331f7",
          "sha256": "ef4f0b35668b162c9a8a0a76b4449eddc73cf6fed69f53671718e31d3feeee01",
          "sha1": "1838fedcac2b4763d14336c4abfe3cfcc952f2e5",
          "md5": "9f6e06610560e40314d77c832e39a1eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.2.8.jar",
          "url": "displee-2.2.8.jar",
          "size": 111913,
          "sha512": "1ffee6cbf77112921c9bb2867c451776d8d56f08cdaffb26c49abb8d1c8fef91ed42a811d0b01a305d9c25ed59faca6f59d10b55a1c1b30f18a798a82da331f7",
          "sha256": "ef4f0b35668b162c9a8a0a76b4449eddc73cf6fed69f53671718e31d3feeee01",
          "sha1": "1838fedcac2b4763d14336c4abfe3cfcc952f2e5",
          "md5": "9f6e06610560e40314d77c832e39a1eb"
        }
      ]
    }
  ]
}
