{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.4.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.4.13.jar",
          "url": "displee-2.4.13.jar",
          "size": 111913,
          "sha512": "2eeec759e2bbceb37bc1ec497851f83d685dec783da2d94d1807b0a63e4732b60ae73afcd5451f27b621ee1d2712ecef4007575154825ff93a3055f8ad26d171",
          "sha256": "ef1e31183f78d95493a139a3e765655195782674e6c3308249b78ee31591f84f",
          "sha1": "8d567c10b38a8c519c007db4e3df5d4731404d99",
          "md5": "9be4d8db8d06e1bc5c9ad944ff8ddf3f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.4.13.jar",
          "url": "displee-2.4.13.jar",
          "size": 111913,
          "sha512": "2eeec759e2bbceb37bc1ec497851f83d685dec783da2d94d1807b0a63e4732b60ae73afcd5451f27b621ee1d2712ecef4007575154825ff93a3055f8ad26d171",
          "sha256": "ef1e31183f78d95493a139a3e765655195782674e6c3308249b78ee31591f84f",
          "sha1": "8d567c10b38a8c519c007db4e3df5d4731404d99",
          "md5": "9be4d8db8d06e1bc5c9ad944ff8ddf3f"
        }
      ]
    }
  ]
}
