{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs",
    "version": "2.4.2-cache",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-2.4.2-cache.jar",
          "url": "osrs-2.4.2-cache.jar",
          "size": 88412,
          "sha512": "003650320b6abc70b6dea76d5292563ff2def7c6a2a38143393e34274edf5cf5b970b22d8df4ef523f842a16cc2e0e994a5ae2249e30bd637f13e261761abaff",
          "sha256": "334157f4cefb2a5434780dd3bfc6ecc9ad2a74bfccf8580d8cda97427f47d4f9",
          "sha1": "54eb753115cbc33dd6aeca338af35bf4532cb5f5",
          "md5": "a3296d330ceb7af194d9a0718bd04804"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.2-cache"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-2.4.2-cache.jar",
          "url": "osrs-2.4.2-cache.jar",
          "size": 88412,
          "sha512": "003650320b6abc70b6dea76d5292563ff2def7c6a2a38143393e34274edf5cf5b970b22d8df4ef523f842a16cc2e0e994a5ae2249e30bd637f13e261761abaff",
          "sha256": "334157f4cefb2a5434780dd3bfc6ecc9ad2a74bfccf8580d8cda97427f47d4f9",
          "sha1": "54eb753115cbc33dd6aeca338af35bf4532cb5f5",
          "md5": "a3296d330ceb7af194d9a0718bd04804"
        }
      ]
    }
  ]
}
