{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718",
    "version": "2.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-2.4.6.jar",
          "url": "r718-2.4.6.jar",
          "size": 14446,
          "sha512": "fc976551cda75276ac8f75e193c94221e6fa7fb7e068e79527d3cf5a399f7fda104633cd7439d07f2174a473ea6bce7094dfab89a374b8df0246e5ab1c3bcd4e",
          "sha256": "d21556bb4441ac63686057bd690607e4d2e7d9fa5a12e4dee9918d4736327b2a",
          "sha1": "c13042b9334c99c62cd6870a7918790fe6ef5fe0",
          "md5": "17f8bf5726bd2d2807b80e0be7b60f03"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.6"
          }
        }
      ],
      "files": [
        {
          "name": "r718-2.4.6.jar",
          "url": "r718-2.4.6.jar",
          "size": 14446,
          "sha512": "fc976551cda75276ac8f75e193c94221e6fa7fb7e068e79527d3cf5a399f7fda104633cd7439d07f2174a473ea6bce7094dfab89a374b8df0246e5ab1c3bcd4e",
          "sha256": "d21556bb4441ac63686057bd690607e4d2e7d9fa5a12e4dee9918d4736327b2a",
          "sha1": "c13042b9334c99c62cd6870a7918790fe6ef5fe0",
          "md5": "17f8bf5726bd2d2807b80e0be7b60f03"
        }
      ]
    }
  ]
}
