{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "filestore",
    "version": "1.3.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-1.3.6.1.jar",
          "url": "filestore-1.3.6.1.jar",
          "size": 575126,
          "sha512": "00882a8f62418de0b74e47465337c7164bbdd79434a333d016e63788d0bc35410c1bdfd1c112b49f4dcbaafb78438720d51a3ca76b5d5620fb9ef093e089986a",
          "sha256": "27d71984f44f932413f757d35a3fb2da6564638b3758d0a4cc46264d5fbf1e2d",
          "sha1": "702f007457ae79f650c7a8df9655b5f3d7562ce9",
          "md5": "e28766a9f8b08f2fec10847431413fde"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.10.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-1.3.6.1.jar",
          "url": "filestore-1.3.6.1.jar",
          "size": 575126,
          "sha512": "00882a8f62418de0b74e47465337c7164bbdd79434a333d016e63788d0bc35410c1bdfd1c112b49f4dcbaafb78438720d51a3ca76b5d5620fb9ef093e089986a",
          "sha256": "27d71984f44f932413f757d35a3fb2da6564638b3758d0a4cc46264d5fbf1e2d",
          "sha1": "702f007457ae79f650c7a8df9655b5f3d7562ce9",
          "md5": "e28766a9f8b08f2fec10847431413fde"
        }
      ]
    }
  ]
}
