{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "definition",
    "version": "2.4.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "definition-2.4.15.jar",
          "url": "definition-2.4.15.jar",
          "size": 537810,
          "sha512": "5e8eb9734159b031e0342a8339dba8ab689e9032127fdceb328571319e4e79fe920d34741f0ad3e6f35b98e119dc72ecad18394459747a612ca3b108269fa7c2",
          "sha256": "4a961ecebab30ca68603e14de65f96fe87a3b0e4dc2a44f0e95c9559224d18f3",
          "sha1": "a276b7fabb589b5637b3236261a1237e56195c79",
          "md5": "6baa3d19462fc8020d8b5d6819c28e65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "toml-core",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "definition-2.4.15.jar",
          "url": "definition-2.4.15.jar",
          "size": 537810,
          "sha512": "5e8eb9734159b031e0342a8339dba8ab689e9032127fdceb328571319e4e79fe920d34741f0ad3e6f35b98e119dc72ecad18394459747a612ca3b108269fa7c2",
          "sha256": "4a961ecebab30ca68603e14de65f96fe87a3b0e4dc2a44f0e95c9559224d18f3",
          "sha1": "a276b7fabb589b5637b3236261a1237e56195c79",
          "md5": "6baa3d19462fc8020d8b5d6819c28e65"
        }
      ]
    }
  ]
}
