{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718-fs",
    "version": "2.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-fs-2.4.5.jar",
          "url": "r718-fs-2.4.5.jar",
          "size": 7588,
          "sha512": "15f3472193d60db8a198e5e30b919d11388bf0325b71d7251008c3a7cfe994d7b92de52da2eab6f5354e669d810b5a5ddfc381deea0751df89d4d62a4600d822",
          "sha256": "e0a5fc5dc68e1e83e2993df3afa9c5952af3f83ece1f3e36e0dc842f79ee6f5b",
          "sha1": "353be7ef58faaffc42c2c976f6f8b2e4a9e2b1be",
          "md5": "b5f247ef0a2deab5767e4793a7bdb11f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.4.5"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.5"
          }
        },
        {
          "group": "dev.or2",
          "module": "r718",
          "version": {
            "requires": "2.4.5"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.5"
          }
        }
      ],
      "files": [
        {
          "name": "r718-fs-2.4.5.jar",
          "url": "r718-fs-2.4.5.jar",
          "size": 7588,
          "sha512": "15f3472193d60db8a198e5e30b919d11388bf0325b71d7251008c3a7cfe994d7b92de52da2eab6f5354e669d810b5a5ddfc381deea0751df89d4d62a4600d822",
          "sha256": "e0a5fc5dc68e1e83e2993df3afa9c5952af3f83ece1f3e36e0dc842f79ee6f5b",
          "sha1": "353be7ef58faaffc42c2c976f6f8b2e4a9e2b1be",
          "md5": "b5f247ef0a2deab5767e4793a7bdb11f"
        }
      ]
    }
  ]
}
