{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718",
    "version": "2.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-2.0.2.jar",
          "url": "r718-2.0.2.jar",
          "size": 14003,
          "sha512": "353629691ed76efd81c9fb8d3e1eda79d1f46edf72e07b511545cf2be1b3cded527f6841792cef74c04faf7916d37cc8c643b745d395ef1f46745b2618e04aae",
          "sha256": "f86560dbff3e6966392f8b716b7c99d5a361d9fc2c73d73cf114607c4c9fdf55",
          "sha1": "f68186ff689f37a51bb9220f3ded02acb9c0c719",
          "md5": "8fa3a7c81399dd3ffae4b5a30a3d85c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "r718-2.0.2.jar",
          "url": "r718-2.0.2.jar",
          "size": 14003,
          "sha512": "353629691ed76efd81c9fb8d3e1eda79d1f46edf72e07b511545cf2be1b3cded527f6841792cef74c04faf7916d37cc8c643b745d395ef1f46745b2618e04aae",
          "sha256": "f86560dbff3e6966392f8b716b7c99d5a361d9fc2c73d73cf114607c4c9fdf55",
          "sha1": "f68186ff689f37a51bb9220f3ded02acb9c0c719",
          "md5": "8fa3a7c81399dd3ffae4b5a30a3d85c6"
        }
      ]
    }
  ]
}
