{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs-fs",
    "version": "3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-fs-3.0.1.jar",
          "url": "osrs-fs-3.0.1.jar",
          "size": 27057,
          "sha512": "1a41cb78b6d13f28e20c3ccfed05939240daa250af0ce307fe8e6046a3927fa317eaf0bc7171e476af8eed2fd42e8e55e5c5347461a6b90e73d33905a5d62b00",
          "sha256": "7cc9a6e700a748fd97e42d4b4f45411e82c6e7fb8584b59fa824d6ea7352c4db",
          "sha1": "c7617fc7e6dc3edad5006e52b2577a7d48f5ca01",
          "md5": "8cbe1652053cef6799c895482e9c3651"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "3.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-fs-3.0.1.jar",
          "url": "osrs-fs-3.0.1.jar",
          "size": 27057,
          "sha512": "1a41cb78b6d13f28e20c3ccfed05939240daa250af0ce307fe8e6046a3927fa317eaf0bc7171e476af8eed2fd42e8e55e5c5347461a6b90e73d33905a5d62b00",
          "sha256": "7cc9a6e700a748fd97e42d4b4f45411e82c6e7fb8584b59fa824d6ea7352c4db",
          "sha1": "c7617fc7e6dc3edad5006e52b2577a7d48f5ca01",
          "md5": "8cbe1652053cef6799c895482e9c3651"
        }
      ]
    }
  ]
}
