{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718-fs",
    "version": "2.4.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-fs-2.4.14.jar",
          "url": "r718-fs-2.4.14.jar",
          "size": 7588,
          "sha512": "b9ab7554e0faf7a9831b44951cfda2c3d71e5f9ee44165cc988c8a7eb340f2ac5fa08f08a0cb10128788b35a850b00df3d01540dc2e9d220eb26746671a9c5a9",
          "sha256": "79a232e0f52c1455cadf5f7410efae1cebbec751fe1d4570e83d31bc77001ec9",
          "sha1": "f6334be16db07f1d3e96702cbf32171e4f2979d9",
          "md5": "a4390894982b455f78ebd61d1ff54c29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.4.14"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.14"
          }
        },
        {
          "group": "dev.or2",
          "module": "r718",
          "version": {
            "requires": "2.4.14"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.14"
          }
        }
      ],
      "files": [
        {
          "name": "r718-fs-2.4.14.jar",
          "url": "r718-fs-2.4.14.jar",
          "size": 7588,
          "sha512": "b9ab7554e0faf7a9831b44951cfda2c3d71e5f9ee44165cc988c8a7eb340f2ac5fa08f08a0cb10128788b35a850b00df3d01540dc2e9d220eb26746671a9c5a9",
          "sha256": "79a232e0f52c1455cadf5f7410efae1cebbec751fe1d4570e83d31bc77001ec9",
          "sha1": "f6334be16db07f1d3e96702cbf32171e4f2979d9",
          "md5": "a4390894982b455f78ebd61d1ff54c29"
        }
      ]
    }
  ]
}
