{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "cache",
    "version": "2.4.2-cache",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "cache-2.4.2-cache.jar",
          "url": "cache-2.4.2-cache.jar",
          "size": 56905,
          "sha512": "f886883b48b900551cae1685334d55e73254652c02e99f53096979b8dd499949e74342ce0f1ec938847508d64172ec05235a6ca5ef05f78f07e87cb5c705a332",
          "sha256": "9dba7704e9a4a25e92461b60ef57987a10361286c20cad9712842b76b829795d",
          "sha1": "59e072ac206fba345c4092563cd9a7b86f6ff330",
          "md5": "0062eb47411f632524720e455a12fcb0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2.openrs2",
          "module": "buffer",
          "version": {
            "requires": "1.0.0-openrune"
          }
        },
        {
          "group": "dev.or2.openrs2",
          "module": "cache",
          "version": {
            "requires": "1.0.0-openrune"
          }
        },
        {
          "group": "dev.or2.openrs2",
          "module": "crypto",
          "version": {
            "requires": "1.0.0-openrune"
          }
        }
      ],
      "files": [
        {
          "name": "cache-2.4.2-cache.jar",
          "url": "cache-2.4.2-cache.jar",
          "size": 56905,
          "sha512": "f886883b48b900551cae1685334d55e73254652c02e99f53096979b8dd499949e74342ce0f1ec938847508d64172ec05235a6ca5ef05f78f07e87cb5c705a332",
          "sha256": "9dba7704e9a4a25e92461b60ef57987a10361286c20cad9712842b76b829795d",
          "sha1": "59e072ac206fba345c4092563cd9a7b86f6ff330",
          "md5": "0062eb47411f632524720e455a12fcb0"
        }
      ]
    }
  ]
}
