{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs",
    "version": "2.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-2.3.1.jar",
          "url": "osrs-2.3.1.jar",
          "size": 87540,
          "sha512": "20f7d5e74333c8a14ff3533d379214098ea618ce83184be63f68502ac2d52d63f7dab6ed2c93a1497b9e9558ca776a3c3b2586b71062f4dcca018d31a12708b1",
          "sha256": "48e2ae018c9c30c272d6ae6f501e5350485980a69171758c90b7b8e95563df35",
          "sha1": "50e7e18b77704f127824494b7e58857b4e1ea912",
          "md5": "951e7c4b46ca27de805d83d312886181"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-2.3.1.jar",
          "url": "osrs-2.3.1.jar",
          "size": 87540,
          "sha512": "20f7d5e74333c8a14ff3533d379214098ea618ce83184be63f68502ac2d52d63f7dab6ed2c93a1497b9e9558ca776a3c3b2586b71062f4dcca018d31a12708b1",
          "sha256": "48e2ae018c9c30c272d6ae6f501e5350485980a69171758c90b7b8e95563df35",
          "sha1": "50e7e18b77704f127824494b7e58857b4e1ea912",
          "md5": "951e7c4b46ca27de805d83d312886181"
        }
      ]
    }
  ]
}
