{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "server-utils",
    "version": "0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "server-utils-0.7.jar",
          "url": "server-utils-0.7.jar",
          "size": 329599,
          "sha512": "292a7c5d82b6b58377707821d2238cd3dd9db01179ed1c679d058f250e89385ef71abb8861eb1faadbe905870aa6612c06b5fa5775a2f6dcf58382635391ec59",
          "sha256": "6128c876624cb23d7fc809243c126f0423a1a03d2e2c69d2479c08544b669b8f",
          "sha1": "dfbe23f28eaefdf4cc2bfbfd770765926e1ba312",
          "md5": "3f1607dc4c0ea424ce85546f596c797c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.or2",
          "module": "all",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "server-utils-0.7.jar",
          "url": "server-utils-0.7.jar",
          "size": 329599,
          "sha512": "292a7c5d82b6b58377707821d2238cd3dd9db01179ed1c679d058f250e89385ef71abb8861eb1faadbe905870aa6612c06b5fa5775a2f6dcf58382635391ec59",
          "sha256": "6128c876624cb23d7fc809243c126f0423a1a03d2e2c69d2479c08544b669b8f",
          "sha1": "dfbe23f28eaefdf4cc2bfbfd770765926e1ba312",
          "md5": "3f1607dc4c0ea424ce85546f596c797c"
        }
      ]
    }
  ]
}
