{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "filestore-tools",
    "version": "1.3.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-tools-1.3.6.2.jar",
          "url": "filestore-tools-1.3.6.2.jar",
          "size": 125628,
          "sha512": "eaa4a979edc03c7ee857b1e411505898b145dcdc16b387c2882a7ccc3cb4e0819e5f454aeff1f69e3f5231fdc1dbdc79c1fc1575cac3c5897f295541245e3249",
          "sha256": "0b44cd802248957ca375b8999c5a365d97251f05de9ffc26fbc153e11090d32f",
          "sha1": "5c6526b1337335dbecc2f59d95ac27e40da09f8e",
          "md5": "14888badc6090c3ca1b84dee0cd6d482"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "dev.openrune",
          "module": "filestore",
          "version": {
            "requires": "1.3.6.2"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.openrune",
          "module": "js5server",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.11.5"
          }
        },
        {
          "group": "cc.ekblad",
          "module": "4koma",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "com.displee",
          "module": "rs-cache-library",
          "version": {
            "requires": "7.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-tools-1.3.6.2.jar",
          "url": "filestore-tools-1.3.6.2.jar",
          "size": 125628,
          "sha512": "eaa4a979edc03c7ee857b1e411505898b145dcdc16b387c2882a7ccc3cb4e0819e5f454aeff1f69e3f5231fdc1dbdc79c1fc1575cac3c5897f295541245e3249",
          "sha256": "0b44cd802248957ca375b8999c5a365d97251f05de9ffc26fbc153e11090d32f",
          "sha1": "5c6526b1337335dbecc2f59d95ac27e40da09f8e",
          "md5": "14888badc6090c3ca1b84dee0cd6d482"
        }
      ]
    }
  ]
}
