{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "tools",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "tools-1.3.0.jar",
          "url": "tools-1.3.0.jar",
          "size": 109824,
          "sha512": "3e86a9556e80b23c2137a5c6a3948e2a14f37cbb14260ac584e313313cea8ac036e05392f63b302f1bf0fcee9433d9cb2dc53fef374de7df12ad07892fb43637",
          "sha256": "630aca8b66735544fcb8aca3595cfd23136e84a93dad8793ae89a6db81d1ae58",
          "sha1": "0d1c5e06dae1f37c4eb431e5e94ced4837cb5c94",
          "md5": "966d5f223ae4d8b480f4957ff4ff796a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.beust",
          "module": "klaxon",
          "version": {
            "requires": "5.5"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.displee",
          "module": "rs-cache-library",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "dev.openrune",
          "module": "filestore",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.openrune",
          "module": "js5server",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.11.5"
          }
        },
        {
          "group": "cc.ekblad",
          "module": "4koma",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "tools-1.3.0.jar",
          "url": "tools-1.3.0.jar",
          "size": 109824,
          "sha512": "3e86a9556e80b23c2137a5c6a3948e2a14f37cbb14260ac584e313313cea8ac036e05392f63b302f1bf0fcee9433d9cb2dc53fef374de7df12ad07892fb43637",
          "sha256": "630aca8b66735544fcb8aca3595cfd23136e84a93dad8793ae89a6db81d1ae58",
          "sha1": "0d1c5e06dae1f37c4eb431e5e94ced4837cb5c94",
          "md5": "966d5f223ae4d8b480f4957ff4ff796a"
        }
      ]
    }
  ]
}
