{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.4.4.jar",
          "url": "displee-2.4.4.jar",
          "size": 112561,
          "sha512": "05e74679600c1ff768ff46dfd704764519266d59c3ffc17a36cbe991025a2d6a9d24c6066579da7c4fe8d180596ee22d3df55d3ca7e2457ddf239fcc74c35fdb",
          "sha256": "21d3eea3121418c9c0436bffc3b964983581fdc15f3bbdca983fda240584cca4",
          "sha1": "9b3c54b9e27876e14c79c37ea938a13b757f888e",
          "md5": "1eb2383d03fd59c93fd1c2309d4c9903"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.4.4.jar",
          "url": "displee-2.4.4.jar",
          "size": 112561,
          "sha512": "05e74679600c1ff768ff46dfd704764519266d59c3ffc17a36cbe991025a2d6a9d24c6066579da7c4fe8d180596ee22d3df55d3ca7e2457ddf239fcc74c35fdb",
          "sha256": "21d3eea3121418c9c0436bffc3b964983581fdc15f3bbdca983fda240584cca4",
          "sha1": "9b3c54b9e27876e14c79c37ea938a13b757f888e",
          "md5": "1eb2383d03fd59c93fd1c2309d4c9903"
        }
      ]
    }
  ]
}
