{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filestore",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-2.4.0.jar",
          "url": "filestore-2.4.0.jar",
          "size": 94722,
          "sha512": "8001bebb8f016d13ef5a25a45e3026211e3b79cfd0841e1c7b769a6f4bee851e9b2098e6cabc8c2b681cd0e92257bedada82d02e349aaa8eafc5f76e8c94bb88",
          "sha256": "1df31b48213e299870f0a507609bb4627232fe8584a2cebec3f14fe47d0160c5",
          "sha1": "3fe525a637d3dcb9520902f270546462b07137b3",
          "md5": "c60ee9d7f5faff7c9a60d73659a6c51d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-2.4.0.jar",
          "url": "filestore-2.4.0.jar",
          "size": 94722,
          "sha512": "8001bebb8f016d13ef5a25a45e3026211e3b79cfd0841e1c7b769a6f4bee851e9b2098e6cabc8c2b681cd0e92257bedada82d02e349aaa8eafc5f76e8c94bb88",
          "sha256": "1df31b48213e299870f0a507609bb4627232fe8584a2cebec3f14fe47d0160c5",
          "sha1": "3fe525a637d3dcb9520902f270546462b07137b3",
          "md5": "c60ee9d7f5faff7c9a60d73659a6c51d"
        }
      ]
    }
  ]
}
