{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "opcode",
    "version": "2.4.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "opcode-2.4.7.jar",
          "url": "opcode-2.4.7.jar",
          "size": 127117,
          "sha512": "2feb6b69076890e7d6f165c5f372053dc2ba5dbf31a566375ded28876c752de860dedae8ecc8e318d35616ddfc3d5587423d907d22b85dc4ee39ac22e7e282b6",
          "sha256": "c293272d9205c72aeb62161d6c1c0dfdf9f5164464013dd32a05a6ddc3a0cb07",
          "sha1": "e09047d94fe341e7ca38c3e82753425fd153c089",
          "md5": "21c9df79b077fb378b55dd441b46aeef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.7"
          }
        }
      ],
      "files": [
        {
          "name": "opcode-2.4.7.jar",
          "url": "opcode-2.4.7.jar",
          "size": 127117,
          "sha512": "2feb6b69076890e7d6f165c5f372053dc2ba5dbf31a566375ded28876c752de860dedae8ecc8e318d35616ddfc3d5587423d907d22b85dc4ee39ac22e7e282b6",
          "sha256": "c293272d9205c72aeb62161d6c1c0dfdf9f5164464013dd32a05a6ddc3a0cb07",
          "sha1": "e09047d94fe341e7ca38c3e82753425fd153c089",
          "md5": "21c9df79b077fb378b55dd441b46aeef"
        }
      ]
    }
  ]
}
