{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718",
    "version": "2.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-2.3.5.jar",
          "url": "r718-2.3.5.jar",
          "size": 14132,
          "sha512": "9987f45bb32d09649fd2eb21fe61d5545e8e8db1205bd8d3634d5c821c26f9d7b93582602cd9e6d8663caa68bb1e872c88613fb429f372992055280a59f58ada",
          "sha256": "6e25cbf83831161eafc56fb12d425ab65d688e08d0cc774fe8f9559207fc0a25",
          "sha1": "df50ca37aaa14f545f5205d7fc3b028e54eb6bdd",
          "md5": "77906233b4cc426fd3bf628a8749c774"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "r718-2.3.5.jar",
          "url": "r718-2.3.5.jar",
          "size": 14132,
          "sha512": "9987f45bb32d09649fd2eb21fe61d5545e8e8db1205bd8d3634d5c821c26f9d7b93582602cd9e6d8663caa68bb1e872c88613fb429f372992055280a59f58ada",
          "sha256": "6e25cbf83831161eafc56fb12d425ab65d688e08d0cc774fe8f9559207fc0a25",
          "sha1": "df50ca37aaa14f545f5205d7fc3b028e54eb6bdd",
          "md5": "77906233b4cc426fd3bf628a8749c774"
        }
      ]
    }
  ]
}
