{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.0.14.jar",
          "url": "displee-2.0.14.jar",
          "size": 111759,
          "sha512": "54ad72fc9dd46e2b9018df26e9b90f34ca5039952ec36de603bc06e6cf01800d454ea37f7f60b370cc3b629de110bbd9d5a3f7b30ffa2f09c4bc08cb537e07fb",
          "sha256": "b0e688cc049002ad5bded4f33d72f594b4c66e9f1ce6cdc0ea5927407cc9b6ad",
          "sha1": "3ce24fac6c132dbc79306cfe58d9d81499856010",
          "md5": "799121bff2d4713bb259b89c7063aaeb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.0.14.jar",
          "url": "displee-2.0.14.jar",
          "size": 111759,
          "sha512": "54ad72fc9dd46e2b9018df26e9b90f34ca5039952ec36de603bc06e6cf01800d454ea37f7f60b370cc3b629de110bbd9d5a3f7b30ffa2f09c4bc08cb537e07fb",
          "sha256": "b0e688cc049002ad5bded4f33d72f594b4c66e9f1ce6cdc0ea5927407cc9b6ad",
          "sha1": "3ce24fac6c132dbc79306cfe58d9d81499856010",
          "md5": "799121bff2d4713bb259b89c7063aaeb"
        }
      ]
    }
  ]
}
