{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filesystem",
    "version": "2.0.16.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filesystem-2.0.16.1.jar",
          "url": "filesystem-2.0.16.1.jar",
          "size": 75515,
          "sha512": "fb0a815038e7a4123c9b82f1e73a8763cb391c9713b1c1c5d149a72cb213982ee0c5aaf625db60f79a91dea7fa31182ee69b4d83b57aeb9765cd7b2cdc112e1b",
          "sha256": "27af1458058335bd073c9430e4425ab55f8d4c54d2040dc8b8b35c57c94a527c",
          "sha1": "ac49ec6141472168717261bf2e08cfaab85e5d2f",
          "md5": "01848b6b153039019862f9cce025ab86"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "filesystem-2.0.16.1.jar",
          "url": "filesystem-2.0.16.1.jar",
          "size": 75515,
          "sha512": "fb0a815038e7a4123c9b82f1e73a8763cb391c9713b1c1c5d149a72cb213982ee0c5aaf625db60f79a91dea7fa31182ee69b4d83b57aeb9765cd7b2cdc112e1b",
          "sha256": "27af1458058335bd073c9430e4425ab55f8d4c54d2040dc8b8b35c57c94a527c",
          "sha1": "ac49ec6141472168717261bf2e08cfaab85e5d2f",
          "md5": "01848b6b153039019862f9cce025ab86"
        }
      ]
    }
  ]
}
