{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "openrune-central",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "openrune-central-1.2.jar",
          "url": "openrune-central-1.2.jar",
          "size": 433246,
          "sha512": "a33bf138dbc49602aff1989722123092f1931cafebc249fa7ec36321d03f9c8e41831ee2509739445b61b1af58840cd406bb7ea536fdc7b5548e9a5503a6791a",
          "sha256": "49b0ee1282c169f1a4ceeb4f9d10286a6449e25ba38862802a79f356f02696c2",
          "sha1": "4601fb7f2113e38dd29ab8db0befc4ec315fcde6",
          "md5": "e146dd0febfaf7412c0200ac0ba78638"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.or2",
          "module": "central-common",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-bom",
          "version": {
            "requires": "3.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-content-negotiation"
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-status-pages"
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-config-yaml"
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.7"
          }
        },
        {
          "group": "io.zonky.test",
          "module": "embedded-postgres",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.16"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "de.mkammerer",
          "module": "argon2-jvm",
          "version": {
            "requires": "2.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "openrune-central-1.2.jar",
          "url": "openrune-central-1.2.jar",
          "size": 433246,
          "sha512": "a33bf138dbc49602aff1989722123092f1931cafebc249fa7ec36321d03f9c8e41831ee2509739445b61b1af58840cd406bb7ea536fdc7b5548e9a5503a6791a",
          "sha256": "49b0ee1282c169f1a4ceeb4f9d10286a6449e25ba38862802a79f356f02696c2",
          "sha1": "4601fb7f2113e38dd29ab8db0befc4ec315fcde6",
          "md5": "e146dd0febfaf7412c0200ac0ba78638"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "openrune-central-1.2-all.jar",
          "url": "openrune-central-1.2-all.jar",
          "size": 101056233,
          "sha512": "6d7bf9d96bc7e8b0dfa70e1d111bea56601b45cb26805b2ca157ed86375b7309834040109fb34587df286f243d7d31dcd8b379296b5ad767f76d40f8a31fd95f",
          "sha256": "2d07022dc732c2a6a0225052fa5b39df56deebedcfdcb4ec84a6eb0199e241c9",
          "sha1": "19f4f91b6644d65b5e380a42a364816ceea9830e",
          "md5": "cd0db5f9c244eafa418cb553f23d0d51"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "openrune-central-1.2-sources.jar",
          "url": "openrune-central-1.2-sources.jar",
          "size": 62818,
          "sha512": "3ea40198afd417aa50c5f37e7e99e3f5d54b75ba463e13653a09e494ae13edc96fc8efd2cf3b85842ef734fdcb3f88df91081ced175c3b049dfb3c1659611a2d",
          "sha256": "042864ebc2abbdf6d6523946b2d2e6cd7a5db6b410ae9b5666dafeb717f184d9",
          "sha1": "8932e88d03d5b399d2618bb1d6ce067d4da91563",
          "md5": "2019d94658cd3e175f0a5b0c43b2fd74"
        }
      ]
    }
  ]
}
