{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filestore",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-3.0.0.jar",
          "url": "filestore-3.0.0.jar",
          "size": 114514,
          "sha512": "3679a7b5f1446a1e055aef694a0c85534fad548830fbe2a2a5165cc15e9b892de410ab982bfbdecf8980d06405a8111d6dfcf57e788dcab512698793f3aef913",
          "sha256": "8879d1363e2abfe036c4190b4bf98d05c32b3ade11118f3457e78bdd5a0edc57",
          "sha1": "3dd17b39dce1f1e707cfd14851a3a43da88ea43b",
          "md5": "8e4ea22eae295edb177c3ce93a647d89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-3.0.0.jar",
          "url": "filestore-3.0.0.jar",
          "size": 114514,
          "sha512": "3679a7b5f1446a1e055aef694a0c85534fad548830fbe2a2a5165cc15e9b892de410ab982bfbdecf8980d06405a8111d6dfcf57e788dcab512698793f3aef913",
          "sha256": "8879d1363e2abfe036c4190b4bf98d05c32b3ade11118f3457e78bdd5a0edc57",
          "sha1": "3dd17b39dce1f1e707cfd14851a3a43da88ea43b",
          "md5": "8e4ea22eae295edb177c3ce93a647d89"
        }
      ]
    }
  ]
}
