{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-3.0.0.jar",
          "url": "displee-3.0.0.jar",
          "size": 111957,
          "sha512": "5462f203199eddf4baadafdb6388c25160f774157b569fbb0e78f3ec8347c34275d9a219ddfcfcfcd8eed0b7043a1730f5b4a6e36703e8ec1e5b13c4f538ca41",
          "sha256": "8dcd383c99d1ce2ca63c0e4b6e84a42a1aa07e1a743d1f8bb9e40ad4b869d21f",
          "sha1": "ad6f439e95f367534e02e92b4f786546f4a62517",
          "md5": "43c68df76af64d204dcfbf5839366812"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-3.0.0.jar",
          "url": "displee-3.0.0.jar",
          "size": 111957,
          "sha512": "5462f203199eddf4baadafdb6388c25160f774157b569fbb0e78f3ec8347c34275d9a219ddfcfcfcd8eed0b7043a1730f5b4a6e36703e8ec1e5b13c4f538ca41",
          "sha256": "8dcd383c99d1ce2ca63c0e4b6e84a42a1aa07e1a743d1f8bb9e40ad4b869d21f",
          "sha1": "ad6f439e95f367534e02e92b4f786546f4a62517",
          "md5": "43c68df76af64d204dcfbf5839366812"
        }
      ]
    }
  ]
}
