{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718-fs",
    "version": "2.4.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-fs-2.4.13.jar",
          "url": "r718-fs-2.4.13.jar",
          "size": 7588,
          "sha512": "bdfcf80122ae6b1a74c05c53a16d1c09848f83c782c8e1b878ae6d943ff95fd1c4116a52c91c89e77f3f28c00c72b0a199ce5191c416ab46d2ee229cad0fcb82",
          "sha256": "aa1872c3e25e66a93c31292501576033f6534d19ac0e776b3d6cbb42a7b70bcd",
          "sha1": "11f58ee4438eb10cf6a80ab8e3e4398a404d5d3b",
          "md5": "f0e6df634cc17db1396424ef8a2402e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.4.13"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.13"
          }
        },
        {
          "group": "dev.or2",
          "module": "r718",
          "version": {
            "requires": "2.4.13"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.13"
          }
        }
      ],
      "files": [
        {
          "name": "r718-fs-2.4.13.jar",
          "url": "r718-fs-2.4.13.jar",
          "size": 7588,
          "sha512": "bdfcf80122ae6b1a74c05c53a16d1c09848f83c782c8e1b878ae6d943ff95fd1c4116a52c91c89e77f3f28c00c72b0a199ce5191c416ab46d2ee229cad0fcb82",
          "sha256": "aa1872c3e25e66a93c31292501576033f6534d19ac0e776b3d6cbb42a7b70bcd",
          "sha1": "11f58ee4438eb10cf6a80ab8e3e4398a404d5d3b",
          "md5": "f0e6df634cc17db1396424ef8a2402e2"
        }
      ]
    }
  ]
}
