{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718-fs",
    "version": "2.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-fs-2.3.5.jar",
          "url": "r718-fs-2.3.5.jar",
          "size": 7588,
          "sha512": "b6ce2dcd181b99d02db9cd15219e8983c4ab302675160da83713cf2e06dd672dedcd5a4a2e881aabf14d2a260e258266acf3596f6280d564ad374a4177c92471",
          "sha256": "c6038bfb4a135075a446f560c77398847e137782cff8dfa8be3b924e826836f9",
          "sha1": "ca1e25fe0ad0ff20627a47201e305b76cb2c2dca",
          "md5": "de05d7378be64df3faf2ae4ae0cedbc5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "dev.or2",
          "module": "r718",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "r718-fs-2.3.5.jar",
          "url": "r718-fs-2.3.5.jar",
          "size": 7588,
          "sha512": "b6ce2dcd181b99d02db9cd15219e8983c4ab302675160da83713cf2e06dd672dedcd5a4a2e881aabf14d2a260e258266acf3596f6280d564ad374a4177c92471",
          "sha256": "c6038bfb4a135075a446f560c77398847e137782cff8dfa8be3b924e826836f9",
          "sha1": "ca1e25fe0ad0ff20627a47201e305b76cb2c2dca",
          "md5": "de05d7378be64df3faf2ae4ae0cedbc5"
        }
      ]
    }
  ]
}
