{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filestore",
    "version": "2.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-2.0.11.jar",
          "url": "filestore-2.0.11.jar",
          "size": 23613,
          "sha512": "2e57fb1bbfc40fd61ab2610789092a0928b11e0b0c88c2addeca661b49212a44579d7b306d60c561f456d8c59376706b2c401bfc84a345475999cdc6f742163a",
          "sha256": "bb0a79f15cca9a8d8019b016cc58a37254c3c10873a0a2cce596d207caf65cb7",
          "sha1": "8400739af60afdafa85ec63e88488c26fa5aa343",
          "md5": "b605cce94f27f50f4b1cd2c7c53a7749"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.11"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.0.11"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-2.0.11.jar",
          "url": "filestore-2.0.11.jar",
          "size": 23613,
          "sha512": "2e57fb1bbfc40fd61ab2610789092a0928b11e0b0c88c2addeca661b49212a44579d7b306d60c561f456d8c59376706b2c401bfc84a345475999cdc6f742163a",
          "sha256": "bb0a79f15cca9a8d8019b016cc58a37254c3c10873a0a2cce596d207caf65cb7",
          "sha1": "8400739af60afdafa85ec63e88488c26fa5aa343",
          "md5": "b605cce94f27f50f4b1cd2c7c53a7749"
        }
      ]
    }
  ]
}
