{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "rs3",
    "version": "2.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "rs3-2.4.2.jar",
          "url": "rs3-2.4.2.jar",
          "size": 8872,
          "sha512": "d4ffb0162be4929b5cffb8622aa434ed7a74a69c057738dbb387a1cb0ff60ac59524a3c9c455a0c4c24a1ca38ca18a3c553ce1e1b21a627a3f8795b4bf6ee5aa",
          "sha256": "5bb213bf646780bdd7b8d2cdd4cdb3df89d62ccc897bacca8462ede8767ae286",
          "sha1": "4e5443e30ef644b79f30c22e516d78801398e3b2",
          "md5": "06683b1ab150938f910f561202b97e9a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "rs3-2.4.2.jar",
          "url": "rs3-2.4.2.jar",
          "size": 8872,
          "sha512": "d4ffb0162be4929b5cffb8622aa434ed7a74a69c057738dbb387a1cb0ff60ac59524a3c9c455a0c4c24a1ca38ca18a3c553ce1e1b21a627a3f8795b4bf6ee5aa",
          "sha256": "5bb213bf646780bdd7b8d2cdd4cdb3df89d62ccc897bacca8462ede8767ae286",
          "sha1": "4e5443e30ef644b79f30c22e516d78801398e3b2",
          "md5": "06683b1ab150938f910f561202b97e9a"
        }
      ]
    }
  ]
}
