{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filesystem",
    "version": "2.4.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filesystem-2.4.16.jar",
          "url": "filesystem-2.4.16.jar",
          "size": 51650,
          "sha512": "0b04a581a6a7b3644b17bfdac60f7811e03b371c115625c5ad5270c0526ad73ab0bdb81bca5a9214278b74feba5e013e4088e98a73715439f09a6667f645a413",
          "sha256": "e86561a7c13656ac6d0ac6c5d13fabcb24e1db689f363ff534e4796e56f4dbf4",
          "sha1": "e47b049b30f33fc7135383e5f52967e59f547f1e",
          "md5": "9d6d997134a0d36cdce9dc644a05bb0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "filesystem-2.4.16.jar",
          "url": "filesystem-2.4.16.jar",
          "size": 51650,
          "sha512": "0b04a581a6a7b3644b17bfdac60f7811e03b371c115625c5ad5270c0526ad73ab0bdb81bca5a9214278b74feba5e013e4088e98a73715439f09a6667f645a413",
          "sha256": "e86561a7c13656ac6d0ac6c5d13fabcb24e1db689f363ff534e4796e56f4dbf4",
          "sha1": "e47b049b30f33fc7135383e5f52967e59f547f1e",
          "md5": "9d6d997134a0d36cdce9dc644a05bb0b"
        }
      ]
    }
  ]
}
