{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "definition",
    "version": "2.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "definition-2.3.7.jar",
          "url": "definition-2.3.7.jar",
          "size": 425796,
          "sha512": "8f4a161e4082137839570374d9a62821806bd8ac8e9a364b80cc0cfac5bd2a4db9ceab7879673ff01f4020072c5a3c1c2d6bd3bbb42d63644ffe0f1a1a6571ea",
          "sha256": "d9be0ed8b9d1c5438952307ad5c85b28838dc44b29a45785c7d09c7cb70635e8",
          "sha1": "218c5ca691131f90f78e60dbe863e20503113345",
          "md5": "ee31b05a87fb4af0a8cd0ad163907c2e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        }
      ],
      "files": [
        {
          "name": "definition-2.3.7.jar",
          "url": "definition-2.3.7.jar",
          "size": 425796,
          "sha512": "8f4a161e4082137839570374d9a62821806bd8ac8e9a364b80cc0cfac5bd2a4db9ceab7879673ff01f4020072c5a3c1c2d6bd3bbb42d63644ffe0f1a1a6571ea",
          "sha256": "d9be0ed8b9d1c5438952307ad5c85b28838dc44b29a45785c7d09c7cb70635e8",
          "sha1": "218c5ca691131f90f78e60dbe863e20503113345",
          "md5": "ee31b05a87fb4af0a8cd0ad163907c2e"
        }
      ]
    }
  ]
}
