{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-2.4.0.jar",
          "url": "osrs-2.4.0.jar",
          "size": 87689,
          "sha512": "d3cc3c52a376f9109421528e4348273bcda04e98896407057bdf08c1ea101c4c8ec25997102d1c211fc1ad604c827d8bf708b9ffc59cff8dd96cdcafad57401f",
          "sha256": "4c4888bc684d3565646d585e55d37e51bf7a83de53fdb2c82bcf10f5d605f24e",
          "sha1": "778e3d80df274040f51da7dca51491ad09a6067f",
          "md5": "fbdc95f123c5a643dbd0bc570dd78c56"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-2.4.0.jar",
          "url": "osrs-2.4.0.jar",
          "size": 87689,
          "sha512": "d3cc3c52a376f9109421528e4348273bcda04e98896407057bdf08c1ea101c4c8ec25997102d1c211fc1ad604c827d8bf708b9ffc59cff8dd96cdcafad57401f",
          "sha256": "4c4888bc684d3565646d585e55d37e51bf7a83de53fdb2c82bcf10f5d605f24e",
          "sha1": "778e3d80df274040f51da7dca51491ad09a6067f",
          "md5": "fbdc95f123c5a643dbd0bc570dd78c56"
        }
      ]
    }
  ]
}
