{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718-fs",
    "version": "2.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-fs-2.4.4.jar",
          "url": "r718-fs-2.4.4.jar",
          "size": 7620,
          "sha512": "4575cee120df0e28d3ccaed085050c0a755208535071e4ddebabdf8df49072282cda35a241be47e5fd06fdd4c414039f3acae0d8804dbc25ce002ab5655c6e19",
          "sha256": "2c1248632a6ba05feb03040ba5b2183ce1e8a9a257d68bfb559b0e3d82d6b3f6",
          "sha1": "c523c4b27e6096fea58a66f3c6b72aac2418d0dc",
          "md5": "60084a8d1c140d778e22e3204406bc54"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.4.4"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.4"
          }
        },
        {
          "group": "dev.or2",
          "module": "r718",
          "version": {
            "requires": "2.4.4"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "r718-fs-2.4.4.jar",
          "url": "r718-fs-2.4.4.jar",
          "size": 7620,
          "sha512": "4575cee120df0e28d3ccaed085050c0a755208535071e4ddebabdf8df49072282cda35a241be47e5fd06fdd4c414039f3acae0d8804dbc25ce002ab5655c6e19",
          "sha256": "2c1248632a6ba05feb03040ba5b2183ce1e8a9a257d68bfb559b0e3d82d6b3f6",
          "sha1": "c523c4b27e6096fea58a66f3c6b72aac2418d0dc",
          "md5": "60084a8d1c140d778e22e3204406bc54"
        }
      ]
    }
  ]
}
