{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "filestore",
    "version": "1.3.5-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-1.3.5-beta.jar",
          "url": "filestore-1.3.5-beta.jar",
          "size": 219030,
          "sha512": "fce36f2b9075a15341341276a28ffb65344f3943a68cac07d3163b5ca1ffbf7efb38a198e0d918de1d74a087ab74ff4fa6e32a5afd40c2b698ec2b32ec068b34",
          "sha256": "2018ae6153c8a6aa45bd93fe5f728adf5fa5ddcf3ae69334b4319889fee6a2ab",
          "sha1": "05d1150f2a42c2a9b0512a9fdd28cfb0ce02862e",
          "md5": "2e1c6853eb6f091e1544bc44d1b4c7eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-1.3.5-beta.jar",
          "url": "filestore-1.3.5-beta.jar",
          "size": 219030,
          "sha512": "fce36f2b9075a15341341276a28ffb65344f3943a68cac07d3163b5ca1ffbf7efb38a198e0d918de1d74a087ab74ff4fa6e32a5afd40c2b698ec2b32ec068b34",
          "sha256": "2018ae6153c8a6aa45bd93fe5f728adf5fa5ddcf3ae69334b4319889fee6a2ab",
          "sha1": "05d1150f2a42c2a9b0512a9fdd28cfb0ce02862e",
          "md5": "2e1c6853eb6f091e1544bc44d1b4c7eb"
        }
      ]
    }
  ]
}
