{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "filestore",
    "version": "1.3.5-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-1.3.5-beta.jar",
          "url": "filestore-1.3.5-beta.jar",
          "size": 218974,
          "sha512": "28c985647aec0827c8671eba6963e58cd31e0fc6f6d9592f1105b33993d31cc1e0193326521c04d5e367682c20e300b3f672a17ede37ac253b7ad06ec60b776b",
          "sha256": "adae536594c44da8525ba23510376f001efd4b6825b2c503aeb1f7b6f74551bd",
          "sha1": "2d73e1fd4575f7a7f87407d2a0caed3951e99fff",
          "md5": "20a035c6f3991a669020e8cc496e3303"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-1.3.5-beta.jar",
          "url": "filestore-1.3.5-beta.jar",
          "size": 218974,
          "sha512": "28c985647aec0827c8671eba6963e58cd31e0fc6f6d9592f1105b33993d31cc1e0193326521c04d5e367682c20e300b3f672a17ede37ac253b7ad06ec60b776b",
          "sha256": "adae536594c44da8525ba23510376f001efd4b6825b2c503aeb1f7b6f74551bd",
          "sha1": "2d73e1fd4575f7a7f87407d2a0caed3951e99fff",
          "md5": "20a035c6f3991a669020e8cc496e3303"
        }
      ]
    }
  ]
}
