{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718-fs",
    "version": "2.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-fs-2.4.6.jar",
          "url": "r718-fs-2.4.6.jar",
          "size": 7588,
          "sha512": "a16cf33b2eb7293e8842dc700dc0deff4034d6f227df6f98656bb5c9e2960de18b153ecde92780461de6588849a500e139a9a6a2470fad6b55fe1cc6584b3220",
          "sha256": "ba834ea2c5e2b886d9e5dec3531550945382fe7794cbe64ca02c909a0f57cb06",
          "sha1": "7d4e4b06af340a595fcb3ccaaec92759fa68c72b",
          "md5": "6fc72e5f39500262c3d7205cf2d4a0bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.4.6"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.6"
          }
        },
        {
          "group": "dev.or2",
          "module": "r718",
          "version": {
            "requires": "2.4.6"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.6"
          }
        }
      ],
      "files": [
        {
          "name": "r718-fs-2.4.6.jar",
          "url": "r718-fs-2.4.6.jar",
          "size": 7588,
          "sha512": "a16cf33b2eb7293e8842dc700dc0deff4034d6f227df6f98656bb5c9e2960de18b153ecde92780461de6588849a500e139a9a6a2470fad6b55fe1cc6584b3220",
          "sha256": "ba834ea2c5e2b886d9e5dec3531550945382fe7794cbe64ca02c909a0f57cb06",
          "sha1": "7d4e4b06af340a595fcb3ccaaec92759fa68c72b",
          "md5": "6fc72e5f39500262c3d7205cf2d4a0bd"
        }
      ]
    }
  ]
}
