{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filestore",
    "version": "2.0.92",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-2.0.92.jar",
          "url": "filestore-2.0.92.jar",
          "size": 24242,
          "sha512": "5459483cc7e16323b8aebe133a1ce697a5f2c39ddffe9b4771b9fd0c24a94f5341f67c1a0af324525fac1e27745f2f34b6d82d5e8ffb1581f19bbfb1ad4499b3",
          "sha256": "2c0e48a5f41e4236189273e446692192504ed0887fa1d22b8efdd6df43eafd4b",
          "sha1": "4d2d1dc131c11d95ae370ac51f2fb2f40fdc5323",
          "md5": "9c73a4dfb6e2c2f6ca4f8c6482ad0020"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.92"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.0.92"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-2.0.92.jar",
          "url": "filestore-2.0.92.jar",
          "size": 24242,
          "sha512": "5459483cc7e16323b8aebe133a1ce697a5f2c39ddffe9b4771b9fd0c24a94f5341f67c1a0af324525fac1e27745f2f34b6d82d5e8ffb1581f19bbfb1ad4499b3",
          "sha256": "2c0e48a5f41e4236189273e446692192504ed0887fa1d22b8efdd6df43eafd4b",
          "sha1": "4d2d1dc131c11d95ae370ac51f2fb2f40fdc5323",
          "md5": "9c73a4dfb6e2c2f6ca4f8c6482ad0020"
        }
      ]
    }
  ]
}
