{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "definition",
    "version": "2.4.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "definition-2.4.19.jar",
          "url": "definition-2.4.19.jar",
          "size": 551096,
          "sha512": "5bc5db77ddf1aa4adec462b7963a5a31ccb654b4a55a336df33ebc4fcb085af62669f2f2b4e6f337f0dd8182c3d8c7002c1ab34f35279195eccc2c696d078675",
          "sha256": "31d34f84bb875ebb09630314cdced6ce7180f0c7da6458962850d2ae93a33836",
          "sha1": "053731cfdbc3a8be39f36cdf32ec7e68011472f7",
          "md5": "0ea523222d255ed0bc55468e62f1a7ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "toml-core",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "definition-2.4.19.jar",
          "url": "definition-2.4.19.jar",
          "size": 551096,
          "sha512": "5bc5db77ddf1aa4adec462b7963a5a31ccb654b4a55a336df33ebc4fcb085af62669f2f2b4e6f337f0dd8182c3d8c7002c1ab34f35279195eccc2c696d078675",
          "sha256": "31d34f84bb875ebb09630314cdced6ce7180f0c7da6458962850d2ae93a33836",
          "sha1": "053731cfdbc3a8be39f36cdf32ec7e68011472f7",
          "md5": "0ea523222d255ed0bc55468e62f1a7ce"
        }
      ]
    }
  ]
}
