{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.2.1.jar",
          "url": "displee-2.2.1.jar",
          "size": 111913,
          "sha512": "71df0f826393f7d21cf56ad2ccf8ddf5d008420028878f23825dab50dc34085be6179a0f4e6695d3ff6cc278a6181ebb50e2ca2991aecfcaec70d40619003cf8",
          "sha256": "0294ce05c6613f722b9a3952b531c7dc18a18f04ca71b90d6143885091ed55bc",
          "sha1": "1788548d8c8b26c237357d84dc91d2cd01f32eb5",
          "md5": "0fba4db85efbeaf1d3383d8470d95b8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.2.1.jar",
          "url": "displee-2.2.1.jar",
          "size": 111913,
          "sha512": "71df0f826393f7d21cf56ad2ccf8ddf5d008420028878f23825dab50dc34085be6179a0f4e6695d3ff6cc278a6181ebb50e2ca2991aecfcaec70d40619003cf8",
          "sha256": "0294ce05c6613f722b9a3952b531c7dc18a18f04ca71b90d6143885091ed55bc",
          "sha1": "1788548d8c8b26c237357d84dc91d2cd01f32eb5",
          "md5": "0fba4db85efbeaf1d3383d8470d95b8b"
        }
      ]
    }
  ]
}
