{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718",
    "version": "2.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-2.3.8.jar",
          "url": "r718-2.3.8.jar",
          "size": 14408,
          "sha512": "b55a140cd5122ab6967b3434778100ebeda99c520cc030274f26aac00dc66c20d480455ee2bcc7038c6947637cd232471abe698f6077ef5b02ec460f1c7282a1",
          "sha256": "e5c009837cd4e9c48bdec8c30c4928316aefc798f86e83dcb32a013c4a2fda8f",
          "sha1": "1ccd145daab267a1bca99d1de6ad4f4f8b1af665",
          "md5": "fcdc163ddf3b7ea5fa6741924c56b897"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "r718-2.3.8.jar",
          "url": "r718-2.3.8.jar",
          "size": 14408,
          "sha512": "b55a140cd5122ab6967b3434778100ebeda99c520cc030274f26aac00dc66c20d480455ee2bcc7038c6947637cd232471abe698f6077ef5b02ec460f1c7282a1",
          "sha256": "e5c009837cd4e9c48bdec8c30c4928316aefc798f86e83dcb32a013c4a2fda8f",
          "sha1": "1ccd145daab267a1bca99d1de6ad4f4f8b1af665",
          "md5": "fcdc163ddf3b7ea5fa6741924c56b897"
        }
      ]
    }
  ]
}
