{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filestore",
    "version": "2.4.2-cache",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-2.4.2-cache.jar",
          "url": "filestore-2.4.2-cache.jar",
          "size": 94965,
          "sha512": "9d2b4e22af44153d137c67867551c5c5a8eec30248da97f570f946b2e3e675077a3036cf595357fbc48f3ee4d89d5e7e1b33afafc9f3078e489138d6677711e5",
          "sha256": "d87cb7de1bccb759cb2c659c2de5d5582033741d7115c92733f4426d54426722",
          "sha1": "b06efc37935513200b1b9e7aa70be14cc90d63c1",
          "md5": "a671fc4de99acfd0c982699a89873c39"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.2-cache"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "cache",
          "version": {
            "requires": "2.4.2-cache"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-2.4.2-cache.jar",
          "url": "filestore-2.4.2-cache.jar",
          "size": 94965,
          "sha512": "9d2b4e22af44153d137c67867551c5c5a8eec30248da97f570f946b2e3e675077a3036cf595357fbc48f3ee4d89d5e7e1b33afafc9f3078e489138d6677711e5",
          "sha256": "d87cb7de1bccb759cb2c659c2de5d5582033741d7115c92733f4426d54426722",
          "sha1": "b06efc37935513200b1b9e7aa70be14cc90d63c1",
          "md5": "a671fc4de99acfd0c982699a89873c39"
        }
      ]
    }
  ]
}
