{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filestore",
    "version": "2.4.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filestore-2.4.14.jar",
          "url": "filestore-2.4.14.jar",
          "size": 97552,
          "sha512": "9e6a898896c7b4ae651e978e86085481256ae317215d8c9701b33df3c8f334fb8d5d6b4edfb4755fcad6f1191f85587f8ed05525b885e7bf2125e8c21ab5405c",
          "sha256": "5623c977a1cb8113caab6f5f33a6bd1cf866fe3516380870a311b4283baa2e81",
          "sha1": "52d31b38ae396b0069a199611aee1d992366d05c",
          "md5": "2fa8b38cf941f9750760d47eebf21eef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.14"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.14"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-2.4.14.jar",
          "url": "filestore-2.4.14.jar",
          "size": 97552,
          "sha512": "9e6a898896c7b4ae651e978e86085481256ae317215d8c9701b33df3c8f334fb8d5d6b4edfb4755fcad6f1191f85587f8ed05525b885e7bf2125e8c21ab5405c",
          "sha256": "5623c977a1cb8113caab6f5f33a6bd1cf866fe3516380870a311b4283baa2e81",
          "sha1": "52d31b38ae396b0069a199611aee1d992366d05c",
          "md5": "2fa8b38cf941f9750760d47eebf21eef"
        }
      ]
    }
  ]
}
