{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filestore-server",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-server-0.3.jar",
          "url": "filestore-server-0.3.jar",
          "size": 894524,
          "sha512": "87eab73bead44d1a4df5a0e77f91e1825f03c61c6f786f82fa8a80be1fc74970a0513df9290787644676dce12f2ea17cdd68b6ffb33d0f636671f6cfb335664d",
          "sha256": "75b9caa6e830440ca1b9e76d071ab7b1239f367e9095978b5e5a95e7e2e56171",
          "sha1": "d7346dbf8d636fde4994b870034bdbf51f4f3e8c",
          "md5": "df310e81c57cbb66ffb8db53549eff5b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.or2",
          "module": "all",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-all",
          "version": {
            "requires": "5.0.0.Alpha2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-server-0.3.jar",
          "url": "filestore-server-0.3.jar",
          "size": 894524,
          "sha512": "87eab73bead44d1a4df5a0e77f91e1825f03c61c6f786f82fa8a80be1fc74970a0513df9290787644676dce12f2ea17cdd68b6ffb33d0f636671f6cfb335664d",
          "sha256": "75b9caa6e830440ca1b9e76d071ab7b1239f367e9095978b5e5a95e7e2e56171",
          "sha1": "d7346dbf8d636fde4994b870034bdbf51f4f3e8c",
          "md5": "df310e81c57cbb66ffb8db53549eff5b"
        }
      ]
    }
  ]
}
