{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs",
    "version": "2.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-2.4.3.jar",
          "url": "osrs-2.4.3.jar",
          "size": 87691,
          "sha512": "e8a7193308768f2d0c8db3ea49992b4a4e7ea7e23ecc14beee5e867d07f4505f4c6729a3fea31f2a8508c7d2708d4fef3c5f7415718dfba0af51d89d01201f70",
          "sha256": "ee6f58da7dc895872c6b65948ab52d741974df6c13108193e1e4ab2712197e26",
          "sha1": "ac1443bfcd68b201bdeb23ac9be6fd2c75e76f4d",
          "md5": "b1959adf987780475512cca48693e555"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-2.4.3.jar",
          "url": "osrs-2.4.3.jar",
          "size": 87691,
          "sha512": "e8a7193308768f2d0c8db3ea49992b4a4e7ea7e23ecc14beee5e867d07f4505f4c6729a3fea31f2a8508c7d2708d4fef3c5f7415718dfba0af51d89d01201f70",
          "sha256": "ee6f58da7dc895872c6b65948ab52d741974df6c13108193e1e4ab2712197e26",
          "sha1": "ac1443bfcd68b201bdeb23ac9be6fd2c75e76f4d",
          "md5": "b1959adf987780475512cca48693e555"
        }
      ]
    }
  ]
}
