{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs-fs",
    "version": "2.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-fs-2.4.2.jar",
          "url": "osrs-fs-2.4.2.jar",
          "size": 26599,
          "sha512": "2121644f01b00a0ff858c8ae1e3907354ac6b1a9658fd284197840439e59d9e401bade3355d9ee7440c997faf40706808e1b691e1e0c81bce3a32d35b760bdaa",
          "sha256": "c0ce0d2151dd1dc666ed84a9eea5cc002bf8a93da7c87bbc63f11da5f43238b5",
          "sha1": "1a1863ce4cbbbd4a3b53fc06f908162c5f657b0c",
          "md5": "7f0941dd01047e9df2609dcd5aa0bbd0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-fs-2.4.2.jar",
          "url": "osrs-fs-2.4.2.jar",
          "size": 26599,
          "sha512": "2121644f01b00a0ff858c8ae1e3907354ac6b1a9658fd284197840439e59d9e401bade3355d9ee7440c997faf40706808e1b691e1e0c81bce3a32d35b760bdaa",
          "sha256": "c0ce0d2151dd1dc666ed84a9eea5cc002bf8a93da7c87bbc63f11da5f43238b5",
          "sha1": "1a1863ce4cbbbd4a3b53fc06f908162c5f657b0c",
          "md5": "7f0941dd01047e9df2609dcd5aa0bbd0"
        }
      ]
    }
  ]
}
