{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.4.1.jar",
          "url": "displee-2.4.1.jar",
          "size": 111913,
          "sha512": "dc36bd7ff969725fc1b2920243dbcdb3d86df6d77f51461a4ba0e6cac4d7362a16871fdc473c2c22c9276c7098b82e74581c7ba062e29b7c7d56dbdec6860734",
          "sha256": "04b1b3445c4defaa63e0d3df7e08a35278f4ad72080021cd0c9ceaced730ad3b",
          "sha1": "110a95a445ed805f1d33c615708a7cfa26ef0e50",
          "md5": "7fd831e3b22cd7ab659fc4fdfccf5121"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.4.1.jar",
          "url": "displee-2.4.1.jar",
          "size": 111913,
          "sha512": "dc36bd7ff969725fc1b2920243dbcdb3d86df6d77f51461a4ba0e6cac4d7362a16871fdc473c2c22c9276c7098b82e74581c7ba062e29b7c7d56dbdec6860734",
          "sha256": "04b1b3445c4defaa63e0d3df7e08a35278f4ad72080021cd0c9ceaced730ad3b",
          "sha1": "110a95a445ed805f1d33c615708a7cfa26ef0e50",
          "md5": "7fd831e3b22cd7ab659fc4fdfccf5121"
        }
      ]
    }
  ]
}
