{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs",
    "version": "2.0.91",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-2.0.91.jar",
          "url": "osrs-2.0.91.jar",
          "size": 73215,
          "sha512": "a647c861b77d3cbcf13658beadfdd6f675707fc9b1b65c275f0f9258bc18f27caf94a78c3ebd9b8f277662e84f725c275e3e20b2963b9acb5751934344fa8321",
          "sha256": "1584f53d2063c4f0a5d44e34f288f981aa8f13f930065ff8be3bdc3db14de8d1",
          "sha1": "b65045ed943fedc21ec5082ee3389ad3654cf1d4",
          "md5": "34381940a9b62e00a7e4c5e00a29e998"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.91"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-2.0.91.jar",
          "url": "osrs-2.0.91.jar",
          "size": 73215,
          "sha512": "a647c861b77d3cbcf13658beadfdd6f675707fc9b1b65c275f0f9258bc18f27caf94a78c3ebd9b8f277662e84f725c275e3e20b2963b9acb5751934344fa8321",
          "sha256": "1584f53d2063c4f0a5d44e34f288f981aa8f13f930065ff8be3bdc3db14de8d1",
          "sha1": "b65045ed943fedc21ec5082ee3389ad3654cf1d4",
          "md5": "34381940a9b62e00a7e4c5e00a29e998"
        }
      ]
    }
  ]
}
