{
  "formatVersion": "1.1",
  "component": {
    "group": "me.filby",
    "module": "clientscript-compiler",
    "version": "0.0.7-openrune",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.filby",
          "module": "runescript-compiler",
          "version": {
            "requires": "0.0.7-openrune"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "clientscript-compiler-0.0.7-openrune.jar",
          "url": "clientscript-compiler-0.0.7-openrune.jar",
          "size": 1577914,
          "sha512": "87b6e944ea2e77b8f1b342f6e00d7c7e911090aaa5d7d18ae57556c21b795d308792d6ba81f76f5f1a7852b25ed294a5c2d76ad49367854261930b5c1fc0aad9",
          "sha256": "e15c930ae092fc3aa2f2fca96d1c19fef2167174bf77920b0bce5e1d6d6cd166",
          "sha1": "e51596cafbfa9b3b3a39a1413bf0b503fa874571",
          "md5": "fc88cedb1584fb11005f17f6d6f18454"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.0-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.116.Final"
          }
        },
        {
          "group": "cc.ekblad",
          "module": "4koma",
          "version": {
            "requires": "1.2.0-openrune"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          },
          "excludes": [
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.11"
          }
        },
        {
          "group": "me.filby",
          "module": "runescript-compiler",
          "version": {
            "requires": "0.0.7-openrune"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "clientscript-compiler-0.0.7-openrune.jar",
          "url": "clientscript-compiler-0.0.7-openrune.jar",
          "size": 1577914,
          "sha512": "87b6e944ea2e77b8f1b342f6e00d7c7e911090aaa5d7d18ae57556c21b795d308792d6ba81f76f5f1a7852b25ed294a5c2d76ad49367854261930b5c1fc0aad9",
          "sha256": "e15c930ae092fc3aa2f2fca96d1c19fef2167174bf77920b0bce5e1d6d6cd166",
          "sha1": "e51596cafbfa9b3b3a39a1413bf0b503fa874571",
          "md5": "fc88cedb1584fb11005f17f6d6f18454"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "clientscript-compiler-0.0.7-openrune-sources.jar",
          "url": "clientscript-compiler-0.0.7-openrune-sources.jar",
          "size": 1414015,
          "sha512": "997b82cd95dbeeae39d2682d85cd327aae226c511c55b014397125a7342fdac9ad0a9f20da4948189311e16d77f336c0b1a3bafa7f7a8639221be72f12dd53dd",
          "sha256": "14e6d7d6d9b045ba6592b7deedd073a54361ae26cc170d4a7aed3665ecd68cb3",
          "sha1": "3606f5225df16aae44bc11737ee49c84c2ab71f4",
          "md5": "fd2a0e1b90c1f95d03cd1ce59395b0f6"
        },
        {
          "name": "clientscript-compiler-0.0.7-openrune-sources.jar",
          "url": "clientscript-compiler-0.0.7-openrune-sources.jar",
          "size": 1414015,
          "sha512": "997b82cd95dbeeae39d2682d85cd327aae226c511c55b014397125a7342fdac9ad0a9f20da4948189311e16d77f336c0b1a3bafa7f7a8639221be72f12dd53dd",
          "sha256": "14e6d7d6d9b045ba6592b7deedd073a54361ae26cc170d4a7aed3665ecd68cb3",
          "sha1": "3606f5225df16aae44bc11737ee49c84c2ab71f4",
          "md5": "fd2a0e1b90c1f95d03cd1ce59395b0f6"
        }
      ]
    }
  ]
}
