{
  "formatVersion": "1.1",
  "component": {
    "group": "me.filby",
    "module": "clientscript-compiler",
    "version": "0.0.7-openrune",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.filby",
          "module": "runescript-compiler",
          "version": {
            "requires": "0.0.7-openrune"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "clientscript-compiler-0.0.7-openrune.jar",
          "url": "clientscript-compiler-0.0.7-openrune.jar",
          "size": 1576534,
          "sha512": "21c5c993532ae18b30a57f9a7356a843a7ba9cc682048293c24f7ececdbe0729f4ed211695f9bb2155c497d4a6891de5580e1917d78c23d2c174e1919f140572",
          "sha256": "d3c203d8d0e241aefd7e490b8c01e5482a06291eb0cbaaca70192e8f9e8ee4c6",
          "sha1": "eda8b19a5ad07abaff3d11c727a263fe25efed8c",
          "md5": "653ba547e774c639a977ee3ec451b348"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.0-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.116.Final"
          }
        },
        {
          "group": "cc.ekblad",
          "module": "4koma",
          "version": {
            "requires": "1.2.0-openrune"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          },
          "excludes": [
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.11"
          }
        },
        {
          "group": "me.filby",
          "module": "runescript-compiler",
          "version": {
            "requires": "0.0.7-openrune"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "clientscript-compiler-0.0.7-openrune.jar",
          "url": "clientscript-compiler-0.0.7-openrune.jar",
          "size": 1576534,
          "sha512": "21c5c993532ae18b30a57f9a7356a843a7ba9cc682048293c24f7ececdbe0729f4ed211695f9bb2155c497d4a6891de5580e1917d78c23d2c174e1919f140572",
          "sha256": "d3c203d8d0e241aefd7e490b8c01e5482a06291eb0cbaaca70192e8f9e8ee4c6",
          "sha1": "eda8b19a5ad07abaff3d11c727a263fe25efed8c",
          "md5": "653ba547e774c639a977ee3ec451b348"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "clientscript-compiler-0.0.7-openrune-sources.jar",
          "url": "clientscript-compiler-0.0.7-openrune-sources.jar",
          "size": 1413637,
          "sha512": "acc76886c888bc489bba06998136a9882eda0fff4fc21f1be20506d8b7558e2ca642d2e0a9c2afbc3f1263ea489ef4d8bd767b3c4504a2f16b44bdb64f8fc4a5",
          "sha256": "e358c7a21a6606984e6a6ddc27b49ec622289e5f5e151057d9d296db053d11f9",
          "sha1": "c7ae050842c91b03dd250d8b6040e217909c46ba",
          "md5": "4da1f5f6ad97255a5d634e74bfdff16e"
        },
        {
          "name": "clientscript-compiler-0.0.7-openrune-sources.jar",
          "url": "clientscript-compiler-0.0.7-openrune-sources.jar",
          "size": 1413637,
          "sha512": "acc76886c888bc489bba06998136a9882eda0fff4fc21f1be20506d8b7558e2ca642d2e0a9c2afbc3f1263ea489ef4d8bd767b3c4504a2f16b44bdb64f8fc4a5",
          "sha256": "e358c7a21a6606984e6a6ddc27b49ec622289e5f5e151057d9d296db053d11f9",
          "sha1": "c7ae050842c91b03dd250d8b6040e217909c46ba",
          "md5": "4da1f5f6ad97255a5d634e74bfdff16e"
        }
      ]
    }
  ]
}
