{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs-fs",
    "version": "2.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-fs-2.0.12.jar",
          "url": "osrs-fs-2.0.12.jar",
          "size": 23585,
          "sha512": "a6f912c6e2cb900248c1ec5f7607aa3eb47903de4ffd75f8f1df91bacb1d7d03bc2eda0eeb44749d5b2cdeda19612eaeac13c448a8381e292481a782c36982b3",
          "sha256": "55bf8f3210a2f48580bd9ef7c6a8dc7ec68a0a3342f9db6b3e88787307932f56",
          "sha1": "78c0b2fb84129444dc8c0b31f162c632198776a2",
          "md5": "aaf71bddb904fa9bd0c475d501d05017"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.0.12"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.0.12"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.0.12"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.12"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-fs-2.0.12.jar",
          "url": "osrs-fs-2.0.12.jar",
          "size": 23585,
          "sha512": "a6f912c6e2cb900248c1ec5f7607aa3eb47903de4ffd75f8f1df91bacb1d7d03bc2eda0eeb44749d5b2cdeda19612eaeac13c448a8381e292481a782c36982b3",
          "sha256": "55bf8f3210a2f48580bd9ef7c6a8dc7ec68a0a3342f9db6b3e88787307932f56",
          "sha1": "78c0b2fb84129444dc8c0b31f162c632198776a2",
          "md5": "aaf71bddb904fa9bd0c475d501d05017"
        }
      ]
    }
  ]
}
