{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.2.4.jar",
          "url": "displee-2.2.4.jar",
          "size": 111913,
          "sha512": "f27544a935ecd8d59a8626ce24c6d357575fc5aaccf73e598c6f31c0d8ab26b3d8a54353320f0b4f2f87e6ab40c0199c6e16ff5562102834956126b29408af7f",
          "sha256": "1c53ab7b83797d7765061043f438ba82ddbc4b724535b53442c32876235f6878",
          "sha1": "ae822308c06fab7e472e7c104c5cc43c9f236ca1",
          "md5": "f77dbf390a1c3bdd025e66c31ed3b177"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.2.4.jar",
          "url": "displee-2.2.4.jar",
          "size": 111913,
          "sha512": "f27544a935ecd8d59a8626ce24c6d357575fc5aaccf73e598c6f31c0d8ab26b3d8a54353320f0b4f2f87e6ab40c0199c6e16ff5562102834956126b29408af7f",
          "sha256": "1c53ab7b83797d7765061043f438ba82ddbc4b724535b53442c32876235f6878",
          "sha1": "ae822308c06fab7e472e7c104c5cc43c9f236ca1",
          "md5": "f77dbf390a1c3bdd025e66c31ed3b177"
        }
      ]
    }
  ]
}
