{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "2.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-2.2.7.jar",
          "url": "displee-2.2.7.jar",
          "size": 111913,
          "sha512": "f82c6cbf73a48d94b87154a33e0059bfd5402a8f981ddb287e8203b726416ba629402859ba5b4883c942679ab097d3b3bdf79535d33d4c758209188d20032575",
          "sha256": "b3aad9c00de50044aabaefaca24982cb743d707ecb0a5fd7c900509f9ebee995",
          "sha1": "0c96a999cf4804df8ce12f97f793f94e304d875b",
          "md5": "8a1e3089f8dda2876de505455b7ba118"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-2.2.7.jar",
          "url": "displee-2.2.7.jar",
          "size": 111913,
          "sha512": "f82c6cbf73a48d94b87154a33e0059bfd5402a8f981ddb287e8203b726416ba629402859ba5b4883c942679ab097d3b3bdf79535d33d4c758209188d20032575",
          "sha256": "b3aad9c00de50044aabaefaca24982cb743d707ecb0a5fd7c900509f9ebee995",
          "sha1": "0c96a999cf4804df8ce12f97f793f94e304d875b",
          "md5": "8a1e3089f8dda2876de505455b7ba118"
        }
      ]
    }
  ]
}
