{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "osrs-fs",
    "version": "2.4.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "osrs-fs-2.4.15.jar",
          "url": "osrs-fs-2.4.15.jar",
          "size": 27384,
          "sha512": "f5c53545ef5ccb91c727022d2c212a07b8c34553fccfb414683410d0c3bba5ab4e95db569e1c650030518a620bdc33b316a6086b4ee2b7fa37018d395718d60c",
          "sha256": "782d6d71037ccda6f52648d453167a9a19ce0415b95b5481635cbd3987675c0e",
          "sha1": "3309e34d45e5438458ac5e29496444c6db27854c",
          "md5": "e4f9f29907cddaa6916b3b0080656d56"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.4.15"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.4.15"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.4.15"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.15"
          }
        }
      ],
      "files": [
        {
          "name": "osrs-fs-2.4.15.jar",
          "url": "osrs-fs-2.4.15.jar",
          "size": 27384,
          "sha512": "f5c53545ef5ccb91c727022d2c212a07b8c34553fccfb414683410d0c3bba5ab4e95db569e1c650030518a620bdc33b316a6086b4ee2b7fa37018d395718d60c",
          "sha256": "782d6d71037ccda6f52648d453167a9a19ce0415b95b5481635cbd3987675c0e",
          "sha1": "3309e34d45e5438458ac5e29496444c6db27854c",
          "md5": "e4f9f29907cddaa6916b3b0080656d56"
        }
      ]
    }
  ]
}
