{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "tools",
    "version": "2.0.16.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "tools-2.0.16.2.jar",
          "url": "tools-2.0.16.2.jar",
          "size": 318269,
          "sha512": "d5e3017b4a11f331013f9fa0243eb8de991401f13c63b6f990fc2676d78476bb7a86972f8e26ee25a1f52a047d87a3659b8db0995f7415df55ae6c5c2d44a222",
          "sha256": "02d32d117f2f1219b7b08c1599e87847a456a4eda21ca35848f2a49baca03870",
          "sha1": "f637bd73ef7131ea1d02cb683259f7b164fe9406",
          "md5": "ddef8b7b965f1b0d24517c607a68691f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.0.16.2"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.0.16.2"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.0.16.2"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs",
          "version": {
            "requires": "2.0.16.2"
          }
        },
        {
          "group": "dev.or2",
          "module": "osrs-fs",
          "version": {
            "requires": "2.0.16.2"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.11.5"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "dev.or2",
          "module": "displee",
          "version": {
            "requires": "2.0.16.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "cc.ekblad",
          "module": "4koma",
          "version": {
            "requires": "1.2.2-openrune"
          }
        },
        {
          "group": "me.filby",
          "module": "clientscript-compiler",
          "version": {
            "requires": "0.0.2-openrune"
          }
        }
      ],
      "files": [
        {
          "name": "tools-2.0.16.2.jar",
          "url": "tools-2.0.16.2.jar",
          "size": 318269,
          "sha512": "d5e3017b4a11f331013f9fa0243eb8de991401f13c63b6f990fc2676d78476bb7a86972f8e26ee25a1f52a047d87a3659b8db0995f7415df55ae6c5c2d44a222",
          "sha256": "02d32d117f2f1219b7b08c1599e87847a456a4eda21ca35848f2a49baca03870",
          "sha1": "f637bd73ef7131ea1d02cb683259f7b164fe9406",
          "md5": "ddef8b7b965f1b0d24517c607a68691f"
        }
      ]
    }
  ]
}
