{
  "formatVersion": "1.1",
  "component": {
    "group": "org.openrs2",
    "module": "openrs2-deob-util",
    "version": "0.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.openrs2",
          "module": "openrs2-asm",
          "version": {
            "requires": "0.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.openrs2",
          "module": "openrs2-yaml",
          "version": {
            "requires": "0.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "openrs2-deob-util-0.1.2-SNAPSHOT.jar",
          "url": "openrs2-deob-util-0.1.2-SNAPSHOT.jar",
          "size": 16160,
          "sha512": "02d5cf676192520ddb4fbe2e504c39e6a517e856b8f1f20562f684f6931375586f9a108039f11f23dc74c9993cb7d29d33a1f5f3ac4fad9ad8eb50d02b80112c",
          "sha256": "be5ca7b1d8b748027e31e5007b09ef9c70355d31107be0cce0e283de3891d1c9",
          "sha1": "4d0584218b6c28bd5752c53d7dd11ee72472575d",
          "md5": "ac6fd1930bf914d32fcb58fcdff9ef2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "org.openrs2",
          "module": "openrs2-asm",
          "version": {
            "requires": "0.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.openrs2",
          "module": "openrs2-yaml",
          "version": {
            "requires": "0.1.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "openrs2-deob-util-0.1.2-SNAPSHOT.jar",
          "url": "openrs2-deob-util-0.1.2-SNAPSHOT.jar",
          "size": 16160,
          "sha512": "02d5cf676192520ddb4fbe2e504c39e6a517e856b8f1f20562f684f6931375586f9a108039f11f23dc74c9993cb7d29d33a1f5f3ac4fad9ad8eb50d02b80112c",
          "sha256": "be5ca7b1d8b748027e31e5007b09ef9c70355d31107be0cce0e283de3891d1c9",
          "sha1": "4d0584218b6c28bd5752c53d7dd11ee72472575d",
          "md5": "ac6fd1930bf914d32fcb58fcdff9ef2b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "openrs2-deob-util-0.1.2-SNAPSHOT-sources.jar",
          "url": "openrs2-deob-util-0.1.2-SNAPSHOT-sources.jar",
          "size": 3605,
          "sha512": "efdcb4ad1a7c05e17539ba393de72189466a5a4c9cdf4841442af597be8fcd57b806e782c33a077cacf5631456f571d4eb2f7544f20705406fe968819faca55a",
          "sha256": "5e663ba35a58d7ccda6bb36a1091ce2c3f11a571a570254e37dcd0df516baa75",
          "sha1": "25f850850cf5b3cca1088d3f62ebe6bf43b8d003",
          "md5": "3280e40373ab6622db2749cd8591923d"
        },
        {
          "name": "openrs2-deob-util-0.1.2-SNAPSHOT-sources.jar",
          "url": "openrs2-deob-util-0.1.2-SNAPSHOT-sources.jar",
          "size": 3605,
          "sha512": "efdcb4ad1a7c05e17539ba393de72189466a5a4c9cdf4841442af597be8fcd57b806e782c33a077cacf5631456f571d4eb2f7544f20705406fe968819faca55a",
          "sha256": "5e663ba35a58d7ccda6bb36a1091ce2c3f11a571a570254e37dcd0df516baa75",
          "sha1": "25f850850cf5b3cca1088d3f62ebe6bf43b8d003",
          "md5": "3280e40373ab6622db2749cd8591923d"
        }
      ]
    }
  ]
}
