{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "displee",
    "version": "3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "displee-3.0.4.jar",
          "url": "displee-3.0.4.jar",
          "size": 119255,
          "sha512": "ff7038bc764690bb143b6453e1abc17c721bcf7721f35961a80443c312aa0b076cfe92e056768e5bfadb52d406d714e13d01781ca796cddf6d5d3bb0799d22f0",
          "sha256": "90b537ae85e30fc833803ef7b09da88ebb53cae792f1c37226d6f54cf01aeca6",
          "sha1": "8d1fc3a840cd3a301cc4452b0b1c92e0214b8f38",
          "md5": "ca9c2c03b77ab9e4620a453a02496b41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          }
        },
        {
          "group": "com.displee",
          "module": "disio",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "displee-3.0.4.jar",
          "url": "displee-3.0.4.jar",
          "size": 119255,
          "sha512": "ff7038bc764690bb143b6453e1abc17c721bcf7721f35961a80443c312aa0b076cfe92e056768e5bfadb52d406d714e13d01781ca796cddf6d5d3bb0799d22f0",
          "sha256": "90b537ae85e30fc833803ef7b09da88ebb53cae792f1c37226d6f54cf01aeca6",
          "sha1": "8d1fc3a840cd3a301cc4452b0b1c92e0214b8f38",
          "md5": "ca9c2c03b77ab9e4620a453a02496b41"
        }
      ]
    }
  ]
}
