{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718",
    "version": "3.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-3.0.4.jar",
          "url": "r718-3.0.4.jar",
          "size": 15441,
          "sha512": "52e955554096f23664ed9889e82826d6d50ce8a89aa11975e15b06c1e6d31361d20e712bd86ca7a800a46e64e2db91248d283c42017456b2429731494c560308",
          "sha256": "b40bdf7d7dd14ddda4844905f361e444d91549df67b88b5b28bc3fc215df32c2",
          "sha1": "e6c82eca441faeee2558a8d0e036433e2fa3bb3d",
          "md5": "6344b20257e731d38171045260d37dd9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "3.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "r718-3.0.4.jar",
          "url": "r718-3.0.4.jar",
          "size": 15441,
          "sha512": "52e955554096f23664ed9889e82826d6d50ce8a89aa11975e15b06c1e6d31361d20e712bd86ca7a800a46e64e2db91248d283c42017456b2429731494c560308",
          "sha256": "b40bdf7d7dd14ddda4844905f361e444d91549df67b88b5b28bc3fc215df32c2",
          "sha1": "e6c82eca441faeee2558a8d0e036433e2fa3bb3d",
          "md5": "6344b20257e731d38171045260d37dd9"
        }
      ]
    }
  ]
}
