{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "definition",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "definition-2.0.1.jar",
          "url": "definition-2.0.1.jar",
          "size": 306828,
          "sha512": "56855bfab3dd06b93f8ac999f40871ae2f0bc5438704d88080699d08327c0680c79da4170b710e7531f6f1d38670592e3dae73769c134b81feac5bfa56bc05ea",
          "sha256": "b729dffbb0d15dd764106a7574f3e9eb1909f2f2614b626e1565ec3b261cf8f9",
          "sha1": "9d1a810c9bcd7a9ff6ebb1188354889d35584b4e",
          "md5": "766954642e651660321626376011b0cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0-Beta1"
          }
        }
      ],
      "files": [
        {
          "name": "definition-2.0.1.jar",
          "url": "definition-2.0.1.jar",
          "size": 306828,
          "sha512": "56855bfab3dd06b93f8ac999f40871ae2f0bc5438704d88080699d08327c0680c79da4170b710e7531f6f1d38670592e3dae73769c134b81feac5bfa56bc05ea",
          "sha256": "b729dffbb0d15dd764106a7574f3e9eb1909f2f2614b626e1565ec3b261cf8f9",
          "sha1": "9d1a810c9bcd7a9ff6ebb1188354889d35584b4e",
          "md5": "766954642e651660321626376011b0cd"
        }
      ]
    }
  ]
}
