{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718",
    "version": "2.4.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-2.4.8.jar",
          "url": "r718-2.4.8.jar",
          "size": 14446,
          "sha512": "bef1c71d2866a2e7c0d79f5ab75ec814fc6230ee26e9ecff524c93900e3deaee3f840ed5fcb0b83bde72126900d0d66b7c0863c0a4e346fa3f3bcd92edbeae62",
          "sha256": "4b15001ecbc101791a1ababf6cf35d18412033512ac7df10f9bf51b9cccdc239",
          "sha1": "b21f2322f00012e878f8bbd3d2f07688b02a813a",
          "md5": "3df4b3b426a95f86d999a6fc16871edd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "r718-2.4.8.jar",
          "url": "r718-2.4.8.jar",
          "size": 14446,
          "sha512": "bef1c71d2866a2e7c0d79f5ab75ec814fc6230ee26e9ecff524c93900e3deaee3f840ed5fcb0b83bde72126900d0d66b7c0863c0a4e346fa3f3bcd92edbeae62",
          "sha256": "4b15001ecbc101791a1ababf6cf35d18412033512ac7df10f9bf51b9cccdc239",
          "sha1": "b21f2322f00012e878f8bbd3d2f07688b02a813a",
          "md5": "3df4b3b426a95f86d999a6fc16871edd"
        }
      ]
    }
  ]
}
