{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filesystem",
    "version": "2.4.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filesystem-2.4.11.jar",
          "url": "filesystem-2.4.11.jar",
          "size": 51650,
          "sha512": "4573ac699568860957979577966975ad5397dd813bd113bc1c2e17a8e81b4d01dcc536ca7c2debcf6f15501d7842a0d4f49e1c2a24a9fa2c28d5d22c2bfe0ffc",
          "sha256": "4dfdf961e3c295a6d64d88b5d3b0ad979362ff2994edf19981e10c496af1481b",
          "sha1": "531104b70c5881ee296f771992e033f278088e4e",
          "md5": "b58875846f3831083a1129696fa9337f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "filesystem-2.4.11.jar",
          "url": "filesystem-2.4.11.jar",
          "size": 51650,
          "sha512": "4573ac699568860957979577966975ad5397dd813bd113bc1c2e17a8e81b4d01dcc536ca7c2debcf6f15501d7842a0d4f49e1c2a24a9fa2c28d5d22c2bfe0ffc",
          "sha256": "4dfdf961e3c295a6d64d88b5d3b0ad979362ff2994edf19981e10c496af1481b",
          "sha1": "531104b70c5881ee296f771992e033f278088e4e",
          "md5": "b58875846f3831083a1129696fa9337f"
        }
      ]
    }
  ]
}
