{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filesystem",
    "version": "2.4.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "filesystem-2.4.11.jar",
          "url": "filesystem-2.4.11.jar",
          "size": 51650,
          "sha512": "6f7d954ab94bd3f0bd6279ede867b961b96264bca3eb5cbde4314d7b630e9eba1d3021fdc2b4ef775d4a9cf541e587716063f45fadc69ad02c2bf451c84f45c9",
          "sha256": "ab1d7a3181196a32809ee7b504a7faf5a6292695cf09a41c5b39b8ccb871fc5c",
          "sha1": "f9d002db8e4bca084dfbd7205381371ee9f059e5",
          "md5": "65a80ebe5258d5129e30a8e151907eb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "filesystem-2.4.11.jar",
          "url": "filesystem-2.4.11.jar",
          "size": 51650,
          "sha512": "6f7d954ab94bd3f0bd6279ede867b961b96264bca3eb5cbde4314d7b630e9eba1d3021fdc2b4ef775d4a9cf541e587716063f45fadc69ad02c2bf451c84f45c9",
          "sha256": "ab1d7a3181196a32809ee7b504a7faf5a6292695cf09a41c5b39b8ccb871fc5c",
          "sha1": "f9d002db8e4bca084dfbd7205381371ee9f059e5",
          "md5": "65a80ebe5258d5129e30a8e151907eb8"
        }
      ]
    }
  ]
}
