{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "opcode",
    "version": "2.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "opcode-2.4.4.jar",
          "url": "opcode-2.4.4.jar",
          "size": 127188,
          "sha512": "7194aa374aa81edbc51be2275e9bb0e9b12f01120bc43e9e907218327a742a1acb8dd09c57ec1505f96a4b473fb1ff0e5860cc51538ef2955b5b1133245acf42",
          "sha256": "24f937d7bb404935e9255cc82975ef568b7538b28e5dececccf73326cd65aab0",
          "sha1": "2d51e8909d3fe50285fa8573d40831ca7db7d958",
          "md5": "2c284e8b9cb36cec57056e1c15084e4d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "opcode-2.4.4.jar",
          "url": "opcode-2.4.4.jar",
          "size": 127188,
          "sha512": "7194aa374aa81edbc51be2275e9bb0e9b12f01120bc43e9e907218327a742a1acb8dd09c57ec1505f96a4b473fb1ff0e5860cc51538ef2955b5b1133245acf42",
          "sha256": "24f937d7bb404935e9255cc82975ef568b7538b28e5dececccf73326cd65aab0",
          "sha1": "2d51e8909d3fe50285fa8573d40831ca7db7d958",
          "md5": "2c284e8b9cb36cec57056e1c15084e4d"
        }
      ]
    }
  ]
}
