{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "definition",
    "version": "2.0.90",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "definition-2.0.90.jar",
          "url": "definition-2.0.90.jar",
          "size": 317414,
          "sha512": "693747d90f0300ed648397f7abcdfb0e8d5c2596e7b939bd48ea2069013b3f828ea7586026b977b19516f8745f469697e7cb41514baafa7203ad8d9357a218d7",
          "sha256": "dc91b691a4f4376b2d5aa901c67be19d815e4f3ecff0473bf221a09cb204b0b3",
          "sha1": "0db9883a505a134a0ddc4e67e7144cb5b1b6546b",
          "md5": "fd8ef783ba8c62104755b9cf91827c0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0-Beta1"
          }
        }
      ],
      "files": [
        {
          "name": "definition-2.0.90.jar",
          "url": "definition-2.0.90.jar",
          "size": 317414,
          "sha512": "693747d90f0300ed648397f7abcdfb0e8d5c2596e7b939bd48ea2069013b3f828ea7586026b977b19516f8745f469697e7cb41514baafa7203ad8d9357a218d7",
          "sha256": "dc91b691a4f4376b2d5aa901c67be19d815e4f3ecff0473bf221a09cb204b0b3",
          "sha1": "0db9883a505a134a0ddc4e67e7144cb5b1b6546b",
          "md5": "fd8ef783ba8c62104755b9cf91827c0b"
        }
      ]
    }
  ]
}
