{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "opcode",
    "version": "2.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "opcode-2.4.2.jar",
          "url": "opcode-2.4.2.jar",
          "size": 127100,
          "sha512": "11ca09e280cef8607c7622c4731e59419982b61796685d81e3c0c870eb7bf76000e49f0561ca32a42bfc75fbcdfd54b624375cb5584b19d4115a79a4e24fcd28",
          "sha256": "e6b31b30f2e1db382e8b1e18840d9af9d60add4543ec7b193d9528339e9d86c9",
          "sha1": "5a152bdbc5833d315abf9b07fc42ea3754936e0d",
          "md5": "c543f5293b7b9f753e577517297605c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "opcode-2.4.2.jar",
          "url": "opcode-2.4.2.jar",
          "size": 127100,
          "sha512": "11ca09e280cef8607c7622c4731e59419982b61796685d81e3c0c870eb7bf76000e49f0561ca32a42bfc75fbcdfd54b624375cb5584b19d4115a79a4e24fcd28",
          "sha256": "e6b31b30f2e1db382e8b1e18840d9af9d60add4543ec7b193d9528339e9d86c9",
          "sha1": "5a152bdbc5833d315abf9b07fc42ea3754936e0d",
          "md5": "c543f5293b7b9f753e577517297605c4"
        }
      ]
    }
  ]
}
