{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "filestore-server",
    "version": "0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-server-0.4.jar",
          "url": "filestore-server-0.4.jar",
          "size": 893280,
          "sha512": "0ba2192baf9a27db1cedd3e1c5ef41fe434003e4ac9bcdc06bb06c5a2188f24357cbaaa4f5eb9ed4bde8a43d33467de4e24c7882f448a4f8b0a2fb97bd8acd49",
          "sha256": "2e9b8c398b9a838e63eb8b73f2cca00ae841a90dc26c0a939258af98e5f821bb",
          "sha1": "91ac8e5f5f9a207f4752cc6daa9abcf068911753",
          "md5": "6e862c7cc27c05d376754eff14b705fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.or2",
          "module": "all",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-all",
          "version": {
            "requires": "5.0.0.Alpha2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-server-0.4.jar",
          "url": "filestore-server-0.4.jar",
          "size": 893280,
          "sha512": "0ba2192baf9a27db1cedd3e1c5ef41fe434003e4ac9bcdc06bb06c5a2188f24357cbaaa4f5eb9ed4bde8a43d33467de4e24c7882f448a4f8b0a2fb97bd8acd49",
          "sha256": "2e9b8c398b9a838e63eb8b73f2cca00ae841a90dc26c0a939258af98e5f821bb",
          "sha1": "91ac8e5f5f9a207f4752cc6daa9abcf068911753",
          "md5": "6e862c7cc27c05d376754eff14b705fc"
        }
      ]
    }
  ]
}
