{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.or2",
    "module": "r718-fs",
    "version": "2.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "r718-fs-2.3.9.jar",
          "url": "r718-fs-2.3.9.jar",
          "size": 7588,
          "sha512": "56464594a140f1de3ed666c92e9d14c8632f94e4576326053f7dc2ad0adca36949e548a949d500fa066153b42a5adbbccdeb69fcaf72973eed0327d276b53730",
          "sha256": "8ed63e9c64b41539c4fe3a7014b279c50583ecd1400bbc1a9e37a5506a381453",
          "sha1": "c4b37a0d4c786feb9588af8be85abdefaaecf07e",
          "md5": "5f5f19d4759c4dd38a5e04012d51d5fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.michael-bull.kotlin-inline-logger",
          "module": "kotlin-inline-logger",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.or2",
          "module": "filestore",
          "version": {
            "requires": "2.3.9"
          }
        },
        {
          "group": "dev.or2",
          "module": "definition",
          "version": {
            "requires": "2.3.9"
          }
        },
        {
          "group": "dev.or2",
          "module": "r718",
          "version": {
            "requires": "2.3.9"
          }
        },
        {
          "group": "dev.or2",
          "module": "filesystem",
          "version": {
            "requires": "2.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "r718-fs-2.3.9.jar",
          "url": "r718-fs-2.3.9.jar",
          "size": 7588,
          "sha512": "56464594a140f1de3ed666c92e9d14c8632f94e4576326053f7dc2ad0adca36949e548a949d500fa066153b42a5adbbccdeb69fcaf72973eed0327d276b53730",
          "sha256": "8ed63e9c64b41539c4fe3a7014b279c50583ecd1400bbc1a9e37a5506a381453",
          "sha1": "c4b37a0d4c786feb9588af8be85abdefaaecf07e",
          "md5": "5f5f19d4759c4dd38a5e04012d51d5fe"
        }
      ]
    }
  ]
}
